Repository TEAMMATES/teammates, pull requests merged in 2018-07, with the labels that each got.

#8865 Instructor: create session: Improve error message shown when session created with invalid information #8471
  src/main/java/teammates/common/util/FieldValidator.java
  src/test/java/teammates/test/cases/action/InstructorFeedbackCopyActionTest.java
  src/test/java/teammates/test/cases/action/InstructorFeedbackEditCopyActionTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackQuestionAttributesTest.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackSessionAttributesTest.java
Labels: e.1, s.ToMerge

#8862 InstructorCourseDetailsPageUiTest: testing on live server: increase success rate for checking email delivery #7788
  src/test/java/teammates/test/cases/browsertests/InstructorCourseDetailsPageUiTest.java
  src/test/java/teammates/test/driver/EmailAccount.java
Labels: s.ToMerge

#8923 Instructor: view results: add missing space and icon for 'Edit' link #8921
  src/main/webapp/WEB-INF/tags/instructor/results/sessionPanel.tag
  src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java
  src/test/resources/pages/instructorFeedbackResultsAddComment.html
  src/test/resources/pages/instructorFeedbackResultsAjaxByGQR.html
  src/test/resources/pages/instructorFeedbackResultsAjaxByGRQ.html
  src/test/resources/pages/instructorFeedbackResultsAjaxByQuestion.html
  src/test/resources/pages/instructorFeedbackResultsAjaxByRGQ.html
  src/test/resources/pages/instructorFeedbackResultsAjaxByRQG.html
  src/test/resources/pages/instructorFeedbackResultsDeleteComment.html
  src/test/resources/pages/instructorFeedbackResultsEditComment.html
  src/test/resources/pages/instructorFeedbackResultsEditCommentByDifferentInstructor.html
  src/test/resources/pages/instructorFeedbackResultsFilteredByNoSection.html
  src/test/resources/pages/instructorFeedbackResultsFilteredBySectionA.html
  src/test/resources/pages/instructorFeedbackResultsFilteredBySectionB.html
  src/test/resources/pages/instructorFeedbackResultsPageEmpty.html
  src/test/resources/pages/instructorFeedbackResultsPageGQRWithSanitizedData.html
  src/test/resources/pages/instructorFeedbackResultsPageMcqQuestionViewWithWeightsAttached.html
  src/test/resources/pages/instructorFeedbackResultsPageMcqQuestionViewWithoutWeightsAttached.html
  src/test/resources/pages/instructorFeedbackResultsPageOpen.html
  src/test/resources/pages/instructorFeedbackResultsPageRankGQRView.html
  src/test/resources/pages/instructorFeedbackResultsPageRankGRQView.html
  src/test/resources/pages/instructorFeedbackResultsPageRankQuestionView.html
  src/test/resources/pages/instructorFeedbackResultsPageRankRGQView.html
  src/test/resources/pages/instructorFeedbackResultsPageRankRQGView.html
  src/test/resources/pages/instructorFeedbackResultsPageRankRecipient.html
  src/test/resources/pages/instructorFeedbackResultsPageRubricGQRView.html
  src/test/resources/pages/instructorFeedbackResultsPageRubricGRQView.html
  src/test/resources/pages/instructorFeedbackResultsPageRubricQuestionView.html
  src/test/resources/pages/instructorFeedbackResultsPageRubricRGQView.html
  src/test/resources/pages/instructorFeedbackResultsPageRubricRQGView.html
  src/test/resources/pages/instructorFeedbackResultsPageWithSanitizedData.html
  src/test/resources/pages/instructorFeedbackResultsSortGiverQuestionRecipient.html
  src/test/resources/pages/instructorFeedbackResultsSortGiverQuestionRecipientTeam.html
  src/test/resources/pages/instructorFeedbackResultsSortGiverRecipientQuestion.html
  src/test/resources/pages/instructorFeedbackResultsSortGiverRecipientQuestionTeam.html
  src/test/resources/pages/instructorFeedbackResultsSortQuestionTeam.html
  src/test/resources/pages/instructorFeedbackResultsSortRecipientGiverQuestion.html
  src/test/resources/pages/instructorFeedbackResultsSortRecipientGiverQuestionTeam.html
  src/test/resources/pages/instructorFeedbackResultsSortRecipientQuestionGiver.html
  src/test/resources/pages/instructorFeedbackResultsSortRecipientQuestionGiverTeam.html
  src/test/resources/pages/instructorFeedbackResultsSortSecondSessionFilteredBySectionATeam.html
  src/test/resources/pages/instructorFeedbackResultsSortSecondSessionGiverQuestionRecipient.html
  src/test/resources/pages/instructorFeedbackResultsSortSecondSessionGiverQuestionRecipientTeam.html
  src/test/resources/pages/instructorFeedbackResultsSortSecondSessionGiverRecipientQuestion.html
  src/test/resources/pages/instructorFeedbackResultsSortSecondSessionGiverRecipientQuestionTeam.html
  src/test/resources/pages/instructorFeedbackResultsSortSecondSessionQuestionTeam.html
  src/test/resources/pages/instructorFeedbackResultsSortSecondSessionRecipientGiverQuestion.html
  src/test/resources/pages/instructorFeedbackResultsSortSecondSessionRecipientGiverQuestionTeam.html
  src/test/resources/pages/instructorFeedbackResultsSortSecondSessionRecipientQuestionGiver.html
  src/test/resources/pages/instructorFeedbackResultsSortSecondSessionRecipientQuestionGiverTeam.html
  src/test/resources/pages/newlyJoinedInstructorFirstFeedbackSessionResultsPage.html
  src/test/resources/pages/newlyJoinedInstructorSecondFeedbackSessionResultsPage.html
  src/test/resources/pages/newlyJoinedInstructorThirdFeedbackSessionResultsPage.html
Labels: s.FinalReview

#8890 InstructorSessionEdit: Duplicate question easily with a duplicate button #8876
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/controller/InstructorFeedbackQuestionEditAction.java
  src/main/webapp/WEB-INF/tags/instructor/feedbackEdit/questionEditForm.tag
  src/main/webapp/dev/js/main/instructorFeedbackEdit.js
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java
  src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
  src/test/resources/pages/instructorFeedbackConstSumOptionQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackConstSumOptionQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackConstSumRecipientQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackConstSumRecipientQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackContribQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackContribQuestionEdit.html
  src/test/resources/pages/instructorFeedbackContribQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackCopyQuestionSuccess.html
  src/test/resources/pages/instructorFeedbackEditCopyFail.html
  src/test/resources/pages/instructorFeedbackEditCopyPage.html
  src/test/resources/pages/instructorFeedbackEditPageTestingSanitization.html
  src/test/resources/pages/instructorFeedbackMcqQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackMcqQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackMcqQuestionWeightAddSuccess.html
  src/test/resources/pages/instructorFeedbackMcqQuestionWeightEditSuccess.html
  src/test/resources/pages/instructorFeedbackMsqQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackMsqQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackNumScaleQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackNumScaleQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackQuestionEditToTeamToTeam.html
  src/test/resources/pages/instructorFeedbackQuestionVisibilityOptions.html
  src/test/resources/pages/instructorFeedbackQuestionVisibilityPreview.html
  src/test/resources/pages/instructorFeedbackRankMinMaxChoicesSuccess.html
  src/test/resources/pages/instructorFeedbackRankQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackRankQuestionEdit.html
  src/test/resources/pages/instructorFeedbackRankQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEdit.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditChoiceSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditDescriptionSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditSubQuestionSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditWeightSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionMoveColumnNewQuestionSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionMoveColumnSuccess.html
  src/test/resources/pages/instructorFeedbackTeamPeerEvalTemplateAddSuccess.html
Labels: e.1, s.ToMerge

#8936 Instructor: edit student details: email contains raw template literals after resending past links to the new email #8935
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java
  src/test/resources/emails/summaryOfFeedbackSessionsOfCourseEmailForUnregisteredStudent.html
Labels: s.ToMerge

#8924 Fix assertion error in instructorCourseJoinEmail on live server #8452
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/InstructorsLogic.java
  src/main/java/teammates/storage/api/InstructorsDb.java
  src/main/java/teammates/storage/api/StudentsDb.java
  src/main/java/teammates/storage/entity/Instructor.java
  src/main/java/teammates/ui/automated/InstructorCourseJoinEmailWorkerAction.java
Labels: s.ToMerge

#8939 Improve setting-up.md documentation #8920
  docs/setting-up.md
Labels: e.1, s.ToMerge

#8930 InstructorFeedbackResultsPage: Show consistent data on the webpage and downloaded data #8929
  src/main/java/teammates/storage/api/FeedbackResponsesDb.java
  src/main/resources/InstructorSampleData.json
  src/test/java/teammates/test/cases/storage/FeedbackResponsesDbTest.java
Labels: e.1, s.ToMerge

#8946 Release V6.7.0 #8945
  src/main/webapp/data/developers.json
Labels: c.Release, s.ToMerge

#8934 Instructor: Question view: visibility icon does not appear for new comments #8899
  src/main/java/teammates/ui/pagedata/InstructorFeedbackResponseCommentAjaxPageData.java
  src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java
  src/main/java/teammates/ui/pagedata/InstructorSearchPageData.java
  src/main/java/teammates/ui/pagedata/PageData.java
  src/main/java/teammates/ui/pagedata/StudentFeedbackResultsPageData.java
  src/main/java/teammates/ui/template/FeedbackResponseCommentRow.java
  src/main/java/teammates/ui/template/FeedbackResponseRow.java
  src/main/webapp/WEB-INF/tags/shared/feedbackResponseCommentRow.tag
  src/test/resources/pages/instructorFeedbackResultsAddComment.html
  src/test/resources/pages/instructorFeedbackResultsEditComment.html
  src/test/resources/pages/instructorFeedbackResultsEditCommentByDifferentInstructor.html
  src/test/resources/pages/instructorFeedbackResultsPageGQRWithSanitizedData.html
  src/test/resources/pages/instructorFeedbackResultsPageWithSanitizedData.html
  src/test/resources/pages/instructorSearchPageSearchCommentsAsHelper.html
  src/test/resources/pages/instructorSearchPageSearchFeedbackResponseComments.html
  src/test/resources/pages/instructorSearchPageSearchTestingSanitization.html
  src/test/resources/pages/instructorStudentRecords.html
  src/test/resources/pages/instructorStudentRecordsPageEditedComment.html
  src/test/resources/pages/instructorStudentRecordsPageEditedCommentOfDifferentInstructor.html
  src/test/resources/pages/newlyJoinedInstructorStudentFeedbackResultsPage.html
  src/test/resources/pages/studentFeedbackResultsPageNewlyRegistered.html
  src/test/resources/pages/studentFeedbackResultsPageOpen.html
  src/test/resources/pages/studentFeedbackResultsPageTeamToTeam.html
  src/test/resources/pages/unregisteredStudentFeedbackResultsPageOpen.html
Labels: e.2, s.ToMerge

#8948 Edit ide-setup.md #8944
  docs/ide-setup.md
Labels: e.1, s.ToMerge

#8859 InstructorFeedbackResultsPageUiTest: Improve testing logic and procedure #8858
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageResponseCommentUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java
  src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java
  src/test/resources/data/InstructorFeedbackResultsPageResponseCommentUiTest.json
  src/test/resources/pages/instructorFeedbackResultsAddComment.html
  src/test/resources/pages/instructorFeedbackResultsDeleteComment.html
  src/test/resources/pages/instructorFeedbackResultsEditComment.html
  src/test/resources/pages/instructorFeedbackResultsEditCommentByDifferentInstructor.html
  src/test/testng-ci.xml
Labels: e.2, s.ToMerge

#8949 Instructor: Feedback Session: question number drop down menu #8942
  src/main/java/teammates/common/util/Const.java
  src/main/webapp/WEB-INF/tags/instructor/feedbackEdit/questionEditForm.tag
  src/main/webapp/dev/js/common/const.js
  src/main/webapp/dev/js/main/instructorFeedbackEdit.js
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java
  src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
  src/test/resources/pages/instructorFeedbackConstSumOptionQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackConstSumOptionQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackConstSumRecipientQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackConstSumRecipientQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackContribQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackContribQuestionEdit.html
  src/test/resources/pages/instructorFeedbackContribQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackCopyQuestionSuccess.html
  src/test/resources/pages/instructorFeedbackEditCopyFail.html
  src/test/resources/pages/instructorFeedbackEditCopyPage.html
  src/test/resources/pages/instructorFeedbackEditPageTestingSanitization.html
  src/test/resources/pages/instructorFeedbackMcqQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackMcqQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackMcqQuestionWeightAddSuccess.html
  src/test/resources/pages/instructorFeedbackMcqQuestionWeightEditSuccess.html
  src/test/resources/pages/instructorFeedbackMsqQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackMsqQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackNumScaleQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackNumScaleQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackQuestionEditToTeamToTeam.html
  src/test/resources/pages/instructorFeedbackQuestionVisibilityOptions.html
  src/test/resources/pages/instructorFeedbackQuestionVisibilityPreview.html
  src/test/resources/pages/instructorFeedbackRankMinMaxChoicesSuccess.html
  src/test/resources/pages/instructorFeedbackRankQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackRankQuestionEdit.html
  src/test/resources/pages/instructorFeedbackRankQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEdit.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditChoiceSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditDescriptionSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditSubQuestionSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditWeightSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionMoveColumnNewQuestionSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionMoveColumnSuccess.html
  src/test/resources/pages/instructorFeedbackTeamPeerEvalTemplateAddSuccess.html
Labels: e.2, s.ToMerge

#8967 Instructor Home Page: Hide options for instructors without corresponding privileges #8962
  src/main/java/teammates/ui/pagedata/InstructorHomeCourseAjaxPageData.java
  src/test/resources/pages/instructorHomeHTMLWithHelperView.html
Labels: e.1, s.ToMerge

#8928 Instructor: recycle bin feature: add instructions for managing deleted courses in instructor help page #8927
  src/main/webapp/partials/instructorHelpCourses.jsp
Labels: s.FinalReview

#8970 AdminActivityLogPageAction: fix bug in generation of status message #6711
  src/main/java/teammates/common/util/StringHelper.java
  src/main/java/teammates/ui/pagedata/AdminActivityLogPageData.java
  src/main/webapp/WEB-INF/tags/admin/activity/filterPanel.tag
  src/test/java/teammates/test/cases/action/AdminActivityLogPageActionTest.java
  src/test/java/teammates/test/cases/util/StringHelperTest.java
Labels: s.ToMerge

#8784 Student: view results: rank questions: show average #8701
  src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRankRecipientsQuestionDetails.java
  src/main/resources/feedbackQuestionRankResultStatsRecipientTemplate.html
  src/test/java/teammates/test/cases/browsertests/FeedbackRankQuestionUiTest.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackSessionResultsBundleTest.java
  src/test/resources/data/FeedbackRankQuestionUiTest.json
  src/test/resources/data/FeedbackSessionResultsBundleTest.json
  src/test/resources/pages/instructorFeedbackResultsPageRankRecipient.html
  src/test/resources/pages/studentFeedbackResultsPageRank.html
  src/test/resources/pages/studentFeedbackSubmitPageRank.html
  src/test/resources/pages/studentFeedbackSubmitPageSuccessRank.html
Labels: s.ToMerge

#8956 Student: submit responses: implement back-end integrity check for responses #2542
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/controller/FeedbackSubmissionEditSaveAction.java
  src/test/java/teammates/test/cases/action/InstructorFeedbackSubmissionEditSaveActionTest.java
  src/test/java/teammates/test/cases/action/StudentFeedbackSubmissionEditSaveActionTest.java
Labels: s.ToMerge

#8897 Instructor: comment on responses: support entering comments for each response from view GQR #8872
  src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java
  src/main/webapp/WEB-INF/tags/instructor/results/questionPanel.tag
  src/main/webapp/dev/js/main/instructorFeedbackResultsGQR.js
  src/main/webapp/jsp/instructorFeedbackResultsByGiverQuestionRecipient.jsp
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageResponseCommentUiTest.java
  src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java
  src/test/resources/pages/instructorFeedbackResultsAjaxByGQR.html
  src/test/resources/pages/instructorFeedbackResultsAjaxByQuestion.html
  src/test/resources/pages/instructorFeedbackResultsAjaxByQuestionViewForHelperTwo.html
  src/test/resources/pages/instructorFeedbackResultsDuplicateQuestionNumberPanel1.html
  src/test/resources/pages/instructorFeedbackResultsDuplicateQuestionNumberPanel2.html
  src/test/resources/pages/instructorFeedbackResultsEditComment.html
  src/test/resources/pages/instructorFeedbackResultsEditCommentByDifferentInstructor.html
  src/test/resources/pages/instructorFeedbackResultsPageMcqQuestionViewWithWeightsAttached.html
  src/test/resources/pages/instructorFeedbackResultsPageMcqQuestionViewWithoutWeightsAttached.html
  src/test/resources/pages/instructorFeedbackResultsPageMsqQuestionViewWithWeightsAttached.html
  src/test/resources/pages/instructorFeedbackResultsPageMsqQuestionViewWithoutWeightsAttached.html
  src/test/resources/pages/instructorFeedbackResultsPageOpen.html
  src/test/resources/pages/instructorFeedbackResultsPageOpenViewForHelperTwo.html
  src/test/resources/pages/instructorFeedbackResultsPageRankQuestionView.html
  src/test/resources/pages/instructorFeedbackResultsPageRankRecipient.html
  src/test/resources/pages/instructorFeedbackResultsPageRubricGQRView.html
  src/test/resources/pages/instructorFeedbackResultsPageRubricQuestionView.html
  src/test/resources/pages/instructorFeedbackResultsPageWithSanitizedData.html
  src/test/resources/pages/instructorFeedbackResultsSortGiverQuestionRecipient.html
  src/test/resources/pages/instructorFeedbackResultsSortGiverQuestionRecipientTeam.html
  src/test/resources/pages/instructorFeedbackResultsSortQuestionTeam.html
  src/test/resources/pages/instructorFeedbackResultsSortSecondSessionFilteredBySectionATeam.html
  src/test/resources/pages/instructorFeedbackResultsSortSecondSessionGiverQuestionRecipient.html
  src/test/resources/pages/instructorFeedbackResultsSortSecondSessionGiverQuestionRecipientTeam.html
  src/test/resources/pages/instructorFeedbackResultsSortSecondSessionQuestionTeam.html
  src/test/resources/pages/newlyJoinedInstructorFirstFeedbackSessionResultsPage.html
  src/test/resources/pages/newlyJoinedInstructorThirdFeedbackSessionResultsPage.html
Labels: s.ToMerge

#8991 Instructor: delete course: rephrase message shown when there are no more courses left #8980
  src/main/java/teammates/common/util/Const.java
  src/test/java/teammates/test/cases/action/InstructorCoursesPageActionTest.java
  src/test/resources/pages/instructorCoursesNoCourse.html
Labels: e.1, s.ToMerge

#8992 Instructor: comment on responses: support entering comments for each response from view RQG #8987
  src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java
  src/main/webapp/dev/js/main/instructorFeedbackResultsRQG.js
  src/main/webapp/jsp/instructorFeedbackResultsByRecipientQuestionGiver.jsp
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageResponseCommentUiTest.java
  src/test/resources/pages/instructorFeedbackResultsAjaxByRQG.html
  src/test/resources/pages/instructorFeedbackResultsPageRankRQGView.html
  src/test/resources/pages/instructorFeedbackResultsPageRubricRQGView.html
  src/test/resources/pages/instructorFeedbackResultsSortRecipientQuestionGiver.html
  src/test/resources/pages/instructorFeedbackResultsSortRecipientQuestionGiverTeam.html
  src/test/resources/pages/instructorFeedbackResultsSortSecondSessionRecipientQuestionGiver.html
  src/test/resources/pages/instructorFeedbackResultsSortSecondSessionRecipientQuestionGiverTeam.html
Labels: c.Feature, s.ToMerge

#8976 Instructor: enroll students: add a 'paste' option to the context menu #8972
  src/main/webapp/dev/js/main/instructorCourseEnrollHelper.js
  src/main/webapp/dev/js/main/instructorCourseEnrollPage.js
Labels: s.ToMerge

#8966 ProfilesDbTest.testUpdateStudentProfile failing on live server #8958
  src/test/java/teammates/test/cases/BaseTestCaseWithMinimalGaeEnvironment.java
  src/test/java/teammates/test/cases/testdriver/EmailCheckerTest.java
  src/test/java/teammates/test/driver/EmailChecker.java
Labels: s.ToMerge

#8999 Release V6.8.0 #8997
  src/main/webapp/data/developers.json
Labels: c.Release, s.ToMerge

#8861 Instructor: Add Course title to Student Details page #8854
  src/main/java/teammates/ui/pagedata/InstructorCourseStudentDetailsPageData.java
  src/main/java/teammates/ui/template/StudentInfoTable.java
  src/main/webapp/WEB-INF/tags/instructor/courseStudentDetails/studentInformationTable.tag
  src/main/webapp/WEB-INF/tags/instructor/courseStudentDetails/studentProfile.tag
  src/main/webapp/WEB-INF/tags/instructor/courseStudentDetailsEdit/studentInformationTable.tag
  src/main/webapp/WEB-INF/tags/instructor/moreInfo.tag
  src/main/webapp/jsp/instructorCourseStudentDetails.jsp
  src/main/webapp/stylesheets/teammatesCommon.css
  src/test/java/teammates/test/cases/action/InstructorCourseStudentDetailsEditPageActionTest.java
  src/test/java/teammates/test/cases/action/InstructorCourseStudentDetailsPageActionTest.java
  src/test/java/teammates/test/cases/pagedata/InstructorCourseStudentDetailsEditPageDataTest.java
  src/test/java/teammates/test/cases/pagedata/InstructorCourseStudentDetailsPageDataTest.java
  src/test/java/teammates/test/pageobjects/InstructorCourseStudentDetailsViewPage.java
  src/test/resources/pages/instructorCourseStudentDetailsRegistered.html
  src/test/resources/pages/instructorCourseStudentDetailsRegisteredWithAttemptedScriptInjection.html
  src/test/resources/pages/instructorCourseStudentDetailsRegisteredWithHelperView.html
  src/test/resources/pages/instructorCourseStudentDetailsUnregistered.html
  src/test/resources/pages/instructorStudentRecords.html
  src/test/resources/pages/instructorStudentRecordsPageEditedComment.html
  src/test/resources/pages/instructorStudentRecordsPageEditedCommentOfDifferentInstructor.html
  src/test/resources/pages/instructorStudentRecordsPageMixedQuestionType.html
  src/test/resources/pages/instructorStudentRecordsPageWithPrivateFeedback.html
  src/test/resources/pages/instructorStudentRecordsPageWithScriptInjectionProfile.html
Labels: s.ToMerge
