Repository TEAMMATES/teammates, pull requests merged in 2018-05, with the labels that each got.

#8806 AboutUs and Readme.md: Acknowledge GSoC2018 #8805
  README.md
  src/main/webapp/about.jsp
Labels: s.ToMerge

#8812 InstructorFeedbackSessionsPageUiTest: New Session start and end with past date #8811
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java
Labels: e.1, s.ToMerge

#8802 Session reminder emails: mention editing responses #8708
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/test/resources/emails/sessionClosingEmailForInstructor.html
  src/test/resources/emails/sessionClosingEmailForStudent.html
  src/test/resources/emails/sessionOpeningEmailForInstructor.html
  src/test/resources/emails/sessionOpeningEmailForStudent.html
  src/test/resources/emails/sessionOpeningEmailTestingSanitizationForInstructor.html
  src/test/resources/emails/sessionOpeningEmailTestingSanitzationForStudent.html
  src/test/resources/emails/sessionReminderEmailCopyToInstructor.html
  src/test/resources/emails/sessionReminderEmailForInstructor.html
  src/test/resources/emails/sessionReminderEmailForStudent.html
Labels: e.1, s.ToMerge

#8781 TimeHelper: update documentation and standardize method naming #8780
  src/main/java/teammates/common/datatransfer/attributes/AdminEmailAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/CourseAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributes.java
  src/main/java/teammates/common/util/TimeHelper.java
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java
  src/main/java/teammates/ui/controller/AdminSessionsPageAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackAbstractAction.java
  src/main/java/teammates/ui/pagedata/AdminSessionsPageData.java
  src/main/java/teammates/ui/pagedata/InstructorFeedbackResponseCommentAjaxPageData.java
  src/main/java/teammates/ui/pagedata/InstructorHomeCourseAjaxPageData.java
  src/main/java/teammates/ui/pagedata/StudentHomePageData.java
  src/main/java/teammates/ui/template/AdminAccountManagementAccountTableRow.java
  src/main/java/teammates/ui/template/AdminActivityLogTableRow.java
  src/main/java/teammates/ui/template/AdminEmailTableRow.java
  src/main/java/teammates/ui/template/FeedbackResponseCommentRow.java
  src/main/java/teammates/ui/template/InstructorFeedbackResultsSessionPanel.java
  src/test/java/teammates/test/cases/action/AdminActivityLogPageActionTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java
  src/test/java/teammates/test/cases/datatransfer/AdminEmailAttributesTest.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackSessionAttributesTest.java
  src/test/java/teammates/test/cases/pagedata/StudentHomePageDataTest.java
  src/test/java/teammates/test/cases/util/TimeHelperTest.java
  src/test/java/teammates/test/driver/HtmlHelper.java
  src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
Labels: e.2, s.ToMerge

#8793 Instructor: edit session: allow making session visible from a future date #8790
  src/main/webapp/dev/js/common/datepicker.js
  src/test/java/teammates/test/cases/browsertests/AllJsTests.java
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java
  src/test/java/teammates/test/pageobjects/InstructorFeedbackSessionsPage.java
Labels: e.1, s.ToMerge

#8825 Remove JS coverage requirement #8768
  src/test/java/teammates/test/cases/browsertests/AllJsTests.java
Labels: s.ToMerge

#8770 Add AdminExceptionTestActionTest #6902
  src/main/java/teammates/ui/controller/AdminExceptionTestAction.java
  src/test/java/teammates/test/cases/action/AdminExceptionTestActionTest.java
Labels: s.ToReview

#8766 Student: submit responses: warn if there are unanswered questions #8598
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/controller/FeedbackSubmissionEditSaveAction.java
  src/main/webapp/dev/js/main/feedbackSubmissionsEdit.js
  src/main/webapp/stylesheets/teammatesCommon.css
  src/test/java/teammates/test/cases/action/InstructorEditInstructorFeedbackSaveActionTest.java
  src/test/java/teammates/test/cases/action/InstructorEditStudentFeedbackSaveActionTest.java
  src/test/java/teammates/test/cases/action/InstructorFeedbackSubmissionEditSaveActionTest.java
  src/test/java/teammates/test/cases/action/StudentFeedbackSubmissionEditSaveActionTest.java
  src/test/java/teammates/test/cases/browsertests/FeedbackRankQuestionUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorEditStudentFeedbackPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSubmitPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/StudentFeedbackSubmitPageUiTest.java
  src/test/java/teammates/test/pageobjects/FeedbackSubmitPage.java
  src/test/resources/pages/unregisteredStudentFeedbackSubmitPagePartiallyFilled.html
Labels: s.ToMerge
