Repository TEAMMATES/teammates, pull requests merged in 2018-08, with the labels that each got.

#9006 instructorFeedbackResultsPage: Team Contribution Question: Help link is not showing statistics table #9004
  src/main/webapp/partials/instructorHelpQuestions.jsp
Labels: c.Bug, s.ToMerge

#8998 Fix assertion error in instructorCourseJoinEmail on live server #8452
  src/main/java/teammates/ui/automated/InstructorCourseJoinEmailWorkerAction.java
  src/main/java/teammates/ui/automated/StudentCourseJoinEmailWorkerAction.java
  src/main/webapp/WEB-INF/queue.xml
Labels: c.Bug, s.ToMerge

#9023 UI tests against live server: update automated login to match new Google login page #9015
  src/test/java/teammates/test/pageobjects/GoogleLoginPage.java
Labels: c.Bug, s.ToMerge

#9035 Student: Comment on responses: Fix put document error #9034
  src/main/java/teammates/ui/controller/FeedbackSubmissionEditSaveAction.java
  src/test/java/teammates/test/cases/BaseComponentTestCase.java
  src/test/java/teammates/test/cases/action/InstructorEditInstructorFeedbackSaveActionTest.java
  src/test/java/teammates/test/cases/action/InstructorEditStudentFeedbackSaveActionTest.java
  src/test/java/teammates/test/cases/action/InstructorFeedbackSubmissionEditSaveActionTest.java
  src/test/java/teammates/test/cases/action/StudentFeedbackSubmissionEditSaveActionTest.java
  src/test/java/teammates/test/cases/search/FeedbackResponseCommentSearchTest.java
Labels: c.Bug, s.ToMerge

#8875 StudentHomePageUiTest: fix state leak #8524
  src/test/java/teammates/test/cases/browsertests/StudentHomePageUiTest.java
  src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java
  src/test/java/teammates/test/driver/BackDoor.java
  src/test/resources/data/StudentHomePageUiTest.json
  src/test/resources/data/StudentProfilePageUiTest.json
  src/test/resources/pages/studentProfilePageDefault.html
  src/test/resources/pages/studentProfilePageWithAttemptedScriptInjection.html
Labels: s.ToMerge

#9036 Student: comment on MCQ response: tweak comment UI #9029
  src/main/webapp/WEB-INF/tags/shared/feedbackResponseCommentFormForFeedbackParticipant.tag
  src/test/resources/pages/instructorEditStudentFeedbackPageModified.html
  src/test/resources/pages/instructorEditStudentFeedbackPageOpen.html
  src/test/resources/pages/instructorFeedbackSubmitPageClosed.html
  src/test/resources/pages/instructorFeedbackSubmitPageFullyFilled.html
  src/test/resources/pages/instructorFeedbackSubmitPageModified.html
  src/test/resources/pages/instructorFeedbackSubmitPageOpen.html
  src/test/resources/pages/instructorFeedbackSubmitPageOpenWithHelperView.html
  src/test/resources/pages/instructorFeedbackSubmitPagePartiallyFilled.html
  src/test/resources/pages/studentFeedbackSubmitPageClosed.html
  src/test/resources/pages/studentFeedbackSubmitPageFullyFilled.html
  src/test/resources/pages/studentFeedbackSubmitPageModified.html
  src/test/resources/pages/studentFeedbackSubmitPageOpen.html
  src/test/resources/pages/studentFeedbackSubmitPagePartiallyFilled.html
  src/test/resources/pages/unregisteredStudentFeedbackSubmitPageOpen.html
  src/test/resources/pages/unregisteredStudentFeedbackSubmitPagePartiallyFilled.html
Labels: c.Task, s.ToMerge

#9008 Rubric questions: allow weight for each cell: Migrate legacy data into new format #9007
  src/client/java/teammates/client/scripts/DataMigrationForRubricQuestionsWithWeightsAttached.java
Labels: c.Task, s.ToMerge

#9020 FeedbackNumericalScaleQuestionDetails: refactor long methods #6657
  src/main/java/teammates/common/datatransfer/questions/FeedbackNumericalScaleQuestionDetails.java
Labels: c.Task, s.ToMerge

#8884 Spreadsheet Interface for Student Data UI: Phase II upgrade for instructorCourseEnrollPage #8883
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/controller/ActionFactory.java
  src/main/java/teammates/ui/controller/InstructorCourseEnrollAjaxPageAction.java
  src/main/java/teammates/ui/pagedata/InstructorCourseEnrollAjaxPageData.java
  src/main/resources/package.json
  src/main/webapp/dev/js/common/instructorEnroll.js
  src/main/webapp/dev/js/main/instructorCourseEnrollPage.js
  src/main/webapp/dev/js/test/InstructorEnrolmentJsTest.js
  src/main/webapp/jsp/instructorCourseEnroll.jsp
  src/main/webapp/stylesheets/teammatesCommon.css
  src/test/java/teammates/test/cases/action/InstructorCourseEnrollAjaxPageActionTest.java
  src/test/java/teammates/test/driver/HtmlHelper.java
  src/test/java/teammates/test/pageobjects/AppPage.java
  src/test/resources/pages/instructorCourseEnrollError.html
  src/test/resources/pages/instructorCourseEnrollPage.html
Labels: s.ToMerge

#9047 Rubric questions: allow weight for each cell: Migrate legacy data into new format #9007
  src/client/java/teammates/client/scripts/DataMigrationForRubricQuestionsWithWeightsAttached.java
Labels: s.ToMerge

#9055 InstructorHelpPageUiTest failing on AppVeyor master #9052
  src/main/webapp/dev/js/common/onStart.js
  src/main/webapp/dev/js/main/about.js
  src/main/webapp/dev/js/main/instructorCourses.js
  src/main/webapp/dev/js/main/instructorHelp.js
  src/main/webapp/dev/js/test/CommonTestFunctions.js
  static-analysis/teammates-eslint.yml
Labels: s.FinalReview

#9028 Rubric questions: allow weight for each cell: Remove legacy code #9026
  src/client/java/teammates/client/scripts/DataMigrationForRubricQuestionToRemoveLegacyWeightList.java
  src/client/java/teammates/client/scripts/DataMigrationForRubricQuestionsWithWeightsAttached.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetails.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackRubricQuestionDetailsTest.java
  src/test/resources/data/FeedbackRubricQuestionUiTest.json
  src/test/resources/data/FeedbackSessionQuestionTypeTest.json
Labels: c.Task, s.ToMerge

#9073 Instructor: enroll students: blank lines processed by back-end during enrollment #9071
  src/main/webapp/dev/js/common/instructorEnroll.js
Labels: c.Bug, s.ToMerge

#9070 Data Migration: Able to resume/restart from where it fails/stops #9044
  src/client/java/teammates/client/scripts/DataMigrationForOrphanedStudentProfile.java
  src/client/java/teammates/client/scripts/DataMigrationWithCheckpointForEntities.java
Labels: c.Task, s.ToMerge

#9077 Update workflow/process documents #8565
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/help-request.md
  docs/README.md
  docs/compressing-images.md
  docs/dependencies.md
  docs/development.md
  docs/ide-setup.md
  docs/intellij-automated-setup-behavior.md
  docs/maintainer-guide.md
  docs/process.md
  docs/setting-up.md
  docs/static-analysis.md
  docs/troubleshooting-guide.md
Labels: s.FinalReview

#9078 [#8565] Update workflow/process documents
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/data-migration.md
  docs/maintainer-guide.md
  docs/process.md
Labels: s.ToMerge

#9058 [#9053] TimeHelper.java: combine methods 'formatDateForInstructorCoursesPage' & 'formatDateForInstructorSessionsPage' into 'formatDateForInstructorPages'
  src/main/java/teammates/common/datatransfer/attributes/CourseAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributes.java
  src/main/java/teammates/common/util/TimeHelper.java
  src/test/java/teammates/test/cases/util/TimeHelperTest.java
  src/test/java/teammates/test/driver/HtmlHelper.java
Labels: s.ToMerge

#9087 [#9065] Fix unstable testToEntity() in StudentProfileAttributesTest
  src/test/java/teammates/test/cases/datatransfer/StudentProfileAttributesTest.java
Labels: c.Task, s.ToMerge

#9097 [#9090] Instructor edit email of student: send the correct link to student
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditSaveAction.java
  src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java
  src/test/resources/data/EmailGeneratorTest.json
  src/test/resources/emails/summaryOfFeedbackSessionsOfCourseEmailForUnregisteredStudent.html
Labels: s.ToMerge
