Repository TEAMMATES/teammates, pull requests merged in 2018-11, with the labels that each got.

#9223 [#9200] Update timezone database to 2018g
  src/main/resources/tzdb.dat
  src/main/webapp/data/moment-timezone-with-data.min.js
Labels: s.ToMerge

#9222 [#8866] Submit feedback: optimize layout of questions
  src/main/webapp/WEB-INF/tags/shared/feedbackSubmissionEdit/questionWithResponses.tag
  src/test/resources/pages/instructorEditStudentFeedbackPageModified.html
  src/test/resources/pages/instructorEditStudentFeedbackPageOpen.html
  src/test/resources/pages/instructorFeedbackResultsPageRankSubmission.html
  src/test/resources/pages/instructorFeedbackSubmitPageAwaiting.html
  src/test/resources/pages/instructorFeedbackSubmitPageClosed.html
  src/test/resources/pages/instructorFeedbackSubmitPageFullyFilled.html
  src/test/resources/pages/instructorFeedbackSubmitPageGracePeriod.html
  src/test/resources/pages/instructorFeedbackSubmitPageModified.html
  src/test/resources/pages/instructorFeedbackSubmitPageOpen.html
  src/test/resources/pages/instructorFeedbackSubmitPageOpenWithHelperView.html
  src/test/resources/pages/instructorFeedbackSubmitPagePartiallyFilled.html
  src/test/resources/pages/instructorFeedbackSubmitPagePreview.html
  src/test/resources/pages/instructorFeedbackSubmitPageRankHelper.html
  src/test/resources/pages/newlyJoinedInstructorStudentFeedbackSubmissionEdit.html
  src/test/resources/pages/studentFeedbackSubmitPageAwaiting.html
  src/test/resources/pages/studentFeedbackSubmitPageClosed.html
  src/test/resources/pages/studentFeedbackSubmitPageFullyFilled.html
  src/test/resources/pages/studentFeedbackSubmitPageGracePeriod.html
  src/test/resources/pages/studentFeedbackSubmitPageModified.html
  src/test/resources/pages/studentFeedbackSubmitPageOpen.html
  src/test/resources/pages/studentFeedbackSubmitPagePartiallyFilled.html
  src/test/resources/pages/studentFeedbackSubmitPagePreview.html
  src/test/resources/pages/studentFeedbackSubmitPageRank.html
  src/test/resources/pages/studentFeedbackSubmitPageRubricSuccess.html
  src/test/resources/pages/studentFeedbackSubmitPageSuccessRank.html
  src/test/resources/pages/unregisteredStudentFeedbackSubmitPageOpen.html
  src/test/resources/pages/unregisteredStudentFeedbackSubmitPagePartiallyFilled.html
Labels: s.ToMerge

#9209 [#9208] InstructorFeedbackSessionsPageUiTest failing against the live server
  src/test/java/teammates/test/pageobjects/InstructorFeedbackSessionsPage.java
Labels: c.Bug, s.ToMerge

#9021 [#8589] Student Profile: add a 'Upload/Edit Photo' tooltip
  src/main/java/teammates/common/util/Const.java
  src/main/webapp/WEB-INF/tags/student/profile/studentProfileDiv.tag
  src/test/resources/pages/studentProfileEditDivExistingValues.html
  src/test/resources/pages/studentProfilePageDefault.html
  src/test/resources/pages/studentProfilePageFilled.html
  src/test/resources/pages/studentProfilePageWithAttemptedScriptInjection.html
Labels: s.ToReview
