Repository TEAMMATES/teammates, pull requests merged in 2018-03, with the labels that each got.

#8568 Running dev server via CLI: preserve local datastore across builds #8567
  build.gradle
Labels: e.1, s.ToMerge

#8521 FeedbackSessionQuestionTypeTest.json: fix malformed question metadata #8418
  src/test/resources/data/FeedbackSessionQuestionTypeTest.json
Labels: e.1, s.ToMerge

#8570 FeedbackSessionAttributes: isInGracePeriod: handle corner case #8569
  src/main/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributes.java
Labels: e.1, s.ToMerge

#8502 Enhancement: Instructor: All Records of Student: Improve UI #8492
  src/main/webapp/WEB-INF/tags/instructor/moreInfo.tag
  src/test/resources/pages/instructorCourseStudentDetailsRegistered.html
  src/test/resources/pages/instructorCourseStudentDetailsRegisteredWithAttemptedScriptInjection.html
  src/test/resources/pages/instructorCourseStudentDetailsRegisteredWithHelperView.html
  src/test/resources/pages/instructorStudentRecords.html
  src/test/resources/pages/instructorStudentRecordsPageEditedComment.html
  src/test/resources/pages/instructorStudentRecordsPageEditedCommentOfDifferentInstructor.html
  src/test/resources/pages/instructorStudentRecordsPageMixedQuestionType.html
  src/test/resources/pages/instructorStudentRecordsPageWithPrivateFeedback.html
  src/test/resources/pages/instructorStudentRecordsPageWithScriptInjectionProfile.html
Labels: e.1, s.ToMerge

#8540 TimeHelper: migrate to Java 8's `java.time` #8362 - Migrate course `createdAt` and `timeZone` fields
  build.gradle
  src/main/java/teammates/common/datatransfer/attributes/CourseAttributes.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/common/util/FieldValidator.java
  src/main/java/teammates/common/util/JsonUtils.java
  src/main/java/teammates/common/util/TimeHelper.java
  src/main/java/teammates/storage/entity/Course.java
  src/main/webapp/dev/js/common/timezone.js
  src/main/webapp/test/timezone.jsp
  src/test/java/teammates/test/cases/browsertests/TimezoneSyncerTest.java
  src/test/java/teammates/test/cases/datatransfer/CourseAttributesTest.java
  src/test/resources/data/FeedbackSessionsLogicTest.json
  src/test/resources/data/InstructorCourseDetailsPageUiTest.json
  src/test/resources/data/InstructorCourseEditPageUiTest.json
  src/test/resources/data/InstructorCourseStudentDetailsPageUiTest.json
  src/test/resources/data/InstructorFeedbackEditCopyTest.json
  src/test/resources/data/InstructorFeedbackEditPageUiTest.json
  src/test/resources/data/InstructorHomePageUiTest1.json
  src/test/resources/data/InstructorHomePageUiTest2.json
  src/test/resources/data/InstructorSearchPageUiTest.json
  src/test/resources/data/InstructorStudentListPageUiTest.json
  src/test/resources/data/InstructorStudentRecordsPageUiTest.json
  src/test/resources/data/StudentCourseDetailsPageUiTest.json
  src/test/resources/data/StudentCourseJoinAuthenticatedTest.json
  src/test/resources/data/StudentHomePageUiTest.json
  src/test/resources/data/StudentProfilePageUiTest.json
  src/test/resources/data/typicalDataBundle.json
Labels: e.2, s.ToMerge

#8581 Instructor: session results: add a tooltip to the 'Remind all' button #8558
  src/main/webapp/WEB-INF/tags/instructor/results/remindButton.tag
  src/test/resources/pages/instructorFeedbackResultsPageEmpty.html
  src/test/resources/pages/instructorFeedbackResultsPageOpen.html
  src/test/resources/pages/newlyJoinedInstructorFirstFeedbackSessionResultsPage.html
  src/test/resources/pages/newlyJoinedInstructorThirdFeedbackSessionResultsPage.html
Labels: e.1, s.ToMerge

#8551 AccountAttributes: Add test cases for builder #8496
  src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java
Labels: e.2, s.ToMerge

#8377 Replace 'disabled' attributes from HTML anchor tags #7943
  src/main/webapp/WEB-INF/tags/instructor/feedbacks/feedbackSessionActions.tag
  src/main/webapp/WEB-INF/tags/instructor/feedbacks/feedbackSessionPublishButton.tag
  src/main/webapp/WEB-INF/tags/instructor/results/expandCollapseButton.tag
  src/main/webapp/WEB-INF/tags/instructor/results/remindButton.tag
  src/main/webapp/WEB-INF/tags/instructor/studentList.tag
  src/main/webapp/WEB-INF/tags/instructor/studentList/studentsTable.tag
  src/main/webapp/WEB-INF/tags/shared/feedbackResponseCommentRow.tag
  src/main/webapp/WEB-INF/tags/student/home/rowActions.tag
  src/test/java/teammates/test/cases/browsertests/StudentHomePageUiTest.java
  src/test/java/teammates/test/pageobjects/AppPage.java
  src/test/resources/pages/instructorCourseDetailsWithSectionsWithHelperView.html
  src/test/resources/pages/instructorFeedbackAllSessionTypes.html
  src/test/resources/pages/instructorFeedbackAllSessionTypesWithHelperView.html
  src/test/resources/pages/instructorFeedbackDeleteSuccessful.html
  src/test/resources/pages/instructorFeedbackPublishSuccessful.html
  src/test/resources/pages/instructorFeedbackResultsAjaxByQuestion.html
  src/test/resources/pages/instructorFeedbackResultsAjaxByQuestionViewForHelperOne.html
  src/test/resources/pages/instructorFeedbackResultsAjaxByQuestionViewForHelperTwo.html
  src/test/resources/pages/instructorFeedbackResultsPageOpenViewForHelperOne.html
  src/test/resources/pages/instructorFeedbackResultsPageOpenViewForHelperTwo.html
  src/test/resources/pages/instructorFeedbackUnpublishSuccessful.html
  src/test/resources/pages/instructorHomeCourseArchiveSuccessful.html
  src/test/resources/pages/instructorHomeHTML.html
  src/test/resources/pages/instructorHomeHTMLResponseRateFail.html
  src/test/resources/pages/instructorHomeHTMLResponseRatePass.html
  src/test/resources/pages/instructorHomeHTMLSortByDate.html
  src/test/resources/pages/instructorHomeHTMLSortById.html
  src/test/resources/pages/instructorHomeHTMLSortByName.html
  src/test/resources/pages/instructorHomeHTMLSortSessionsByEndDate.html
  src/test/resources/pages/instructorHomeHTMLSortSessionsByName.html
  src/test/resources/pages/instructorHomeHTMLSortSessionsByStartDate.html
  src/test/resources/pages/instructorHomeHTMLWithHelperView.html
  src/test/resources/pages/instructorStudentListWithHelperView.html
  src/test/resources/pages/newlyJoinedInstructorFirstFeedbackSessionResultsPage.html
  src/test/resources/pages/newlyJoinedInstructorHomePage.html
  src/test/resources/pages/newlyJoinedInstructorThirdFeedbackSessionResultsPage.html
  src/test/resources/pages/studentHomeFeedbackDeletedHTML.html
  src/test/resources/pages/studentHomeTypicalHTML.html
Labels: e.4, s.ToMerge

#8535 Instructor: remind students: send email copies only to requesting instructor #8531
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/main/java/teammates/logic/api/TaskQueuer.java
  src/main/java/teammates/ui/automated/FeedbackSessionRemindEmailWorkerAction.java
  src/main/java/teammates/ui/automated/FeedbackSessionRemindParticularUsersEmailWorkerAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackRemindAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackRemindParticularStudentsAction.java
  src/test/java/teammates/test/cases/automated/FeedbackSessionRemindEmailWorkerActionTest.java
  src/test/java/teammates/test/cases/automated/FeedbackSessionRemindParticularUsersEmailWorkerActionTest.java
  src/test/java/teammates/test/cases/logic/EmailGeneratorTest.java
Labels: e.2, s.ToMerge

#8587 Update third-party dependencies #8566
  build.gradle
  docs/static-analysis.md
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  package.json
  src/main/java/teammates/logic/core/SendgridService.java
  src/main/resources/package.json
  src/main/webapp/stylesheets/teammatesCommon.css
  src/test/java/teammates/test/cases/logic/EmailSenderTest.java
  src/test/java/teammates/test/driver/HtmlHelper.java
  src/test/resources/pages/instructorCourseEditHelper.html
  src/test/resources/pages/instructorCoursesNoCourse.html
  src/test/resources/pages/instructorFeedbackEditEmpty.html
  src/test/resources/pages/instructorFeedbackEmptyAll.html
  src/test/resources/pages/instructorFeedbackResultsPageOpen.html
  src/test/resources/pages/instructorFeedbackSubmitPageAwaiting.html
  src/test/resources/pages/instructorStudentRecords.html
  src/test/resources/pages/studentFeedbackSubmitPageAwaiting.html
  src/test/resources/pages/unregisteredStudentFeedbackSubmitPageOpen.html
  static-analysis/teammates-eslint.yml
  static-analysis/teammates-stylelint.yml
Labels: e.2, s.ToMerge

#8564 TimeHelper: migrate to Java 8's `java.time` #8362 - migrate is/get methods in TimeHelper
  src/main/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributes.java
  src/main/java/teammates/common/util/StringHelper.java
  src/main/java/teammates/common/util/TimeHelper.java
  src/test/java/teammates/test/cases/browsertests/AutomatedSessionRemindersTest.java
  src/test/java/teammates/test/cases/util/TimeHelperTest.java
  src/test/java/teammates/test/driver/AssertHelper.java
  src/test/java/teammates/test/driver/TimeHelperExtension.java
Labels: e.2, s.ToMerge

#8602 Update workflow/process documents #8565
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/help-request.md
  .github/template-bugReport.md
  .github/template-contributorIntro.md
  README.md
  docs/community.md
  docs/issues.md
  docs/orientation-guide.md
  docs/process.md
Labels: e.1, s.ToMerge

#8384 Instructor: edit question: fix erratic behavior when editing followed by deleting #8333
  src/main/webapp/dev/js/main/instructorFeedbackEdit.js
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java
Labels: e.2, s.ToMerge

#8548 Instructor: students: all records: fix error when course has a session with null startTime #8547
  src/main/java/teammates/common/datatransfer/attributes/SessionAttributes.java
Labels: e.1, s.ToMerge

#8443 Sessions: student view results: stop showing a random identifier for anonymous responses #6092
  src/main/java/teammates/ui/pagedata/StudentFeedbackResultsPageData.java
  src/test/resources/pages/newlyJoinedInstructorStudentFeedbackResultsPage.html
  src/test/resources/pages/studentExtendedFeedbackResultsPageRubric.html
  src/test/resources/pages/studentFeedbackResultsPageMCQ.html
  src/test/resources/pages/studentFeedbackResultsPageNUMSCALE.html
  src/test/resources/pages/studentFeedbackResultsPageNewlyRegistered.html
  src/test/resources/pages/studentFeedbackResultsPageOpen.html
  src/test/resources/pages/studentFeedbackResultsPageRank.html
  src/test/resources/pages/studentFeedbackResultsPageTeamToTeam.html
  src/test/resources/pages/unregisteredStudentFeedbackResultsPageMCQ.html
  src/test/resources/pages/unregisteredStudentFeedbackResultsPageOpen.html
Labels: e.1, s.ToMerge

#8604 Instructor: Edit session : Distribute (Options) question : Points per option button stays hidden #8603
  src/main/webapp/dev/js/main/instructorFeedbackEdit.js
  src/test/java/teammates/test/cases/browsertests/FeedbackConstSumOptionQuestionUiTest.java
Labels: s.ToMerge

#8293 Instructor: edit feedback session: show course name and session status in edit form #1103
  src/main/java/teammates/ui/pagedata/InstructorFeedbackEditPageData.java
  src/main/java/teammates/ui/pagedata/InstructorFeedbackSessionsPageData.java
  src/main/java/teammates/ui/template/FeedbackSessionsForm.java
  src/main/webapp/WEB-INF/tags/instructor/feedbacks/feedbackSessionsForm.tag
  src/main/webapp/dev/js/main/instructorFeedbacks.js
  src/main/webapp/jsp/instructorFeedbackEdit.jsp
  src/main/webapp/jsp/instructorFeedbacks.jsp
  src/test/resources/pages/instructorFeedbackAddSuccess.html
  src/test/resources/pages/instructorFeedbackAllSessionTypes.html
  src/test/resources/pages/instructorFeedbackAllSessionTypesWithHelperView.html
  src/test/resources/pages/instructorFeedbackConstSumOptionQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackConstSumOptionQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackConstSumRecipientQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackConstSumRecipientQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackContribQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackContribQuestionEdit.html
  src/test/resources/pages/instructorFeedbackContribQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackCopyQuestionSuccess.html
  src/test/resources/pages/instructorFeedbackCopySuccess.html
  src/test/resources/pages/instructorFeedbackCopyTrimmedSuccess.html
  src/test/resources/pages/instructorFeedbackDeleteSuccessful.html
  src/test/resources/pages/instructorFeedbackEditCopyFail.html
  src/test/resources/pages/instructorFeedbackEditCopyPage.html
  src/test/resources/pages/instructorFeedbackEditCopySuccess.html
  src/test/resources/pages/instructorFeedbackEditEmpty.html
  src/test/resources/pages/instructorFeedbackEditManuallyPublished.html
  src/test/resources/pages/instructorFeedbackEditPageTestingSanitization.html
  src/test/resources/pages/instructorFeedbackEditSuccess.html
  src/test/resources/pages/instructorFeedbackEmptyAll.html
  src/test/resources/pages/instructorFeedbackEmptySession.html
  src/test/resources/pages/instructorFeedbackMcqQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackMcqQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackMsqQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackMsqQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackNumScaleQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackNumScaleQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackPublishSuccessful.html
  src/test/resources/pages/instructorFeedbackQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackQuestionEditToTeamToTeam.html
  src/test/resources/pages/instructorFeedbackQuestionVisibilityOptions.html
  src/test/resources/pages/instructorFeedbackQuestionVisibilityPreview.html
  src/test/resources/pages/instructorFeedbackRankMinMaxChoicesSuccess.html
  src/test/resources/pages/instructorFeedbackRankQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackRankQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEdit.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditChoiceSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditDescriptionSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditSubQuestionSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditWeightSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionMoveColumnNewQuestionSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionMoveColumnSuccess.html
  src/test/resources/pages/instructorFeedbackTeamPeerEvalTemplateAddSuccess.html
  src/test/resources/pages/instructorFeedbackUnpublishSuccessful.html
Labels: s.ToMerge

#8637 Migrate *Attributes time fields from Date to Instant #8636
  src/main/java/teammates/common/datatransfer/attributes/AccountAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/AdminEmailAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/FeedbackQuestionAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/FeedbackResponseAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/FeedbackResponseCommentAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/StudentAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/StudentProfileAttributes.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/AdminEmailsLogic.java
  src/main/java/teammates/logic/core/FeedbackResponseCommentsLogic.java
  src/main/java/teammates/storage/api/AdminEmailsDb.java
  src/main/java/teammates/storage/api/FeedbackResponseCommentsDb.java
  src/main/java/teammates/storage/api/ProfilesDb.java
  src/main/java/teammates/storage/entity/Account.java
  src/main/java/teammates/storage/entity/AdminEmail.java
  src/main/java/teammates/storage/entity/CourseStudent.java
  src/main/java/teammates/storage/entity/FeedbackQuestion.java
  src/main/java/teammates/storage/entity/FeedbackResponse.java
  src/main/java/teammates/storage/entity/FeedbackResponseComment.java
  src/main/java/teammates/storage/entity/StudentProfile.java
  src/main/java/teammates/storage/search/FeedbackResponseCommentSearchDocument.java
  src/main/java/teammates/ui/controller/AdminEmailComposeSendAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackResponseCommentAddAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackResponseCommentEditAction.java
  src/main/java/teammates/ui/pagedata/InstructorFeedbackResponseCommentAjaxPageData.java
  src/main/java/teammates/ui/pagedata/PageData.java
  src/main/java/teammates/ui/template/AdminAccountManagementAccountTableRow.java
  src/main/java/teammates/ui/template/AdminActivityLogTableRow.java
  src/main/java/teammates/ui/template/FeedbackResponseCommentRow.java
  src/main/resources/InstructorSampleData.json
  src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java
  src/test/java/teammates/test/cases/datatransfer/AdminEmailAttributesTest.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackQuestionAttributesTest.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackResponseAttributesTest.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackResponseCommentAttributesTest.java
  src/test/java/teammates/test/cases/datatransfer/StudentAttributesTest.java
  src/test/java/teammates/test/cases/datatransfer/StudentProfileAttributesTest.java
  src/test/java/teammates/test/cases/storage/AccountsDbTest.java
  src/test/java/teammates/test/cases/storage/FeedbackQuestionsDbTest.java
  src/test/java/teammates/test/cases/storage/FeedbackResponseCommentsDbTest.java
  src/test/java/teammates/test/cases/storage/FeedbackResponsesDbTest.java
  src/test/java/teammates/test/cases/storage/StudentsDbTest.java
  src/test/java/teammates/test/driver/AssertHelper.java
  src/test/resources/data/AllAccessControlUiTest.json
  src/test/resources/data/FeedbackSessionsLogicTest.json
  src/test/resources/data/InstructorFeedbackResultsPageUiTest.json
  src/test/resources/data/InstructorSearchPageUiTest.json
  src/test/resources/data/InstructorStudentRecordsPageUiTest.json
  src/test/resources/data/MashupPageUiTest.json
  src/test/resources/data/StudentFeedbackResultsPageUiTest.json
  src/test/resources/data/StudentFeedbackSubmissionEditPageActionTest.json
  src/test/resources/data/typicalDataBundle.json
Labels: e.1, s.ToMerge

#8642 Migrate FeedbackSessionAttributes gracePeriod field to Duration #8641
  src/main/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributes.java
  src/main/java/teammates/common/util/JsonUtils.java
  src/main/java/teammates/storage/api/FeedbackSessionsDb.java
  src/main/java/teammates/storage/entity/FeedbackSession.java
  src/main/java/teammates/ui/controller/InstructorFeedbackAbstractAction.java
  src/main/java/teammates/ui/pagedata/PageData.java
  src/main/java/teammates/ui/template/FeedbackSessionsForm.java
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/StudentFeedbackSubmitPageUiTest.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackSessionAttributesTest.java
  src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
  src/test/java/teammates/test/cases/logic/StudentsLogicTest.java
  src/test/java/teammates/test/cases/storage/FeedbackSessionsDbTest.java
  src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
  src/test/java/teammates/test/pageobjects/InstructorFeedbackSessionsPage.java
Labels: e.1, s.ToMerge

#8367 Student: submit responses: mention that partial answers can be saved #7993
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/controller/FeedbackSubmissionEditPageAction.java
  src/main/java/teammates/ui/controller/FeedbackSubmissionEditSaveAction.java
  src/test/java/teammates/test/cases/action/InstructorFeedbackSubmissionEditPageActionTest.java
  src/test/java/teammates/test/cases/action/StudentFeedbackSubmissionEditPageActionTest.java
  src/test/java/teammates/test/cases/browsertests/AdminAccountDetailsPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/AdminAccountManagementPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/AdminActivityLogPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/AdminEmailPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java
  src/test/java/teammates/test/cases/browsertests/AdminSearchPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/AdminSessionsPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/AllAccessControlUiTests.java
  src/test/java/teammates/test/cases/browsertests/FeedbackConstSumOptionQuestionUiTest.java
  src/test/java/teammates/test/cases/browsertests/FeedbackConstSumRecipientQuestionUiTest.java
  src/test/java/teammates/test/cases/browsertests/FeedbackContributionQuestionUiTest.java
  src/test/java/teammates/test/cases/browsertests/FeedbackMcqQuestionUiTest.java
  src/test/java/teammates/test/cases/browsertests/FeedbackMsqQuestionUiTest.java
  src/test/java/teammates/test/cases/browsertests/FeedbackNumScaleQuestionUiTest.java
  src/test/java/teammates/test/cases/browsertests/FeedbackRankQuestionUiTest.java
  src/test/java/teammates/test/cases/browsertests/FeedbackRubricQuestionUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorCourseDetailsPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorCourseEditPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorCourseEnrollPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorCourseJoinConfirmationPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorCourseStudentDetailsEditPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorCoursesPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorEditStudentFeedbackPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditCopyUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSubmitPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorHomePageUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorStudentListPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/StudentCourseJoinConfirmationPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/StudentFeedbackSubmitPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java
  src/test/java/teammates/test/cases/browsertests/SystemErrorEmailReportTest.java
  src/test/java/teammates/test/pageobjects/AppPage.java
  src/test/resources/pages/instructorFeedbackResultsPageRankSubmission.html
  src/test/resources/pages/instructorFeedbackSubmitPageEmpty.html
  src/test/resources/pages/instructorFeedbackSubmitPageFullyFilled.html
  src/test/resources/pages/instructorFeedbackSubmitPageModified.html
  src/test/resources/pages/instructorFeedbackSubmitPageOpen.html
  src/test/resources/pages/instructorFeedbackSubmitPageOpenWithHelperView.html
  src/test/resources/pages/instructorFeedbackSubmitPagePartiallyFilled.html
  src/test/resources/pages/instructorFeedbackSubmitPagePrivate.html
  src/test/resources/pages/instructorFeedbackSubmitPageRankHelper.html
  src/test/resources/pages/studentFeedbackSubmitPageEmpty.html
  src/test/resources/pages/studentFeedbackSubmitPageFullyFilled.html
  src/test/resources/pages/studentFeedbackSubmitPageModified.html
  src/test/resources/pages/studentFeedbackSubmitPageOpen.html
  src/test/resources/pages/studentFeedbackSubmitPagePartiallyFilled.html
  src/test/resources/pages/studentFeedbackSubmitPageRank.html
  src/test/resources/pages/studentFeedbackSubmitPageRubricSuccess.html
  src/test/resources/pages/studentFeedbackSubmitPageSuccessRank.html
  src/test/resources/pages/unregisteredStudentFeedbackSubmitPageOpen.html
Labels: s.ToMerge

#8654 Feedback Sessions: migrate sessions with 'Never Publish' option in JSON files #8652
  src/test/resources/data/AllAccessControlUiTest.json
  src/test/resources/data/FeedbackSessionDetailsTest.json
  src/test/resources/data/FeedbackSessionResultsTest.json
  src/test/resources/data/FeedbackSessionsLogicTest.json
  src/test/resources/data/InstructorFeedbackQuestionSubmitPageUiTest.json
  src/test/resources/data/InstructorFeedbackSessionsPageUiTest.json
  src/test/resources/data/InstructorFeedbackSubmissionEditSaveActionTest.json
  src/test/resources/data/InstructorFeedbackSubmitPageUiTest.json
  src/test/resources/data/InstructorHomePageUiTest2.json
  src/test/resources/data/InstructorSubmissionAdjustmentUiTest.json
  src/test/resources/data/MashupPageUiTest.json
  src/test/resources/data/StudentFeedbackSubmissionEditPageActionTest.json
  src/test/resources/data/typicalDataBundle.json
Labels: e.1, s.ToMerge

#8656 TimeHelper: convertLocalDateToUtc: do not shift special time representations #8655
  src/main/java/teammates/common/util/TimeHelper.java
  src/test/java/teammates/test/cases/util/TimeHelperTest.java
Labels: e.1, s.ToMerge

#8658 Release V6.4.0 #8657
  src/main/webapp/data/developers.json
Labels: e.1, s.ToMerge

#8679 Instructor: search responses: handle legacy search documents #8662
  src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocumentDateFormat.java
  src/main/java/teammates/common/util/JsonUtils.java
Labels: e.1, s.ToMerge

#8682 SendgridService: fix successful request detection #8663
  src/main/java/teammates/logic/core/EmailSenderService.java
  src/main/java/teammates/logic/core/MailgunService.java
  src/main/java/teammates/logic/core/MailjetService.java
  src/main/java/teammates/logic/core/SendgridService.java
Labels: e.1, s.ToMerge

#8612 Distribute points questions: fix total points to distribute being reset to non-default value #8605
  src/main/java/teammates/common/datatransfer/questions/FeedbackConstantSumQuestionDetails.java
  src/main/webapp/dev/js/common/questionConstSum.js
  src/main/webapp/dev/js/main/instructorFeedbackEdit.js
  src/test/java/teammates/test/cases/browsertests/FeedbackConstSumOptionQuestionUiTest.java
  src/test/java/teammates/test/cases/browsertests/FeedbackConstSumRecipientQuestionUiTest.java
  src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
Labels: e.1, s.ToMerge

#8584 Instuctor : Feedback Questions : MCQ/MSQ questions : Disable drop down menu by default #8576
  src/main/java/teammates/common/datatransfer/questions/FeedbackMcqQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackMsqQuestionDetails.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/common/util/Templates.java
  src/main/resources/feedbackQuestionMcqEditFormTemplate.html
  src/main/resources/feedbackQuestionMsqEditFormTemplate.html
  src/main/webapp/WEB-INF/tags/instructor/feedbackEdit/newQuestionForm.tag
  src/main/webapp/dev/js/common/questionMcq.js
  src/main/webapp/dev/js/common/questionMsq.js
  src/main/webapp/dev/js/main/instructorFeedbackEdit.js
  src/main/webapp/partials/instructorHelpSessions.jsp
  src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionAddActionTest.java
  src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionEditActionTest.java
  src/test/java/teammates/test/cases/browsertests/FeedbackMcqQuestionUiTest.java
  src/test/java/teammates/test/cases/browsertests/FeedbackMsqQuestionUiTest.java
  src/test/resources/pages/instructorFeedbackAddSuccess.html
  src/test/resources/pages/instructorFeedbackConstSumOptionQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackConstSumOptionQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackConstSumRecipientQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackConstSumRecipientQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackContribQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackContribQuestionEdit.html
  src/test/resources/pages/instructorFeedbackContribQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackCopyQuestionSuccess.html
  src/test/resources/pages/instructorFeedbackCopySuccess.html
  src/test/resources/pages/instructorFeedbackCopyTrimmedSuccess.html
  src/test/resources/pages/instructorFeedbackEditCopyFail.html
  src/test/resources/pages/instructorFeedbackEditCopyPage.html
  src/test/resources/pages/instructorFeedbackEditEmpty.html
  src/test/resources/pages/instructorFeedbackEditManuallyPublished.html
  src/test/resources/pages/instructorFeedbackEditPageTestingSanitization.html
  src/test/resources/pages/instructorFeedbackEditSuccess.html
  src/test/resources/pages/instructorFeedbackMcqQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackMcqQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackMsqQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackMsqQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackNumScaleQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackNumScaleQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackQuestionEditToTeamToTeam.html
  src/test/resources/pages/instructorFeedbackQuestionVisibilityOptions.html
  src/test/resources/pages/instructorFeedbackQuestionVisibilityPreview.html
  src/test/resources/pages/instructorFeedbackRankMinMaxChoicesSuccess.html
  src/test/resources/pages/instructorFeedbackRankQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackRankQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEdit.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditChoiceSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditDescriptionSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditSubQuestionSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditWeightSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionMoveColumnNewQuestionSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionMoveColumnSuccess.html
  src/test/resources/pages/instructorFeedbackTeamPeerEvalTemplateAddSuccess.html
Labels: s.ToMerge

#8600 Instructor: add new session: rename session template options #8563
  src/main/java/teammates/ui/pagedata/InstructorFeedbackSessionsPageData.java
  src/main/webapp/partials/instructorHelpGettingStarted.jsp
  src/main/webapp/partials/instructorHelpSessions.jsp
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java
  src/test/java/teammates/test/cases/pagedata/InstructorFeedbackSessionsPageDataTest.java
  src/test/resources/pages/instructorFeedbackAllSessionTypes.html
  src/test/resources/pages/instructorFeedbackAllSessionTypesWithHelperView.html
  src/test/resources/pages/instructorFeedbackDeleteSuccessful.html
  src/test/resources/pages/instructorFeedbackEditCopySuccess.html
  src/test/resources/pages/instructorFeedbackEmptyAll.html
  src/test/resources/pages/instructorFeedbackEmptySession.html
  src/test/resources/pages/instructorFeedbackPublishSuccessful.html
  src/test/resources/pages/instructorFeedbackUnpublishSuccessful.html
Labels: e.1, s.ToMerge

#8651 Admin: recent activity log: show correct 'time stamp in instructor timezone' #8594
  src/main/java/teammates/common/util/TimeHelper.java
  src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java
  src/main/java/teammates/ui/pagedata/AdminActivityLogPageData.java
  src/main/webapp/dev/js/main/adminActivityLog.js
  src/test/java/teammates/test/cases/action/AdminActivityLogPageActionTest.java
  src/test/java/teammates/test/cases/browsertests/AdminActivityLogPageUiTest.java
  src/test/java/teammates/test/pageobjects/AdminActivityLogPage.java
  src/test/resources/data/typicalDataBundle.json
Labels: e.2, s.ToMerge

#8626 Update workflow/process documents #8565
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/help-request.md
  .github/SUPPORT.md
  README.md
  appveyor.yml
  docs/CONTRIBUTING.md
  docs/development.md
  docs/images/IssueLifecycle.png
  docs/images/IssueLifecycle.pptx
  docs/images/RolesAndTechnologies.png
  docs/images/RolesAndTechnologies.pptx
  docs/images/workflow.png
  docs/images/workflow.pptx
  docs/maintainer-guide.md
  docs/orientation-guide.md
  docs/process.md
  src/test/resources/test.template.properties
Labels: s.FinalReview

#8698 JsonUtils: remove code handling legacy data #8681
  src/main/java/teammates/common/util/JsonUtils.java
Labels: e.1, s.ToMerge

#8653 Instructor: remind particular students: show sorted student list #8630
  src/main/java/teammates/common/datatransfer/FeedbackSessionResponseStatus.java
  src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/ui/template/InstructorFeedbackResultsNoResponsePanel.java
  src/main/webapp/jsp/instructorFeedbackAjaxRemindParticularStudentsModal.jsp
  src/test/java/teammates/test/cases/action/InstructorFeedbackRemindParticularStudentsPageActionTest.java
  src/test/java/teammates/test/cases/automated/FeedbackSessionUpdateRespondentWorkerActionTest.java
Labels: e.1, s.ToMerge

#8711 AdminActivityLogPage: Typo in Log for adminSearchPage Load #8707
  src/main/java/teammates/ui/controller/AdminSearchPageAction.java
Labels: e.1, s.ToMerge

#8373 Instructor: add ranking question: leave min/max boxes empty by default #8320
  src/main/java/teammates/common/datatransfer/questions/FeedbackRankOptionsQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRankQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRankRecipientsQuestionDetails.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/common/util/Templates.java
  src/main/resources/feedbackQuestionRankOptionsEditFormTemplate.html
  src/main/resources/feedbackQuestionRankRecipientsEditFormTemplate.html
  src/main/resources/feedbackQuestionRankSubmissionFormTemplate.html
  src/main/webapp/dev/js/common/const.js
  src/main/webapp/dev/js/common/questionRank.js
  src/main/webapp/dev/js/main/instructorFeedbackEdit.js
  src/test/java/teammates/test/cases/browsertests/FeedbackRankQuestionUiTest.java
  src/test/java/teammates/test/pageobjects/AppPage.java
  src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
  src/test/resources/pages/instructorFeedbackAddSuccess.html
  src/test/resources/pages/instructorFeedbackConstSumOptionQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackConstSumOptionQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackConstSumRecipientQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackConstSumRecipientQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackContribQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackContribQuestionEdit.html
  src/test/resources/pages/instructorFeedbackContribQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackCopyQuestionSuccess.html
  src/test/resources/pages/instructorFeedbackCopySuccess.html
  src/test/resources/pages/instructorFeedbackCopyTrimmedSuccess.html
  src/test/resources/pages/instructorFeedbackEditCopyFail.html
  src/test/resources/pages/instructorFeedbackEditCopyPage.html
  src/test/resources/pages/instructorFeedbackEditEmpty.html
  src/test/resources/pages/instructorFeedbackEditManuallyPublished.html
  src/test/resources/pages/instructorFeedbackEditPageTestingSanitization.html
  src/test/resources/pages/instructorFeedbackEditSuccess.html
  src/test/resources/pages/instructorFeedbackMcqQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackMcqQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackMsqQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackMsqQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackNumScaleQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackNumScaleQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackQuestionEditToTeamToTeam.html
  src/test/resources/pages/instructorFeedbackQuestionVisibilityOptions.html
  src/test/resources/pages/instructorFeedbackQuestionVisibilityPreview.html
  src/test/resources/pages/instructorFeedbackRankMinMaxChoicesSuccess.html
  src/test/resources/pages/instructorFeedbackRankQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackRankQuestionEdit.html
  src/test/resources/pages/instructorFeedbackRankQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEdit.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditChoiceSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditDescriptionSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditSubQuestionSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditWeightSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionMoveColumnNewQuestionSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionMoveColumnSuccess.html
  src/test/resources/pages/instructorFeedbackTeamPeerEvalTemplateAddSuccess.html
Labels: s.ToMerge

#8672 Sessions: add/edit: validate gracePeriod values #8643
  src/main/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributes.java
  src/main/java/teammates/common/util/FieldValidator.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackSessionAttributesTest.java
Labels: e.1, s.ToMerge

#8489 Update user map for Jan 2018 #8473
  src/main/webapp/data/userMapData.json
Labels: s.ToMerge

#8633 Instructor: search: rename tick box to be more accurate #8526
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/controller/InstructorSearchPageAction.java
  src/main/java/teammates/ui/pagedata/InstructorSearchPageData.java
  src/main/java/teammates/ui/template/SearchFeedbackSessionDataTable.java
  src/main/webapp/WEB-INF/tags/instructor/home/search.tag
  src/main/webapp/WEB-INF/tags/instructor/search/feedbackSessionDataSearchResults.tag
  src/main/webapp/WEB-INF/tags/instructor/search/searchPageInput.tag
  src/main/webapp/WEB-INF/tags/instructor/studentList/searchBox.tag
  src/main/webapp/instructorHelp.jsp
  src/main/webapp/jsp/instructorSearch.jsp
  src/main/webapp/partials/instructorHelpComments.jsp
  src/main/webapp/partials/instructorHelpSearch.jsp
  src/main/webapp/partials/instructorHelpSessions.jsp
  src/test/java/teammates/test/pageobjects/InstructorSearchPage.java
  src/test/resources/pages/instructorHomeCourseArchiveSuccessful.html
  src/test/resources/pages/instructorHomeCourseDeleteSuccessful.html
  src/test/resources/pages/instructorHomeHTML.html
  src/test/resources/pages/instructorHomeHTMLEmpty.html
  src/test/resources/pages/instructorHomeHTMLPersistenceCheck.html
  src/test/resources/pages/instructorHomeHTMLResponseRateFail.html
  src/test/resources/pages/instructorHomeHTMLResponseRatePass.html
  src/test/resources/pages/instructorHomeHTMLSortByDate.html
  src/test/resources/pages/instructorHomeHTMLSortById.html
  src/test/resources/pages/instructorHomeHTMLSortByName.html
  src/test/resources/pages/instructorHomeHTMLSortSessionsByEndDate.html
  src/test/resources/pages/instructorHomeHTMLSortSessionsByName.html
  src/test/resources/pages/instructorHomeHTMLSortSessionsByStartDate.html
  src/test/resources/pages/instructorHomeHTMLWithHelperView.html
  src/test/resources/pages/instructorHomeHTMLWithUnloadedCourse.html
  src/test/resources/pages/instructorHomeNewInstructorWithSampleCourse.html
  src/test/resources/pages/instructorHomeNewInstructorWithoutSampleCourse.html
  src/test/resources/pages/instructorHomeTestingSanitization.html
  src/test/resources/pages/instructorSearchPageDefault.html
  src/test/resources/pages/instructorSearchPageSearchCommentsAsHelper.html
  src/test/resources/pages/instructorSearchPageSearchFeedbackResponseComments.html
  src/test/resources/pages/instructorSearchPageSearchNone.html
  src/test/resources/pages/instructorSearchPageSearchStudentsForStudent1.html
  src/test/resources/pages/instructorSearchPageSearchStudentsForStudent2.html
  src/test/resources/pages/instructorSearchPageSearchStudentsForStudent2WithExactString.html
  src/test/resources/pages/instructorSearchPageSearchTestingSanitization.html
  src/test/resources/pages/instructorStudentList.html
  src/test/resources/pages/instructorStudentListPageDisplayArchivedCourses.html
  src/test/resources/pages/instructorStudentListPageHideArchivedCourses.html
  src/test/resources/pages/instructorStudentListPageNoCourse.html
  src/test/resources/pages/instructorStudentListPageNoStudent.html
  src/test/resources/pages/instructorStudentListPageSearchNoMatch.html
  src/test/resources/pages/instructorStudentListPageSearchStudent.html
  src/test/resources/pages/instructorStudentListPageSearchStudentMultiple.html
  src/test/resources/pages/instructorStudentListPageTestingSanitization.html
  src/test/resources/pages/instructorStudentListPageWithPicture.html
  src/test/resources/pages/instructorStudentListWithHelperView.html
  src/test/resources/pages/newlyJoinedInstructorHomePage.html
Labels: e.2, s.ToMerge

#8553 StudentFeedbackResultsPage: move additional information about work distribution to lightbox #8498
  src/main/resources/feedbackQuestionContribAdditionalInfoTemplate.html
  src/main/resources/feedbackQuestionContribResultStatsStudentViewAdditionalInfo.html
  src/main/resources/feedbackQuestionContribResultStatsStudentViewTemplate.html
  src/test/resources/pages/newlyJoinedInstructorStudentFeedbackResultsPage.html
  src/test/resources/pages/studentFeedbackResultsPageCONTRIB.html
Labels: e.2, s.ToMerge

#8689 Instructor: edit session: multiple choice questions: support generating options for all other teams #8661
  src/main/java/teammates/common/datatransfer/FeedbackParticipantType.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackMcqQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackMsqQuestionDetails.java
  src/main/java/teammates/common/util/Templates.java
  src/main/resources/feedbackQuestionMcqEditFormTemplate.html
  src/main/resources/feedbackQuestionMsqEditFormTemplate.html
  src/test/java/teammates/test/cases/browsertests/FeedbackMcqQuestionUiTest.java
  src/test/java/teammates/test/cases/browsertests/FeedbackMsqQuestionUiTest.java
  src/test/java/teammates/test/cases/browsertests/StudentFeedbackSubmitPageUiTest.java
  src/test/resources/data/StudentFeedbackSubmitPageUiTest.json
  src/test/resources/pages/instructorFeedbackAddSuccess.html
  src/test/resources/pages/instructorFeedbackConstSumOptionQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackConstSumOptionQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackConstSumRecipientQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackConstSumRecipientQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackContribQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackContribQuestionEdit.html
  src/test/resources/pages/instructorFeedbackContribQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackCopyQuestionSuccess.html
  src/test/resources/pages/instructorFeedbackCopySuccess.html
  src/test/resources/pages/instructorFeedbackCopyTrimmedSuccess.html
  src/test/resources/pages/instructorFeedbackEditCopyFail.html
  src/test/resources/pages/instructorFeedbackEditCopyPage.html
  src/test/resources/pages/instructorFeedbackEditEmpty.html
  src/test/resources/pages/instructorFeedbackEditManuallyPublished.html
  src/test/resources/pages/instructorFeedbackEditPageTestingSanitization.html
  src/test/resources/pages/instructorFeedbackEditSuccess.html
  src/test/resources/pages/instructorFeedbackMcqQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackMcqQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackMsqQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackMsqQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackNumScaleQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackNumScaleQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackQuestionEditToTeamToTeam.html
  src/test/resources/pages/instructorFeedbackQuestionVisibilityOptions.html
  src/test/resources/pages/instructorFeedbackQuestionVisibilityPreview.html
  src/test/resources/pages/instructorFeedbackRankMinMaxChoicesSuccess.html
  src/test/resources/pages/instructorFeedbackRankQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackRankQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEdit.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditChoiceSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditDescriptionSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditSubQuestionSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditWeightSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionMoveColumnNewQuestionSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionMoveColumnSuccess.html
  src/test/resources/pages/instructorFeedbackTeamPeerEvalTemplateAddSuccess.html
  src/test/resources/pages/studentFeedbackSubmitPageFullyFilled.html
  src/test/resources/pages/studentFeedbackSubmitPageModified.html
  src/test/resources/pages/studentFeedbackSubmitPageOpen.html
  src/test/resources/pages/studentFeedbackSubmitPagePartiallyFilled.html
  src/test/resources/pages/unregisteredStudentFeedbackSubmitPageOpen.html
  src/test/resources/pages/unregisteredStudentFeedbackSubmitPagePartiallyFilled.html
Labels: e.2, s.ToMerge

#8703 Add script to delete orphaned comment search documents #8702
  src/client/java/teammates/client/scripts/DataMigrationBaseScript.java
  src/client/java/teammates/client/scripts/DataMigrationForEntities.java
  src/client/java/teammates/client/scripts/DataMigrationForFeedbackResponseCommentSearchDocument.java
  src/client/java/teammates/client/scripts/DataMigrationForOrphanedCommentSearchDocuments.java
  src/client/java/teammates/client/scripts/DataMigrationForSanitizedDataInAdminEmailAttributes.java
  src/client/java/teammates/client/scripts/DataMigrationForSanitizedDataInCourseAttributes.java
  src/client/java/teammates/client/scripts/DataMigrationForSanitizedDataInStudentAttributes.java
  src/client/java/teammates/client/scripts/DataMigrationForSanitizedDataInStudentProfileAttributes.java
Labels: e.1, s.ToMerge

#8713 Upgrade to Webpack 4 #8712
  docs/setting-up.md
  package.json
  webpack-main.config.js
  webpack-test.config.js
Labels: s.ToMerge

#8697 Instructor: Edit question: Check for empty string in Numscale/MSQ/Rank (Options/Recipients) number fields #8683
  src/main/java/teammates/ui/controller/InstructorFeedbackQuestionEditAction.java
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java
Labels: e.1, s.ToMerge
