Repository TEAMMATES/teammates, pull requests merged in 2018-10, with the labels that each got.

#9098 [#9096] Logic.java: Clean up unused methods
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/FeedbackResponseCommentsLogic.java
  src/main/java/teammates/logic/core/FeedbackResponsesLogic.java
  src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
  src/test/java/teammates/test/cases/logic/FeedbackResponseCommentsLogicTest.java
  src/test/java/teammates/test/cases/logic/FeedbackResponsesLogicTest.java
Labels: c.Task, s.ToMerge

#9159 [#9157] AssertionError: If the instructor hasn't been retrieved yet there is some problem in adding of instructor
  src/main/java/teammates/ui/automated/InstructorCourseJoinEmailWorkerAction.java
  src/main/java/teammates/ui/automated/StudentCourseJoinEmailWorkerAction.java
  src/main/java/teammates/ui/controller/InstructorCourseInstructorAddAction.java
  src/test/java/teammates/test/cases/action/InstructorCourseInstructorAddActionTest.java
Labels: c.Bug, s.ToMerge

#9172 [#8527] Migrate back to JUnit 4's Assert API
  build.gradle
  src/test/java/teammates/test/cases/BaseTestCase.java
  src/test/java/teammates/test/driver/AssertHelper.java
  src/test/java/teammates/test/driver/EmailChecker.java
  src/test/java/teammates/test/driver/GaeSimulation.java
  src/test/java/teammates/test/driver/HtmlHelper.java
  src/test/java/teammates/test/pageobjects/AdminAccountDetailsPage.java
  src/test/java/teammates/test/pageobjects/AdminAccountManagementPage.java
  src/test/java/teammates/test/pageobjects/AdminActivityLogPage.java
  src/test/java/teammates/test/pageobjects/AdminEmailLogPage.java
  src/test/java/teammates/test/pageobjects/AppPage.java
  src/test/java/teammates/test/pageobjects/FeedbackSubmitPage.java
  src/test/java/teammates/test/pageobjects/InstructorCopyFsToModal.java
  src/test/java/teammates/test/pageobjects/InstructorCourseDetailsPage.java
  src/test/java/teammates/test/pageobjects/InstructorCourseEditPage.java
  src/test/java/teammates/test/pageobjects/InstructorCourseEnrollPage.java
  src/test/java/teammates/test/pageobjects/InstructorCourseStudentDetailsEditPage.java
  src/test/java/teammates/test/pageobjects/InstructorCourseStudentDetailsViewPage.java
  src/test/java/teammates/test/pageobjects/InstructorCoursesPage.java
  src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
  src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java
  src/test/java/teammates/test/pageobjects/InstructorFeedbackSessionsPage.java
  src/test/java/teammates/test/pageobjects/InstructorStudentRecordsPage.java
  src/test/java/teammates/test/pageobjects/StudentProfilePage.java
  src/test/java/teammates/test/pageobjects/StudentProfilePicturePage.java
  src/test/java/teammates/test/pageobjects/UserErrorReportPage.java
  static-analysis/teammates-checkstyle.xml
Labels: s.ToMerge

#9173 [#9059] Testing: Use correct EXPECTED_SNIPPET_SIGN_IN in GoogleLoginPage
  src/test/java/teammates/test/pageobjects/GoogleLoginPage.java
Labels: c.Task, s.ToMerge

#9138 [#9137] FeedbackResponseCommentAttributes: getIdentificationString() should return the identifier of the attribute
  src/main/java/teammates/common/datatransfer/attributes/FeedbackResponseCommentAttributes.java
Labels: c.Task, s.ToMerge

#9180 [#9179] Make JS code ES6-compliant
  src/main/webapp/dev/js/common/onStart.js
  src/main/webapp/dev/js/main/about.js
  src/main/webapp/dev/js/main/instructorCourses.js
  src/main/webapp/dev/js/test/CommonTestFunctions.js
  static-analysis/teammates-eslint.yml
Labels: c.Task, s.ToReview

#9185 [#9184] Lock App Engine SDK at 1.9.65
  .travis.yml
  appveyor.yml
  build.gradle
  docs/setting-up.md
Labels: s.ToReview

#9189 [#9182] Release V6.13.0
  src/main/webapp/data/developers.json
  src/main/webapp/images/teammembers/bao.png
  src/main/webapp/images/teammembers/chunrong.png
  src/main/webapp/images/teammembers/dat.png
  src/main/webapp/images/teammembers/hengyeow.png
  src/main/webapp/images/teammembers/jacob.png
  src/main/webapp/images/teammembers/joanne.png
  src/main/webapp/images/teammembers/mudit.png
  src/main/webapp/images/teammembers/nidhi.png
  src/main/webapp/images/teammembers/shengran.png
  src/main/webapp/images/teammembers/shradheya.png
  src/main/webapp/images/teammembers/sukanta.png
  src/main/webapp/images/teammembers/wenxin.png
Labels: c.Release, s.ToReview

#9178 [#9175] Remove unnecessary integrity check for getFeedbackQuestionsForSession
  docs/design.md
  src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
  src/test/java/teammates/test/cases/logic/FeedbackQuestionsLogicTest.java
  src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
Labels: c.Task, s.ToMerge

#9203 [#9198] Student: submit response to distribute-points question: all responses are rejected
  src/main/java/teammates/common/datatransfer/questions/FeedbackConstantSumQuestionDetails.java
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSubmitPageUiTest.java
  src/test/resources/data/InstructorFeedbackSubmitPageUiTest.json
  src/test/resources/pages/instructorFeedbackSubmitPageFullyFilled.html
  src/test/resources/pages/instructorFeedbackSubmitPageModified.html
  src/test/resources/pages/instructorFeedbackSubmitPageOpen.html
  src/test/resources/pages/instructorFeedbackSubmitPageOpenWithHelperView.html
  src/test/resources/pages/instructorFeedbackSubmitPagePartiallyFilled.html
Labels: c.Bug, s.FinalReview

#9171 [#8957] InstructorCourseDetailsPageUiTest.testRemindAction failing on live server
  src/test/java/teammates/test/cases/browsertests/InstructorCourseDetailsPageUiTest.java
  src/test/java/teammates/test/driver/EmailAccount.java
Labels: c.Bug, s.ToMerge

#9190 [#8814] Update user map for April 2018
  src/main/webapp/data/userMapData.json
Labels: c.Task, s.ToMerge

#9214 [#9213] Remove App Engine SDK version lock
  .travis.yml
  appveyor.yml
  build.gradle
  docs/setting-up.md
  src/main/java/teammates/common/util/CryptoHelper.java
  src/main/java/teammates/ui/controller/Action.java
  src/main/java/teammates/ui/controller/ActionResult.java
  src/test/java/teammates/test/driver/GaeSimulation.java
  src/test/java/teammates/test/driver/HtmlHelper.java
Labels: s.ToReview

#9158 [#9139] CourseAttributesTest: fix unstable testBuilderWithDeletedAt()
  src/test/java/teammates/test/cases/datatransfer/CourseAttributesTest.java
Labels: s.ToMerge

#9192 [#9191] FeedbackResponsesLogicTest.java: Make use of `assertEquals` consistent
  src/test/java/teammates/test/cases/logic/FeedbackResponsesLogicTest.java
Labels: s.ToMerge

#9196 [#9096] removed unused methods from Logic.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/CoursesLogic.java
  src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
Labels: c.Task, s.ToMerge
