Repository TEAMMATES/teammates, pull requests merged in 2018-04, with the labels that each got.

#8737 AccountAttributesTest: fix instability due to modified timestamp comparison #8709
  src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java
Labels: e.1, s.ToMerge

#8745 Fix indentation for test resource html pages to avoid irrelevant changes #8744
  src/test/resources/pages/studentFeedbackSubmitPageFullyFilled.html
  src/test/resources/pages/studentFeedbackSubmitPageModified.html
  src/test/resources/pages/studentFeedbackSubmitPageOpen.html
  src/test/resources/pages/studentFeedbackSubmitPagePartiallyFilled.html
  src/test/resources/pages/unregisteredStudentFeedbackSubmitPageOpen.html
  src/test/resources/pages/unregisteredStudentFeedbackSubmitPagePartiallyFilled.html
Labels: e.1, s.ToMerge

#8746 HtmlHelper: fix broken detection of current time #8640
  src/test/java/teammates/test/cases/browsertests/StudentHomePageUiTest.java
  src/test/java/teammates/test/driver/HtmlHelper.java
Labels: e.1, s.ToMerge

#8517 Rubric questions: show summary excluding self-evaluation #6887
  src/main/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetails.java
  src/main/java/teammates/common/util/Templates.java
  src/main/resources/feedbackQuestionRubricResultStatsTemplate.html
  src/main/webapp/dev/js/common/instructorFeedbackResults.js
  src/main/webapp/dev/js/main/instructorFeedbackResultsGQR.js
  src/main/webapp/dev/js/main/instructorFeedbackResultsQuestion.js
  src/main/webapp/dev/js/main/instructorFeedbackResultsRQG.js
  src/main/webapp/dev/js/main/studentFeedbackResults.js
  src/main/webapp/dev/js/test/instructorFeedbackResultsTest.js
  src/main/webapp/test/allJsUnitTests.jsp
  src/test/java/teammates/test/cases/browsertests/AllJsTests.java
  src/test/resources/pages/instructorFeedbackResultsPageRubricGQRView.html
  src/test/resources/pages/instructorFeedbackResultsPageRubricQuestionView.html
  src/test/resources/pages/instructorFeedbackResultsPageRubricRQGView.html
  src/test/resources/pages/newlyJoinedInstructorThirdFeedbackSessionResultsPage.html
  src/test/resources/pages/studentExtendedFeedbackResultsPageRubric.html
  src/test/resources/pages/studentFeedbackResultsPageRubric.html
Labels: e.4, s.ToMerge

#8706 AdminActivityLogPage: incorrect log message for change of course time zone #8695
  src/main/java/teammates/ui/controller/InstructorCourseEditSaveAction.java
Labels: e.1, s.ToMerge

#8738 Rename ambiguous method isChangesRequiresResponseDeletion -> shouldChangesRequireResponseDeletion #8721
  src/main/java/teammates/common/datatransfer/attributes/FeedbackQuestionAttributes.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackConstantSumQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackMcqQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackMsqQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackNumericalScaleQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRankOptionsQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRankRecipientsQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackTextQuestionDetails.java
Labels: e.1, s.ToMerge

#8727 AdminActivityLogPage: fix inconsistent StudentProfilePage Load message #8717
  src/main/java/teammates/ui/controller/StudentProfilePageAction.java
  src/test/java/teammates/test/cases/action/StudentProfilePageActionTest.java
Labels: e.1, s.ToMerge

#8743 Webpack: Refactor config to support development and production environment. Add Sourcemap Dev Tool. #8716
  docs/development.md
  package.json
  webpack-main-dev.config.js
  webpack-main-prod.config.js
  webpack-main.config.js
Labels: s.ToMerge

#8734 AdminSessionsPage: fix parse failure for dates selected via datepicker #8733
  src/main/java/teammates/common/util/TimeHelper.java
  src/main/java/teammates/ui/controller/AdminSessionsPageAction.java
  src/main/java/teammates/ui/pagedata/AdminSessionsPageData.java
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java
Labels: e.1, s.ToMerge

#8758 Account: update setStudentProfile javadoc #8757
  src/main/java/teammates/storage/entity/Account.java
Labels: e.1, s.ToMerge

#8736 AdminSessions*: migrate to java.time #8645
  src/main/java/teammates/common/util/TimeHelper.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/storage/api/FeedbackSessionsDb.java
  src/main/java/teammates/ui/controller/AdminSessionsPageAction.java
  src/main/java/teammates/ui/pagedata/AdminSessionsPageData.java
  src/main/java/teammates/ui/pagedata/PageData.java
Labels: s.ToMerge

#8762 Instructor: fix bug where session closed email copy is sent to the instructor even when it was not sent to students #8761
  src/main/java/teammates/logic/api/EmailGenerator.java
Labels: e.1, s.ToMerge

#8725 Instructor: home page: give menu option to edit a course #8541
  src/main/java/teammates/ui/pagedata/InstructorHomeCourseAjaxPageData.java
  src/test/resources/pages/instructorHomeCourseArchiveSuccessful.html
  src/test/resources/pages/instructorHomeHTML.html
  src/test/resources/pages/instructorHomeHTMLResponseRateFail.html
  src/test/resources/pages/instructorHomeHTMLResponseRatePass.html
  src/test/resources/pages/instructorHomeHTMLSortByDate.html
  src/test/resources/pages/instructorHomeHTMLSortById.html
  src/test/resources/pages/instructorHomeHTMLSortByName.html
  src/test/resources/pages/instructorHomeHTMLSortSessionsByEndDate.html
  src/test/resources/pages/instructorHomeHTMLSortSessionsByName.html
  src/test/resources/pages/instructorHomeHTMLSortSessionsByStartDate.html
  src/test/resources/pages/instructorHomeHTMLWithHelperView.html
  src/test/resources/pages/instructorHomeHTMLWithUnloadedCourse.html
  src/test/resources/pages/instructorHomeNewInstructorWithSampleCourse.html
  src/test/resources/pages/instructorHomeTestingSanitization.html
  src/test/resources/pages/newlyJoinedInstructorHomePage.html
Labels: e.1, s.ToMerge

#8539 Instructor: Feedback: View Results: fix the disappearing 'No specific recipient' panel bug #7633
  src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java
  src/main/java/teammates/ui/pagedata/InstructorFeedbackResultsPageData.java
  src/main/webapp/dev/js/common/instructorFeedbackResults.js
  src/test/java/teammates/test/cases/browsertests/FeedbackRankQuestionUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java
  src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java
  src/test/resources/data/InstructorFeedbackResultsPageUiTest.json
  src/test/resources/pages/instructorFeedbackResultsPageGQRWithSanitizedData.html
  src/test/resources/pages/instructorFeedbackResultsPageRankRGQView.html
  src/test/resources/pages/instructorFeedbackResultsPageRankRQGView.html
  src/test/resources/pages/instructorFeedbackResultsSortSecondSessionFilteredBySectionATeam.html
  src/test/resources/pages/instructorFeedbackResultsSortSecondSessionGiverQuestionRecipient.html
  src/test/resources/pages/instructorFeedbackResultsSortSecondSessionGiverQuestionRecipientTeam.html
  src/test/resources/pages/instructorFeedbackResultsSortSecondSessionGiverRecipientQuestion.html
  src/test/resources/pages/instructorFeedbackResultsSortSecondSessionGiverRecipientQuestionTeam.html
Labels: s.FinalReview

#8678 Instructor: Edit Session: MSQ: Address the case where a number field is left blank #8611
  src/main/resources/feedbackQuestionMsqEditFormTemplate.html
  src/test/java/teammates/test/cases/browsertests/FeedbackMsqQuestionUiTest.java
  src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
  src/test/resources/pages/instructorFeedbackAddSuccess.html
  src/test/resources/pages/instructorFeedbackConstSumOptionQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackConstSumOptionQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackConstSumRecipientQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackConstSumRecipientQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackContribQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackContribQuestionEdit.html
  src/test/resources/pages/instructorFeedbackContribQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackCopyQuestionSuccess.html
  src/test/resources/pages/instructorFeedbackCopySuccess.html
  src/test/resources/pages/instructorFeedbackCopyTrimmedSuccess.html
  src/test/resources/pages/instructorFeedbackEditCopyFail.html
  src/test/resources/pages/instructorFeedbackEditCopyPage.html
  src/test/resources/pages/instructorFeedbackEditEmpty.html
  src/test/resources/pages/instructorFeedbackEditManuallyPublished.html
  src/test/resources/pages/instructorFeedbackEditPageTestingSanitization.html
  src/test/resources/pages/instructorFeedbackEditSuccess.html
  src/test/resources/pages/instructorFeedbackMcqQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackMcqQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackMsqQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackMsqQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackNumScaleQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackNumScaleQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackQuestionEditToTeamToTeam.html
  src/test/resources/pages/instructorFeedbackQuestionVisibilityOptions.html
  src/test/resources/pages/instructorFeedbackQuestionVisibilityPreview.html
  src/test/resources/pages/instructorFeedbackRankMinMaxChoicesSuccess.html
  src/test/resources/pages/instructorFeedbackRankQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackRankQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEdit.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditChoiceSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditDescriptionSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditSubQuestionSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditWeightSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionMoveColumnNewQuestionSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionMoveColumnSuccess.html
  src/test/resources/pages/instructorFeedbackTeamPeerEvalTemplateAddSuccess.html
Labels: s.ToMerge

#8686 Instructor: search students: add a confirmation dialog for the "delete" button #3091
  src/main/webapp/dev/js/main/instructorSearch.js
  src/test/java/teammates/test/cases/browsertests/InstructorSearchPageUiTest.java
  src/test/java/teammates/test/pageobjects/InstructorSearchPage.java
Labels: e.1, s.ToMerge

#8596 InstructorAttributes: remove HTML sanitization before saving for role, displayedName #7726
  src/client/java/teammates/client/scripts/DataMigrationForSanitizedDataInInstructorAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/InstructorAttributes.java
  src/main/java/teammates/storage/search/InstructorSearchDocument.java
  src/main/java/teammates/ui/template/CourseEditInstructorPanel.java
  src/main/java/teammates/ui/template/FeedbackResponseCommentRow.java
  src/main/webapp/WEB-INF/tags/instructor/course/courseEditInstructorListPanelBody.tag
  src/main/webapp/WEB-INF/tags/student/courseDetails/displayInstructors.tag
  src/test/resources/data/InstructorCourseDetailsPageUiTest.json
  src/test/resources/data/InstructorCourseEditPageUiTest.json
  src/test/resources/data/InstructorCourseStudentDetailsPageUiTest.json
  src/test/resources/data/InstructorHomePageUiTest2.json
  src/test/resources/data/InstructorSearchPageUiTest.json
  src/test/resources/data/InstructorStudentListPageUiTest.json
  src/test/resources/data/InstructorStudentRecordsPageUiTest.json
  src/test/resources/data/StudentCourseDetailsPageUiTest.json
  src/test/resources/data/StudentCourseJoinAuthenticatedTest.json
  src/test/resources/data/StudentHomePageUiTest.json
  src/test/resources/data/StudentProfilePageUiTest.json
  src/test/resources/data/typicalDataBundle.json
  src/test/resources/pages/instructorCourseEditTestingSanitization.html
  src/test/resources/pages/instructorSearchPageSearchTestingSanitization.html
  src/test/resources/pages/studentCourseDetailsTestingSanitization.html
Labels: e.2, s.ToMerge

#8776 AccountAttributes: remove HTML sanitization before saving for email #8775
  src/main/java/teammates/common/datatransfer/attributes/AccountAttributes.java
  src/main/webapp/WEB-INF/tags/admin/accounts/accountDetailsForInstructorPanel.tag
  src/main/webapp/WEB-INF/tags/admin/activity/activityLogTableRow.tag
  src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java
Labels: e.1, s.ToMerge

#8732 Migrate remaining classes to use java.time #8731
  src/main/java/teammates/common/datatransfer/attributes/AdminEmailAttributes.java
  src/main/java/teammates/common/util/AdminLogQuery.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/common/util/JsonUtils.java
  src/main/java/teammates/common/util/LogMessageGenerator.java
  src/main/java/teammates/common/util/TimeHelper.java
  src/main/java/teammates/storage/api/FeedbackSessionsDb.java
  src/main/java/teammates/ui/automated/CompileLogsAction.java
  src/main/java/teammates/ui/controller/AdminActivityLogPageAction.java
  src/main/java/teammates/ui/controller/ControllerServlet.java
  src/main/java/teammates/ui/pagedata/AdminActivityLogPageData.java
  src/main/java/teammates/ui/pagedata/AdminEmailLogPageData.java
  src/main/java/teammates/ui/template/AdminAccountManagementAccountTableRow.java
  src/main/java/teammates/ui/template/AdminActivityLogTableRow.java
  src/main/java/teammates/ui/template/AdminEmailTableRow.java
  src/test/java/teammates/test/cases/action/AdminActivityLogPageActionTest.java
  src/test/java/teammates/test/cases/action/AdminEmailLogPageActionTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java
  src/test/java/teammates/test/cases/datatransfer/AdminEmailAttributesTest.java
  src/test/java/teammates/test/cases/util/AdminLogQueryTest.java
  src/test/java/teammates/test/cases/util/TimeHelperTest.java
  src/test/java/teammates/test/driver/HtmlHelper.java
  src/test/java/teammates/test/driver/TimeHelperExtension.java
  src/test/java/teammates/test/pageobjects/AdminActivityLogPage.java
  src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
  src/test/java/teammates/test/pageobjects/InstructorFeedbackSessionsPage.java
Labels: e.4, s.ToMerge

#8778 Release V6.5.0 #8777
  docs/community.md
  src/main/webapp/about.jsp
  src/main/webapp/data/developers.json
  src/main/webapp/dev/js/main/about.js
  src/main/webapp/dev/js/main/index.js
Labels: e.1, s.ToMerge

#8742 Student: submit responses: tick email confirmation option if the form is empty #8606
  src/main/java/teammates/ui/pagedata/FeedbackSubmissionEditPageData.java
  src/main/webapp/WEB-INF/tags/shared/feedbackSubmissionEdit/feedbackSubmissionForm.tag
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSubmitPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/StudentFeedbackSubmitPageUiTest.java
  src/test/java/teammates/test/pageobjects/FeedbackSubmitPage.java
  src/test/resources/pages/instructorFeedbackResultsPageRankSubmission.html
  src/test/resources/pages/instructorFeedbackSubmitPageAwaiting.html
  src/test/resources/pages/instructorFeedbackSubmitPageClosed.html
  src/test/resources/pages/instructorFeedbackSubmitPageGracePeriod.html
  src/test/resources/pages/instructorFeedbackSubmitPageOpen.html
  src/test/resources/pages/instructorFeedbackSubmitPageOpenWithHelperView.html
  src/test/resources/pages/instructorFeedbackSubmitPagePreview.html
  src/test/resources/pages/instructorFeedbackSubmitPagePrivate.html
  src/test/resources/pages/instructorFeedbackSubmitPageRankHelper.html
  src/test/resources/pages/studentFeedbackSubmitPageAwaiting.html
  src/test/resources/pages/studentFeedbackSubmitPageClosed.html
  src/test/resources/pages/studentFeedbackSubmitPageGracePeriod.html
  src/test/resources/pages/studentFeedbackSubmitPageOpen.html
  src/test/resources/pages/studentFeedbackSubmitPagePreview.html
  src/test/resources/pages/unregisteredStudentFeedbackSubmitPageOpen.html
Labels: e.2, s.ToMerge

#8789 InstructorFeedbackAddAction: fix NullPointerException upon invalid publish time #8788
  src/main/java/teammates/ui/template/FeedbackSessionsForm.java
  src/test/java/teammates/test/cases/action/InstructorFeedbackAddActionTest.java
Labels: e.1, s.ToMerge

#8724 Instructor: Session Results: Comment box shrinks when canceling and adding comment again #8723
  src/main/webapp/dev/js/common/feedbackResponseComments.js
Labels: s.ToMerge

#8739 Use builder instead of telescoping constructor antipattern in FeedbackQuestionAttributes class #7190
  src/main/java/teammates/common/datatransfer/attributes/FeedbackQuestionAttributes.java
  src/main/java/teammates/storage/api/FeedbackQuestionsDb.java
  src/main/java/teammates/ui/controller/InstructorFeedbackQuestionAddAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackQuestionEditAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackQuestionVisibilityMessageAction.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackQuestionAttributesTest.java
  src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
  src/test/java/teammates/test/cases/storage/FeedbackQuestionsDbTest.java
Labels: s.ToMerge

#8476 Instructor: update on number of char left for Session Name input #8475
  src/main/webapp/WEB-INF/tags/instructor/feedbacks/copyFromModal.tag
  src/main/webapp/dev/js/common/const.js
  src/main/webapp/dev/js/common/countRemainingCharactersOnInput.js
  src/main/webapp/dev/js/common/instructor.js
  src/main/webapp/dev/js/main/instructorFeedbacks.js
  src/main/webapp/jsp/instructorFeedbackCopyModal.jsp
  src/test/resources/pages/instructorFeedbackAllSessionTypes.html
  src/test/resources/pages/instructorFeedbackAllSessionTypesWithHelperView.html
  src/test/resources/pages/instructorFeedbackDeleteSuccessful.html
  src/test/resources/pages/instructorFeedbackEditCopyFail.html
  src/test/resources/pages/instructorFeedbackEditCopyPage.html
  src/test/resources/pages/instructorFeedbackEditCopySuccess.html
  src/test/resources/pages/instructorFeedbackEmptyAll.html
  src/test/resources/pages/instructorFeedbackEmptySession.html
  src/test/resources/pages/instructorFeedbackPublishSuccessful.html
  src/test/resources/pages/instructorFeedbackUnpublishSuccessful.html
Labels: s.ToMerge

#8783 Use Java 8 map.putIfAbsent and map.computeIfAbsent #8215
  src/client/java/teammates/client/scripts/StatisticsPerInstitute.java
  src/main/java/teammates/common/datatransfer/InstructorPrivileges.java
  src/main/java/teammates/logic/core/FeedbackResponsesLogic.java
  src/test/java/teammates/test/cases/logic/InstructorsLogicTest.java
Labels: e.1, s.ToMerge

#8801 Remove the need to specify application URL in build.properties #8800
  docs/development.md
  docs/troubleshooting-guide.md
  src/main/java/teammates/common/util/Config.java
  src/main/resources/build.template.properties
  src/test/java/teammates/test/cases/testdriver/EmailCheckerTest.java
  src/test/java/teammates/test/driver/EmailChecker.java
  src/test/java/teammates/test/driver/GaeSimulation.java
Labels: e.1, s.ToMerge

#8804 AccountAttributesTest: fix instability due to modified timestamp comparison #8803
  src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java
Labels: e.1, s.ToMerge

#8676 Instructor: students: add invite button #8648
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/controller/InstructorCourseRemindAction.java
  src/main/java/teammates/ui/pagedata/InstructorCourseDetailsPageData.java
  src/main/java/teammates/ui/pagedata/InstructorSearchPageData.java
  src/main/java/teammates/ui/pagedata/InstructorStudentListAjaxPageData.java
  src/main/java/teammates/ui/template/StudentListSectionData.java
  src/main/java/teammates/ui/template/StudentListStudentData.java
  src/main/java/teammates/ui/template/StudentListTeamData.java
  src/main/webapp/WEB-INF/tags/instructor/studentList.tag
  src/main/webapp/dev/js/common/instructor.js
  src/main/webapp/dev/js/main/instructorCourseDetails.js
  src/main/webapp/dev/js/main/instructorStudentList.js
  src/test/java/teammates/test/cases/action/InstructorCourseRemindActionTest.java
  src/test/java/teammates/test/cases/browsertests/AllJsTests.java
  src/test/resources/pages/instructorCourseDetailsStudentDeleteSuccessful.html
  src/test/resources/pages/instructorCourseDetailsWithSections.html
  src/test/resources/pages/instructorCourseDetailsWithoutSections.html
  src/test/resources/pages/instructorStudentList.html
  src/test/resources/pages/instructorStudentListPageDisplayArchivedCourses.html
  src/test/resources/pages/instructorStudentListPageHideArchivedCourses.html
  src/test/resources/pages/instructorStudentListPageWithPicture.html
  src/test/resources/pages/instructorStudentListWithHelperView.html
  src/test/resources/pages/newlyJoinedInstructorCourseDetailsPage.html
Labels: e.2, s.ToMerge

#8296 Improve general reliability of tests #8209
  src/main/webapp/dev/js/common/bootboxWrapper.js
  src/main/webapp/dev/js/common/feedbackResponseComments.js
  src/main/webapp/dev/js/common/helper.js
  src/main/webapp/dev/js/test/CommonJsTest.js
  src/main/webapp/dev/js/test/CommonTestFunctions.js
  src/test/java/teammates/test/cases/browsertests/FeedbackConstSumOptionQuestionUiTest.java
  src/test/java/teammates/test/cases/browsertests/FeedbackConstSumRecipientQuestionUiTest.java
  src/test/java/teammates/test/cases/browsertests/FeedbackContributionQuestionUiTest.java
  src/test/java/teammates/test/cases/browsertests/FeedbackMcqQuestionUiTest.java
  src/test/java/teammates/test/cases/browsertests/FeedbackMsqQuestionUiTest.java
  src/test/java/teammates/test/cases/browsertests/FeedbackNumScaleQuestionUiTest.java
  src/test/java/teammates/test/cases/browsertests/FeedbackRankQuestionUiTest.java
  src/test/java/teammates/test/cases/browsertests/FeedbackRubricQuestionUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackResultsPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java
  src/test/java/teammates/test/driver/TestProperties.java
  src/test/java/teammates/test/pageobjects/AppPage.java
  src/test/java/teammates/test/pageobjects/Browser.java
  src/test/java/teammates/test/pageobjects/FeedbackSubmitPage.java
  src/test/java/teammates/test/pageobjects/GoogleLoginPage.java
  src/test/java/teammates/test/pageobjects/InstructorCopyFsToModal.java
  src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
  src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java
  src/test/java/teammates/test/pageobjects/InstructorFeedbackSessionsPage.java
  src/test/java/teammates/test/pageobjects/InstructorHomePage.java
Labels: e.4, s.ToMerge
