Repository TEAMMATES/teammates, pull requests merged in 2018-09, with the labels that each got.

#9086 [#8755] Update usermap to match data for March 2018
  src/main/webapp/data/userMapData.json
Labels: s.ToMerge

#8874 [#3432] Instructor View: perceived contribution for student who has not submit response in 'All Records' mode
  src/main/java/teammates/ui/pagedata/InstructorStudentRecordsAjaxPageData.java
  src/main/java/teammates/ui/template/FeedbackResponsePersonRow.java
  src/main/java/teammates/ui/template/FeedbackResponseRow.java
  src/main/java/teammates/ui/template/FeedbackResultsTable.java
Labels: s.ToMerge

#9039 [#9038] Instructor: delete all courses/sessions permanently: specify courses/sessions being deleted
  src/main/webapp/WEB-INF/tags/instructor/course/softDeletedCoursesTable.tag
  src/main/webapp/WEB-INF/tags/instructor/feedbacks/softDeletedFeedbackSessionsTable.tag
  src/main/webapp/dev/js/common/instructor.js
  src/test/resources/pages/instructorCoursesAddDupIdFailed.html
  src/test/resources/pages/instructorCoursesAddInvalidIdFailed.html
  src/test/resources/pages/instructorCoursesAddMissingParamsFailed.html
  src/test/resources/pages/instructorCoursesAddSuccessful.html
  src/test/resources/pages/instructorCoursesDeleteSuccessful.html
  src/test/resources/pages/instructorCoursesMoveToRecycleBinSuccessful.html
  src/test/resources/pages/instructorCoursesMultipleCourses.html
  src/test/resources/pages/instructorCoursesRestoreSuccessful.html
  src/test/resources/pages/instructorCoursesStatsAjaxFailure.html
  src/test/resources/pages/instructorCoursesStatsAjaxSuccessful.html
  src/test/resources/pages/instructorFeedbackDeleteSuccessful.html
  src/test/resources/pages/instructorFeedbackMoveToRecycleBinSuccessful.html
  src/test/resources/pages/instructorFeedbackRestoreSuccessful.html
  src/test/resources/pages/instructorOfCS2105WithMultipleSoftDeletedSessions.html
  src/test/resources/pages/instructorOfCS2106WithMultipleSoftDeletedSessions.html
  src/test/resources/pages/otherInstructorCoursesMultipleSoftDeletedCourses.html
  static-analysis/teammates-eslint.yml
Labels: s.ToMerge

#9099 [#9083] Data Migration: FeedbackResponseComment commentGiverType and isCommentFromFeedbackParticipant
  src/client/java/teammates/client/scripts/DataMigrationForInstructorFeedbackResponseComments.java
Labels: c.Task, s.ToMerge

#9101 [#8448] Complete migration of FeedbackSession entities
  src/client/java/teammates/client/scripts/DataMigrationForSessions.java
Labels: c.Task, s.FinalReview

#9110 [#9109] Deactivate deleted sessions
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/backdoor/BackDoorLogic.java
  src/main/java/teammates/logic/backdoor/BackDoorOperation.java
  src/main/java/teammates/logic/backdoor/BackDoorServlet.java
  src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/storage/api/FeedbackSessionsDb.java
  src/main/java/teammates/ui/controller/InstructorFeedbackDeleteSoftDeletedSessionAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackRestoreSoftDeletedSessionAction.java
  src/test/java/teammates/test/cases/action/InstructorFeedbackDeleteActionTest.java
  src/test/java/teammates/test/cases/action/InstructorFeedbackResultsPageActionTest.java
  src/test/java/teammates/test/cases/action/StudentFeedbackResultsPageActionTest.java
  src/test/java/teammates/test/cases/action/StudentFeedbackSubmissionEditPageActionTest.java
  src/test/java/teammates/test/cases/action/StudentFeedbackSubmissionEditSaveActionTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java
  src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
  src/test/java/teammates/test/cases/storage/FeedbackSessionsDbTest.java
  src/test/java/teammates/test/driver/BackDoor.java
Labels: s.FinalReview

#9112 [#9079] Set up authentication workflow
  angular.json
  src/e2e/java/teammates/e2e/cases/e2e/StaticPageE2ETest.java
  src/main/java/teammates/common/datatransfer/UserType.java
  src/main/java/teammates/common/util/Config.java
  src/main/java/teammates/ui/controller/LoginServlet.java
  src/main/java/teammates/ui/controller/LogoutServlet.java
  src/main/java/teammates/ui/newcontroller/AuthServlet.java
  src/main/java/teammates/ui/newcontroller/CorsFilter.java
  src/main/java/teammates/ui/newcontroller/package-info.java
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/googleAccountHint.jsp
  src/web/app/app.component.ts
  src/web/app/app.module.ts
  src/web/app/page-not-found/page-not-found.component.html
  src/web/app/page-not-found/page-not-found.component.scss
  src/web/app/page-not-found/page-not-found.component.ts
  src/web/app/page-not-found/page-not-found.module.ts
  src/web/app/page.component.html
  src/web/app/page.component.scss
  src/web/app/page.component.ts
  src/web/app/pages-admin/admin-home-page/admin-home-page.component.html
  src/web/app/pages-admin/admin-home-page/admin-home-page.component.scss
  src/web/app/pages-admin/admin-home-page/admin-home-page.component.ts
  src/web/app/pages-admin/admin-page.component.ts
  src/web/app/pages-admin/admin-pages.module.ts
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.scss
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.ts
  src/web/app/pages-instructor/instructor-page.component.ts
  src/web/app/pages-instructor/instructor-pages.module.ts
  src/web/app/pages-static/about-page/about-page.component.ts
  src/web/app/pages-static/index-page/index-page.component.ts
  src/web/app/pages-static/request-page/request-page.component.ts
  src/web/app/pages-static/static-page.component.html
  src/web/app/pages-static/static-page.component.scss
  src/web/app/pages-static/static-page.component.ts
  src/web/app/pages-static/static-pages.module.ts
  src/web/app/pages-static/usermap-page/usermap-page.component.ts
  src/web/app/pages-student/student-home-page/student-home-page.component.html
  src/web/app/pages-student/student-home-page/student-home-page.component.scss
  src/web/app/pages-student/student-home-page/student-home-page.component.ts
  src/web/app/pages-student/student-page.component.ts
  src/web/app/pages-student/student-pages.module.ts
  src/web/app/pages.module.ts
  src/web/environments/environment.prod.ts
  src/web/environments/environment.ts
  src/web/services/auth.service.spec.ts
  src/web/services/auth.service.ts
  src/web/test.ts
  static-analysis/teammates-macker.xml
  static-analysis/teammates-tslint.yml
Labels: s.ToReview

#9108 [#9100] Release V6.11.0
  src/main/webapp/data/developers.json
Labels: s.ToMerge

#9121 [#9120] Deactivate all sessions in deleted courses
  src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
  src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
Labels: s.ToMerge

#9118 [#9084] Data Migration: FeedbackSession timeZone, all time fields, is*EmailEnabled and feedbackSessionType
  src/client/java/teammates/client/scripts/DataMigrationForSessions.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/common/util/TimeHelper.java
  src/main/java/teammates/storage/api/FeedbackSessionsDb.java
  src/main/java/teammates/storage/entity/FeedbackSession.java
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java
  src/test/java/teammates/test/cases/storage/FeedbackSessionsDbTest.java
  src/test/java/teammates/test/cases/util/TimeHelperTest.java
  src/test/resources/data/InstructorFeedbackEditPageUiTest.json
Labels: s.ToMerge

#9088 [#9082] Objectify: Use java.time.Instant instead of java.util.Date for entity
  src/main/java/teammates/common/util/TimeHelper.java
  src/main/java/teammates/storage/api/AdminEmailsDb.java
  src/main/java/teammates/storage/api/FeedbackResponseCommentsDb.java
  src/main/java/teammates/storage/api/FeedbackSessionsDb.java
  src/main/java/teammates/storage/api/OfyHelper.java
  src/main/java/teammates/storage/entity/Account.java
  src/main/java/teammates/storage/entity/AdminEmail.java
  src/main/java/teammates/storage/entity/BaseEntity.java
  src/main/java/teammates/storage/entity/Course.java
  src/main/java/teammates/storage/entity/CourseStudent.java
  src/main/java/teammates/storage/entity/FeedbackQuestion.java
  src/main/java/teammates/storage/entity/FeedbackResponse.java
  src/main/java/teammates/storage/entity/FeedbackResponseComment.java
  src/main/java/teammates/storage/entity/FeedbackSession.java
  src/main/java/teammates/storage/entity/StudentProfile.java
  static-analysis/teammates-macker.xml
Labels: s.ToMerge

#9009 [#8981] Instructor: delete session: rename buttons in alert message to match question being asked
  src/main/webapp/dev/js/common/instructor.js
Labels: c.Feature, s.ToMerge

#9132 [#9129] Update the maintainer guide with instructions on how to update the timezone data
  docs/maintainer-guide.md
  src/main/resources/tzdb.dat
  src/main/webapp/data/moment-timezone-with-data-2013-2023.min.js
  src/main/webapp/data/moment-timezone-with-data.min.js
  src/main/webapp/jsp/instructorCourseEdit.jsp
  src/main/webapp/jsp/instructorCourses.jsp
  src/main/webapp/jsp/instructorFeedbackEdit.jsp
  src/main/webapp/jsp/instructorFeedbacks.jsp
  src/main/webapp/test/timezone.jsp
  src/test/java/teammates/test/cases/browsertests/TimezoneSyncerTest.java
  src/test/resources/pages/instructorCourseEditHelper.html
  src/test/resources/pages/instructorCoursesNoCourse.html
  src/test/resources/pages/instructorFeedbackEditEmpty.html
  src/test/resources/pages/instructorFeedbackEmptyAll.html
Labels: s.ToMerge

#9142 [#9141] Release V6.12.0
  src/main/webapp/data/developers.json
Labels: c.Release, s.ToMerge

#9140 [#9135] Remove unused constants and methods in EntitiesDb
  src/main/java/teammates/storage/api/EntitiesDb.java
Labels: s.ToMerge

#9062 [#9057] FeedbackConstSumOptionQuestionUiTest failing on live server
  src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
Labels: s.ToMerge

#9149 [#8277] Adopt SpotBugs in place of FindBugs
  build.gradle
  docs/static-analysis.md
  src/client/java/teammates/client/scripts/scalabilitytests/InstructorFeedbackResultsPageDataGenerator.java
  src/client/java/teammates/client/scripts/util/LoopHelper.java
  src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java
  src/main/java/teammates/common/datatransfer/attributes/InstructorAttributes.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackMcqQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackMsqQuestionDetails.java
  src/main/java/teammates/logic/core/FeedbackResponsesLogic.java
  src/main/java/teammates/logic/core/InstructorsLogic.java
  src/main/java/teammates/ui/controller/InstructorSearchPageAction.java
  src/test/java/teammates/test/cases/BaseComponentTestCase.java
  src/test/java/teammates/test/cases/action/InstructorStudentRecordsAjaxPageActionTest.java
  src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackMcqQuestionDetailsTest.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackMsqQuestionDetailsTest.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackRubricQuestionDetailsTest.java
  src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
  src/test/java/teammates/test/cases/storage/FeedbackResponsesDbTest.java
  src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
  static-analysis/teammates-spotbugs.xml
Labels: s.ToMerge
