Repository TEAMMATES/teammates, pull requests merged in 2018-06, with the labels that each got.

#8840 Instructor: view results: fix bug: sorting results by team is broken #8837
  src/main/webapp/dev/js/common/sortBy.js
Labels: s.ToMerge

#8856 Rubric question add/edit action test: Add missing parameter and additional tests #8855
  src/main/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetails.java
  src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionAddActionTest.java
  src/test/java/teammates/test/cases/action/InstructorFeedbackQuestionEditActionTest.java
Labels: s.ToMerge

#8843 BackDoorTest: add test for deletion of Feedback Session #8842
  src/test/java/teammates/test/cases/testdriver/BackDoorTest.java
Labels: e.1, s.ToMerge

#8863 Instructor: Edit session: Rubric question: Add front-end validation for empty weights #8631
  src/main/webapp/dev/js/common/questionRubric.js
  src/test/java/teammates/test/cases/browsertests/FeedbackRubricQuestionUiTest.java
  src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
  src/test/resources/pages/instructorFeedbackRubricQuestionEditDescriptionSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditWeightSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionMoveColumnNewQuestionSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionMoveColumnSuccess.html
Labels: e.1, s.ToMerge

#8881 Instructor: edit student details: resend past links to the new email not working #8880
  src/main/webapp/dev/js/main/instructorCourseStudentEdit.js
Labels: e.1, s.ToMerge

#8816 Instructor: edit session: show a spinner while saving session #8792
  src/main/webapp/dev/js/main/instructorFeedbackEdit.js
Labels: e.1, s.ToMerge

#8730 Student: view session results: do not show self responses #6290
  src/main/java/teammates/ui/template/StudentFeedbackResultsQuestionWithResponses.java
  src/main/webapp/WEB-INF/tags/student/feedbackResults/questionWithResponses.tag
  src/test/java/teammates/test/cases/pagedata/StudentFeedbackResultsPageDataTest.java
  src/test/resources/pages/newlyJoinedInstructorStudentFeedbackResultsPage.html
  src/test/resources/pages/studentExtendedFeedbackResultsPageRubric.html
  src/test/resources/pages/studentFeedbackResultsPageCONSTSUM.html
  src/test/resources/pages/studentFeedbackResultsPageMCQ.html
  src/test/resources/pages/studentFeedbackResultsPageMSQ.html
  src/test/resources/pages/studentFeedbackResultsPageNUMSCALE.html
  src/test/resources/pages/studentFeedbackResultsPageNewlyRegistered.html
  src/test/resources/pages/studentFeedbackResultsPageOpen.html
  src/test/resources/pages/studentFeedbackResultsPageRank.html
  src/test/resources/pages/studentFeedbackResultsPageRubric.html
  src/test/resources/pages/studentFeedbackResultsPageTeamToTeam.html
  src/test/resources/pages/unregisteredStudentFeedbackResultsPageMCQ.html
  src/test/resources/pages/unregisteredStudentFeedbackResultsPageOpen.html
Labels: s.ToMerge

#8896 Instructor: Results: Use separate result stats templates for MSQ questions instead of re-using MCQ templates #8894
  src/main/java/teammates/common/datatransfer/questions/FeedbackMsqQuestionDetails.java
  src/main/java/teammates/common/util/Templates.java
  src/main/resources/feedbackQuestionMsqResultStatsOptionFragment.html
  src/main/resources/feedbackQuestionMsqResultStatsTemplate.html
Labels: s.ToMerge

#8827 Instructors: sessions page: fix 'resend link to view results' #8822
  src/main/java/teammates/ui/pagedata/InstructorFeedbackSessionsPageData.java
  src/main/webapp/dev/js/main/instructorFeedbacks.js
  src/main/webapp/jsp/instructorFeedbacks.jsp
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java
  src/test/java/teammates/test/pageobjects/InstructorFeedbackSessionsPage.java
  src/test/resources/pages/instructorFeedbackAllSessionTypes.html
  src/test/resources/pages/instructorFeedbackAllSessionTypesWithHelperView.html
  src/test/resources/pages/instructorFeedbackDeleteSuccessful.html
  src/test/resources/pages/instructorFeedbackEditCopySuccess.html
  src/test/resources/pages/instructorFeedbackEmptyAll.html
  src/test/resources/pages/instructorFeedbackEmptySession.html
  src/test/resources/pages/instructorFeedbackPublishSuccessful.html
  src/test/resources/pages/instructorFeedbackUnpublishSuccessful.html
Labels: s.ToMerge

#8902 Testing: unstable behaviour in CI Config.APP_URL can be null sometimes #8898
  src/test/java/teammates/test/cases/BaseTestCaseWithMinimalGaeEnvironment.java
  src/test/java/teammates/test/cases/datatransfer/StudentAttributesTest.java
  src/test/java/teammates/test/cases/pagedata/InstructorFeedbackEditPageDataTest.java
  src/test/java/teammates/test/driver/GaeSimulation.java
  static-analysis/teammates-macker.xml
Labels: s.ToMerge

#8904 Release V6.6.0 #8903
  src/main/webapp/data/developers.json
Labels: e.1, s.ToMerge

#8833 Spreadsheet Interface for Student Data UI: Initial upgrade for instructorCourseEnrollPage #8832
  src/main/java/teammates/common/util/FrontEndLibrary.java
  src/main/resources/package.json
  src/main/webapp/dev/js/main/instructorCourseEnrollHelper.js
  src/main/webapp/dev/js/main/instructorCourseEnrollPage.js
  src/main/webapp/dev/js/test/InstructorEnrolmentJsTest.js
  src/main/webapp/images/enrollInstructions.gif
  src/main/webapp/jsp/instructorCourseEnroll.jsp
  src/main/webapp/stylesheets/teammatesCommon.css
  src/main/webapp/test/allJsUnitTests.jsp
  src/test/java/teammates/test/cases/browsertests/InstructorCourseEnrollPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorSubmissionAdjustmentUiTest.java
  src/test/java/teammates/test/driver/HtmlHelper.java
  src/test/java/teammates/test/pageobjects/AppPage.java
  src/test/java/teammates/test/pageobjects/InstructorCourseEnrollPage.java
  src/test/resources/pages/instructorCourseEnrollError.html
  src/test/resources/pages/instructorCourseEnrollPage.html
  src/test/resources/pages/instructorCourseEnrollPageResult.html
  src/test/resources/pages/instructorCourseEnrollPageResultForEmptyCourse.html
Labels: s.ToMerge

#8849 InstructorView: improve csv UI after being exported #8848
  src/main/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetails.java
  src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
Labels: e.1, s.ToMerge

#8836 Student: feedback submission: distribution points question: explain if equal points are not allowed #8817
  src/main/resources/feedbackQuestionConstSumSubmissionFormOptionFragment.html
  src/main/resources/feedbackQuestionConstSumSubmissionFormTemplate.html
  src/main/resources/feedbackQuestionContribSubmissionFormTemplate.html
  src/main/webapp/WEB-INF/tags/shared/feedbackSubmissionEdit/questionWithResponses.tag
  src/main/webapp/WEB-INF/tags/shared/feedbackSubmissionEdit/response.tag
  src/main/webapp/dev/js/main/feedbackSubmissionsEdit.js
  src/main/webapp/stylesheets/teammatesCommon.css
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSubmitPageUiTest.java
  src/test/java/teammates/test/pageobjects/FeedbackSubmitPage.java
  src/test/resources/data/InstructorFeedbackSubmitPageUiTest.json
  src/test/resources/pages/instructorEditStudentFeedbackPageModified.html
  src/test/resources/pages/instructorEditStudentFeedbackPageOpen.html
  src/test/resources/pages/instructorFeedbackResultsPageRankSubmission.html
  src/test/resources/pages/instructorFeedbackSubmitPageAwaiting.html
  src/test/resources/pages/instructorFeedbackSubmitPageClosed.html
  src/test/resources/pages/instructorFeedbackSubmitPageFullyFilled.html
  src/test/resources/pages/instructorFeedbackSubmitPageGracePeriod.html
  src/test/resources/pages/instructorFeedbackSubmitPageModified.html
  src/test/resources/pages/instructorFeedbackSubmitPageOpen.html
  src/test/resources/pages/instructorFeedbackSubmitPageOpenWithHelperView.html
  src/test/resources/pages/instructorFeedbackSubmitPagePartiallyFilled.html
  src/test/resources/pages/instructorFeedbackSubmitPagePreview.html
  src/test/resources/pages/instructorFeedbackSubmitPageRankHelper.html
  src/test/resources/pages/newlyJoinedInstructorStudentFeedbackSubmissionEdit.html
  src/test/resources/pages/studentFeedbackSubmitPageAwaiting.html
  src/test/resources/pages/studentFeedbackSubmitPageClosed.html
  src/test/resources/pages/studentFeedbackSubmitPageFullyFilled.html
  src/test/resources/pages/studentFeedbackSubmitPageGracePeriod.html
  src/test/resources/pages/studentFeedbackSubmitPageModified.html
  src/test/resources/pages/studentFeedbackSubmitPageOpen.html
  src/test/resources/pages/studentFeedbackSubmitPagePartiallyFilled.html
  src/test/resources/pages/studentFeedbackSubmitPagePreview.html
  src/test/resources/pages/studentFeedbackSubmitPageRank.html
  src/test/resources/pages/studentFeedbackSubmitPageRubricSuccess.html
  src/test/resources/pages/studentFeedbackSubmitPageSuccessRank.html
  src/test/resources/pages/unregisteredStudentFeedbackSubmitPageOpen.html
  src/test/resources/pages/unregisteredStudentFeedbackSubmitPagePartiallyFilled.html
Labels: s.FinalReview

#8891 FeedbackRankQuestionUiTest.json: Fix data for Tests #8794
  src/test/java/teammates/test/cases/browsertests/FeedbackRankQuestionUiTest.java
  src/test/resources/data/FeedbackRankQuestionUiTest.json
  src/test/resources/pages/instructorFeedbackResultsPageRankRecipient.html
  src/test/resources/pages/studentFeedbackResultsPageRank.html
  src/test/resources/pages/studentFeedbackSubmitPageRank.html
  src/test/resources/pages/studentFeedbackSubmitPageSuccessRank.html
Labels: e.2, s.ToMerge

#8756 Instructor: add a cancel button to terminate the process of adding instructor #8754
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/pagedata/InstructorCourseEditPageData.java
  src/main/java/teammates/ui/template/CourseEditInstructorPanel.java
  src/main/webapp/WEB-INF/tags/instructor/course/courseEditAddInstructorPanel.tag
  src/main/webapp/dev/js/main/instructorCourseEdit.js
  src/main/webapp/jsp/instructorCourseEdit.jsp
  src/test/java/teammates/test/cases/browsertests/InstructorCourseEditPageUiTest.java
  src/test/java/teammates/test/pageobjects/InstructorCourseEditPage.java
  src/test/resources/pages/instructorCourseEditAddInstructor.html
  src/test/resources/pages/instructorCourseEditCoowner.html
  src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesBeforeSubmit.html
  src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesModal.html
  src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesSuccessful.html
  src/test/resources/pages/instructorCourseEditEditInstructorPrivilegesSuccessfulAndCheckEditAgain.html
  src/test/resources/pages/instructorCourseEditHelper.html
  src/test/resources/pages/instructorCourseEditManager.html
  src/test/resources/pages/instructorCourseEditObserver.html
  src/test/resources/pages/instructorCourseEditTestingSanitization.html
  src/test/resources/pages/instructorCourseEditTutor.html
  src/test/resources/pages/newlyJoinedInstructorCourseEditPage.html
Labels: e.2, s.ToMerge

#8841 Add a test for whether the scrolling functions are working #4317
  src/main/webapp/dev/js/main/instructorFeedbackEdit.js
  src/test/java/teammates/test/cases/browsertests/ScrollUnitTest.java
  src/test/testng-ci.xml
Labels: s.ToMerge

#8882 InstructorHomePage: Option to download results for each session under the result button #8868
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/controller/InstructorFeedbackResultsDownloadAction.java
  src/main/webapp/WEB-INF/tags/instructor/feedbacks/feedbackSessionActions.tag
  src/test/java/teammates/test/cases/action/InstructorFeedbackResultsDownloadActionTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorHomePageUiTest.java
  src/test/java/teammates/test/pageobjects/InstructorHomePage.java
  src/test/resources/pages/instructorFeedbackAllSessionTypes.html
  src/test/resources/pages/instructorFeedbackAllSessionTypesWithHelperView.html
  src/test/resources/pages/instructorFeedbackDeleteSuccessful.html
  src/test/resources/pages/instructorFeedbackEditCopySuccess.html
  src/test/resources/pages/instructorFeedbackPublishSuccessful.html
  src/test/resources/pages/instructorFeedbackUnpublishSuccessful.html
  src/test/resources/pages/instructorHomeCourseArchiveSuccessful.html
  src/test/resources/pages/instructorHomeHTML.html
  src/test/resources/pages/instructorHomeHTMLResponseRateFail.html
  src/test/resources/pages/instructorHomeHTMLResponseRatePass.html
  src/test/resources/pages/instructorHomeHTMLSortByDate.html
  src/test/resources/pages/instructorHomeHTMLSortById.html
  src/test/resources/pages/instructorHomeHTMLSortByName.html
  src/test/resources/pages/instructorHomeHTMLSortSessionsByEndDate.html
  src/test/resources/pages/instructorHomeHTMLSortSessionsByName.html
  src/test/resources/pages/instructorHomeHTMLSortSessionsByStartDate.html
  src/test/resources/pages/instructorHomeHTMLWithHelperView.html
  src/test/resources/pages/newlyJoinedInstructorHomePage.html
Labels: e.2, s.ToMerge

#8910 EmailGeneratorTest failing on live server #8908
  src/test/java/teammates/test/cases/BaseTestCaseWithMinimalGaeEnvironment.java
  src/test/java/teammates/test/cases/browsertests/AdminHomePageUiTest.java
Labels: s.ToMerge

#8926 Update third-party dependencies #8925
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  package.json
  src/main/java/teammates/common/util/FrontEndLibrary.java
  src/main/java/teammates/storage/entity/FeedbackSession.java
  src/main/java/teammates/ui/template/InstructorFeedbackResultsGroupByQuestionPanel.java
  src/main/java/teammates/ui/template/InstructorFeedbackResultsResponseRow.java
  src/main/resources/package.json
  src/main/webapp/dev/js/common/const.js
  src/main/webapp/dev/js/common/countryCodes.js
  src/main/webapp/dev/js/common/questionRubric.js
  src/main/webapp/dev/js/common/sortBy.js
  src/main/webapp/dev/js/main/adminHome.js
  src/main/webapp/dev/js/main/feedbackSubmissionsEdit.js
  src/main/webapp/dev/js/main/instructorCourseEdit.js
  src/main/webapp/dev/js/main/instructorCourseEnrollPage.js
  src/main/webapp/dev/js/test/InstructorEnrolmentJsTest.js
  src/test/resources/pages/instructorCourseEditHelper.html
  src/test/resources/pages/instructorCoursesNoCourse.html
  src/test/resources/pages/instructorFeedbackEditEmpty.html
  src/test/resources/pages/instructorFeedbackEmptyAll.html
  src/test/resources/pages/instructorFeedbackResultsPageOpen.html
  src/test/resources/pages/instructorFeedbackSubmitPageAwaiting.html
  src/test/resources/pages/instructorStudentRecords.html
  src/test/resources/pages/studentFeedbackSubmitPageAwaiting.html
  src/test/resources/pages/unregisteredStudentFeedbackSubmitPageOpen.html
  static-analysis/teammates-eslint.yml
Labels: s.ToMerge
