Repository TEAMMATES/teammates, pull requests merged in 2018-02, with the labels that each got.

#8404 Instructor: copy sessions: fix inconsistency in instructions #8403
  src/main/webapp/WEB-INF/tags/instructor/feedbacks/copyFromModal.tag
  src/test/resources/pages/instructorFeedbackAllSessionTypes.html
  src/test/resources/pages/instructorFeedbackAllSessionTypesWithHelperView.html
  src/test/resources/pages/instructorFeedbackDeleteSuccessful.html
  src/test/resources/pages/instructorFeedbackEditCopySuccess.html
  src/test/resources/pages/instructorFeedbackEmptyAll.html
  src/test/resources/pages/instructorFeedbackEmptySession.html
  src/test/resources/pages/instructorFeedbackPublishSuccessful.html
  src/test/resources/pages/instructorFeedbackUnpublishSuccessful.html
Labels: e.1, s.MergeApproved

#8425 Release V6.2.0 #8424
  src/main/webapp/data/developers.json
Labels: c.Release, e.1, s.MergeApproved

#8374 Instructor: Session: Disable submit button after session is closed #8368
  src/main/java/teammates/ui/template/InstructorFeedbackSessionActions.java
  src/test/resources/pages/instructorFeedbackAllSessionTypes.html
  src/test/resources/pages/instructorFeedbackAllSessionTypesWithHelperView.html
  src/test/resources/pages/instructorFeedbackDeleteSuccessful.html
  src/test/resources/pages/instructorFeedbackPublishSuccessful.html
  src/test/resources/pages/instructorFeedbackUnpublishSuccessful.html
  src/test/resources/pages/instructorHomeCourseArchiveSuccessful.html
  src/test/resources/pages/instructorHomeHTML.html
  src/test/resources/pages/instructorHomeHTMLResponseRateFail.html
  src/test/resources/pages/instructorHomeHTMLResponseRatePass.html
  src/test/resources/pages/instructorHomeHTMLSortByDate.html
  src/test/resources/pages/instructorHomeHTMLSortById.html
  src/test/resources/pages/instructorHomeHTMLSortByName.html
  src/test/resources/pages/instructorHomeHTMLSortSessionsByEndDate.html
  src/test/resources/pages/instructorHomeHTMLSortSessionsByName.html
  src/test/resources/pages/instructorHomeHTMLSortSessionsByStartDate.html
  src/test/resources/pages/instructorHomeHTMLWithHelperView.html
  src/test/resources/pages/newlyJoinedInstructorHomePage.html
Labels: s.ToMerge

#8400 Average Rank Excluding Self calculation not intuitive to users #8280
  src/main/java/teammates/common/datatransfer/questions/FeedbackRankOptionsQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRankQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRankRecipientsQuestionDetails.java
  src/main/java/teammates/common/util/Templates.java
  src/main/resources/feedbackQuestionRankResultStatsOptionFragment.html
  src/main/resources/feedbackQuestionRankResultStatsRecipientFragment.html
  src/main/resources/feedbackQuestionRankResultStatsRecipientTemplate.html
  src/main/resources/feedbackQuestionRankResultStatsTemplate.html
  src/main/webapp/partials/instructorHelpSessions.jsp
  src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
  src/test/resources/data/FeedbackSessionQuestionTypeTest.json
  src/test/resources/pages/instructorFeedbackResultsPageRankQuestionView.html
  src/test/resources/pages/instructorFeedbackResultsPageRankRQGView.html
  src/test/resources/pages/instructorFeedbackResultsPageRankRecipient.html
  src/test/resources/pages/instructorStudentRecordsPageMixedQuestionType.html
  src/test/resources/pages/newlyJoinedInstructorThirdFeedbackSessionResultsPage.html
Labels: s.ToMerge

#8455 FeedbackSession: repurpose legacy timeZone field #8410
  src/main/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributes.java
  src/main/java/teammates/storage/api/FeedbackSessionsDb.java
  src/main/java/teammates/storage/entity/FeedbackSession.java
Labels: e.1, s.MergeApproved

#8456 FeedbackSession: use primitive type for all booleans #8451
  src/main/java/teammates/storage/entity/FeedbackSession.java
Labels: e.1, s.MergeApproved

#8434 InstructorFeedbackResultsPage: merge tooltips with duplicate information #8432
  src/main/java/teammates/common/util/Const.java
  src/main/resources/feedbackQuestionContribResultStatsTemplate.html
  src/test/resources/pages/instructorFeedbackResultsSortSecondSessionFilteredBySectionATeam.html
  src/test/resources/pages/newlyJoinedInstructorFirstFeedbackSessionResultsPage.html
  src/test/resources/pages/newlyJoinedInstructorThirdFeedbackSessionResultsPage.html
Labels: e.1, s.MergeApproved

#8379 instructorFeedbackEdit: fix visibility checkboxes not responsive after discarding changes #7784
  src/main/webapp/WEB-INF/tags/instructor/feedbackEdit/questionEditForm.tag
  src/main/webapp/dev/js/common/visibilityOptions.js
  src/test/java/teammates/test/pageobjects/InstructorFeedbackEditPage.java
  src/test/resources/pages/instructorFeedbackConstSumOptionQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackConstSumOptionQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackConstSumRecipientQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackConstSumRecipientQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackContribQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackContribQuestionEdit.html
  src/test/resources/pages/instructorFeedbackContribQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackCopyQuestionSuccess.html
  src/test/resources/pages/instructorFeedbackEditCopyFail.html
  src/test/resources/pages/instructorFeedbackEditCopyPage.html
  src/test/resources/pages/instructorFeedbackEditPageTestingSanitization.html
  src/test/resources/pages/instructorFeedbackMcqQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackMcqQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackMsqQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackMsqQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackNumScaleQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackNumScaleQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackQuestionEditToTeamToTeam.html
  src/test/resources/pages/instructorFeedbackQuestionVisibilityOptions.html
  src/test/resources/pages/instructorFeedbackQuestionVisibilityPreview.html
  src/test/resources/pages/instructorFeedbackRankMinMaxChoicesSuccess.html
  src/test/resources/pages/instructorFeedbackRankQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackRankQuestionEdit.html
  src/test/resources/pages/instructorFeedbackRankQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionAddSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEdit.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditChoiceSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditDescriptionSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditSubQuestionSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionEditWeightSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionMoveColumnNewQuestionSuccess.html
  src/test/resources/pages/instructorFeedbackRubricQuestionMoveColumnSuccess.html
  src/test/resources/pages/instructorFeedbackTeamPeerEvalTemplateAddSuccess.html
Labels: e.1, s.MergeApproved

#8413 Instructor: copy session: allow observers to copy sessions #6594
  src/main/java/teammates/ui/controller/InstructorFeedbackEditCopyAction.java
  src/test/java/teammates/test/cases/action/InstructorFeedbackEditCopyActionTest.java
  src/test/resources/data/InstructorFeedbackEditCopyTest.json
  src/test/resources/pages/instructorFeedbackEditCopyFail.html
  src/test/resources/pages/instructorFeedbackEditCopyPage.html
Labels: e.1, s.MergeApproved

#8457 AutomatedServlet: catch all Throwables for logging #8454
  src/main/java/teammates/ui/automated/AutomatedServlet.java
Labels: e.1, s.MergeApproved

#8460 AdminLogQueryTest : Fix PMD problem #8459
  src/test/java/teammates/test/cases/BaseTestCase.java
  src/test/java/teammates/test/cases/util/AdminLogQueryTest.java
Labels: s.MergeApproved

#8401 const.js: rename and document semantics of constants #7706
  src/main/webapp/dev/js/common/bootboxWrapper.js
  src/main/webapp/dev/js/common/const.js
  src/main/webapp/dev/js/common/feedbackResponseComments.js
  src/main/webapp/dev/js/common/instructor.js
  src/main/webapp/dev/js/common/questionConstSum.js
  src/main/webapp/dev/js/common/questionRank.js
  src/main/webapp/dev/js/common/questionRubric.js
  src/main/webapp/dev/js/common/statusMessage.js
  src/main/webapp/dev/js/common/student.js
  src/main/webapp/dev/js/main/adminAccountManagement.js
  src/main/webapp/dev/js/main/adminActivityLog.js
  src/main/webapp/dev/js/main/adminEmail.js
  src/main/webapp/dev/js/main/adminEmailLog.js
  src/main/webapp/dev/js/main/adminSearch.js
  src/main/webapp/dev/js/main/errorPageEmailComposer.js
  src/main/webapp/dev/js/main/feedbackSubmissionsEdit.js
  src/main/webapp/dev/js/main/instructorCourseDetails.js
  src/main/webapp/dev/js/main/instructorCourseEdit.js
  src/main/webapp/dev/js/main/instructorCourseEnrollPage.js
  src/main/webapp/dev/js/main/instructorCourseStudentEdit.js
  src/main/webapp/dev/js/main/instructorCourses.js
  src/main/webapp/dev/js/main/instructorFeedbackEdit.js
  src/main/webapp/dev/js/main/instructorFeedbacks.js
  src/main/webapp/dev/js/main/instructorHome.js
  src/main/webapp/dev/js/main/instructorStudentList.js
  src/main/webapp/dev/js/main/studentProfile.js
  src/main/webapp/dev/js/test/CommonJsTest.js
Labels: s.MergeApproved

#8458 Java: Use Java 7 try-with-resources for AutoCloseable resources #8213
  src/main/java/teammates/common/exception/TeammatesException.java
  src/main/java/teammates/common/util/Config.java
  src/main/java/teammates/common/util/ThreadHelper.java
  src/main/java/teammates/logic/core/MailgunService.java
  src/test/java/teammates/test/cases/logic/EmailSenderTest.java
  src/test/java/teammates/test/driver/GmailServiceMaker.java
  src/test/java/teammates/test/driver/TestProperties.java
Labels: s.MergeApproved

#8484 Fix AppVeyor failing build due to InstructorHomePageUiTest #8483
  src/test/java/teammates/test/pageobjects/InstructorHomePage.java
Labels: e.1, s.MergeApproved

#8482 AutomatedServlet: always log request parameters #8481
  src/main/java/teammates/ui/automated/AutomatedServlet.java
Labels: e.1, s.MergeApproved

#8469 Instructor: add options (Rank and Distribute Points) question: add more options inputs not appearing #8463
  src/main/webapp/dev/js/common/questionConstSum.js
  src/main/webapp/dev/js/common/questionRank.js
  src/main/webapp/dev/js/main/instructorFeedbackEdit.js
Labels: s.MergeApproved

#8441 Instructor: session results: contribution questions: show 'Not Sure' as 'Not Sure' instead of 'N/A' #2908
  src/main/java/teammates/common/datatransfer/TeamEvalResult.java
  src/test/java/teammates/test/cases/datatransfer/TeamEvalResultTest.java
Labels: e.2, s.MergeApproved

#8499 development.md: As Instructor: Remove `Short Name` from credentials of Instructor in Setting up guide #8495
  docs/development.md
Labels: e.1, s.MergeApproved

#8420 Replace all instances of `Const#EOL` with `System#lineSeparator()` #8299
  src/main/java/teammates/common/datatransfer/FeedbackSessionDetailsBundle.java
  src/main/java/teammates/common/datatransfer/TeamEvalResult.java
  src/main/java/teammates/common/datatransfer/attributes/StudentAttributes.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackConstantSumQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackMcqQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackMsqQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackNumericalScaleQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRankOptionsQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRankRecipientsQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetails.java
  src/main/java/teammates/common/exception/TeammatesException.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/common/util/StringHelper.java
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/main/java/teammates/logic/core/CoursesLogic.java
  src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/logic/core/StudentsLogic.java
  src/main/java/teammates/ui/controller/Action.java
  src/main/java/teammates/ui/controller/AdminEmailGroupReceiverListUploadAction.java
  src/main/java/teammates/ui/controller/AdminInstructorAccountAddAction.java
  src/main/java/teammates/ui/controller/ImageUploadAction.java
  src/main/java/teammates/ui/controller/StudentProfilePictureUploadAction.java
  src/test/java/teammates/test/cases/action/InstructorCourseEnrollSaveActionTest.java
  src/test/java/teammates/test/cases/action/InstructorCourseStudentListDownloadActionTest.java
  src/test/java/teammates/test/cases/action/InstructorFeedbackResultsDownloadActionTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorCourseEnrollPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorSubmissionAdjustmentUiTest.java
  src/test/java/teammates/test/cases/browsertests/TimezoneSyncerTest.java
  src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java
  src/test/java/teammates/test/cases/datatransfer/CourseAttributesTest.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackQuestionAttributesTest.java
  src/test/java/teammates/test/cases/datatransfer/InstructorAttributesTest.java
  src/test/java/teammates/test/cases/datatransfer/StudentAttributesTest.java
  src/test/java/teammates/test/cases/datatransfer/TeamEvalResultTest.java
  src/test/java/teammates/test/cases/logic/CoursesLogicTest.java
  src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
  src/test/java/teammates/test/cases/logic/StudentsLogicTest.java
  src/test/java/teammates/test/cases/storage/FeedbackSessionsDbTest.java
  src/test/java/teammates/test/cases/storage/InstructorsDbTest.java
  src/test/java/teammates/test/cases/testdriver/HtmlHelperTest.java
  src/test/java/teammates/test/cases/util/StringHelperTest.java
  src/test/java/teammates/test/driver/EmailChecker.java
  src/test/java/teammates/test/driver/GmailServiceMaker.java
  src/test/java/teammates/test/driver/HtmlHelper.java
  src/test/java/teammates/test/pageobjects/InstructorStudentListPage.java
Labels: s.MergeApproved

#8487 Refactor instructorFeedbackResults<...>.js #5329
  src/main/webapp/dev/js/common/instructorFeedbackResults.js
  src/main/webapp/dev/js/main/instructorFeedbackResultsGQR.js
  src/main/webapp/dev/js/main/instructorFeedbackResultsGRQ.js
  src/main/webapp/dev/js/main/instructorFeedbackResultsRGQ.js
  src/main/webapp/dev/js/main/instructorFeedbackResultsRQG.js
Labels: s.ToReview

#8486 Setup docs: Add installation instructions for Debian and Fedora OS #8491
  docs/setting-up.md
Labels: s.Ongoing

#8326 Attributes tests: avoid passing in an empty Google ID for student profiles #7645
  src/main/java/teammates/common/datatransfer/attributes/AccountAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/StudentProfileAttributes.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/backdoor/BackDoorLogic.java
  src/main/java/teammates/logic/core/AccountsLogic.java
  src/main/java/teammates/storage/api/AccountsDb.java
  src/main/java/teammates/storage/entity/Account.java
  src/main/java/teammates/storage/entity/StudentProfile.java
  src/main/java/teammates/ui/controller/StudentProfileEditSaveAction.java
  src/test/java/teammates/test/cases/BaseTestCaseWithDatastoreAccess.java
  src/test/java/teammates/test/cases/action/InstructorStudentRecordsPageActionTest.java
  src/test/java/teammates/test/cases/action/StudentCourseDetailsPageActionTest.java
  src/test/java/teammates/test/cases/action/StudentProfileEditSaveActionTest.java
  src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java
  src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java
  src/test/java/teammates/test/cases/datatransfer/StudentProfileAttributesTest.java
  src/test/java/teammates/test/cases/logic/AccountsLogicTest.java
  src/test/java/teammates/test/cases/logic/CoursesLogicTest.java
  src/test/java/teammates/test/cases/logic/ProfilesLogicTest.java
  src/test/java/teammates/test/cases/logic/StudentsLogicTest.java
  src/test/java/teammates/test/cases/pagedata/InstructorCourseStudentDetailsPageDataTest.java
  src/test/java/teammates/test/cases/pagedata/StudentProfilePageDataTest.java
  src/test/java/teammates/test/cases/storage/AccountsDbTest.java
  src/test/java/teammates/test/cases/storage/ProfilesDbTest.java
Labels: e.2, s.MergeApproved

#8389 TimeHelper: migrate to Java 8's `java.time` #8362
  src/main/java/teammates/common/util/TimeHelper.java
  src/test/java/teammates/test/cases/util/TimeHelperTest.java
Labels: e.1, s.ToMerge

#8395 Instructor Help: integrate documentation for contribution questions #8328
  src/main/resources/feedbackQuestionContribResultStatsStudentViewAdditionalInfo.html
  src/main/webapp/partials/instructorHelpFAQ.jsp
  src/main/webapp/partials/technicalInformationCalculatePointsContribution.jsp
  src/main/webapp/stylesheets/teammatesCommon.css
  src/main/webapp/technicalInformation.jsp
  src/test/resources/pages/newlyJoinedInstructorStudentFeedbackResultsPage.html
  src/test/resources/pages/studentFeedbackResultsPageCONTRIB.html
Labels: s.MergeApproved

#8506 Instructor: enroll students in course: update link to sample spreadsheet #8500
  src/main/webapp/jsp/instructorCourseEnroll.jsp
  src/test/java/teammates/test/cases/browsertests/InstructorCourseEnrollPageUiTest.java
  src/test/resources/pages/instructorCourseEnrollError.html
  src/test/resources/pages/instructorCourseEnrollPage.html
Labels: e.1, s.MergeApproved

#8520 Release V6.3.0 #8519
  src/main/webapp/data/developers.json
Labels: c.Release, e.1, s.MergeApproved

#8472 MCQ and MSQ question: fix cancel question feature #7934
  src/main/webapp/dev/js/main/instructorFeedbackEdit.js
  src/test/java/teammates/test/cases/browsertests/FeedbackMcqQuestionUiTest.java
  src/test/java/teammates/test/cases/browsertests/FeedbackMsqQuestionUiTest.java
Labels: s.MergeApproved

#8426 AccountAttributes: Add test cases for getCopy() #8419
  src/test/java/teammates/test/cases/BaseTestCase.java
  src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java
Labels: e.2, s.MergeApproved
