Repository TEAMMATES/teammates, pull requests merged in 2019-02, with the labels that each got.

#9395 [#9382] Refactor chained boolean values into function
  src/web/app/pages-help/instructor-help-page/instructor-help-section.component.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.ts
Labels: s.FinalReview

#9388 [#9377] Fix unstable FeedbackSessionsLogicTest
  src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
  src/test/java/teammates/test/cases/storage/FeedbackSessionsDbTest.java
Labels: s.ToMerge

#9380 [#9362] Replace responseMetaData with responseDetails in FeedbackResponseAttributes
  src/client/java/teammates/client/scripts/DataBundleRegenerator.java
  src/main/java/teammates/common/datatransfer/attributes/FeedbackResponseAttributes.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackResponseDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackTextResponseDetails.java
  src/main/java/teammates/common/util/JsonUtils.java
  src/main/java/teammates/logic/core/FeedbackResponsesLogic.java
  src/main/java/teammates/storage/api/FeedbackResponsesDb.java
  src/main/java/teammates/ui/webapi/action/CreateFeedbackResponseAction.java
  src/main/java/teammates/ui/webapi/action/SaveFeedbackResponseAction.java
  src/main/resources/InstructorSampleData.json
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/StudentFeedbackSubmitPageUiTest.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackResponseAttributesTest.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackResponseDetailsTest.java
  src/test/java/teammates/test/cases/logic/FeedbackResponsesLogicTest.java
  src/test/java/teammates/test/cases/storage/FeedbackResponsesDbTest.java
  src/test/resources/data/AllAccessControlUiTest.json
  src/test/resources/data/EmailGeneratorTest.json
  src/test/resources/data/FeedbackMcqQuestionUiTest.json
  src/test/resources/data/FeedbackParticipantFeedbackResponseCommentDeleteTest.json
  src/test/resources/data/FeedbackRankQuestionUiTest.json
  src/test/resources/data/FeedbackRubricQuestionUiTest.json
  src/test/resources/data/FeedbackSessionDetailsTest.json
  src/test/resources/data/FeedbackSessionQuestionTypeTest.json
  src/test/resources/data/FeedbackSessionResultsBundleTest.json
  src/test/resources/data/FeedbackSessionResultsTest.json
  src/test/resources/data/FeedbackSessionsLogicTest.json
  src/test/resources/data/InstructorEditInstructorFeedbackPageTest.json
  src/test/resources/data/InstructorEditStudentFeedbackPageTest.json
  src/test/resources/data/InstructorFeedbackEditCopyTest.json
  src/test/resources/data/InstructorFeedbackResultsPageResponseCommentUiTest.json
  src/test/resources/data/InstructorFeedbackResultsPageUiTest.json
  src/test/resources/data/InstructorFeedbackSubmissionEditSaveActionTest.json
  src/test/resources/data/InstructorSearchPageUiTest.json
  src/test/resources/data/InstructorStudentRecordsPageUiTest.json
  src/test/resources/data/InstructorSubmissionAdjustmentUiTest.json
  src/test/resources/data/MashupPageUiTest.json
  src/test/resources/data/SpecialCharacterTest.json
  src/test/resources/data/StudentFeedbackResultsPageUiTest.json
  src/test/resources/data/StudentFeedbackSubmissionEditPageActionTest.json
  src/test/resources/data/typicalDataBundle.json
Labels: c.Task, s.FinalReview

#9384 [#9382] Integrate rich text editor
  angular.json
  package.json
  src/main/java/teammates/ui/webapi/action/WebPageServlet.java
  src/main/webapp-backup/dev/js/main/feedbackSubmissionsEdit.js
  src/main/webapp-backup/dev/js/main/instructorFeedbackEdit.js
  src/web/app/components/question-types/question-types-session-edit/question-edit-form.component.html
  src/web/app/components/question-types/question-types-session-edit/question-types-session-edit.module.ts
  src/web/app/components/question-types/question-types-session-submission/question-submission-form.component.html
  src/web/app/components/question-types/question-types-session-submission/question-types-session-submission.module.ts
  src/web/app/components/question-types/question-types-session-submission/recipient-submission-form/text-recipient-submission-form/text-recipient-submission-form.component.html
  src/web/app/components/question-types/question-types-session-submission/recipient-submission-form/text-recipient-submission-form/text-recipient-submission-form.component.spec.ts
  src/web/app/components/rich-text-editor/rich-text-editor.component.html
  src/web/app/components/rich-text-editor/rich-text-editor.component.scss
  src/web/app/components/rich-text-editor/rich-text-editor.component.spec.ts
  src/web/app/components/rich-text-editor/rich-text-editor.component.ts
  src/web/app/components/rich-text-editor/rich-text-editor.module.ts
  src/web/app/components/session-edit-form/session-edit-form.component.html
  src/web/app/components/session-edit-form/session-edit-form.module.ts
  src/web/app/components/teammates-common/safe-html.pipe.spec.ts
  src/web/app/components/teammates-common/safe-html.pipe.ts
  src/web/app/components/teammates-common/teammates-common.module.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.component.html
  src/web/app/pages-session/session-submission-page/session-submission-page.module.ts
  src/web/index.html
  src/web/tinymce/placeholder-plugin.js
Labels: s.ToMerge

#9376 [#9116] Push soft-delete logic to DB layer
  src/main/java/teammates/common/datatransfer/attributes/CourseAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributes.java
  src/main/java/teammates/logic/core/CoursesLogic.java
  src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/storage/api/CoursesDb.java
  src/main/java/teammates/storage/api/FeedbackSessionsDb.java
  src/test/java/teammates/test/cases/browsertests/InstructorCoursesPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java
  src/test/java/teammates/test/cases/logic/CoursesLogicTest.java
  src/test/java/teammates/test/cases/storage/CoursesDbTest.java
  src/test/java/teammates/test/cases/storage/FeedbackSessionsDbTest.java
Labels: c.Task, s.ToMerge

#9403 [#9219] live server: NPE in feedbackResponseAdjustment when changing student data
  src/main/java/teammates/logic/core/FeedbackResponsesLogic.java
Labels: s.ToMerge

#9415 [#9407] Remove feedbackQuestionType in FeedbackResponseAttributes
  src/main/java/teammates/common/datatransfer/attributes/FeedbackResponseAttributes.java
  src/main/java/teammates/logic/core/FeedbackResponsesLogic.java
  src/main/java/teammates/ui/template/FeedbackResultsTable.java
  src/main/java/teammates/ui/webapi/action/CreateFeedbackResponseAction.java
  src/main/resources/InstructorSampleData.json
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackResponseAttributesTest.java
  src/test/java/teammates/test/cases/logic/FeedbackResponsesLogicTest.java
  src/test/java/teammates/test/cases/storage/FeedbackResponsesDbTest.java
  src/test/resources/data/AllAccessControlUiTest.json
  src/test/resources/data/EmailGeneratorTest.json
  src/test/resources/data/FeedbackMcqQuestionUiTest.json
  src/test/resources/data/FeedbackParticipantFeedbackResponseCommentDeleteTest.json
  src/test/resources/data/FeedbackRankQuestionUiTest.json
  src/test/resources/data/FeedbackRubricQuestionUiTest.json
  src/test/resources/data/FeedbackSessionDetailsTest.json
  src/test/resources/data/FeedbackSessionQuestionTypeTest.json
  src/test/resources/data/FeedbackSessionResultsBundleTest.json
  src/test/resources/data/FeedbackSessionResultsTest.json
  src/test/resources/data/FeedbackSessionsLogicTest.json
  src/test/resources/data/InstructorEditInstructorFeedbackPageTest.json
  src/test/resources/data/InstructorEditStudentFeedbackPageTest.json
  src/test/resources/data/InstructorFeedbackEditCopyTest.json
  src/test/resources/data/InstructorFeedbackResultsPageResponseCommentUiTest.json
  src/test/resources/data/InstructorFeedbackResultsPageUiTest.json
  src/test/resources/data/InstructorFeedbackSubmissionEditSaveActionTest.json
  src/test/resources/data/InstructorSearchPageUiTest.json
  src/test/resources/data/InstructorStudentRecordsPageUiTest.json
  src/test/resources/data/InstructorSubmissionAdjustmentUiTest.json
  src/test/resources/data/MashupPageUiTest.json
  src/test/resources/data/SpecialCharacterTest.json
  src/test/resources/data/StudentFeedbackResultsPageUiTest.json
  src/test/resources/data/StudentFeedbackSubmissionEditPageActionTest.json
  src/test/resources/data/typicalDataBundle.json
Labels: s.FinalReview

#9414 [#9405] Show default picture as profile photo for student who is yet to join
  src/main/java/teammates/ui/webapi/action/GetCourseStudentDetailsAction.java
  src/test/java/teammates/test/cases/webapi/GetCourseStudentDetailsActionTest.java
  src/web/app/pages-instructor/student-list/student-list.component.ts
Labels: s.ToMerge

#9394 [#9382] Migrate courses section of instructor help page to Angular
  src/web/app/pages-help/instructor-help-page/instructor-help-courses-section/instructor-help-courses-section.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-courses-section/instructor-help-courses-section.component.scss
  src/web/app/pages-help/instructor-help-page/instructor-help-courses-section/instructor-help-courses-section.component.spec.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-courses-section/instructor-help-courses-section.component.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-page.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-page.component.spec.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-page.module.ts
Labels: s.ToMerge

#9397 [#9382] Migrate session and question section in instructor help page
  src/web/app/pages-help/instructor-help-page/instructor-help-page.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-page.component.spec.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-page.module.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.scss
  src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.spec.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.scss
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.spec.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.ts
Labels: s.Ongoing

#9398 [#9382] Migrate instructor getting started page
  src/web/app/pages-help/instructor-help-page/instructor-help-getting-started/instructor-help-getting-started.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-getting-started/instructor-help-getting-started.component.scss
  src/web/app/pages-help/instructor-help-page/instructor-help-getting-started/instructor-help-getting-started.component.spec.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-getting-started/instructor-help-getting-started.component.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-page.module.ts
  src/web/app/pages-instructor/instructor-pages.module.ts
  src/web/app/pages-static/static-pages.module.ts
Labels: s.Ongoing

#9406 [#9366] Tidy up UI design for some system messages
  src/web/app/page.component.html
  src/web/assets/images/angry.png
Labels: s.ToMerge

#9425 [#9382] Migrate technical information portions to Angular
  src/main/webapp-backup/dev/js/main/instructorHelp.js
  src/main/webapp-backup/gettingStarted.jsp
  src/main/webapp-backup/instructorHelp.jsp
  src/main/webapp-backup/partials/instructorHelpCourses.jsp
  src/main/webapp-backup/partials/instructorHelpQuestions.jsp
  src/main/webapp-backup/partials/instructorHelpSessions.jsp
  src/main/webapp-backup/partials/instructorHelpStudents.jsp
  src/main/webapp-backup/partials/instructorHelpTips.jsp
  src/main/webapp-backup/partials/technicalInformationCalculatePointsContribution.jsp
  src/main/webapp-backup/partials/technicalInformationCalculateRanks.jsp
  src/main/webapp-backup/technicalInformation.jsp
  src/web/app/pages-help/instructor-help-page/instructor-help-page.component.spec.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.spec.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.ts
Labels: s.ToReview

#9427 [#9420] Consolidate nationalities RESTFul API
  src/main/java/teammates/ui/webapi/action/GetNationalitiesAction.java
  src/main/java/teammates/ui/webapi/output/NationalitiesData.java
  src/test/java/teammates/test/cases/webapi/GetNationalitiesActionTest.java
  src/web/app/pages-student/student-profile-page/student-profile-page.component.ts
Labels: s.ToMerge

#9430 [#9420] Consolidate time-related RESTFul APIs
  src/main/java/teammates/common/util/TimeHelper.java
  src/main/java/teammates/ui/webapi/action/GetLocalDateTimeInfoAction.java
  src/main/java/teammates/ui/webapi/action/GetTimeZonesAction.java
  src/main/java/teammates/ui/webapi/output/LocalDateTimeInfo.java
  src/main/java/teammates/ui/webapi/output/TimeZonesData.java
  src/test/java/teammates/test/cases/webapi/GetLocalDateTimeInfoActionTest.java
  src/test/java/teammates/test/cases/webapi/GetTimeZonesActionTest.java
  src/web/app/pages-admin/admin-timezone-page/admin-timezone-page.component.ts
  src/web/services/timezone.service.ts
Labels: s.FinalReview

#9418 [#7603] Use enum instead of string for gender field in StudentProfileAttributes and related classes
  src/main/java/teammates/common/datatransfer/attributes/StudentProfileAttributes.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/common/util/FieldValidator.java
  src/main/java/teammates/storage/api/ProfilesDb.java
  src/main/java/teammates/ui/webapi/action/PutStudentProfileAction.java
  src/main/resources/InstructorSampleData.json
  src/test/java/teammates/test/cases/browsertests/StudentProfilePageUiTest.java
  src/test/java/teammates/test/cases/datatransfer/StudentProfileAttributesTest.java
  src/test/java/teammates/test/cases/logic/ProfilesLogicTest.java
  src/test/java/teammates/test/cases/util/FieldValidatorTest.java
  src/test/java/teammates/test/cases/webapi/PutStudentProfileActionTest.java
  src/test/java/teammates/test/pageobjects/StudentProfilePage.java
  src/test/resources/data/AllAccessControlUiTest.json
  src/test/resources/data/FeedbackSessionResultsBundleTest.json
  src/test/resources/data/FeedbackSessionsLogicTest.json
  src/test/resources/data/InstructorCourseDetailsPageUiTest.json
  src/test/resources/data/InstructorCourseStudentDetailsPageUiTest.json
  src/test/resources/data/InstructorEditInstructorFeedbackPageTest.json
  src/test/resources/data/InstructorEditStudentFeedbackPageTest.json
  src/test/resources/data/InstructorSearchPageUiTest.json
  src/test/resources/data/InstructorStudentListPageUiTest.json
  src/test/resources/data/InstructorStudentRecordsPageUiTest.json
  src/test/resources/data/MashupPageUiTest.json
  src/test/resources/data/StudentCourseDetailsPageUiTest.json
  src/test/resources/data/StudentCourseJoinAuthenticatedTest.json
  src/test/resources/data/StudentFeedbackSubmissionEditPageActionTest.json
  src/test/resources/data/StudentHomePageUiTest.json
  src/test/resources/data/StudentProfilePageUiTest.json
  src/test/resources/data/typicalDataBundle.json
Labels: s.FinalReview

#9444 [#9420] Consolidate RPC RESTFul API
  src/main/java/teammates/ui/webapi/action/SendErrorReportAction.java
  src/main/java/teammates/ui/webapi/request/ErrorReportRequest.java
  src/test/java/teammates/test/cases/webapi/SendErrorReportActionTest.java
  src/web/app/components/error-report/error-report.component.ts
Labels: s.ToMerge

#9429 [#9382] Add custom privileges for instructor course edit page
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.html
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.scss
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.ts
Labels: s.ToMerge

#9445 [#9420] Consolidate FeedbackSessionStats RESTFul API
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/webapi/action/ActionFactory.java
  src/main/java/teammates/ui/webapi/action/GetSessionResponseStatsAction.java
  src/main/java/teammates/ui/webapi/output/FeedbackSessionStatsData.java
  src/test/java/teammates/test/cases/webapi/GetSessionResponseStatsActionTest.java
  src/web/app/feedback-session.ts
  src/web/app/pages-admin/admin-sessions-page/admin-sessions-page.component.ts
  src/web/app/pages-instructor/instructor-session-base-page.component.ts
Labels: s.ToMerge

#9441 [#9439] Fix submission button not working caused by serializing FeedbackQuestionAttributes
  src/main/java/teammates/common/util/JsonUtils.java
  src/test/java/teammates/test/cases/util/JsonUtilsTest.java
Labels: s.ToMerge

#9450 [#9382] Fix logic bug when there are no existing students in course
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts
Labels: s.ToMerge

#9400 [#7787] InstructorAttributes: remove HTML sanitization before saving for name
  src/client/java/teammates/client/scripts/DataMigrationForSanitizedInstructorName.java
  src/main/java/teammates/common/datatransfer/attributes/InstructorAttributes.java
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/main/java/teammates/storage/search/InstructorSearchDocument.java
  src/test/java/teammates/test/cases/datatransfer/InstructorAttributesTest.java
Labels: s.FinalReview

#9455 [#9434] Fixed brittle asserts for time zone offsets in GetTimeZonesDataActionTest
  src/test/java/teammates/test/cases/webapi/GetTimeZonesActionTest.java
Labels: s.ToMerge

#9402 [#2515] Instructor: edit instructors: ensure at least one instructor is visible to students
  src/main/java/teammates/logic/core/InstructorsLogic.java
  src/main/java/teammates/storage/api/InstructorsDb.java
  src/main/java/teammates/storage/entity/Instructor.java
  src/main/java/teammates/ui/webapi/action/DeleteInstructorInCourseAction.java
  src/main/java/teammates/ui/webapi/action/EditInstructorInCourseAction.java
  src/main/java/teammates/ui/webapi/action/StudentGetCourseDetailsAction.java
  src/test/java/teammates/test/cases/logic/AccountsLogicTest.java
  src/test/java/teammates/test/cases/logic/InstructorsLogicTest.java
  src/test/java/teammates/test/cases/storage/InstructorsDbTest.java
  src/test/java/teammates/test/cases/webapi/DeleteInstructorInCourseActionTest.java
  src/test/java/teammates/test/cases/webapi/EditInstructorInCourseActionTest.java
  src/test/java/teammates/test/cases/webapi/StudentGetCourseDetailsActionTest.java
  src/test/resources/data/typicalDataBundle.json
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.ts
Labels: s.ToMerge

#9428 [#5616] Implement side nav to replace links on top for Instructor Help Page
  src/web/app/pages-help/instructor-help-page/instructor-help-page.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-page.component.scss
  src/web/app/pages-help/instructor-help-page/instructor-help-page.component.ts
  src/web/app/pages-help/instructor-help-page/sections.ts
Labels: s.ToMerge

#9440 [#9438] Use newly introduced Gender enum in frontend
  src/web/app/pages-instructor/student-profile/student-profile.component.html
  src/web/app/pages-instructor/student-profile/student-profile.component.ts
  src/web/app/pages-instructor/student-profile/student-profile.ts
  src/web/app/pages-student/student-course-details-page/student-course-details-page.component.html
  src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts
  src/web/app/pages-student/student-pages.module.ts
  src/web/app/pages-student/student-profile-page/student-profile-gender.pipe.ts
  src/web/app/pages-student/student-profile-page/student-profile-page.component.html
  src/web/app/pages-student/student-profile-page/student-profile-page.component.spec.ts
  src/web/app/pages-student/student-profile-page/student-profile-page.component.ts
  src/web/types/gender.ts
Labels: c.Task, s.ToMerge

#9464 [#9456] Fix editing question when option filed is empty
  src/main/java/teammates/common/datatransfer/attributes/FeedbackQuestionAttributes.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackQuestionAttributesTest.java
Labels: s.ToMerge

#9463 [#9382] Adopt one-module-per-page pattern for all app pages
  src/web/app/app.module.spec.ts
  src/web/app/components/ajax-loading/ajax-loading.module.spec.ts
  src/web/app/components/ajax-preload/ajax-preload.module.spec.ts
  src/web/app/components/error-report/error-report.module.spec.ts
  src/web/app/components/session-edit-form/session-edit-form.module.spec.ts
  src/web/app/components/status-message/status-message.module.spec.ts
  src/web/app/page-not-found/page-not-found.module.spec.ts
  src/web/app/pages-admin/admin-accounts-page/admin-accounts-page.module.ts
  src/web/app/pages-admin/admin-home-page/admin-home-page.module.ts
  src/web/app/pages-admin/admin-pages.module.spec.ts
  src/web/app/pages-admin/admin-pages.module.ts
  src/web/app/pages-admin/admin-search-page/admin-search-page.module.ts
  src/web/app/pages-admin/admin-sessions-page/admin-sessions-page.module.ts
  src/web/app/pages-admin/admin-timezone-page/admin-timezone-page.module.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-page.module.spec.ts
  src/web/app/pages-help/student-help-page/student-help-page.module.spec.ts
  src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.module.ts
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.module.ts
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.module.ts
  src/web/app/pages-instructor/instructor-course-student-details-page/instructor-course-student-details-page.module.ts
  src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.module.ts
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.module.ts
  src/web/app/pages-instructor/instructor-pages.module.spec.ts
  src/web/app/pages-instructor/instructor-pages.module.ts
  src/web/app/pages-instructor/instructor-search-page/instructor-search-page.module.ts
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.module.spec.ts
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.module.spec.ts
  src/web/app/pages-instructor/instructor-sessions-result-page/instructor-sessions-result-page.module.ts
  src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.module.ts
  src/web/app/pages-instructor/instructor-student-records-page/instructor-student-records-page.module.ts
  src/web/app/pages-instructor/student-list/student-list.module.ts
  src/web/app/pages-instructor/student-profile/student-profile.module.ts
  src/web/app/pages-session/session-result-page/session-result-page.module.spec.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.module.spec.ts
  src/web/app/pages-static/about-page/about-page.module.ts
  src/web/app/pages-static/contact-page/contact-page.module.ts
  src/web/app/pages-static/features-page/features-page.module.ts
  src/web/app/pages-static/index-page/index-page.module.ts
  src/web/app/pages-static/request-page/request-page.module.ts
  src/web/app/pages-static/static-pages.module.spec.ts
  src/web/app/pages-static/static-pages.module.ts
  src/web/app/pages-static/terms-page/terms-page.module.ts
  src/web/app/pages-static/usermap-page/usermap-page.module.ts
  src/web/app/pages-student/student-course-details-page/student-course-details-page.module.ts
  src/web/app/pages-student/student-home-page/student-home-page.module.ts
  src/web/app/pages-student/student-pages.module.spec.ts
  src/web/app/pages-student/student-pages.module.ts
  src/web/app/pages-student/student-profile-page/student-profile-page.module.ts
  src/web/app/pages.module.spec.ts
  src/web/app/pipes/pipes.module.spec.ts
  src/web/jest.config.js
Labels: s.ToMerge

#9374 [#9382] Migrate part of instructor students page to Angular
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/controller/ActionFactory.java
  src/main/java/teammates/ui/controller/InstructorStudentListAjaxPageAction.java
  src/main/java/teammates/ui/controller/InstructorStudentListPageAction.java
  src/main/java/teammates/ui/datatransfer/InstructorStudentListPageCourseData.java
  src/main/java/teammates/ui/pagedata/InstructorStudentListAjaxPageData.java
  src/main/java/teammates/ui/pagedata/InstructorStudentListPageData.java
  src/main/java/teammates/ui/template/InstructorStudentListFilterBox.java
  src/main/java/teammates/ui/template/InstructorStudentListFilterCourse.java
  src/main/java/teammates/ui/template/InstructorStudentListSearchBox.java
  src/main/java/teammates/ui/template/InstructorStudentListStudentsTableCourse.java
  src/main/java/teammates/ui/webapi/action/ActionFactory.java
  src/main/java/teammates/ui/webapi/action/GetCourseStudentsAction.java
  src/main/java/teammates/ui/webapi/action/InstructorGetCoursesAction.java
  src/main/webapp-backup/WEB-INF/tags/instructor/studentList/filterBox.tag
  src/main/webapp-backup/WEB-INF/tags/instructor/studentList/searchBox.tag
  src/main/webapp-backup/WEB-INF/tags/instructor/studentList/studentsTable.tag
  src/main/webapp-backup/dev/js/main/instructorStudentList.js
  src/main/webapp-backup/jsp/instructorStudentList.jsp
  src/main/webapp-backup/jsp/instructorStudentListAjax.jsp
  src/test/java/teammates/test/cases/action/InstructorStudentListAjaxPageActionTest.java
  src/test/java/teammates/test/cases/action/InstructorStudentListPageActionTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorStudentListPageUiTest.java
  src/test/java/teammates/test/cases/webapi/BaseActionTest.java
  src/test/java/teammates/test/cases/webapi/GetCourseStudentsActionTest.java
  src/test/java/teammates/test/cases/webapi/InstructorGetCoursesActionTest.java
  src/test/java/teammates/test/driver/DataBundleHelper.java
  src/web/app/pages-instructor/instructor-search-page/instructor-search-page.component.ts
  src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.html
  src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.scss
  src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.spec.ts
  src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts
  src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.module.ts
  src/web/app/pages-instructor/student-list/student-list.component.html
  src/web/app/pages-instructor/student-list/student-list.component.ts
Labels: s.ToMerge

#9446 [#9420] Consolidate FeedbackQuestionRecipients RESTFul API
  src/main/java/teammates/ui/webapi/action/Action.java
  src/main/java/teammates/ui/webapi/action/BasicFeedbackSubmissionAction.java
  src/main/java/teammates/ui/webapi/action/GetFeedbackQuestionRecipientsAction.java
  src/main/java/teammates/ui/webapi/output/FeedbackQuestionRecipientData.java
  src/main/java/teammates/ui/webapi/output/FeedbackQuestionRecipientsData.java
  src/test/java/teammates/test/cases/webapi/BaseActionTest.java
  src/test/java/teammates/test/cases/webapi/GetFeedbackQuestionRecipientsActionTest.java
  src/test/resources/data/GetFeedbackQuestionRecipientsActionTest.json
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
Labels: c.Task, s.ToMerge

#9472 [#9461] Focus state of nav bar item results in bad readability
  src/web/app/page.component.scss
Labels: s.ToMerge

#9448 [#9411] Use bootstrap button in instructor courses page
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.html
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.scss
Labels: s.ToMerge

#9468 [#9449] Instructor Course Page: Tooltip in table 'Archived Courses' resulted in abnormal behaviour
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.html
Labels: s.ToMerge

#9476 [#9382] Migrate session results skeleton back-end
  src/main/java/teammates/common/datatransfer/questions/FeedbackConstantSumQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackMcqQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackMsqQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackNumericalScaleQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRankOptionsQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRankRecipientsQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackResponseDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackTextQuestionDetails.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/webapi/action/ActionFactory.java
  src/main/java/teammates/ui/webapi/action/GetSessionResultsAction.java
  src/main/java/teammates/ui/webapi/action/Intent.java
  src/main/java/teammates/ui/webapi/action/SaveFeedbackResponseAction.java
  src/main/java/teammates/ui/webapi/output/SessionResultsData.java
Labels: s.ToMerge

#9410 [#9363] Replace questionMetaData with questionDetails in FeedbackQuestionAttributes
  src/client/java/teammates/client/scripts/DataBundleRegenerator.java
  src/main/java/teammates/common/datatransfer/attributes/FeedbackQuestionAttributes.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackTextQuestionDetails.java
  src/main/java/teammates/common/util/JsonUtils.java
  src/main/java/teammates/storage/api/FeedbackQuestionsDb.java
  src/main/java/teammates/ui/webapi/action/CreateFeedbackQuestionAction.java
  src/main/resources/InstructorSampleData.json
  src/test/java/teammates/test/cases/browsertests/FeedbackConstSumOptionQuestionUiTest.java
  src/test/java/teammates/test/cases/browsertests/FeedbackMcqQuestionUiTest.java
  src/test/java/teammates/test/cases/browsertests/FeedbackMsqQuestionUiTest.java
  src/test/java/teammates/test/cases/browsertests/FeedbackRankQuestionUiTest.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackQuestionAttributesTest.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackQuestionDetailsTest.java
  src/test/java/teammates/test/cases/logic/FeedbackQuestionsLogicTest.java
  src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
  src/test/java/teammates/test/cases/storage/FeedbackQuestionsDbTest.java
  src/test/java/teammates/test/cases/util/JsonUtilsTest.java
  src/test/resources/data/AllAccessControlUiTest.json
  src/test/resources/data/AutomatedSessionRemindersTest.json
  src/test/resources/data/EmailGeneratorTest.json
  src/test/resources/data/FeedbackMcqQuestionUiTest.json
  src/test/resources/data/FeedbackParticipantFeedbackResponseCommentDeleteTest.json
  src/test/resources/data/FeedbackRankQuestionUiTest.json
  src/test/resources/data/FeedbackRubricQuestionUiTest.json
  src/test/resources/data/FeedbackSessionDetailsTest.json
  src/test/resources/data/FeedbackSessionQuestionTypeTest.json
  src/test/resources/data/FeedbackSessionResultsBundleTest.json
  src/test/resources/data/FeedbackSessionResultsTest.json
  src/test/resources/data/FeedbackSessionsLogicTest.json
  src/test/resources/data/GetFeedbackQuestionRecipientsActionTest.json
  src/test/resources/data/InstructorEditInstructorFeedbackPageTest.json
  src/test/resources/data/InstructorEditStudentFeedbackPageTest.json
  src/test/resources/data/InstructorFeedbackEditCopyTest.json
  src/test/resources/data/InstructorFeedbackEditPageUiTest.json
  src/test/resources/data/InstructorFeedbackQuestionSubmitPageUiTest.json
  src/test/resources/data/InstructorFeedbackResultsPageResponseCommentUiTest.json
  src/test/resources/data/InstructorFeedbackResultsPageUiTest.json
  src/test/resources/data/InstructorFeedbackSubmissionEditSaveActionTest.json
  src/test/resources/data/InstructorFeedbackSubmitPageUiTest.json
  src/test/resources/data/InstructorHomePageUiTest2.json
  src/test/resources/data/InstructorSearchPageUiTest.json
  src/test/resources/data/InstructorStudentRecordsPageUiTest.json
  src/test/resources/data/InstructorSubmissionAdjustmentUiTest.json
  src/test/resources/data/MashupPageUiTest.json
  src/test/resources/data/SpecialCharacterTest.json
  src/test/resources/data/StudentCourseJoinAuthenticatedTest.json
  src/test/resources/data/StudentFeedbackQuestionSubmitPageUiTest.json
  src/test/resources/data/StudentFeedbackResultsPageUiTest.json
  src/test/resources/data/StudentFeedbackSubmissionEditPageActionTest.json
  src/test/resources/data/StudentFeedbackSubmitPageUiTest.json
  src/test/resources/data/StudentHomePageUiTest.json
  src/test/resources/data/typicalDataBundle.json
Labels: s.ToMerge

#9471 [#7285] Live Server: disallow team name to be valid email
  src/main/java/teammates/common/util/FieldValidator.java
Labels: c.Task, s.ToMerge

#9462 [#9382] Migrate response comments back-end
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/controller/ActionFactory.java
  src/main/java/teammates/ui/controller/FeedbackParticipantFeedbackResponseCommentDeleteAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackResponseCommentAbstractAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackResponseCommentAddAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackResponseCommentDeleteAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackResponseCommentEditAction.java
  src/main/java/teammates/ui/pagedata/FeedbackResponseCommentAjaxPageData.java
  src/main/java/teammates/ui/webapi/action/Action.java
  src/main/java/teammates/ui/webapi/action/ActionFactory.java
  src/main/java/teammates/ui/webapi/action/CreateFeedbackResponseCommentAction.java
  src/main/java/teammates/ui/webapi/action/DeleteFeedbackResponseCommentAction.java
  src/main/java/teammates/ui/webapi/action/UpdateFeedbackResponseCommentAction.java
  src/main/java/teammates/ui/webapi/output/FeedbackResponseCommentData.java
  src/main/java/teammates/ui/webapi/request/FeedbackResponseCommentSaveRequest.java
  src/test/java/teammates/test/cases/action/FeedbackParticipantFeedbackResponseCommentDeleteActionTest.java
  src/test/java/teammates/test/cases/action/InstructorFeedbackResponseCommentAddActionTest.java
  src/test/java/teammates/test/cases/action/InstructorFeedbackResponseCommentDeleteActionTest.java
  src/test/java/teammates/test/cases/action/InstructorFeedbackResponseCommentEditActionTest.java
  src/test/java/teammates/test/cases/webapi/BaseActionTest.java
  src/test/java/teammates/test/cases/webapi/CreateFeedbackResponseCommentActionTest.java
  src/test/java/teammates/test/cases/webapi/DeleteFeedbackResponseCommentActionTest.java
  src/test/java/teammates/test/cases/webapi/UpdateFeedbackResponseCommentActionTest.java
Labels: s.ToMerge

#9457 [#9417] Throw exception for negative integers of recommended length
  src/main/java/teammates/common/datatransfer/questions/FeedbackTextQuestionDetails.java
  src/main/java/teammates/common/util/Const.java
  src/test/java/teammates/test/cases/webapi/SaveFeedbackQuestionActionTest.java
Labels: s.ToMerge

#9393 [#9174] Fix integrity of test data for FeedbackResponseComment
  src/test/resources/data/AllAccessControlUiTest.json
  src/test/resources/data/FeedbackParticipantFeedbackResponseCommentDeleteTest.json
  src/test/resources/data/FeedbackSessionResultsBundleTest.json
  src/test/resources/data/StudentFeedbackSubmissionEditPageActionTest.json
Labels: s.ToMerge

#9492 [#9491] Fix link from getting started page to instructor help page
  src/web/app/pages-help/instructor-help-page/instructor-help-getting-started/instructor-help-getting-started.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-getting-started/instructor-help-getting-started.component.ts
  src/web/app/pages-instructor/instructor-pages.module.ts
  src/web/app/pages-static/static-pages.module.ts
Labels: s.ToMerge

#9408 [#9382] Implement profile picture features for Student Profile Page
  package.json
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/ProfilesLogic.java
  src/main/java/teammates/storage/api/ProfilesDb.java
  src/main/java/teammates/ui/controller/ActionFactory.java
  src/main/java/teammates/ui/controller/CreateImageUploadUrlAction.java
  src/main/java/teammates/ui/controller/ImageUploadAction.java
  src/main/java/teammates/ui/controller/StudentProfileCreateFormUrlAction.java
  src/main/java/teammates/ui/controller/StudentProfilePictureEditAction.java
  src/main/java/teammates/ui/controller/StudentProfilePictureUploadAction.java
  src/main/java/teammates/ui/pagedata/StudentProfileCreateFormUrlAjaxPageData.java
  src/main/java/teammates/ui/webapi/action/ActionFactory.java
  src/main/java/teammates/ui/webapi/action/DeleteStudentProfilePictureAction.java
  src/main/java/teammates/ui/webapi/action/PostStudentProfilePictureAction.java
  src/main/java/teammates/ui/webapi/action/WebApiServlet.java
  src/main/java/teammates/ui/webapi/output/StudentProfilePictureResults.java
  src/main/webapp-backup/WEB-INF/tags/student/profile/uploadPhotoModal.tag
  src/test/java/teammates/test/cases/action/StudentProfileCreateFormUrlActionTest.java
  src/test/java/teammates/test/cases/action/StudentProfilePictureEditActionTest.java
  src/test/java/teammates/test/cases/webapi/BaseActionTest.java
  src/test/java/teammates/test/cases/webapi/DeleteStudentProfilePictureActionTest.java
  src/test/java/teammates/test/cases/webapi/PostStudentProfilePictureActionTest.java
  src/test/java/teammates/test/driver/GaeSimulation.java
  src/test/java/teammates/test/driver/MockHttpServletRequest.java
  src/test/java/teammates/test/driver/MockPart.java
  src/web/app/pages-instructor/student-list/student-list.component.ts
  src/web/app/pages-instructor/student-profile/student-profile.component.ts
  src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts
  src/web/app/pages-student/student-profile-page/student-profile-page.component.html
  src/web/app/pages-student/student-profile-page/student-profile-page.component.scss
  src/web/app/pages-student/student-profile-page/student-profile-page.component.ts
  src/web/app/pages-student/student-profile-page/student-profile-page.module.ts
  src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.html
  src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.scss
  src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.spec.ts
  src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.ts
  static-analysis/teammates-macker.xml
Labels: s.ToMerge

#9453 [#9420] Consolidate Sessions RESTFul API
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/storage/api/FeedbackSessionsDb.java
  src/main/java/teammates/ui/webapi/action/ActionFactory.java
  src/main/java/teammates/ui/webapi/action/GetOngoingSessionsAction.java
  src/main/java/teammates/ui/webapi/output/OngoingSession.java
  src/main/java/teammates/ui/webapi/output/OngoingSessionsData.java
  src/test/java/teammates/test/cases/webapi/GetOngoingSessionsActionTest.java
  src/web/app/pages-admin/admin-sessions-page/admin-sessions-page.component.html
  src/web/app/pages-admin/admin-sessions-page/admin-sessions-page.component.ts
  src/web/services/feedback-sessions.service.ts
Labels: s.ToMerge

#9469 [#9451] Instructor Home Page: Multiple dropdown menus stay expanded if clicked consecutively
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.ts
Labels: s.ToMerge

#9484 [#9424] Remove feedbackQuestionType in FeedbackQuestionAttributes
  src/main/java/teammates/common/datatransfer/attributes/FeedbackQuestionAttributes.java
  src/main/java/teammates/common/util/Templates.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
  src/main/java/teammates/ui/template/FeedbackResponseRow.java
  src/main/java/teammates/ui/webapi/action/CreateFeedbackQuestionAction.java
  src/main/java/teammates/ui/webapi/output/SessionResultsData.java
  src/main/resources/InstructorSampleData.json
  src/main/resources/feedbackSessionTeamEvaluationTemplate.json
  src/test/java/teammates/test/cases/datatransfer/FeedbackQuestionAttributesTest.java
  src/test/java/teammates/test/cases/logic/FeedbackQuestionsLogicTest.java
  src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
  src/test/java/teammates/test/cases/storage/FeedbackQuestionsDbTest.java
  src/test/java/teammates/test/cases/util/JsonUtilsTest.java
  src/test/resources/data/AllAccessControlUiTest.json
  src/test/resources/data/AutomatedSessionRemindersTest.json
  src/test/resources/data/EmailGeneratorTest.json
  src/test/resources/data/FeedbackMcqQuestionUiTest.json
  src/test/resources/data/FeedbackParticipantFeedbackResponseCommentDeleteTest.json
  src/test/resources/data/FeedbackRankQuestionUiTest.json
  src/test/resources/data/FeedbackRubricQuestionUiTest.json
  src/test/resources/data/FeedbackSessionDetailsTest.json
  src/test/resources/data/FeedbackSessionQuestionTypeTest.json
  src/test/resources/data/FeedbackSessionResultsBundleTest.json
  src/test/resources/data/FeedbackSessionResultsTest.json
  src/test/resources/data/FeedbackSessionsLogicTest.json
  src/test/resources/data/GetFeedbackQuestionRecipientsActionTest.json
  src/test/resources/data/InstructorEditInstructorFeedbackPageTest.json
  src/test/resources/data/InstructorEditStudentFeedbackPageTest.json
  src/test/resources/data/InstructorFeedbackEditCopyTest.json
  src/test/resources/data/InstructorFeedbackEditPageUiTest.json
  src/test/resources/data/InstructorFeedbackQuestionSubmitPageUiTest.json
  src/test/resources/data/InstructorFeedbackResultsPageResponseCommentUiTest.json
  src/test/resources/data/InstructorFeedbackResultsPageUiTest.json
  src/test/resources/data/InstructorFeedbackSubmissionEditSaveActionTest.json
  src/test/resources/data/InstructorFeedbackSubmitPageUiTest.json
  src/test/resources/data/InstructorHomePageUiTest2.json
  src/test/resources/data/InstructorSearchPageUiTest.json
  src/test/resources/data/InstructorStudentRecordsPageUiTest.json
  src/test/resources/data/InstructorSubmissionAdjustmentUiTest.json
  src/test/resources/data/MashupPageUiTest.json
  src/test/resources/data/SpecialCharacterTest.json
  src/test/resources/data/StudentCourseJoinAuthenticatedTest.json
  src/test/resources/data/StudentFeedbackQuestionSubmitPageUiTest.json
  src/test/resources/data/StudentFeedbackResultsPageUiTest.json
  src/test/resources/data/StudentFeedbackSubmissionEditPageActionTest.json
  src/test/resources/data/StudentFeedbackSubmitPageUiTest.json
  src/test/resources/data/StudentHomePageUiTest.json
  src/test/resources/data/typicalDataBundle.json
Labels: c.Task, s.ToMerge

#9502 [#9501] Fix technical debts in GCS layer
  src/client/java/teammates/client/scripts/GoogleIdMigrationBaseScript.java
  src/main/java/teammates/common/datatransfer/attributes/StudentProfileAttributes.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/common/util/GoogleCloudStorageHelper.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/ProfilesLogic.java
  src/main/java/teammates/storage/api/ProfilesDb.java
  src/main/java/teammates/storage/entity/StudentProfile.java
  src/main/java/teammates/ui/pagedata/CreateImageUploadUrlAjaxPageData.java
  src/main/java/teammates/ui/pagedata/FileUploadPageData.java
  src/main/java/teammates/ui/webapi/action/DeleteStudentProfilePictureAction.java
  src/main/java/teammates/ui/webapi/action/ImageResult.java
  src/main/java/teammates/ui/webapi/action/PostStudentProfilePictureAction.java
  src/test/java/teammates/test/cases/BaseComponentTestCase.java
  src/test/java/teammates/test/cases/datatransfer/StudentProfileAttributesTest.java
  src/test/java/teammates/test/cases/logic/ProfilesLogicTest.java
  src/test/java/teammates/test/cases/storage/ProfilesDbTest.java
  static-analysis/teammates-macker.xml
Labels: s.ToMerge

#9500 [#9494] Consolidate GET /students RESTFul API
  src/main/java/teammates/ui/webapi/action/ActionFactory.java
  src/main/java/teammates/ui/webapi/action/GetStudentsAction.java
  src/main/java/teammates/ui/webapi/output/JoinState.java
  src/main/java/teammates/ui/webapi/output/StudentData.java
  src/main/java/teammates/ui/webapi/output/StudentsData.java
  src/test/java/teammates/test/cases/webapi/GetStudentsActionTest.java
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.html
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
  src/web/app/student.ts
Labels: s.ToMerge

#9507 [#9494] Consolidate GET /instructors RESTFul API
  src/main/java/teammates/ui/webapi/action/ActionFactory.java
  src/main/java/teammates/ui/webapi/action/GetInstructorsAction.java
  src/main/java/teammates/ui/webapi/output/InstructorData.java
  src/main/java/teammates/ui/webapi/output/InstructorsData.java
  src/test/java/teammates/test/cases/webapi/GetInstructorsActionTest.java
  src/web/app/Instructor.ts
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.html
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
Labels: s.ToMerge

#9485 [#9420] Consolidate Join RESTFul API
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/webapi/action/ActionFactory.java
  src/main/java/teammates/ui/webapi/action/GetCourseJoinStatusAction.java
  src/main/java/teammates/ui/webapi/action/RemindInstructorCourseStudentsAction.java
  src/main/java/teammates/ui/webapi/action/SendJoinReminderEmailAction.java
  src/main/java/teammates/ui/webapi/output/JoinStatus.java
  src/test/java/teammates/test/cases/webapi/GetCourseJoinStatusActionTest.java
  src/test/java/teammates/test/cases/webapi/SendJoinReminderEmailActionTest.java
  src/test/java/teammates/test/cases/webapi/SendReminderEmailActionTest.java
  src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.ts
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.ts
  src/web/app/pages-instructor/student-list/student-list.component.ts
  src/web/app/user-join-page.component.ts
  src/web/services/course.service.spec.ts
  src/web/services/course.service.ts
Labels: s.ToMerge

#9489 [#9420] Consolidate Recycle Bin RESTFul API
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/webapi/action/ActionFactory.java
  src/main/java/teammates/ui/webapi/action/RestoreCourseAction.java
  src/test/java/teammates/test/cases/webapi/RestoreCourseActionTest.java
  src/test/java/teammates/test/cases/webapi/RestoreInstructorSoftDeletedCourseActionTest.java
Labels: s.ToMerge

#9473 [#9134] Instructor: rename buttons in alert message to match question being asked
  src/web/app/components/question-edit-form/question-edit-form.component.html
  src/web/app/components/session-edit-form/session-edit-form.component.html
  src/web/app/components/sessions-table/confirm-publishing-session-modal/confirm-publishing-session-modal.component.html
  src/web/app/components/sessions-table/confirm-session-move-to-recycle-bin-modal/confirm-session-move-to-recycle-bin-modal.component.html
  src/web/app/components/sessions-table/confirm-unpublishing-session-modal/confirm-unpublishing-session-modal.component.html
  src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.html
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.html
  src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.html
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
  src/web/app/pages-instructor/student-list/student-list.component.html
Labels: s.ToMerge

#9443 [#9420] Consolidate Instructor RESTFul API
  src/main/java/teammates/ui/webapi/action/ActionFactory.java
  src/main/java/teammates/ui/webapi/action/CreateInstructorAction.java
  src/main/java/teammates/ui/webapi/action/GetInstructorAction.java
  src/main/java/teammates/ui/webapi/action/UpdateInstructorAction.java
  src/main/java/teammates/ui/webapi/request/InstructorCreateRequest.java
  src/test/java/teammates/test/cases/webapi/CreateInstructorActionTest.java
  src/test/java/teammates/test/cases/webapi/CreateInstructorInCourseActionTest.java
  src/test/java/teammates/test/cases/webapi/EditInstructorInCourseActionTest.java
  src/test/java/teammates/test/cases/webapi/GetInstructorActionTest.java
  src/test/java/teammates/test/cases/webapi/UpdateInstructorActionTest.java
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
Labels: s.ToMerge

#9436 [#9420] Consolidate account, student RESTFul API
  src/main/java/teammates/common/datatransfer/CommonAccountSearchResult.java
  src/main/java/teammates/common/datatransfer/InstructorAccountSearchResult.java
  src/main/java/teammates/common/datatransfer/StudentAccountSearchResult.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/InstructorsLogic.java
  src/main/java/teammates/ui/webapi/action/ActionFactory.java
  src/main/java/teammates/ui/webapi/action/CreateAccountAction.java
  src/main/java/teammates/ui/webapi/action/GetAccountAction.java
  src/main/java/teammates/ui/webapi/action/GetAccountsAction.java
  src/main/java/teammates/ui/webapi/action/GetStudentsAsCsvAction.java
  src/main/java/teammates/ui/webapi/action/ResetAccountAction.java
  src/main/java/teammates/ui/webapi/action/SearchAccountsAction.java
  src/main/java/teammates/ui/webapi/action/UpdateStudentProfileAction.java
  src/main/java/teammates/ui/webapi/output/AccountData.java
  src/main/java/teammates/ui/webapi/output/AdminSearchResultData.java
  src/main/java/teammates/ui/webapi/output/JoinLinkData.java
  src/main/java/teammates/ui/webapi/request/AccountCreateRequest.java
  src/main/java/teammates/ui/webapi/request/StudentProfileUpdateRequest.java
  src/test/java/teammates/test/cases/webapi/CreateAccountActionTest.java
  src/test/java/teammates/test/cases/webapi/DeleteAccountActionTest.java
  src/test/java/teammates/test/cases/webapi/DowngradeAccountActionTest.java
  src/test/java/teammates/test/cases/webapi/GetAccountActionTest.java
  src/test/java/teammates/test/cases/webapi/GetAccountsActionTest.java
  src/test/java/teammates/test/cases/webapi/GetStudentsAsCsvActionTest.java
  src/test/java/teammates/test/cases/webapi/ResetAccountActionTest.java
  src/test/java/teammates/test/cases/webapi/SearchAccountsActionTest.java
  src/test/java/teammates/test/cases/webapi/UpdateStudentProfileActionTest.java
  src/web/app/pages-admin/admin-accounts-page/admin-accounts-page.component.ts
  src/web/app/pages-admin/admin-home-page/admin-home-page.component.ts
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.ts
  src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.ts
  src/web/app/pages-student/student-profile-page/student-profile-page.component.ts
  src/web/services/account.service.spec.ts
  src/web/services/account.service.ts
  src/web/services/student-profile.service.spec.ts
  src/web/services/student-profile.service.ts
Labels: s.ToMerge

#9518 [#9516] Instructor Course: Fix restoring a deleted course functionality
  src/main/java/teammates/common/util/Const.java
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts
Labels: s.ToMerge
