Repository TEAMMATES/teammates, pull requests merged in 2019-01, with the labels that each got.

#9280 [#9119] FeedbackResponseCommentsLogicTest: Fix verification for test
  src/test/java/teammates/test/cases/logic/FeedbackResponseCommentsLogicTest.java
Labels: c.Task, s.ToMerge

#9287 [#9284] Remove creatorOnly in GateKeeper
  src/main/java/teammates/logic/api/GateKeeper.java
  src/main/java/teammates/ui/controller/FeedbackParticipantFeedbackResponseCommentDeleteAction.java
  src/main/java/teammates/ui/controller/FeedbackSessionStatsPageAction.java
  src/main/java/teammates/ui/controller/InstructorEditInstructorFeedbackPageAction.java
  src/main/java/teammates/ui/controller/InstructorEditInstructorFeedbackSaveAction.java
  src/main/java/teammates/ui/controller/InstructorEditStudentFeedbackPageAction.java
  src/main/java/teammates/ui/controller/InstructorEditStudentFeedbackSaveAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackDeleteAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackDeleteAllSoftDeletedSessionsAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackDeleteSoftDeletedSessionAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackEditCopyAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackEditPageAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackEditSaveAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackPreviewAsInstructorAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackPreviewAsStudentAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackPublishAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackQuestionAddAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackQuestionCopyAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackQuestionCopyPageAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackQuestionEditAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackRemindAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackRemindParticularStudentsAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackRemindParticularStudentsPageAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackResendPublishedEmailAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackResendPublishedEmailPageAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackResponseCommentAbstractAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackResponseCommentAddAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackRestoreAllSoftDeletedSessionsAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackRestoreSoftDeletedSessionAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackResultsDownloadAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackResultsPageAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackSubmissionEditPageAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackSubmissionEditSaveAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackTemplateQuestionAddAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackUnpublishAction.java
Labels: s.ToMerge

#9285 [#9255] Migrate Instructor Course Student Details page to Angular
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/controller/ActionFactory.java
  src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsPageAction.java
  src/main/java/teammates/ui/controller/StudentProfilePictureAction.java
  src/main/java/teammates/ui/newcontroller/Action.java
  src/main/java/teammates/ui/newcontroller/ActionFactory.java
  src/main/java/teammates/ui/newcontroller/GetCourseStudentDetailsAction.java
  src/main/java/teammates/ui/newcontroller/GetStudentProfilePictureAction.java
  src/main/java/teammates/ui/newcontroller/ImageResult.java
  src/main/java/teammates/ui/newcontroller/WebApiServlet.java
  src/main/webapp-backup/WEB-INF/tags/instructor/courseStudentDetails/studentInformationTable.tag
  src/main/webapp-backup/jsp/instructorCourseStudentDetails.jsp
  src/test/java/teammates/test/cases/action/InstructorCourseStudentDetailsPageActionTest.java
  src/test/java/teammates/test/cases/action/StudentProfilePictureActionTest.java
  src/test/java/teammates/test/cases/newaction/BaseActionTest.java
  src/test/java/teammates/test/cases/newaction/GetAuthInfoActionTest.java
  src/test/java/teammates/test/cases/newaction/GetCourseStudentDetailsActionTest.java
  src/test/java/teammates/test/cases/newaction/GetStudentProfilePictureActionTest.java
  src/web/app/pages-instructor/instructor-course-student-details-page/instructor-course-student-details-page.component.html
  src/web/app/pages-instructor/instructor-course-student-details-page/instructor-course-student-details-page.component.scss
  src/web/app/pages-instructor/instructor-course-student-details-page/instructor-course-student-details-page.component.spec.ts
  src/web/app/pages-instructor/instructor-course-student-details-page/instructor-course-student-details-page.component.ts
  src/web/assets/images/profile_picture_default.png
  src/web/styles.scss
Labels: s.ToMerge

#9295 [#9249] remove keep update timestamp feedback question
  src/main/java/teammates/storage/api/FeedbackQuestionsDb.java
  src/main/java/teammates/storage/entity/FeedbackQuestion.java
  src/test/java/teammates/test/cases/storage/FeedbackQuestionsDbTest.java
Labels: c.Task, s.ToMerge

#9316 [#9250] Removed keepUpdateTimestamp in CourseStudent
  src/main/java/teammates/logic/core/StudentsLogic.java
  src/main/java/teammates/storage/api/StudentsDb.java
  src/main/java/teammates/storage/entity/CourseStudent.java
  src/test/java/teammates/test/cases/storage/StudentsDbTest.java
Labels: s.ToMerge

#9315 [#9255] Migrate student help page to Angular
  src/main/webapp-backup/studentHelp.jsp
  src/web/app/pages-help/student-help-page/student-help-page.component.html
  src/web/app/pages-help/student-help-page/student-help-page.component.scss
Labels: s.ToMerge

#9305 [#9251] Remove/Replace methods *WithoutDocument in StudentsDb
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/backdoor/BackDoorLogic.java
  src/main/java/teammates/logic/core/StudentsLogic.java
  src/main/java/teammates/storage/api/StudentsDb.java
  src/test/java/teammates/test/cases/action/InstructorCourseEnrollSaveActionTest.java
  src/test/java/teammates/test/cases/action/InstructorCourseRemindActionTest.java
  src/test/java/teammates/test/cases/action/InstructorStudentRecordsPageActionTest.java
  src/test/java/teammates/test/cases/action/StudentCourseJoinActionTest.java
  src/test/java/teammates/test/cases/action/StudentFeedbackSubmissionEditPageActionTest.java
  src/test/java/teammates/test/cases/automated/FeedbackResponseAdjustmentWorkerActionTest.java
  src/test/java/teammates/test/cases/logic/AccountsLogicTest.java
  src/test/java/teammates/test/cases/logic/FeedbackResponsesLogicTest.java
  src/test/java/teammates/test/cases/logic/GateKeeperTest.java
  src/test/java/teammates/test/cases/logic/StudentsLogicTest.java
  src/test/java/teammates/test/cases/search/StudentSearchTest.java
  src/test/java/teammates/test/cases/storage/StudentsDbTest.java
Labels: s.ToMerge

#9301 [#9255] Migrate Instructor Course Student Details Edit page to Angular
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/controller/ActionFactory.java
  src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditPageAction.java
  src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditSaveAction.java
  src/main/java/teammates/ui/newcontroller/ActionFactory.java
  src/main/java/teammates/ui/newcontroller/GetStudentEditDetailsAction.java
  src/main/java/teammates/ui/newcontroller/PutCourseStudentDetailsEditAction.java
  src/main/java/teammates/ui/pagedata/InstructorCourseStudentDetailsEditPageData.java
  src/main/webapp-backup/WEB-INF/tags/instructor/courseStudentDetailsEdit/studentInformationTable.tag
  src/main/webapp-backup/dev/js/main/instructorCourseStudentEdit.js
  src/main/webapp-backup/jsp/instructorCourseStudentEdit.jsp
  src/test/java/teammates/test/cases/action/InstructorCourseStudentDetailsEditPageActionTest.java
  src/test/java/teammates/test/cases/action/InstructorCourseStudentDetailsEditSaveActionTest.java
  src/test/java/teammates/test/cases/newaction/BaseActionTest.java
  src/test/java/teammates/test/cases/newaction/GetStudentEditDetailsActionTest.java
  src/test/java/teammates/test/cases/newaction/PutCourseStudentDetailsEditActionTest.java
  src/web/app/message-output.ts
  src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.html
  src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.scss
  src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.spec.ts
  src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.ts
  src/web/app/pages-instructor/instructor-pages.module.ts
Labels: s.ToMerge

#9289 [#9255] Migrate student home page to Angular
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/controller/ActionFactory.java
  src/main/java/teammates/ui/controller/StudentHomePageAction.java
  src/main/java/teammates/ui/newcontroller/ActionFactory.java
  src/main/java/teammates/ui/newcontroller/GetStudentCoursesAction.java
  src/main/java/teammates/ui/pagedata/StudentHomePageData.java
  src/main/java/teammates/ui/template/StudentHomeFeedbackSessionRow.java
  src/main/webapp-backup/WEB-INF/tags/student/home/coursePanel.tag
  src/main/webapp-backup/WEB-INF/tags/student/home/courseTable.tag
  src/main/webapp-backup/WEB-INF/tags/student/home/rowActions.tag
  src/main/webapp-backup/jsp/studentHome.jsp
  src/test/java/teammates/test/cases/action/StudentHomePageActionTest.java
  src/test/java/teammates/test/cases/newaction/GetStudentCoursesActionTest.java
  src/web/app/pages-student/student-home-page/student-home-page.component.html
  src/web/app/pages-student/student-home-page/student-home-page.component.scss
  src/web/app/pages-student/student-home-page/student-home-page.component.spec.ts
  src/web/app/pages-student/student-home-page/student-home-page.component.ts
  src/web/app/pages-student/student-pages.module.ts
  src/web/app/pipes/pipes.module.spec.ts
  src/web/app/pipes/pipes.module.ts
  src/web/app/pipes/session-response-status.pipe.spec.ts
  src/web/app/pipes/session-response-status.pipe.ts
  src/web/app/pipes/session-submission-status.pipe.spec.ts
  src/web/app/pipes/session-submission-status.pipe.ts
Labels: s.ToMerge

#9332 [#9331] Update automated login to match new Google login page
  src/test/java/teammates/test/pageobjects/GoogleLoginPage.java
Labels: s.ToMerge

#9325 [#9255] Migrate Student Course Details Page to Angular
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/controller/ActionFactory.java
  src/main/java/teammates/ui/controller/StudentCourseDetailsPageAction.java
  src/main/java/teammates/ui/newcontroller/ActionFactory.java
  src/main/java/teammates/ui/newcontroller/StudentGetCourseDetailsAction.java
  src/main/java/teammates/ui/pagedata/StudentCourseDetailsPageData.java
  src/main/java/teammates/ui/template/StudentCourseDetailsPanel.java
  src/main/webapp-backup/WEB-INF/tags/student/courseDetails/displayDetails.tag
  src/main/webapp-backup/WEB-INF/tags/student/courseDetails/displayInstructors.tag
  src/main/webapp-backup/WEB-INF/tags/student/courseDetails/displayTeammates.tag
  src/main/webapp-backup/dev/js/main/studentCourseDetails.js
  src/main/webapp-backup/jsp/studentCourseDetails.jsp
  src/test/java/teammates/test/cases/action/StudentCourseDetailsPageActionTest.java
  src/test/java/teammates/test/cases/newaction/StudentGetCourseDetailsActionTest.java
  src/web/app/pages-student/student-course-details-page/student-course-details-page.component.html
  src/web/app/pages-student/student-course-details-page/student-course-details-page.component.scss
  src/web/app/pages-student/student-course-details-page/student-course-details-page.component.spec.ts
  src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts
Labels: s.ToMerge

#9166 [#9165] Added Docker support (#9165)
  Dockerfile
  bootstrap.sh
  build.gradle
  docker-compose.yml
  docs/README.md
  docs/setting-up-with-docker.md
Labels: s.ToMerge

#9329 [#9255] Migrate Instructor Course Enroll page to Angular (Part 1)
  package.json
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/ui/newcontroller/ActionFactory.java
  src/main/java/teammates/ui/newcontroller/GetCourseEnrollPageDataAction.java
  src/main/java/teammates/ui/newcontroller/GetStudentEditDetailsAction.java
  src/main/java/teammates/ui/newcontroller/PostCourseEnrollSaveAction.java
  src/test/java/teammates/test/cases/newaction/GetCourseEnrollPageDataActionTest.java
  src/test/java/teammates/test/cases/newaction/PostCourseEnrollSaveActionTest.java
  src/web/app/components/status-message/status-message.component.html
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.html
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.scss
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.spec.ts
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts
  src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.ts
  src/web/app/pages-instructor/instructor-pages.module.spec.ts
  src/web/app/pages-instructor/instructor-pages.module.ts
Labels: s.ToMerge

#9340 [#9255] Migrate remaining features of Instructor Course Enroll page to Angular
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/newcontroller/ActionFactory.java
  src/main/java/teammates/ui/newcontroller/GetCourseEnrollStudentsAction.java
  src/test/java/teammates/test/cases/newaction/GetCourseEnrollStudentsActionTest.java
  src/web/app/components/ajax-preload/ajax-preload.component.html
  src/web/app/components/ajax-preload/ajax-preload.component.scss
  src/web/app/components/ajax-preload/ajax-preload.component.spec.ts
  src/web/app/components/ajax-preload/ajax-preload.component.ts
  src/web/app/components/ajax-preload/ajax-preload.module.spec.ts
  src/web/app/components/ajax-preload/ajax-preload.module.ts
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.html
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.scss
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts
  src/web/app/pages-instructor/instructor-pages.module.ts
  src/web/assets/images/ajax-preload.gif
  src/web/styles.scss
Labels: s.ToReview

#9355 [#9354] Fix path for userMapData.json in sort-usermap.js
  sort-usermap.js
Labels: s.ToMerge

#9309 [#8943] Update user map as at Jun 2018
  src/web/data/userMapData.json
Labels: s.ToMerge

#9333 [#9255] Migrate Instructor Course Details Page to Angular
  package.json
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/controller/ActionFactory.java
  src/main/java/teammates/ui/controller/InstructorCourseDetailsPageAction.java
  src/main/java/teammates/ui/controller/InstructorCourseRemindAction.java
  src/main/java/teammates/ui/controller/InstructorCourseStudentDeleteAllAction.java
  src/main/java/teammates/ui/controller/InstructorCourseStudentListDownloadAction.java
  src/main/java/teammates/ui/newcontroller/ActionFactory.java
  src/main/java/teammates/ui/newcontroller/CsvResult.java
  src/main/java/teammates/ui/newcontroller/DeleteInstructorCourseAllStudentsAction.java
  src/main/java/teammates/ui/newcontroller/GetInstructorCourseAllStudentsInCsvAction.java
  src/main/java/teammates/ui/newcontroller/GetInstructorCourseDetailsAction.java
  src/main/java/teammates/ui/newcontroller/RemindInstructorCourseStudentsAction.java
  src/test/java/teammates/test/cases/action/InstructorCourseDetailsPageActionTest.java
  src/test/java/teammates/test/cases/action/InstructorCourseRemindActionTest.java
  src/test/java/teammates/test/cases/action/InstructorCourseStudentDeleteAllActionTest.java
  src/test/java/teammates/test/cases/newaction/BaseActionTest.java
  src/test/java/teammates/test/cases/newaction/DeleteInstructorCourseAllStudentsActionTest.java
  src/test/java/teammates/test/cases/newaction/GetInstructorCourseAllStudentsInCsvActionTest.java
  src/test/java/teammates/test/cases/newaction/GetInstructorCourseDetailsActionTest.java
  src/test/java/teammates/test/cases/newaction/RemindInstructorCourseStudentsActionTest.java
  src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.html
  src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.scss
  src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.spec.ts
  src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.ts
  src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.ts
  src/web/app/pages-instructor/instructor-pages.module.ts
  src/web/app/pages-instructor/instructor-search-page/instructor-search-page.component.html
  src/web/app/pages-instructor/instructor-search-page/instructor-search-page.component.spec.ts
  src/web/app/pages-instructor/student-list/student-list.component.html
  src/web/app/pages-instructor/student-list/student-list.component.ts
  src/web/services/http-request.service.spec.ts
  src/web/services/http-request.service.ts
  src/web/services/navigation.service.ts
  src/web/typings.d.ts
Labels: s.ToMerge

#9364 [#9311] ide-setup.md: improve IntelliJ indentation guideline
  docs/ide-setup.md
Labels: s.ToMerge

#9335 [#9255] Migrate instructor course edit page to Angular
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/newcontroller/ActionFactory.java
  src/main/java/teammates/ui/newcontroller/CreateInstructorInCourseAction.java
  src/main/java/teammates/ui/newcontroller/DeleteCourseAction.java
  src/main/java/teammates/ui/newcontroller/DeleteInstructorInCourseAction.java
  src/main/java/teammates/ui/newcontroller/EditInstructorInCourseAction.java
  src/main/java/teammates/ui/newcontroller/GetCourseEditDetailsAction.java
  src/main/java/teammates/ui/newcontroller/SaveCourseEditDetailsAction.java
  src/main/java/teammates/ui/newcontroller/SendReminderEmailAction.java
  src/main/java/teammates/ui/newcontroller/UpdateInstructorPrivilegesAbstractAction.java
  src/test/java/teammates/test/cases/newaction/ArchiveCourseActionTest.java
  src/test/java/teammates/test/cases/newaction/BaseActionTest.java
  src/test/java/teammates/test/cases/newaction/CreateInstructorInCourseActionTest.java
  src/test/java/teammates/test/cases/newaction/DeleteCourseActionTest.java
  src/test/java/teammates/test/cases/newaction/DeleteInstructorActionTest.java
  src/test/java/teammates/test/cases/newaction/DeleteInstructorInCourseActionTest.java
  src/test/java/teammates/test/cases/newaction/EditInstructorInCourseActionTest.java
  src/test/java/teammates/test/cases/newaction/GetCourseEditDetailsActionTest.java
  src/test/java/teammates/test/cases/newaction/SaveCourseEditDetailsActionTest.java
  src/test/java/teammates/test/cases/newaction/SendReminderEmailActionTest.java
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.html
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.scss
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.spec.ts
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.ts
  src/web/app/pages-instructor/instructor-pages.module.ts
Labels: s.Ongoing

#9372 [#9255] Migrate part of Student Profile Page to Angular
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/controller/ActionFactory.java
  src/main/java/teammates/ui/controller/StudentProfileEditSaveAction.java
  src/main/java/teammates/ui/controller/StudentProfilePageAction.java
  src/main/java/teammates/ui/newcontroller/Action.java
  src/main/java/teammates/ui/newcontroller/ActionFactory.java
  src/main/java/teammates/ui/newcontroller/GetNationalitiesAction.java
  src/main/java/teammates/ui/newcontroller/GetStudentProfileAction.java
  src/main/java/teammates/ui/newcontroller/PutStudentProfileAction.java
  src/test/java/teammates/test/cases/action/StudentProfileEditSaveActionTest.java
  src/test/java/teammates/test/cases/action/StudentProfilePageActionTest.java
  src/test/java/teammates/test/cases/newaction/GetNationalitiesActionTest.java
  src/test/java/teammates/test/cases/newaction/GetStudentProfileActionTest.java
  src/test/java/teammates/test/cases/newaction/PutStudentProfileActionTest.java
  src/web/app/pages-student/student-pages.module.ts
  src/web/app/pages-student/student-profile-page/student-profile-gender.pipe.spec.ts
  src/web/app/pages-student/student-profile-page/student-profile-gender.pipe.ts
  src/web/app/pages-student/student-profile-page/student-profile-page.component.html
  src/web/app/pages-student/student-profile-page/student-profile-page.component.scss
  src/web/app/pages-student/student-profile-page/student-profile-page.component.spec.ts
  src/web/app/pages-student/student-profile-page/student-profile-page.component.ts
Labels: s.ToMerge

#9347 [#8215] Java: Use Java 8 map.putIfAbsent and map.computeIfAbsent
  src/main/java/teammates/common/datatransfer/questions/FeedbackConstantSumQuestionDetails.java
  src/main/java/teammates/logic/core/DataBundleLogic.java
  src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/ui/controller/InstructorCourseInstructorAbstractAction.java
Labels: s.ToMerge

#9378 [#9360] Add front-end configuration point
  .gitignore
  build.gradle
  docs/development.md
  src/main/resources/build.template.properties
  src/web/app/pages-help/student-help-page/student-help-page.component.html
  src/web/app/pages-help/student-help-page/student-help-page.component.ts
  src/web/app/pages-static/contact-page/contact-page.component.html
  src/web/app/pages-static/contact-page/contact-page.component.ts
  src/web/app/pages-static/request-page/request-page.component.html
  src/web/app/pages-static/request-page/request-page.component.ts
  src/web/environments/config.template.ts
  src/web/environments/environment.prod.ts
  src/web/environments/environment.ts
Labels: s.ToMerge

#9298 [#9297] Add script to change googleId in batch
  .gitignore
  build.gradle
  docs/development.md
  src/client/java/teammates/client/remoteapi/RemoteApiClient.java
  src/client/java/teammates/client/scripts/DataMigrationEntitiesBaseScript.java
  src/client/java/teammates/client/scripts/GoogleIdMigrationBaseScript.java
  src/client/java/teammates/client/scripts/SingleAccountGoogleIdMigrationScript.java
  src/client/java/teammates/client/util/ClientProperties.java
  src/client/resources/client.template.properties
  src/e2e/java/teammates/e2e/util/TestProperties.java
  static-analysis/teammates-macker.xml
Labels: s.ToMerge

#9368 [#8779] AccountAttributes: Remove HTML sanitization before saving for googleId, name, institute
  src/main/java/teammates/common/datatransfer/attributes/AccountAttributes.java
  src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java
Labels: s.FinalReview

#9383 [#9382] Migrate first part of instructor help page to Angular
  src/web/app/pages-help/instructor-help-page/instructor-help-page.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-page.component.spec.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-page.component.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-page.module.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-section.component.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.scss
  src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.spec.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.ts
  static-analysis/teammates-tslint.yml
Labels: s.Ongoing

#9385 [#9373] Standardize footer design
  src/main/java/teammates/ui/webapi/action/GetAuthInfoAction.java
  src/main/java/teammates/ui/webapi/output/AuthInfo.java
  src/test/java/teammates/test/cases/webapi/GetAuthInfoActionTest.java
  src/web/app/page.component.html
  src/web/app/page.component.scss
  src/web/app/page.component.ts
  src/web/app/pages-admin/admin-page.component.html
  src/web/app/pages-admin/admin-page.component.ts
  src/web/app/pages-instructor/instructor-page.component.html
  src/web/app/pages-instructor/instructor-page.component.ts
  src/web/app/pages-static/static-page.component.html
  src/web/app/pages-static/static-page.component.ts
  src/web/app/pages-student/student-page.component.html
  src/web/app/pages-student/student-page.component.ts
Labels: s.ToMerge

#9379 [#9367] Display hints/messages to users when they have no internet connection
  src/web/app/page.component.html
  src/web/app/page.component.ts
Labels: s.ToMerge

#9365 [#9136] Change getBackUpIdentifier messages to make them more meaningful
  src/main/java/teammates/common/datatransfer/attributes/AccountAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/CourseAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/FeedbackQuestionAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/FeedbackResponseAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/FeedbackResponseCommentAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/InstructorAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/StudentAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/StudentProfileAttributes.java
  src/main/java/teammates/common/util/Const.java
  src/test/java/teammates/test/cases/datatransfer/AccountAttributesTest.java
  src/test/java/teammates/test/cases/datatransfer/CourseAttributesTest.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackQuestionAttributesTest.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackResponseAttributesTest.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackResponseCommentAttributesTest.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackSessionAttributesTest.java
  src/test/java/teammates/test/cases/datatransfer/InstructorAttributesTest.java
  src/test/java/teammates/test/cases/datatransfer/StudentAttributesTest.java
  src/test/java/teammates/test/cases/datatransfer/StudentProfileAttributesTest.java
  src/web/app/pages-student/student-profile-page/student-profile-page.component.html
Labels: s.FinalReview
