Repository TEAMMATES/teammates, pull requests merged in 2020-11, with the labels that each got.

#10820 [#9536] Fix Feedback Question E2E tests problems
  src/e2e/java/teammates/e2e/cases/BaseFeedbackQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackConstSumOptionQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackConstSumRecipientQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackContributionQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackMcqQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackMsqQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackNumScaleQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackRankOptionQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackRankRecipientQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackRubricQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackSubmitPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackTextQuestionE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/AppPage.java
  src/e2e/java/teammates/e2e/pageobjects/FeedbackSubmitPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java
  src/e2e/java/teammates/e2e/util/TestNgXmlTest.java
  src/web/app/components/question-submission-form/question-submission-form.component.html
Labels: s.ToMerge

#10696 [#9536] Student Feedback Results Page E2E Test
  src/e2e/java/teammates/e2e/cases/StudentFeedbackResultsPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/StudentFeedbackResultsPage.java
  src/e2e/resources/data/StudentFeedbackResultsPageE2ETest.json
  src/e2e/resources/testng-e2e.xml
  src/web/app/components/comment-box/comment-row/comment-row.component.html
  src/web/app/components/question-responses/student-view-responses/student-view-responses.component.html
  src/web/app/components/question-text-with-info/__snapshots__/question-text-with-info.component.spec.ts.snap
  src/web/app/components/question-text-with-info/question-text-with-info.component.html
  src/web/app/components/question-types/question-response/rubric-question-response.component.html
  src/web/app/components/question-types/question-statistics/contribution-question-statistics/contribution-question-statistics.component.html
  src/web/app/components/question-types/question-statistics/num-scale-question-statistics.component.html
  src/web/app/components/question-types/question-statistics/rubric-question-statistics.component.html
  src/web/app/pages-session/session-result-page/session-result-page.component.html
Labels: s.ToMerge

#10813 [#10569] Missing loading icons and bugs
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.html
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.ts
Labels: c.Feature, s.ToMerge

#10790 [#10580] Student view team page: Loading Indicator for loading teammates not centralised
  src/web/app/pages-student/student-course-details-page/__snapshots__/student-course-details-page.component.spec.ts.snap
  src/web/app/pages-student/student-course-details-page/student-course-details-page.component.html
Labels: c.Bug, s.ToMerge

#10831 [#10828] MCQ questions: submitted comments not shown
  src/main/java/teammates/ui/output/FeedbackResponsesData.java
  src/main/java/teammates/ui/webapi/GetFeedbackResponsesAction.java
  src/test/java/teammates/ui/webapi/GetFeedbackResponsesActionTest.java
Labels: c.Bug, s.ToMerge

#10837 [#10834] Update developers.json
  src/web/data/developers.json
Labels: c.Task

#10836 [#10835] Admin who is instructor cannot delete last instructor
  src/main/java/teammates/ui/webapi/DeleteInstructorAction.java
Labels: c.Bug, s.ToMerge

#10827 [#9536] Improve E2E for Production Server Testing
  docs/e2e-testing.md
  src/e2e/java/teammates/e2e/cases/AdminSearchPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/BaseE2ETestCase.java
  src/e2e/java/teammates/e2e/cases/BaseFeedbackQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackSubmitPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorCourseDetailsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorCourseStudentDetailsEditPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorHomePageE2ETest.java
  src/e2e/java/teammates/e2e/cases/StudentFeedbackResultsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/StudentHomePageE2ETest.java
  src/e2e/java/teammates/e2e/cases/TimezoneSyncerTest.java
  src/e2e/java/teammates/e2e/pageobjects/AdminSearchPage.java
  src/e2e/java/teammates/e2e/pageobjects/AppPage.java
  src/e2e/java/teammates/e2e/pageobjects/Browser.java
  src/e2e/java/teammates/e2e/pageobjects/FeedbackSubmitPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorCourseEditPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorCourseEnrollPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorCoursesPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorHomePage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorSearchPage.java
  src/e2e/java/teammates/e2e/util/EmailAccount.java
  src/e2e/java/teammates/e2e/util/EmailAccountTest.java
  src/e2e/java/teammates/e2e/util/TestProperties.java
  src/e2e/resources/test.template.properties
  src/e2e/resources/test.travis-chrome.properties
  src/e2e/resources/test.travis.properties
  src/main/java/teammates/common/util/Const.java
Labels: s.ToMerge
