Repository TEAMMATES/teammates, pull requests merged in 2020-04, with the labels that each got.

#9961 [#9382] Enable downloading of feedback session results as CSV
  src/main/java/teammates/common/datatransfer/SectionDetail.java
  src/main/java/teammates/common/exception/RequestExceedingRangeException.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/controller/InstructorFeedbackResultsDownloadAction.java
  src/main/java/teammates/ui/controller/InstructorFeedbackResultsPageAction.java
  src/main/java/teammates/ui/webapi/action/ActionFactory.java
  src/main/java/teammates/ui/webapi/action/GetSessionResultsAction.java
  src/main/java/teammates/ui/webapi/action/GetSessionResultsAsCsvAction.java
  src/main/java/teammates/ui/webapi/endpoints/ResourceEndpoints.java
  src/main/java/teammates/ui/webapi/output/SessionResultsData.java
  src/test/java/teammates/test/cases/webapi/GetSessionResultsActionTest.java
  src/test/java/teammates/test/cases/webapi/GetSessionResultsAsCsvActionTest.java
  src/test/resources/csv/feedbackSessionResultsStatisticsHidden_actionTest.csv
  src/test/resources/csv/feedbackSessionResultsStatisticsShown_actionTest.csv
  src/test/resources/data/FeedbackSessionResultsCsvActionTest.json
  src/web/app/components/sessions-table/__snapshots__/sessions-table.component.spec.ts.snap
  src/web/app/components/sessions-table/sessions-table.component.html
  src/web/app/components/sessions-table/sessions-table.component.ts
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.ts
  src/web/app/pages-instructor/instructor-session-base-page.component.ts
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.html
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.ts
  src/web/services/feedback-sessions.service.ts
Labels: s.FinalReview

#10001 [#9986] Added Teammates link in course register email
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/main/resources/userEmailTemplate-userRegisterForCourse.html
  src/test/resources/emails/instructorCourseRegisterEmail.html
  src/test/resources/emails/studentCourseRegisterEmail.html
Labels: s.ToMerge

#9958 [#9646] Add L&P tests for backend endpoints
  build.gradle
  src/e2e/java/teammates/e2e/cases/lnp/FeedbackSessionSubmitLNPTest.java
  src/e2e/java/teammates/e2e/cases/lnp/FeedbackSessionViewLNPTest.java
  src/e2e/java/teammates/e2e/cases/lnp/InstructorSessionResultLNPTest.java
Labels: s.ToMerge

#10004 [#9940] Refactor Admin Endpoints
  src/web/app/components/error-report/__snapshots__/error-report.component.spec.ts.snap
  src/web/app/components/error-report/error-report.component.ts
  src/web/app/pages-admin/admin-accounts-page/admin-accounts-page.component.ts
  src/web/app/pages-admin/admin-sessions-page/admin-sessions-page.component.ts
  src/web/app/pages-admin/admin-timezone-page/admin-timezone-page.component.ts
  src/web/app/pages-help/session-links-recovery/session-links-recovery-page.component.ts
  src/web/app/pages-session/session-result-page/session-result-page.component.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
  src/web/services/error-report.service.spec.ts
  src/web/services/error-report.service.ts
  src/web/services/feedback-questions.service.spec.ts
  src/web/services/feedback-questions.service.ts
  src/web/services/feedback-responses.service.ts
  src/web/services/feedback-sessions.service.ts
  src/web/services/instructor.service.ts
  src/web/services/student.service.ts
  src/web/services/timezone.service.spec.ts
  src/web/services/timezone.service.ts
Labels: s.FinalReview

#10007 [#10006] Fix incorrect `disabled` flag for student home page view responses button
  src/web/app/pages-student/student-home-page/__snapshots__/student-home-page.component.spec.ts.snap
  src/web/app/pages-student/student-home-page/student-home-page.component.html
Labels: s.ToMerge

#9997 [#9996] Typo in the pop-up message of the button "Send Invite"
  src/web/app/pages-instructor/student-list/__snapshots__/student-list.component.spec.ts.snap
  src/web/app/pages-instructor/student-list/student-list.component.html
Labels: s.ToMerge

#9991 [#9946] Add additional fields for Instructor Search Migration
  src/main/java/teammates/ui/webapi/action/SearchInstructorsAction.java
  src/main/java/teammates/ui/webapi/output/InstructorData.java
  src/main/java/teammates/ui/webapi/output/InstructorsData.java
  src/test/java/teammates/test/cases/webapi/SearchInstructorsActionTest.java
Labels: s.ToMerge

#9990 [#9946] Add additional fields for Student Search Migration
  src/main/java/teammates/ui/webapi/action/SearchStudentsAction.java
  src/main/java/teammates/ui/webapi/output/StudentData.java
  src/main/java/teammates/ui/webapi/output/StudentsData.java
Labels: s.ToMerge

#9794 [#9564] Consolidate RESTFul FeedbackResponseComment API
  src/main/java/teammates/common/datatransfer/FeedbackSessionResultsBundle.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/FeedbackResponseCommentsLogic.java
  src/main/java/teammates/storage/api/FeedbackResponseCommentsDb.java
  src/main/java/teammates/ui/webapi/action/ActionFactory.java
  src/main/java/teammates/ui/webapi/action/BasicCommentSubmissionAction.java
  src/main/java/teammates/ui/webapi/action/BasicFeedbackSubmissionAction.java
  src/main/java/teammates/ui/webapi/action/CreateFeedbackResponseCommentAction.java
  src/main/java/teammates/ui/webapi/action/DeleteFeedbackResponseCommentAction.java
  src/main/java/teammates/ui/webapi/action/GetFeedbackResponseCommentAction.java
  src/main/java/teammates/ui/webapi/action/UpdateFeedbackResponseCommentAction.java
  src/main/java/teammates/ui/webapi/output/CommentVisibilityType.java
  src/main/java/teammates/ui/webapi/output/FeedbackResponseCommentData.java
  src/main/java/teammates/ui/webapi/request/FeedbackResponseCommentBasicRequest.java
  src/main/java/teammates/ui/webapi/request/FeedbackResponseCommentCreateRequest.java
  src/main/java/teammates/ui/webapi/request/FeedbackResponseCommentUpdateRequest.java
  src/test/java/teammates/test/cases/webapi/CreateFeedbackResponseCommentActionTest.java
  src/test/java/teammates/test/cases/webapi/DeleteFeedbackResponseCommentActionTest.java
  src/test/java/teammates/test/cases/webapi/GetFeedbackResponseCommentActionTest.java
  src/test/java/teammates/test/cases/webapi/UpdateFeedbackResponseCommentActionTest.java
  src/test/resources/data/FeedbackResponseCommentCRUDTest.json
  src/web/app/components/comment-box/comment-box.module.ts
  src/web/app/components/comment-box/comment-edit-form/comment-edit-form.component.html
  src/web/app/components/comment-box/comment-edit-form/comment-edit-form.component.scss
  src/web/app/components/comment-box/comment-edit-form/comment-edit-form.component.spec.ts
  src/web/app/components/comment-box/comment-edit-form/comment-edit-form.component.ts
  src/web/app/components/comment-box/comment-row/comment-row.component.html
  src/web/app/components/comment-box/comment-row/comment-row.component.scss
  src/web/app/components/comment-box/comment-row/comment-row.component.spec.ts
  src/web/app/components/comment-box/comment-row/comment-row.component.ts
  src/web/app/components/comment-box/confirm-delete-comment-modal/confirm-delete-comment-modal.component.html
  src/web/app/components/comment-box/confirm-delete-comment-modal/confirm-delete-comment-modal.component.scss
  src/web/app/components/comment-box/confirm-delete-comment-modal/confirm-delete-comment-modal.component.spec.ts
  src/web/app/components/comment-box/confirm-delete-comment-modal/confirm-delete-comment-modal.component.ts
  src/web/app/components/question-submission-form/question-submission-form-model.ts
  src/web/app/components/question-submission-form/question-submission-form.component.html
  src/web/app/components/question-submission-form/question-submission-form.component.spec.ts
  src/web/app/components/question-submission-form/question-submission-form.component.ts
  src/web/app/components/question-submission-form/question-submission-form.module.ts
  src/web/app/components/sessions-table/sessions-table.module.ts
  src/web/app/components/teammates-common/format-date-brief.pipe.spec.ts
  src/web/app/components/teammates-common/format-date-brief.pipe.ts
  src/web/app/components/teammates-common/teammates-common.module.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.component.html
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
  src/web/services/feedback-questions.service.ts
  src/web/services/feedback-response-comment.service.spec.ts
  src/web/services/feedback-response-comment.service.ts
Labels: s.ToMerge

#10005 [#9382] Add CourseService Tests
  src/web/services/course.service.spec.ts
Labels: s.ToMerge

#9995 [#9946] Migration to new RESTful search endpoints - Instructor search service
  src/web/app/pages-instructor/instructor-search-page/__snapshots__/instructor-search-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-search-page/instructor-search-bar/instructor-search-bar.component.html
  src/web/app/pages-instructor/instructor-search-page/instructor-search-bar/instructor-search-bar.component.ts
  src/web/app/pages-instructor/instructor-search-page/instructor-search-page.component.ts
  src/web/services/search.service.spec.ts
  src/web/services/search.service.ts
  src/web/services/student.service.spec.ts
  src/web/services/student.service.ts
Labels: s.FinalReview

#9998 [#9946] Migration to new RESTful search endpoints - Admin search service
  src/web/services/__snapshots__/search.service.spec.ts.snap
  src/web/services/feedback-sessions.service.spec.ts
  src/web/services/feedback-sessions.service.ts
  src/web/services/instructor.service.ts
  src/web/services/link.service.spec.ts
  src/web/services/link.service.ts
  src/web/services/search.service.spec.ts
  src/web/services/search.service.ts
Labels: s.ToMerge

#10009 [#10008] Deprecate getfeedbackquestionid method from Backdoor
  src/e2e/java/teammates/e2e/cases/lnp/FeedbackSessionSubmitLNPTest.java
  src/e2e/java/teammates/e2e/cases/lnp/InstructorSessionResultLNPTest.java
  src/e2e/java/teammates/e2e/util/BackDoor.java
Labels: s.ToMerge

#9988 [#9382] Add Tests for Admin Search Page
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.html
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.spec.ts
Labels: s.ToMerge

#10023 [#10020] Prevent potential overflow in TaskQueuer.java
  src/main/java/teammates/logic/api/TaskQueuer.java
Labels: s.ToMerge

#10014 [#9963] Typescript Utility Types and Resource Endpoints
  src/web/app/components/question-responses/gqr-rqg-view-responses/gqr-rqg-view-responses.component.ts
  src/web/app/components/question-responses/grq-rgq-view-responses/grq-rgq-view-responses.component.ts
  src/web/app/components/question-types/question-response/constsum-question-response.component.ts
  src/web/app/page.component.ts
  src/web/app/pages-admin/admin-sessions-page/admin-sessions-page.component.ts
  src/web/app/pages-admin/admin-timezone-page/admin-timezone-page.component.ts
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.spec.ts
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-view.ts
  src/web/app/pages-session/session-result-page/session-result-page.component.ts
  src/web/app/pages-student/student-profile-page/student-profile-page.component.ts
  src/web/services/account.service.spec.ts
  src/web/services/account.service.ts
  src/web/services/auth.service.spec.ts
  src/web/services/auth.service.ts
  src/web/services/course.service.spec.ts
  src/web/services/course.service.ts
  src/web/services/feedback-questions.service.spec.ts
  src/web/services/feedback-questions.service.ts
  src/web/services/feedback-responses.service.ts
  src/web/services/feedback-sessions.service.spec.ts
  src/web/services/feedback-sessions.service.ts
  src/web/services/http-request.service.spec.ts
  src/web/services/http-request.service.ts
  src/web/services/instructor.service.spec.ts
  src/web/services/instructor.service.ts
  src/web/services/navigation.service.ts
  src/web/services/student-profile.service.spec.ts
  src/web/services/student-profile.service.ts
  src/web/services/student.service.spec.ts
  src/web/services/student.service.ts
  src/web/services/timezone.service.spec.ts
  src/web/services/timezone.service.ts
Labels: s.Ongoing

#10018 [#9946] Migrate to new admin search endpoint
  src/e2e/java/teammates/e2e/cases/e2e/AdminSearchPageE2ETest.java
  src/main/java/teammates/common/datatransfer/InstructorAccountSearchResult.java
  src/main/java/teammates/common/datatransfer/StudentAccountSearchResult.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/webapi/action/ActionFactory.java
  src/main/java/teammates/ui/webapi/action/GetCourseAction.java
  src/main/java/teammates/ui/webapi/action/GetFeedbackSessionsAction.java
  src/main/java/teammates/ui/webapi/action/GetInstructorPrivilegeAction.java
  src/main/java/teammates/ui/webapi/action/GetInstructorsAction.java
  src/main/java/teammates/ui/webapi/action/SearchAccountsAction.java
  src/main/java/teammates/ui/webapi/endpoints/ResourceEndpoints.java
  src/main/java/teammates/ui/webapi/output/AdminSearchResultData.java
  src/test/java/teammates/test/cases/webapi/GetCourseActionTest.java
  src/test/java/teammates/test/cases/webapi/GetFeedbackSessionsActionTest.java
  src/test/java/teammates/test/cases/webapi/GetInstructorPrivilegeActionTest.java
  src/test/java/teammates/test/cases/webapi/SearchAccountsActionTest.java
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.spec.ts
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.ts
  src/web/services/__snapshots__/search.service.spec.ts.snap
  src/web/services/account.service.spec.ts
  src/web/services/account.service.ts
  src/web/services/instructor.service.ts
  src/web/services/link.service.spec.ts
  src/web/services/link.service.ts
  src/web/services/search.service.ts
Labels: s.ToMerge

#9992 [#9382] Migrate features to session result page
  src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.html
  src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.scss
  src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.ts
  src/web/app/pages-instructor/instructor-session-base-page.component.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-gqr-view.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-gqr-view.component.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-grq-view.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-grq-view.component.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.scss
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-question-view.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-question-view.component.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rgq-view.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rgq-view.component.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rqg-view.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rqg-view.component.ts
  src/web/services/feedback-sessions.service.ts
  src/web/services/table-comparator.service.ts
  src/web/types/sort-properties.ts
Labels: s.ToReview

#10027 [#10028] Broken url in documentation
  docs/design.md
Labels: s.ToMerge

#10026 [#10021] Missing space afterword `successfully` in the string
  src/main/java/teammates/logic/core/FeedbackResponsesLogic.java
Labels: s.ToMerge
