Repository TEAMMATES/teammates, pull requests merged in 2020-09, with the labels that each got.

#10666 [#10655] Fix getRecipientsOfQuestion in FeedbackQuestionsLogic
  src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
  src/test/java/teammates/test/cases/logic/FeedbackQuestionsLogicTest.java
  src/test/resources/data/typicalDataBundle.json
Labels: c.Bug, s.ToMerge

#10549 [#9536] Feedback Submit Page E2E Test
  src/e2e/java/teammates/e2e/cases/BaseTestCaseWithBackDoorApiAccess.java
  src/e2e/java/teammates/e2e/cases/e2e/FeedbackSubmitPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/e2e/InstructorFeedbackEditPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/AppPage.java
  src/e2e/java/teammates/e2e/pageobjects/FeedbackSubmitPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorCourseEditPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java
  src/e2e/java/teammates/e2e/util/BackDoor.java
  src/e2e/resources/data/FeedbackSubmitPageE2ETest.json
  src/e2e/resources/testng-e2e.xml
  src/main/java/teammates/ui/webapi/action/GetStudentAction.java
  src/web/app/components/comment-box/comment-row/comment-row.component.html
  src/web/app/components/question-submission-form/question-submission-form.component.html
  src/web/app/pages-session/session-submission-page/saving-complete-modal/saving-complete-modal.component.html
  src/web/app/pages-session/session-submission-page/session-submission-page.component.html
Labels: s.ToMerge

#10679 [#9536] Fix various issues in E2E tests
  src/e2e/java/teammates/e2e/cases/e2e/AdminSearchPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/e2e/BaseE2ETestCase.java
  src/e2e/java/teammates/e2e/cases/e2e/FeedbackSubmitPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/e2e/InstructorCourseEditPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/e2e/InstructorCoursesPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/e2e/InstructorFeedbackSessionsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/e2e/StudentHomePageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/AppPage.java
  src/e2e/java/teammates/e2e/pageobjects/Browser.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorCourseEditPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorCourseEnrollPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorCoursesPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java
Labels: s.ToMerge

#10685 [#10684] Fix CI tests
  build.gradle
Labels: c.DevOps, s.ToMerge

#10667 [#9536] Feedback Text Question E2E Test
  src/e2e/java/teammates/e2e/cases/e2e/FeedbackTextQuestionE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/AppPage.java
  src/e2e/java/teammates/e2e/pageobjects/FeedbackSubmitPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java
  src/e2e/resources/data/FeedbackTextQuestionE2ETest.json
  src/e2e/resources/testng-e2e.xml
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditCopyUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackEditPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSubmitPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/StudentFeedbackSubmitPageUiTest.java
  src/test/resources/data/InstructorFeedbackEditQuestionsUiTest.json
  src/test/resources/data/InstructorFeedbackQuestionSubmitPageUiTest.json
  src/test/resources/data/InstructorFeedbackSubmitPageUiTest.json
  src/test/resources/data/StudentFeedbackSubmitPageUiTest.json
  src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap
  src/web/app/components/question-edit-form/question-edit-form.component.html
  src/web/app/components/question-types/question-edit-answer-form/text-question-edit-answer-form.component.html
  src/web/app/components/question-types/question-edit-details-form/text-question-edit-details-form.component.html
Labels: s.ToMerge

#10676 [#10656] Instructor copying sessions: essay questions cannot be copied if recommended length is not set
  src/main/java/teammates/common/datatransfer/questions/FeedbackTextQuestionDetails.java
  src/main/java/teammates/ui/webapi/output/FeedbackQuestionData.java
  src/test/resources/data/typicalDataBundle.json
Labels: s.ToMerge

#10654 [#10594] Fixed instructor page course edit spinner
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.ts
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-edit-panel/instructor-edit-panel.component.html
Labels: c.Bug, s.ToMerge

#10668 [#9536] Feedback MCQ/MSQ Question E2E Test
  src/e2e/java/teammates/e2e/cases/e2e/FeedbackMcqQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/e2e/FeedbackMsqQuestionE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/FeedbackSubmitPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java
  src/e2e/resources/data/FeedbackMcqQuestionE2ETest.json
  src/e2e/resources/data/FeedbackMsqQuestionE2ETest.json
  src/e2e/resources/testng-e2e.xml
  src/test/java/teammates/test/cases/browsertests/FeedbackMcqQuestionUiTest.java
  src/test/java/teammates/test/cases/browsertests/FeedbackMsqQuestionUiTest.java
  src/test/resources/data/FeedbackMcqQuestionUiTest.json
  src/test/resources/data/FeedbackMsqQuestionUiTest.json
  src/web/app/components/question-types/question-constraint/msq-question-constraint.component.html
  src/web/app/components/question-types/question-edit-answer-form/mcq-question-edit-answer-form.component.html
  src/web/app/components/question-types/question-edit-answer-form/msq-question-edit-answer-form.component.html
  src/web/app/components/question-types/question-edit-details-form/mcq-question-edit-details-form.component.html
  src/web/app/components/question-types/question-edit-details-form/msq-question-edit-details-form.component.html
Labels: s.ToMerge

#10646 [#10631] Unnecessary checks in InstructorPrivileges.java
  src/main/java/teammates/common/datatransfer/InstructorPrivileges.java
Labels: s.ToMerge

#10622 [#10613] Reconfigure InstructorFeedbackSubmission access control
  src/main/java/teammates/ui/webapi/action/BasicFeedbackSubmissionAction.java
  src/main/java/teammates/ui/webapi/action/GetFeedbackSessionAction.java
  src/test/java/teammates/test/cases/webapi/GetFeedbackQuestionRecipientsActionTest.java
  src/test/java/teammates/test/cases/webapi/GetFeedbackSessionActionTest.java
Labels: s.ToMerge

#10698 [#10697] Performance improvements when getting session result as students
  src/main/java/teammates/logic/core/FeedbackResponsesLogic.java
  src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/storage/api/FeedbackResponsesDb.java
  src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
  src/test/java/teammates/test/cases/storage/FeedbackResponsesDbTest.java
Labels: s.ToMerge

#10653 [#10650] Add null check for getFeedbackSession in API actions
  src/main/java/teammates/ui/webapi/action/Action.java
  src/main/java/teammates/ui/webapi/action/BinFeedbackSessionAction.java
  src/main/java/teammates/ui/webapi/action/ConfirmFeedbackSessionSubmissionAction.java
  src/main/java/teammates/ui/webapi/action/CreateFeedbackQuestionAction.java
  src/main/java/teammates/ui/webapi/action/CreateFeedbackResponseCommentAction.java
  src/main/java/teammates/ui/webapi/action/CreateFeedbackSessionAction.java
  src/main/java/teammates/ui/webapi/action/DeleteFeedbackQuestionAction.java
  src/main/java/teammates/ui/webapi/action/DeleteFeedbackResponseCommentAction.java
  src/main/java/teammates/ui/webapi/action/GenerateEmailAction.java
  src/main/java/teammates/ui/webapi/action/GetFeedbackQuestionRecipientsAction.java
  src/main/java/teammates/ui/webapi/action/GetFeedbackQuestionsAction.java
  src/main/java/teammates/ui/webapi/action/GetFeedbackResponseCommentAction.java
  src/main/java/teammates/ui/webapi/action/GetFeedbackResponsesAction.java
  src/main/java/teammates/ui/webapi/action/GetFeedbackSessionAction.java
  src/main/java/teammates/ui/webapi/action/GetFeedbackSessionSubmittedGiverSetAction.java
  src/main/java/teammates/ui/webapi/action/GetHasResponsesAction.java
  src/main/java/teammates/ui/webapi/action/GetInstructorAction.java
  src/main/java/teammates/ui/webapi/action/GetSessionResponseStatsAction.java
  src/main/java/teammates/ui/webapi/action/GetSessionResultsAction.java
  src/main/java/teammates/ui/webapi/action/PublishFeedbackSessionAction.java
  src/main/java/teammates/ui/webapi/action/RemindFeedbackSessionResultAction.java
  src/main/java/teammates/ui/webapi/action/RemindFeedbackSessionSubmissionAction.java
  src/main/java/teammates/ui/webapi/action/RestoreFeedbackSessionAction.java
  src/main/java/teammates/ui/webapi/action/SubmitFeedbackResponsesAction.java
  src/main/java/teammates/ui/webapi/action/UnpublishFeedbackSessionAction.java
  src/main/java/teammates/ui/webapi/action/UpdateFeedbackQuestionAction.java
  src/main/java/teammates/ui/webapi/action/UpdateFeedbackResponseCommentAction.java
  src/main/java/teammates/ui/webapi/action/UpdateFeedbackSessionAction.java
  src/test/java/teammates/test/cases/webapi/BinFeedbackSessionActionTest.java
  src/test/java/teammates/test/cases/webapi/CreateFeedbackQuestionActionTest.java
  src/test/java/teammates/test/cases/webapi/GetFeedbackQuestionsActionTest.java
  src/test/java/teammates/test/cases/webapi/GetFeedbackSessionActionTest.java
  src/test/java/teammates/test/cases/webapi/GetHasResponsesActionTest.java
  src/test/java/teammates/test/cases/webapi/UnpublishFeedbackSessionActionTest.java
  src/test/java/teammates/test/cases/webapi/UpdateFeedbackSessionActionTest.java
Labels: s.ToMerge

#10699 [#10645] [#10688] Fix download result function and user links in admin page
  src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts
  src/web/services/__snapshots__/search.service.spec.ts.snap
  src/web/services/link.service.spec.ts
  src/web/services/link.service.ts
  src/web/services/search.service.spec.ts
Labels: s.ToMerge

#10706 [#10704] Update developers.json
  src/web/data/developers.json
Labels: c.Release

#10669 [#9536] Feedback NumScale Question E2E Test
  src/e2e/java/teammates/e2e/cases/e2e/FeedbackNumScaleQuestionE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/FeedbackSubmitPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java
  src/e2e/resources/data/FeedbackNumScaleQuestionE2ETest.json
  src/e2e/resources/testng-e2e.xml
  src/test/java/teammates/test/cases/browsertests/FeedbackNumScaleQuestionUiTest.java
  src/test/resources/data/FeedbackNumScaleQuestionUiTest.json
  src/web/app/components/question-types/question-edit-answer-form/num-scale-question-edit-answer-form.component.html
  src/web/app/components/question-types/question-edit-details-form/num-scale-question-edit-details-form.component.html
Labels: s.ToMerge

#10671 [#9536] Feedback Contribution Question E2E Test
  src/e2e/java/teammates/e2e/cases/e2e/FeedbackContributionQuestionE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/FeedbackSubmitPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java
  src/e2e/resources/data/FeedbackContributionQuestionE2ETest.json
  src/e2e/resources/testng-e2e.xml
  src/test/java/teammates/test/cases/browsertests/FeedbackContributionQuestionUiTest.java
  src/test/resources/data/FeedbackContributionQuestionUiTest.json
  src/web/app/components/question-types/question-edit-details-form/contribution-question-edit-details-form.component.html
Labels: s.ToMerge

#10672 [#9536] Feedback Rank Questions E2E Tests
  src/e2e/java/teammates/e2e/cases/e2e/FeedbackRankOptionQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/e2e/FeedbackRankRecipientQuestionE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/FeedbackSubmitPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java
  src/e2e/resources/data/FeedbackRankOptionQuestionE2ETest.json
  src/e2e/resources/data/FeedbackRankRecipientQuestionE2ETest.json
  src/e2e/resources/testng-e2e.xml
  src/test/java/teammates/test/cases/browsertests/FeedbackRankQuestionUiTest.java
  src/test/resources/data/FeedbackRankQuestionUiTest.json
  src/web/app/components/question-types/question-edit-details-form/rank-options-question-edit-details-form.component.html
  src/web/app/components/question-types/question-edit-details-form/rank-recipients-question-edit-details-form.component.html
  src/web/app/components/question-types/question-instruction/rank-options-question-instruction.component.html
  src/web/app/components/question-types/question-instruction/rank-recipients-question-instruction.component.html
Labels: s.ToMerge

#10670 [#9536] Feedback ConstSum Questions E2E Tests
  src/e2e/java/teammates/e2e/cases/e2e/FeedbackConstSumOptionQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/e2e/FeedbackConstSumRecipientQuestionE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/FeedbackSubmitPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java
  src/e2e/resources/data/FeedbackConstSumOptionQuestionE2ETest.json
  src/e2e/resources/data/FeedbackConstSumRecipientQuestionE2ETest.json
  src/e2e/resources/testng-e2e.xml
  src/test/java/teammates/test/cases/browsertests/FeedbackConstSumOptionQuestionUiTest.java
  src/test/java/teammates/test/cases/browsertests/FeedbackConstSumRecipientQuestionUiTest.java
  src/test/resources/data/FeedbackConstSumOptionQuestionUiTest.json
  src/test/resources/data/FeedbackConstSumRecipientQuestionUiTest.json
  src/web/app/components/question-types/question-edit-details-form/constsum-options-question-edit-details-form.component.html
  src/web/app/components/question-types/question-edit-details-form/constsum-recipients-question-edit-details-form.component.html
  src/web/app/components/question-types/question-instruction/constsum-options-question-instruction.component.html
  src/web/app/components/question-types/question-instruction/constsum-recipients-question-instruction.component.html
Labels: s.ToMerge

#10673 [#9536] Feedback Rubric Question E2E Test
  src/e2e/java/teammates/e2e/cases/e2e/FeedbackRubricQuestionE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/FeedbackSubmitPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java
  src/e2e/resources/data/FeedbackRubricQuestionE2ETest.json
  src/e2e/resources/testng-e2e.xml
  src/test/java/teammates/test/cases/browsertests/FeedbackRubricQuestionUiTest.java
  src/test/resources/data/FeedbackRubricQuestionUiTest.json
  src/web/app/components/question-types/question-edit-details-form/rubric-question-edit-details-form.component.html
Labels: s.ToMerge

#10707 [#9536] Course Join Confirmation Page E2E Tests
  src/e2e/java/teammates/e2e/cases/BaseTestCaseWithBackDoorApiAccess.java
  src/e2e/java/teammates/e2e/cases/e2e/FeedbackConstSumOptionQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/e2e/FeedbackConstSumRecipientQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/e2e/FeedbackContributionQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/e2e/FeedbackMcqQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/e2e/FeedbackMsqQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/e2e/FeedbackNumScaleQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/e2e/FeedbackRankOptionQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/e2e/FeedbackRankRecipientQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/e2e/FeedbackRubricQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/e2e/FeedbackSubmitPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/e2e/FeedbackTextQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/e2e/InstructorCourseJoinConfirmationPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/e2e/StudentCourseJoinConfirmationPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/CourseJoinConfirmationPage.java
  src/e2e/java/teammates/e2e/pageobjects/DevServerLoginPage.java
  src/e2e/java/teammates/e2e/pageobjects/ErrorReportingModal.java
  src/e2e/java/teammates/e2e/util/BackDoor.java
  src/e2e/resources/data/InstructorCourseJoinConfirmationPageE2ETest.json
  src/e2e/resources/data/StudentCourseJoinConfirmationPageE2ETest.json
  src/e2e/resources/testng-e2e.xml
  src/main/java/teammates/common/util/AppUrl.java
  src/main/java/teammates/ui/webapi/action/GetInstructorsAction.java
  src/main/java/teammates/ui/webapi/action/GetStudentAction.java
  src/test/java/teammates/test/cases/browsertests/InstructorCourseJoinConfirmationPageUiTest.java
  src/test/java/teammates/test/cases/browsertests/StudentCourseJoinConfirmationPageUiTest.java
  src/test/resources/data/StudentCourseJoinConfirmationPageUiTest.json
  src/web/app/components/error-report/__snapshots__/error-report.component.spec.ts.snap
  src/web/app/components/error-report/error-report.component.html
  src/web/app/user-join-page.component.html
Labels: s.ToMerge

#10712 [#10711] Link to Feature Overview in CONTRIBUTING.md do not lead to the correct webpage
  docs/CONTRIBUTING.md
Labels: c.Bug, s.ToMerge

#10692 [#10655] Instructor enroll students: incorrect intermediate state shown while loading page
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.html
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.module.ts
Labels: s.ToMerge

#10714 [#10713] Links in CONTRIBUTING.md and SUPPORT.md do not lead to the correct webpage
  .github/SUPPORT.md
  docs/CONTRIBUTING.md
Labels: c.Bug, s.ToMerge

#10724 [#10723] Missing call to AuthService.getAuthUser for public pages
  src/web/app/public-page.component.spec.ts
  src/web/app/public-page.component.ts
Labels: s.ToReview

#10719 [#10705] [#10718] Improve user flow for unregistered student and invalid registration key
  src/main/java/teammates/ui/webapi/action/GetRegkeyValidityAction.java
  src/main/java/teammates/ui/webapi/output/RegkeyValidityData.java
  src/test/java/teammates/test/cases/webapi/GetRegkeyValidityActionTest.java
  src/web/app/pages-session/session-result-page/session-result-page.component.html
  src/web/app/pages-session/session-result-page/session-result-page.component.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.component.html
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
Labels: s.ToMerge

#10633 [#10581] Add top level domain hint for invalid email error
  src/main/java/teammates/common/util/FieldValidator.java
  src/test/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributesTest.java
  src/test/java/teammates/common/util/FieldValidatorTest.java
  src/test/java/teammates/logic/core/InstructorsLogicTest.java
Labels: c.Bug, s.ToMerge

#10727 [#10708] Trim cell values of Enroll Students page
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts
Labels: c.Bug, s.ToMerge

#10729 [#10726] Change banner message for end of v6
  src/web/app/components/redirect-banner/redirect-banner.component.html
Labels: c.Task, s.ToMerge

#10730 [#10726] Update developers.json
  src/web/data/developers.json
Labels: c.Release, s.ToMerge

#10732 [#9536] Reduce E2E tests flakiness due to underlying test structure
  .travis.yml
  build.gradle
  src/e2e/java/teammates/e2e/cases/e2e/BaseE2ETestCase.java
  src/e2e/java/teammates/e2e/cases/e2e/InstructorCourseJoinConfirmationPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/e2e/StudentCourseJoinConfirmationPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/AppPage.java
  src/e2e/java/teammates/e2e/pageobjects/Browser.java
  src/e2e/java/teammates/e2e/pageobjects/BrowserPool.java
  src/e2e/java/teammates/e2e/util/TestProperties.java
  src/e2e/resources/test.template.properties
  src/e2e/resources/test.travis-chrome.properties
  src/e2e/resources/test.travis.properties
  src/test/java/teammates/test/BaseTestCase.java
Labels: s.ToMerge

#10710 [#9536] Instructor Home Page E2E Test
  src/e2e/java/teammates/e2e/cases/e2e/InstructorHomePageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorHomePage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorSearchPage.java
  src/e2e/resources/data/InstructorHomePageE2ETest.json
  src/e2e/resources/testng-e2e.xml
  src/test/java/teammates/test/cases/browsertests/InstructorHomePageUiTest.java
  src/test/resources/data/InstructorHomePageUiTest1.json
  src/test/resources/data/InstructorHomePageUiTest2.json
  src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
  src/web/app/pages-instructor/instructor-search-page/__snapshots__/instructor-search-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-search-page/student-result-table/student-result-table.component.html
Labels: c.Feature, s.ToMerge
