Repository TEAMMATES/teammates, pull requests merged in 2020-12, with the labels that each got.

#10846 [#10844] Admin search page: show instructors and students in different colors
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.html
Labels: s.ToMerge

#10853 [#9536] Fix AdminSessionsPageE2ETest due to wrong year pattern
  src/e2e/java/teammates/e2e/cases/AdminSessionsPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/AdminSessionsPage.java
Labels: s.ToReview

#10849 [#10845] Fix observers cannot view session results
  src/main/java/teammates/ui/webapi/GetFeedbackQuestionsAction.java
  src/test/java/teammates/ui/webapi/GetFeedbackQuestionsActionTest.java
Labels: s.ToMerge

#10767 [#10693] Add allow rich text editor frontend option
  src/main/java/teammates/common/datatransfer/questions/FeedbackTextQuestionDetails.java
  src/test/java/teammates/common/datatransfer/questions/FeedbackTextQuestionDetailsTest.java
  src/test/java/teammates/common/util/JsonUtilsTest.java
  src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap
  src/web/app/components/question-edit-form/question-edit-form.component.scss
  src/web/app/components/question-text-with-info/question-text-with-info.component.spec.ts
  src/web/app/components/question-types/question-edit-answer-form/text-question-edit-answer-form.component.html
  src/web/app/components/question-types/question-edit-answer-form/text-question-edit-answer-form.component.scss
  src/web/app/components/question-types/question-edit-details-form/text-question-edit-details-form.component.html
  src/web/app/components/question-types/question-edit-details-form/text-question-edit-details-form.component.scss
  src/web/app/components/question-types/question-edit-details-form/text-question-edit-details-form.component.ts
  src/web/types/default-question-structs.ts
  src/web/types/question-details-impl/feedback-text-question-details.impl.ts
Labels: c.Feature, s.ToMerge

#10855 [#10854] Update developers.json
  src/web/data/developers.json
Labels: c.Release

#10847 [#10804] [Help for Instructors page][Search field]Enter a word "course" and click on enter twice, the outcome results changes from 31 to 0 search items
  src/web/app/pages-help/instructor-help-page/instructor-help-page.component.ts
Labels: c.Bug, s.ToMerge

#10778 [#10615] Instructor view results: add space after the spinner in the download button
  src/web/app/components/ajax-loading/ajax-loading.component.scss
  src/web/app/components/session-edit-form/session-edit-form.component.html
  src/web/app/pages-help/session-links-recovery/session-links-recovery-page.component.html
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-edit-panel/instructor-edit-panel.component.html
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.html
  src/web/app/pages-session/session-submission-page/session-submission-page.component.html
Labels: c.Bug, s.ToMerge

#10852 [#8528] Instructor: view results: make the explanation of the view more informative
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts
Labels: c.Feature, s.ToMerge

#10801 [#9536] Instructor Feedback Results Page E2E Test
  src/e2e/java/teammates/e2e/cases/InstructorFeedbackResultsPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/AppPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackResultsPage.java
  src/e2e/resources/data/InstructorFeedbackResultsPageE2ETest.json
  src/e2e/resources/testng-e2e.xml
  src/web/app/components/comment-box/comment-table-modal/comment-table-modal.component.html
  src/web/app/components/question-responses/gqr-rqg-view-responses/gqr-rqg-view-responses.component.html
  src/web/app/components/question-responses/grouped-responses/grouped-responses.component.html
  src/web/app/components/question-responses/grq-rgq-view-responses/grq-rgq-view-responses.component.html
  src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.html
  src/web/app/components/question-types/question-statistics/mcq-question-statistics.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-gqr-view.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-grq-view.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-question-view.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rgq-view.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rqg-view.component.html
Labels: s.ToMerge

#10850 [#9536] Enforce page object pattern via architectural check and remove unused items
  build.gradle
  docs/e2e-testing.md
  src/client/java/teammates/client/util/ClientProperties.java
  src/e2e/java/teammates/e2e/cases/AdminSearchPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/BaseE2ETestCase.java
  src/e2e/java/teammates/e2e/cases/BaseFeedbackQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackSubmitPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorCourseEditPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorCourseEnrollPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorCourseJoinConfirmationPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorCourseStudentDetailsEditPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorCourseStudentDetailsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorFeedbackSessionsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorHomePageE2ETest.java
  src/e2e/java/teammates/e2e/cases/StudentCourseJoinConfirmationPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/StudentFeedbackResultsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/StudentHomePageE2ETest.java
  src/e2e/java/teammates/e2e/cases/TimezoneSyncerTest.java
  src/e2e/java/teammates/e2e/pageobjects/AdminSearchPage.java
  src/e2e/java/teammates/e2e/pageobjects/AdminTimezonePage.java
  src/e2e/java/teammates/e2e/pageobjects/AppPage.java
  src/e2e/java/teammates/e2e/pageobjects/Browser.java
  src/e2e/java/teammates/e2e/pageobjects/IanaTimezonePage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorCoursesPage.java
  src/e2e/java/teammates/e2e/pageobjects/NotAuthorizedPage.java
  src/e2e/java/teammates/e2e/pageobjects/NotFoundPage.java
  src/e2e/java/teammates/e2e/pageobjects/StudentCourseDetailsPage.java
  src/e2e/java/teammates/e2e/pageobjects/StudentHelpPage.java
  src/e2e/java/teammates/e2e/pageobjects/StudentHomePage.java
  src/e2e/java/teammates/e2e/pageobjects/StudentProfilePage.java
  src/e2e/java/teammates/e2e/util/Priority.java
  src/e2e/java/teammates/e2e/util/PriorityInterceptor.java
  src/e2e/java/teammates/e2e/util/TestProperties.java
  src/e2e/resources/scripts/addChangeEventHook.js
  src/e2e/resources/testng-e2e.xml
  src/lnp/java/teammates/lnp/util/TestProperties.java
  src/main/java/teammates/common/util/Url.java
  src/test/java/teammates/architecture/ArchitectureTest.java
  src/test/java/teammates/common/util/UrlExtension.java
  src/test/java/teammates/common/util/UrlTest.java
Labels: s.ToMerge

#10867 [#8465] Instructor: edit question: distribute question options vs recipients tooltip (UI)
  src/web/app/components/question-types/question-edit-details-form/constsum-options-question-edit-details-form.component.html
  src/web/app/components/question-types/question-edit-details-form/constsum-recipients-question-edit-details-form.component.html
Labels: c.Bug, s.ToMerge

#10861 [#10860] Student submit responses: prompt the student to save a submission confirmation
  src/e2e/java/teammates/e2e/cases/FeedbackSubmitPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/FeedbackSubmitPage.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/common/util/EmailType.java
  src/main/java/teammates/common/util/Templates.java
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/main/java/teammates/ui/endpoints/ResourceEndpoints.java
  src/main/java/teammates/ui/output/ConfirmationResponse.java
  src/main/java/teammates/ui/output/ConfirmationResult.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/ConfirmFeedbackSessionSubmissionAction.java
  src/main/java/teammates/ui/webapi/SubmitFeedbackResponsesAction.java
  src/main/resources/userEmailTemplate-feedbackSubmissionConfirmation.html
  src/test/java/teammates/common/util/TimeHelperExtension.java
  src/test/java/teammates/logic/api/EmailGeneratorTest.java
  src/test/java/teammates/ui/webapi/ConfirmFeedbackSessionSubmissionActionTest.java
  src/test/resources/emails/sessionSubmissionConfirmationEmailNegativeTimeZone.html
  src/test/resources/emails/sessionSubmissionConfirmationEmailPositiveTimeZone.html
  src/test/resources/emails/sessionSubmissionConfirmationEmailTestingSanitization.html
  src/test/resources/emails/sessionSubmissionConfirmationEmailZeroTimeZone.html
  src/web/app/pages-help/student-help-page/student-help-page.component.html
  src/web/app/pages-session/session-submission-page/saving-complete-modal/saving-complete-modal.component.html
  src/web/app/pages-session/session-submission-page/saving-complete-modal/saving-complete-modal.component.spec.ts
  src/web/app/pages-session/session-submission-page/saving-complete-modal/saving-complete-modal.component.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.component.html
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
  src/web/services/feedback-sessions.service.ts
Labels: c.Feature, s.ToMerge

#10879 [#10870] Improve error messages for 403 errors
  src/main/java/teammates/common/exception/UnauthorizedAccessException.java
  src/main/java/teammates/logic/api/GateKeeper.java
  src/main/java/teammates/ui/webapi/Action.java
  src/main/java/teammates/ui/webapi/BasicFeedbackSubmissionAction.java
  src/main/java/teammates/ui/webapi/DeleteStudentProfilePictureAction.java
  src/main/java/teammates/ui/webapi/GetSessionResultsAction.java
  src/main/java/teammates/ui/webapi/SubmitFeedbackResponsesAction.java
  src/main/java/teammates/ui/webapi/UpdateStudentProfileAction.java
  src/main/java/teammates/ui/webapi/WebApiServlet.java
  src/test/java/teammates/ui/webapi/UpdateStudentProfileActionTest.java
Labels: c.Feature, s.ToMerge

#10864 [#10805] Browse by topic listing comes over the text (fix padding)
  src/web/app/pages-help/instructor-help-page/instructor-help-page.component.scss
Labels: c.Bug, s.ToMerge

#10881 [#10573] Fix styling for error report modal
  src/web/app/components/error-report/__snapshots__/error-report.component.spec.ts.snap
  src/web/app/components/error-report/error-report.component.html
  src/web/app/components/error-report/error-report.component.scss
Labels: c.Bug, s.ToMerge

#10868 [#1501] Add unit tests for FeedbackRankQuestionDetails and FeedbackTextResponseDetails classes
  src/test/java/teammates/common/datatransfer/questions/FeedbackRankQuestionDetailsTest.java
  src/test/java/teammates/common/datatransfer/questions/FeedbackTextResponseDetailsTest.java
Labels: c.Feature, s.ToMerge

#10892 [#10891] Numerical Scale Question: Improve Validation
  src/main/java/teammates/common/datatransfer/questions/FeedbackNumericalScaleQuestionDetails.java
  src/test/java/teammates/common/datatransfer/questions/FeedbackNumericalScaleQuestionDetailsTest.java
Labels: s.ToMerge

#10871 [#10788] Instructor view student list: incorrect state shown very briefly (feedback session page)
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.html
Labels: c.Bug, s.ToMerge

#10791 [#10750] Add institute to footer for unregistered key
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/AccountsLogic.java
  src/main/java/teammates/ui/webapi/GetStudentAction.java
  src/web/app/public-page.component.ts
Labels: c.Feature, s.ToMerge

#10875 [#10874] Migrate CI to Github Actions
  .github/workflows/main.yml
  src/e2e/java/teammates/e2e/pageobjects/AppPage.java
  src/e2e/resources/test.ci-chrome.properties
  src/e2e/resources/test.ci-firefox.properties
Labels: c.DevOps, s.ToMerge

#10865 [#10862] Student viewing results: Add more info to about the 'Team View'
  src/web/app/components/question-types/question-statistics/contribution-question-statistics/contribution-question-statistics.component.html
Labels: c.Feature, s.ToMerge
