Repository TEAMMATES/teammates, pull requests merged in 2020-10, with the labels that each got.

#10735 [#10725] Show student name more prominently
  src/web/app/pages-session/session-submission-page/session-submission-page.component.html
Labels: c.Feature, s.ToMerge

#10717 [#10703] Fix warning when instructor change visibility of question
  src/web/app/components/question-edit-form/question-edit-form-model.ts
  src/web/app/components/question-edit-form/question-edit-form.component.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-data.ts
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
  src/web/app/pages-instructor/instructor-session-edit-page/template-question-modal/template-question-modal.component.ts
Labels: c.Bug, s.ToMerge

#10709 [#10315] Refactor search result for instructor search
  src/web/app/pages-instructor/instructor-search-page/instructor-search-page.component.spec.ts
  src/web/app/pages-instructor/instructor-search-page/instructor-search-page.component.ts
  src/web/services/search.service.spec.ts
  src/web/services/search.service.ts
Labels: c.Task, s.ToMerge

#10733 [#10664] Student trying to access non-existent session: give a better error message
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
Labels: c.Feature, s.ToMerge

#10763 [#10702] Change status code to 400 for non-UTF8 inputs
  src/main/java/teammates/ui/webapi/WebApiServlet.java
  src/main/java/teammates/ui/webapi/WebPageServlet.java
Labels: c.Bug, s.ToMerge

#10762 [#10595] Instructor session results page: better label for questions without specific recipients
  src/web/app/components/question-responses/grouped-responses/grouped-responses.component.ts
  src/web/app/components/question-responses/grq-rgq-view-responses/grq-rgq-view-responses.component.html
  src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.html
  src/web/app/components/teammates-common/student-name/student-name-with-photo.component.html
Labels: c.Feature, s.ToMerge

#10740 [#10739] Reduce bytes transferred for I/O requests
  angular.json
  package-lock.json
  package.json
  src/main/java/teammates/common/util/HttpRequestHelper.java
  src/main/java/teammates/common/util/JsonUtils.java
  src/main/java/teammates/logic/core/TaskQueuesLogic.java
  src/main/java/teammates/storage/search/FeedbackResponseCommentSearchDocument.java
  src/main/java/teammates/ui/request/FeedbackQuestionBasicRequest.java
  src/main/java/teammates/ui/webapi/DatastoreBackupAction.java
  src/main/java/teammates/ui/webapi/JsonResult.java
  src/main/java/teammates/ui/webapi/WebPageServlet.java
  src/test/java/teammates/common/util/JsonUtilsTest.java
  src/web/app/components/loading-spinner/loading-spinner.component.scss
  src/web/app/components/question-types/question-edit-details-form/mcq-field/mcq-field.component.spec.ts
  src/web/app/components/question-types/question-edit-details-form/mcq-question-edit-details-form.component.spec.ts
  src/web/app/components/question-types/question-edit-details-form/option-rich-text-editor/option-rich-text-editor.component.html
  src/web/app/components/question-types/question-edit-details-form/option-rich-text-editor/option-rich-text-editor.component.scss
  src/web/app/components/question-types/question-edit-details-form/option-rich-text-editor/option-rich-text-editor.component.spec.ts
  src/web/app/components/question-types/question-edit-details-form/option-rich-text-editor/option-rich-text-editor.component.ts
  src/web/app/components/question-types/question-edit-details-form/option-rich-text-editor/option-rich-text-editor.module.ts
  src/web/app/components/question-types/question-edit-details-form/question-edit-details-form.module.ts
  src/web/app/components/rich-text-editor/rich-text-editor.component.ts
  src/web/app/components/rich-text-editor/rich-text-editor.module.ts
  src/web/app/components/rich-text-editor/tinymce.ts
  src/web/index.html
  src/web/index.prod.html
  src/web/sitemap.xml
  src/web/styles.scss
Labels: s.ToMerge

#10769 [#10768] Client scripts do not work on production server in V7
  src/main/webapp/WEB-INF/web.xml
Labels: s.ToMerge

#10555 [#10544] Add feedback session copy to multiple courses
  src/web/app/components/copy-session-modal/__snapshots__/copy-session-modal.component.spec.ts.snap
  src/web/app/components/copy-session-modal/copy-session-modal-model.ts
  src/web/app/components/copy-session-modal/copy-session-modal.component.html
  src/web/app/components/copy-session-modal/copy-session-modal.component.spec.ts
  src/web/app/components/copy-session-modal/copy-session-modal.component.ts
  src/web/app/components/sessions-table/sessions-table-model.ts
  src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.ts
  src/web/app/pages-instructor/instructor-session-base-page.component.ts
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.ts
Labels: c.Feature, s.ToMerge

#10773 [#10772] Update contributing guide for label changes
  docs/CONTRIBUTING.md
Labels: c.Task, s.ToMerge

#10776 [#10774] Update developers.json
  src/web/data/developers.json
Labels: c.Task, s.ToMerge

#10771 [#10753] Section selection in session results show duplicate options
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.html
Labels: c.Bug, s.ToMerge

#10777 [#10568] Admin bulk-adding instructors: allow separation by tabs
  src/web/app/pages-admin/admin-home-page/admin-home-page.component.spec.ts
  src/web/app/pages-admin/admin-home-page/admin-home-page.component.ts
Labels: c.Feature, s.ToMerge

#10781 [#10780] Remove Redirect Banner
  src/web/app/components/redirect-banner/redirect-banner.component.html
  src/web/app/components/redirect-banner/redirect-banner.component.scss
  src/web/app/components/redirect-banner/redirect-banner.component.spec.ts
  src/web/app/components/redirect-banner/redirect-banner.component.ts
  src/web/app/components/redirect-banner/redirect-banner.module.ts
  src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.module.ts
  src/web/app/pages-static/index-page/index-page.component.html
  src/web/app/pages-static/index-page/index-page.component.spec.ts
  src/web/app/pages-static/index-page/index-page.module.ts
  src/web/environments/config.template.ts
Labels: c.Task, s.ToMerge

#10775 [#3810] Create a new 'under maintenance' version
  src/main/java/teammates/common/util/Config.java
  src/main/java/teammates/ui/webapi/WebApiServlet.java
  src/main/resources/build.template.properties
  src/web/app/app.module.ts
  src/web/app/maintenance-page.component.html
  src/web/app/maintenance-page.component.scss
  src/web/app/maintenance-page.component.spec.ts
  src/web/app/maintenance-page.component.ts
  src/web/app/public-page.component.ts
  src/web/environments/config.template.ts
Labels: c.Feature, s.ToMerge

#10779 [#9536] Instructor Course Student Details Page E2E Test
  src/e2e/java/teammates/e2e/cases/e2e/InstructorCourseStudentDetailsPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorCourseStudentDetailsViewPage.java
  src/e2e/resources/data/InstructorCourseStudentDetailsPageE2ETest.json
  src/e2e/resources/testng-e2e.xml
  src/test/java/teammates/test/cases/browsertests/InstructorCourseStudentDetailsPageUiTest.java
  src/test/resources/data/InstructorCourseStudentDetailsPageUiTest.json
  src/web/app/pages-instructor/instructor-course-student-details-page/instructor-course-student-details-page.component.html
  src/web/app/pages-instructor/student-profile/course-related-info/course-related-info.component.html
  src/web/app/pages-instructor/student-profile/more-info/more-info.component.html
  src/web/app/pages-instructor/student-profile/student-profile.component.html
Labels: s.ToMerge

#10752 [#9536] Instructor Course Student Details Edit Page E2E Test
  src/e2e/java/teammates/e2e/cases/e2e/InstructorCourseStudentDetailsEditPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorCourseStudentDetailsEditPage.java
  src/e2e/resources/data/InstructorCourseStudentDetailsEditPageE2ETest.json
  src/e2e/resources/testng-e2e.xml
  src/main/java/teammates/ui/webapi/GetStudentAction.java
  src/test/java/teammates/test/cases/browsertests/InstructorCourseStudentDetailsEditPageUiTest.java
  src/web/app/pages-instructor/instructor-course-student-edit-page/__snapshots__/instructor-course-student-edit-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.html
Labels: c.Feature, s.ToMerge

#10766 [#9536] Instructor Course Details Page E2E Test
  src/e2e/java/teammates/e2e/cases/e2e/InstructorCourseDetailsPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorCourseDetailsPage.java
  src/e2e/resources/data/InstructorCourseDetailsPageE2ETest.json
  src/e2e/resources/testng-e2e.xml
  src/test/java/teammates/test/cases/browsertests/InstructorCourseDetailsPageUiTest.java
  src/test/resources/data/InstructorCourseDetailsPageUiTest.json
  src/web/app/components/student-list/__snapshots__/student-list.component.spec.ts.snap
  src/web/app/components/student-list/student-list.component.html
  src/web/app/pages-instructor/instructor-course-details-page/__snapshots__/instructor-course-details-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.html
  src/web/app/pages-instructor/instructor-search-page/__snapshots__/instructor-search-page.component.spec.ts.snap
Labels: s.ToMerge

#10799 [#10523] Edit session button should open the sessions page in edit mode
  src/web/app/components/sessions-table/__snapshots__/sessions-table.component.spec.ts.snap
  src/web/app/components/sessions-table/sessions-table.component.html
  src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
Labels: s.ToMerge

#10807 [#10802] student viewing results: 'not authorized' error shown even if the link is correct
  src/main/java/teammates/ui/webapi/GetSessionResultsAction.java
  src/test/java/teammates/ui/webapi/GetSessionResultsActionTest.java
Labels: c.Bug, s.ToMerge

#10792 [#10739] Reduce number of unnecessary API requests
  src/e2e/java/teammates/e2e/util/BackDoor.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/CoursesLogic.java
  src/main/java/teammates/ui/output/CourseData.java
  src/main/java/teammates/ui/output/FeedbackResponseData.java
  src/main/java/teammates/ui/output/FeedbackSessionData.java
  src/main/java/teammates/ui/webapi/Action.java
  src/main/java/teammates/ui/webapi/CreateFeedbackSessionAction.java
  src/main/java/teammates/ui/webapi/GetCourseAction.java
  src/main/java/teammates/ui/webapi/GetCoursesAction.java
  src/main/java/teammates/ui/webapi/GetFeedbackResponsesAction.java
  src/main/java/teammates/ui/webapi/GetFeedbackSessionsAction.java
  src/main/java/teammates/ui/webapi/GetInstructorPrivilegeAction.java
  src/main/java/teammates/ui/webapi/RestoreFeedbackSessionAction.java
  src/test/java/teammates/logic/core/CoursesLogicTest.java
  src/test/java/teammates/ui/webapi/BinCourseActionTest.java
  src/test/java/teammates/ui/webapi/GetCourseActionTest.java
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.ts
  src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.ts
  src/web/app/pages-instructor/instructor-session-base-page.component.ts
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
  src/web/services/feedback-response-comment.service.ts
  src/web/types/instructor-privilege.ts
Labels: s.ToMerge

#10800 [#10645] [#10688] Fix bugs in instructor results page
  src/web/app/components/question-responses/gqr-rqg-view-responses/gqr-rqg-view-responses.component.html
  src/web/app/components/question-responses/gqr-rqg-view-responses/gqr-rqg-view-responses.component.ts
  src/web/app/components/question-responses/grq-rgq-view-responses/grq-rgq-view-responses.component.html
  src/web/app/components/question-responses/grq-rgq-view-responses/grq-rgq-view-responses.component.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-gqr-view.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-grq-view.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rgq-view.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rqg-view.component.html
Labels: c.Bug, s.ToMerge

#10816 [#10811] Update developers.json
  src/web/data/developers.json
Labels: c.Task

#10821 [#9536] Clean up test accounts and add test data checker
  src/e2e/java/teammates/e2e/cases/e2e/AutomatedSessionRemindersTest.java
  src/e2e/java/teammates/e2e/cases/e2e/BaseE2ETestCase.java
  src/e2e/java/teammates/e2e/cases/e2e/FeedbackSubmitPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/e2e/InstructorCourseDetailsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/e2e/InstructorCourseStudentDetailsEditPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/e2e/InstructorFeedbackSessionsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/e2e/InstructorHomePageE2ETest.java
  src/e2e/java/teammates/e2e/cases/e2e/SystemErrorEmailReportE2ETest.java
  src/e2e/java/teammates/e2e/cases/util/TestDataValidityTest.java
  src/e2e/java/teammates/e2e/pageobjects/AppPage.java
  src/e2e/java/teammates/e2e/pageobjects/DevServerLoginPage.java
  src/e2e/java/teammates/e2e/pageobjects/GoogleLoginPage.java
  src/e2e/java/teammates/e2e/pageobjects/HomePage.java
  src/e2e/java/teammates/e2e/pageobjects/LoginPage.java
  src/e2e/java/teammates/e2e/util/TestProperties.java
  src/e2e/resources/test.template.properties
  src/e2e/resources/test.travis-chrome.properties
  src/e2e/resources/test.travis.properties
  src/main/java/teammates/logic/api/EmailSender.java
  src/test/java/teammates/architecture/ArchitectureTest.java
Labels: s.ToReview

#10695 [#10691] Weighted rubric question missing statistics
  src/main/java/teammates/ui/output/SessionResultsData.java
  src/web/app/components/question-responses/single-statistics/single-statistics.component.ts
  src/web/app/components/question-types/question-statistics/question-statistics-calculation/rubric-question-statistics-calculation.ts
  src/web/app/pages-session/session-result-page/session-result-page.component.html
Labels: c.Feature, s.ToMerge

#10751 [#1501] Add tests to FeedbackRankOptionsQuestionDetails
  src/main/java/teammates/common/datatransfer/questions/FeedbackRankOptionsQuestionDetails.java
  src/test/java/teammates/common/datatransfer/questions/FeedbackRankOptionsQuestionDetailsTest.java
Labels: c.Feature, s.ToMerge

#10765 [#10678] Complete removal of respondingInstructorList and respondingStudentList in FeedbackSessionAttributes
  src/main/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributes.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/api/TaskQueuer.java
  src/main/java/teammates/logic/core/DataBundleLogic.java
  src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
  src/main/java/teammates/logic/core/FeedbackResponsesLogic.java
  src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/logic/core/InstructorsLogic.java
  src/main/java/teammates/logic/core/StudentsLogic.java
  src/main/java/teammates/storage/api/FeedbackResponsesDb.java
  src/main/java/teammates/storage/api/FeedbackSessionsDb.java
  src/main/java/teammates/storage/entity/FeedbackSession.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/ConfirmFeedbackSessionSubmissionAction.java
  src/main/java/teammates/ui/webapi/FeedbackSessionUpdateRespondentWorkerAction.java
  src/main/webapp/WEB-INF/queue.xml
  src/test/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributesTest.java
  src/test/java/teammates/logic/core/FeedbackQuestionsLogicTest.java
  src/test/java/teammates/logic/core/FeedbackResponsesLogicTest.java
  src/test/java/teammates/logic/core/FeedbackSessionsLogicTest.java
  src/test/java/teammates/logic/core/InstructorsLogicTest.java
  src/test/java/teammates/logic/core/StudentsLogicTest.java
  src/test/java/teammates/storage/api/FeedbackSessionsDbTest.java
  src/test/java/teammates/test/BaseTestCaseWithDatastoreAccess.java
  src/test/java/teammates/ui/webapi/ConfirmFeedbackSessionSubmissionActionTest.java
  src/test/java/teammates/ui/webapi/FeedbackSessionRemindEmailWorkerActionTest.java
  src/test/java/teammates/ui/webapi/FeedbackSessionUpdateRespondentWorkerActionTest.java
Labels: c.Task, s.ToMerge
