Repository TEAMMATES/teammates, pull requests merged in 2020-01, with the labels that each got.

#9897 [#9595] Migrate GET /courses/students/details to RESTFul API
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/webapi/action/ActionFactory.java
  src/main/java/teammates/ui/webapi/action/GetCourseStudentDetailsAction.java
  src/test/java/teammates/test/cases/webapi/GetCourseStudentDetailsActionTest.java
  src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.spec.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.ts
  src/web/app/pages-instructor/instructor-course-student-details-page/__snapshots__/instructor-course-student-details-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-course-student-details-page/instructor-course-student-details-page.component.spec.ts
  src/web/app/pages-instructor/instructor-course-student-details-page/instructor-course-student-details-page.component.ts
  src/web/app/pages-instructor/student-profile/course-related-info/course-related-info.component.html
  src/web/app/pages-instructor/student-profile/course-related-info/course-related-info.component.ts
  src/web/app/pages-instructor/student-profile/student-attributes.ts
  src/web/services/student.service.ts
Labels: s.ToReview

#9895 [#9595] Migrate GET /students/editDetails to RESTFul API
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/webapi/action/ActionFactory.java
  src/main/java/teammates/ui/webapi/action/GetStudentEditDetailsAction.java
  src/test/java/teammates/test/cases/webapi/GetStudentEditDetailsActionTest.java
  src/web/app/pages-instructor/instructor-course-student-details-page/instructor-course-student-details-page.component.ts
  src/web/app/pages-instructor/instructor-course-student-edit-page/__snapshots__/instructor-course-student-edit-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.html
  src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.spec.ts
  src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.ts
  src/web/services/student.service.ts
Labels: s.ToMerge

#9905 [#9904] Update timezone database to 2019c
  src/main/resources/tzdb.dat
  src/web/data/timezone.json
Labels: p.High, s.ToReview

#9901 [#9898] All records page does not show profile picture
  src/web/app/pages-instructor/instructor-student-records-page/__snapshots__/instructor-student-records-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-student-records-page/instructor-student-records-page.component.spec.ts
  src/web/app/pages-instructor/instructor-student-records-page/instructor-student-records-page.component.ts
Labels: s.ToMerge

#9908 [#9906] Refactor Intent to be a type
  src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.ts
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.ts
  src/web/app/pages-instructor/instructor-pages.module.ts
  src/web/app/pages-instructor/instructor-session-base-page.component.ts
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts
  src/web/app/pages-session/session-result-page/session-result-page.component.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
  src/web/app/pages-student/student-pages.module.ts
  src/web/app/pages.module.ts
  src/web/types/Intent.ts
Labels: s.ToMerge

#9909 [#9902] Replace src/web/types/gender.ts with Gender in api-output.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.spec.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.ts
  src/web/app/pages-instructor/instructor-course-student-details-page/instructor-course-student-details-page.component.spec.ts
  src/web/app/pages-instructor/student-profile/student-profile.component.ts
  src/web/app/pages-instructor/student-profile/student-profile.ts
  src/web/app/pages-student/student-course-details-page/student-course-details-page.component.spec.ts
  src/web/app/pages-student/student-course-details-page/student-course-details-page.component.ts
  src/web/app/pages-student/student-profile-page/student-profile-gender.pipe.ts
  src/web/app/pages-student/student-profile-page/student-profile-page.component.spec.ts
  src/web/app/pages-student/student-profile-page/student-profile-page.component.ts
  src/web/types/gender.ts
Labels: s.ToMerge

#9910 [#9761] Feedback Session Edit: Button names should be more appropriate
  src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap
  src/web/app/components/question-edit-form/question-edit-form.component.html
  src/web/app/components/question-edit-form/question-edit-form.component.spec.ts
Labels: s.ToMerge

#9914 [#9911] Auto-sync API output type: ConfirmationResponse
  src/main/java/teammates/ui/webapi/action/ConfirmFeedbackSessionSubmissionAction.java
  src/main/java/teammates/ui/webapi/output/ConfirmationResponse.java
  src/main/java/teammates/ui/webapi/output/ConfirmationResult.java
  src/test/java/teammates/test/cases/webapi/ConfirmFeedbackSessionSubmissionActionTest.java
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
Labels: s.ToMerge

#9863 [#9862] Update third-party dependencies
  .travis.yml
  angular.json
  appveyor.yml
  browserslist
  build.gradle
  docs/setting-up.md
  gradle.template.properties
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  jest.config.js
  package.json
  src/main/java/teammates/common/datatransfer/TeamEvalResult.java
  src/main/java/teammates/common/datatransfer/attributes/EntityAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/FeedbackQuestionAttributes.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackContributionResponseDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackResponseDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRubricResponseDetails.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/logic/core/SendgridService.java
  src/main/java/teammates/storage/entity/FeedbackResponseComment.java
  src/main/java/teammates/ui/controller/Action.java
  src/main/java/teammates/ui/controller/ActionResult.java
  src/main/java/teammates/ui/controller/RedirectResult.java
  src/main/java/teammates/ui/pagedata/PageData.java
  src/test/java/teammates/test/cases/action/BaseActionTest.java
  src/test/java/teammates/test/cases/logic/EmailSenderTest.java
  src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
  src/test/java/teammates/test/cases/webapi/GetTimeZonesActionTest.java
  src/test/java/teammates/test/pageobjects/AppPage.java
  src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap
  src/web/app/components/question-responses/gqr-rqg-view-responses/gqr-rqg-view-responses.component.ts
  src/web/app/components/question-responses/grq-rgq-view-responses/grq-rgq-view-responses.component.ts
  src/web/app/components/question-types/question-edit-answer-form/mcq-question-edit-answer-form.component.ts
  src/web/app/components/question-types/question-edit-answer-form/msq-question-edit-answer-form.component.ts
  src/web/app/components/sessions-table/__snapshots__/sessions-table.component.spec.ts.snap
  src/web/app/pages-help/instructor-help-page/instructor-help-page.component.ts
  src/web/app/pages-help/session-links-recovery/session-links-recovery-page.component.ts
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.scss
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts
  src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.scss
  src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-courses-page/add-course-form/add-course-form.component.ts
  src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
  src/web/app/pages-student/student-profile-page/student-profile-page.component.scss
  src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.ts
  src/web/browserslist
  src/web/polyfills.ts
  src/web/tsconfig.app.json
  src/web/tsconfig.tslint-spec.json
  static-analysis/teammates-checkstyle-suppressions.xml
  static-analysis/teammates-checkstyle.xml
  static-analysis/teammates-pmd-6.14.0.xml
  static-analysis/teammates-pmd.xml
  static-analysis/teammates-stylelint.yml
  static-analysis/teammates-tslint.yml
  tsconfig.app.json
  tsconfig.json
  tsconfig.spec.json
Labels: s.ToMerge

#9827 [#9595] Migrate GET /student/courses to RESTFul API
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/webapi/action/ActionFactory.java
  src/main/java/teammates/ui/webapi/action/GetHasResponsesAction.java
  src/main/java/teammates/ui/webapi/action/GetStudentCoursesAction.java
  src/main/java/teammates/ui/webapi/output/FeedbackSessionData.java
  src/test/java/teammates/test/cases/webapi/GetFeedbackSessionsActionTest.java
  src/test/java/teammates/test/cases/webapi/GetHasResponsesActionTest.java
  src/test/java/teammates/test/cases/webapi/GetStudentCoursesActionTest.java
  src/web/app/pages-student/student-home-page/__snapshots__/student-home-page.component.spec.ts.snap
  src/web/app/pages-student/student-home-page/student-home-page.component.html
  src/web/app/pages-student/student-home-page/student-home-page.component.scss
  src/web/app/pages-student/student-home-page/student-home-page.component.spec.ts
  src/web/app/pages-student/student-home-page/student-home-page.component.ts
  src/web/app/pages-student/student-home-page/student-home-page.module.ts
  src/web/services/course.service.ts
  src/web/services/feedback-sessions.service.ts
Labels: s.ToMerge

#9916 [#9841] Instructor/Courses: Courses recycle bin table overflow if text is too long
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.html
Labels: s.ToMerge

#9922 [#9920] Don't load all courses again when deleting/archiving courses in InstructorHomePageComponent
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.ts
Labels: s.ToMerge

#9926 [#9679] Instructor: Preview Sessions Submission Page's navbar covers some content on the page
  src/web/app/pages-session/session-submission-page/session-submission-page.component.html
  src/web/app/pages-session/session-submission-page/session-submission-page.component.scss
Labels: s.ToMerge

#9928 [#9903] Replace src/web/app/pages-instructor/student-profile/student-profile.ts with StudentProfile in api-output.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.spec.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.ts
  src/web/app/pages-instructor/instructor-course-student-details-page/instructor-course-student-details-page.component.spec.ts
  src/web/app/pages-instructor/student-profile/student-profile.component.ts
  src/web/app/pages-instructor/student-profile/student-profile.ts
Labels: s.ToMerge

#9924 [#9886] Login Dropdown List is Not Positioned Properly
  src/web/app/page.component.html
Labels: s.ToMerge
