Repository TEAMMATES/teammates, pull requests merged in 2020-08, with the labels that each got.

#10507 [#10506] User cannot join multiple courses
  src/main/java/teammates/ui/webapi/action/GetCourseJoinStatusAction.java
  src/test/java/teammates/test/cases/webapi/GetCourseJoinStatusActionTest.java
  src/web/app/user-join-page.component.ts
Labels: s.ToMerge

#10519 [#10517] Preview as instructor link not working
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.html
Labels: s.ToMerge

#10503 [#10409] [#10418] [#10447] [#10502] UAT Round 4 Fix: Loading indicators and placeholder text
  src/web/app/components/session-edit-form/session-edit-form.component.html
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-edit-panel/instructor-edit-panel.component.html
  src/web/app/pages-instructor/instructor-search-page/__snapshots__/instructor-search-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-search-page/instructor-search-page.component.html
  src/web/app/pages-instructor/instructor-search-page/instructor-search-page.component.ts
  src/web/app/pages-instructor/instructor-search-page/instructor-search-page.module.ts
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.html
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.component.html
  src/web/styles.scss
Labels: s.ToMerge

#10399 [#10243] Button style changes
  src/web/app/components/comment-box/comment-edit-form/comment-edit-form.component.html
  src/web/app/components/comment-box/comment-row/comment-row.component.html
  src/web/app/components/comment-box/comment-row/comment-row.component.scss
  src/web/app/components/comment-box/comment-table/comment-table.component.html
  src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap
  src/web/app/components/question-edit-form/question-edit-form.component.html
  src/web/app/components/question-edit-form/question-edit-form.component.scss
  src/web/app/components/question-responses/gqr-rqg-view-responses/gqr-rqg-view-responses.component.html
  src/web/app/components/question-responses/grouped-responses/grouped-responses.component.html
  src/web/app/components/question-responses/grq-rgq-view-responses/grq-rgq-view-responses.component.html
  src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.html
  src/web/app/components/question-submission-form/question-submission-form.component.html
  src/web/app/components/question-submission-form/question-submission-form.component.scss
  src/web/app/components/session-edit-form/session-edit-form.component.html
  src/web/app/components/session-edit-form/session-edit-form.component.scss
  src/web/app/components/sessions-recycle-bin-table/sessions-recycle-bin-table.component.html
  src/web/app/components/sessions-recycle-bin-table/sessions-recycle-bin-table.component.scss
  src/web/app/components/sessions-table/sessions-table.component.scss
  src/web/app/components/student-list/__snapshots__/student-list.component.spec.ts.snap
  src/web/app/components/student-list/student-list.component.html
  src/web/app/pages-admin/admin-sessions-page/admin-sessions-page.component.html
  src/web/app/pages-instructor/instructor-course-details-page/__snapshots__/instructor-course-details-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.html
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.html
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-edit-panel/instructor-edit-panel.component.html
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.html
  src/web/app/pages-instructor/instructor-course-student-edit-page/__snapshots__/instructor-course-student-edit-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.html
  src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-courses-page/add-course-form/__snapshots__/add-course-form.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-courses-page/add-course-form/add-course-form.component.html
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.html
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.scss
  src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.scss
  src/web/app/pages-instructor/instructor-search-page/__snapshots__/instructor-search-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.scss
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.scss
  src/web/app/pages-instructor/instructor-session-result-page/response-moderation-button/response-moderation-button.component.html
  src/web/app/pages-instructor/instructor-session-result-page/response-moderation-button/response-moderation-button.component.scss
  src/web/app/pages-instructor/instructor-session-result-page/response-moderation-button/response-moderation-button.component.ts
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.html
  src/web/app/pages-session/session-submission-page/session-submission-page.component.html
  src/web/app/pages-student/student-home-page/__snapshots__/student-home-page.component.spec.ts.snap
  src/web/app/pages-student/student-home-page/student-home-page.component.html
  src/web/app/pages-student/student-profile-page/__snapshots__/student-profile-page.component.spec.ts.snap
  src/web/app/pages-student/student-profile-page/student-profile-page.component.html
  src/web/app/pages-student/student-profile-page/student-profile-page.component.scss
  src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.scss
  src/web/styles.scss
Labels: s.FinalReview

#10541 [#10528] [#10529] [#10531] [#10533] UAT round 5: statistics-related fixes
  src/web/app/components/question-types/question-additional-info/__snapshots__/mcq-question-additional-info.component.spec.ts.snap
  src/web/app/components/question-types/question-additional-info/__snapshots__/msq-question-additional-info.component.spec.ts.snap
  src/web/app/components/question-types/question-additional-info/mcq-question-additional-info.component.html
  src/web/app/components/question-types/question-additional-info/msq-question-additional-info.component.html
  src/web/app/components/question-types/question-additional-info/msq-question-additional-info.component.spec.ts
  src/web/app/components/question-types/question-edit-details-form/mcq-question-edit-details-form.component.spec.ts
  src/web/app/components/question-types/question-edit-details-form/msq-question-edit-details-form.component.spec.ts
  src/web/app/components/question-types/question-edit-details-form/question-edit-details-form.module.ts
  src/web/app/components/question-types/question-response/rubric-question-response.component.html
  src/web/app/components/question-types/question-response/rubric-question-response.component.scss
  src/web/app/components/question-types/question-statistics/question-statistics-calculation/constsum-options-question-statistics-calculation.ts
  src/web/app/components/question-types/question-statistics/question-statistics-calculation/constsum-recipients-question-statistics-calculation.ts
  src/web/app/components/question-types/question-statistics/question-statistics-calculation/msq-question-statistics-calculation.ts
  src/web/app/components/question-types/question-statistics/question-statistics-calculation/rank-options-question-statistics-calculation.ts
  src/web/app/components/question-types/question-statistics/question-statistics-calculation/rank-recipients-question-statistics-calculation.ts
  src/web/app/components/teammates-common/generated-choice.pipe.spec.ts
  src/web/app/components/teammates-common/generated-choice.pipe.ts
  src/web/app/components/teammates-common/teammates-common.module.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.ts
  src/web/types/question-details-impl/feedback-contribution-question-details.impl.ts
Labels: s.ToMerge

#10538 [#10537] Fix respondent list sort
  src/web/app/components/sessions-table/respondent-list-info-table/respondent-list-info-table.component.html
  src/web/app/components/sessions-table/respondent-list-info-table/respondent-list-info-table.component.ts
  src/web/app/components/sessions-table/send-reminders-to-respondents-modal/send-reminders-to-respondents-modal.component.html
  src/web/app/components/sessions-table/send-reminders-to-respondents-modal/send-reminders-to-respondents-modal.component.scss
Labels: s.ToMerge

#10539 [#10526] Make delete session tooltips more detailed
  src/web/app/components/session-edit-form/session-edit-form.component.ts
  src/web/app/components/sessions-table/sessions-table.component.ts
Labels: s.ToMerge

#10540 [#10349] Prevent tooltip from showing on focus
  src/web/app/app.component.ts
Labels: s.ToMerge

#10542 [#10446] Course instructor edit detail: Styling fixes
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.html
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.scss
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.ts
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-edit-panel/instructor-edit-panel.component.html
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-edit-panel/instructor-edit-panel.component.scss
Labels: s.ToMerge

#10548 [#10415] [#10416] [#10417] No response panel related fixes
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.ts
Labels: s.ToMerge

#10546 [#10522] Manually add underline to tooltips
  src/web/app/components/comment-box/comment-edit-form/comment-edit-form.component.html
  src/web/app/components/comment-box/comment-row/comment-row.component.html
  src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap
  src/web/app/components/question-edit-form/question-edit-form.component.html
  src/web/app/components/question-submission-form/question-submission-form.component.html
  src/web/app/components/question-types/question-edit-details-form/constsum-options-question-edit-details-form.component.html
  src/web/app/components/question-types/question-edit-details-form/constsum-recipients-question-edit-details-form.component.html
  src/web/app/components/question-types/question-edit-details-form/num-scale-question-edit-details-form.component.html
  src/web/app/components/question-types/question-edit-details-form/rubric-question-edit-details-form.component.html
  src/web/app/components/question-types/question-edit-details-form/text-question-edit-details-form.component.html
  src/web/app/components/question-types/question-edit-details-form/text-question-edit-details-form.component.scss
  src/web/app/components/question-types/question-statistics/contribution-question-statistics/contribution-question-statistics.component.html
  src/web/app/components/question-types/question-statistics/contribution-question-statistics/contribution.component.html
  src/web/app/components/question-types/question-statistics/rubric-question-statistics.component.html
  src/web/app/components/session-edit-form/session-edit-form.component.html
  src/web/app/components/sessions-recycle-bin-table/sessions-recycle-bin-table.component.html
  src/web/app/components/sessions-table/__snapshots__/sessions-table.component.spec.ts.snap
  src/web/app/components/sessions-table/sessions-table.component.html
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.html
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-edit-panel/instructor-edit-panel.component.html
  src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-courses-page/add-course-form/__snapshots__/add-course-form.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-courses-page/add-course-form/add-course-form.component.html
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.html
  src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.html
  src/web/app/pages-student/student-profile-page/__snapshots__/student-profile-page.component.spec.ts.snap
  src/web/app/pages-student/student-profile-page/student-profile-page.component.html
  src/web/styles.scss
Labels: s.ToMerge

#10547 [#10510][#10346][#10463] Styling fixes
  src/web/app/components/question-submission-form/question-submission-form.component.html
  src/web/app/components/question-types/question-edit-answer-form/num-scale-question-edit-answer-form.component.html
  src/web/app/components/question-types/question-edit-answer-form/rank-recipients-question-edit-answer-form.component.html
  src/web/app/components/question-types/question-edit-answer-form/rank-recipients-question-edit-answer-form.component.scss
  src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
  src/web/app/pages-instructor/instructor-search-page/__snapshots__/instructor-search-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-search-page/student-result-table/student-result-table.component.html
  src/web/app/pages-instructor/instructor-search-page/student-result-table/student-result-table.component.scss
  src/web/styles.scss
Labels: s.ToMerge

#10552 [#10505] Render tinymce only if in viewport
  jest-setup.ts
  package-lock.json
  package.json
  src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap
  src/web/app/components/rich-text-editor/rich-text-editor.component.html
  src/web/app/components/rich-text-editor/rich-text-editor.component.ts
  src/web/app/components/rich-text-editor/rich-text-editor.module.ts
  src/web/polyfills.ts
Labels: s.ToMerge

#10551 [#10518] [#10391] Animation fixes
  src/web/app/components/question-responses/grq-rgq-view-responses/grq-rgq-view-responses.component.html
  src/web/app/components/question-responses/grq-rgq-view-responses/grq-rgq-view-responses.component.ts
  src/web/app/pages-help/session-links-recovery/session-links-recovery-page.component.html
  src/web/app/pages-help/session-links-recovery/session-links-recovery-page.component.spec.ts
  src/web/app/pages-help/session-links-recovery/session-links-recovery-page.component.ts
  src/web/app/pages-help/session-links-recovery/session-links-recovery-page.module.ts
Labels: s.ToMerge

#10554 [#10533] Fix animation at instructor help page
  src/web/app/pages-help/instructor-help-page/instructor-help-panel/collapse-anim.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.html
Labels: s.ToMerge

#10543 [#10509] [#10524] [#10525] [#10535] Add loading indicators when fetching data
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.html
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.component.html
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
Labels: s.ToMerge

#10557 [#10354] [#10428] [#10511] [#10530] [#10545] UAT round 5 fixes: miscellaneous
  src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.html
  src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.scss
  src/web/app/components/question-types/question-statistics/question-statistics-calculation/mcq-question-statistics-calculation.ts
  src/web/app/components/question-types/question-statistics/question-statistics-calculation/msq-question-statistics-calculation.ts
  src/web/app/components/question-types/question-statistics/question-statistics-calculation/num-scale-question-statistics-calculation.ts
  src/web/app/components/question-types/question-statistics/question-statistics-calculation/rubric-question-statistics-calculation.ts
  src/web/app/components/sessions-table/sessions-table.component.scss
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
  src/web/services/__snapshots__/session-result-csv.service.spec.ts.snap
  src/web/styles.scss
Labels: s.ToMerge

#10558 [#10428] Remove excessive toast showing in submission page
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
Labels: s.FinalReview

#10563 [#10559] Pages with rich text editors cannot be displayed
  angular.json
  package-lock.json
  package.json
  src/web/index.html
Labels: s.ToMerge

#10566 [#10565] Instructor course details page: fix sortable header for student table
  src/web/app/pages-instructor/instructor-course-details-page/__snapshots__/instructor-course-details-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.html
  src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.ts
Labels: s.ToMerge

#10583 [#10574] [#10575] [#10576] Fix back-end related issues
  src/main/java/teammates/common/util/FieldValidator.java
  src/main/java/teammates/logic/core/StudentsLogic.java
  src/main/java/teammates/storage/api/FeedbackSessionsDb.java
  src/main/java/teammates/ui/webapi/action/GetStudentProfileAction.java
  src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
  src/test/java/teammates/test/cases/util/FieldValidatorTest.java
  src/test/java/teammates/test/cases/webapi/GetOngoingSessionsActionTest.java
  src/test/java/teammates/test/cases/webapi/GetStudentProfileActionTest.java
  src/test/java/teammates/test/cases/webapi/UpdateStudentProfileActionTest.java
Labels: s.ToMerge

#10571 [#10570] Fix redirect banner dismiss button
  src/web/app/components/redirect-banner/redirect-banner.component.html
  src/web/app/components/redirect-banner/redirect-banner.component.ts
Labels: s.ToMerge

#10236 [#9536] Instructor Feedback Edit Page E2E Test
  src/e2e/java/teammates/e2e/cases/BaseTestCaseWithBackDoorApiAccess.java
  src/e2e/java/teammates/e2e/cases/e2e/InstructorFeedbackEditPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/AppPage.java
  src/e2e/java/teammates/e2e/pageobjects/FeedbackSubmitPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java
  src/e2e/java/teammates/e2e/util/BackDoor.java
  src/e2e/resources/data/InstructorFeedbackEditPageE2ETest.json
  src/e2e/resources/testng-e2e.xml
  src/test/java/teammates/test/cases/BaseTestCaseWithDatastoreAccess.java
  src/test/resources/data/InstructorFeedbackEditCopyTest.json
  src/test/resources/data/InstructorFeedbackEditPageUiTest.json
  src/web/app/components/copy-session-modal/__snapshots__/copy-session-modal.component.spec.ts.snap
  src/web/app/components/copy-session-modal/copy-session-modal.component.html
  src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap
  src/web/app/components/question-edit-form/question-edit-form.component.html
  src/web/app/components/session-edit-form/session-edit-form.component.html
  src/web/app/pages-instructor/instructor-session-edit-page/copy-questions-from-other-sessions-modal/copy-questions-from-other-sessions-modal.component.html
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.html
  src/web/app/pages-instructor/instructor-session-edit-page/template-question-modal/template-question-modal.component.html
  src/web/app/pages-session/session-submission-page/session-submission-page.component.html
Labels: s.ToMerge

#10567 [#10562][#10520][#10514][#10515][#10513][#10512][#10536] Minor UI fixes
  src/web/app/components/student-list/student-list.component.html
  src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.scss
  src/web/app/pages-instructor/instructor-search-page/__snapshots__/instructor-search-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-search-page/instructor-search-bar/instructor-search-bar.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.scss
  src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.html
  src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.scss
Labels: s.ToMerge

#10596 [#10577] [#10582] [#10585] [#10587] [#10588] [#10589] Fix front-end related issues
  src/main/java/teammates/common/datatransfer/questions/FeedbackNumericalScaleResponseDetails.java
  src/web/app/components/question-edit-form/question-edit-form.component.ts
  src/web/app/components/question-types/question-edit-answer-form/num-scale-question-edit-answer-form.component.ts
  src/web/app/components/question-types/question-edit-details-form/mcq-field/mcq-field.component.html
  src/web/app/components/question-types/question-edit-details-form/mcq-question-edit-details-form.component.ts
  src/web/app/components/question-types/question-edit-details-form/msq-field/msq-field.component.html
  src/web/app/components/question-types/question-edit-details-form/msq-question-edit-details-form.component.html
  src/web/app/components/question-types/question-edit-details-form/msq-question-edit-details-form.component.ts
  src/web/app/components/question-types/question-edit-details-form/num-scale-question-edit-details-form.component.html
  src/web/app/components/question-types/question-edit-details-form/num-scale-question-edit-details-form.component.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.html
  src/web/app/pages-instructor/instructor-comments.component.ts
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts
  src/web/app/pages-instructor/instructor-student-records-page/__snapshots__/instructor-student-records-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-student-records-page/instructor-student-records-page.component.html
  src/web/app/pages-instructor/instructor-student-records-page/instructor-student-records-page.component.ts
  src/web/app/pages-instructor/student-profile/course-related-info/course-related-info.component.html
  src/web/app/pages-instructor/student-profile/course-related-info/course-related-info.component.ts
  src/web/services/feedback-questions.service.ts
Labels: s.ToMerge

#10601 [#10600] Update tinymce to 5.4.1
  angular.json
  package-lock.json
  package.json
Labels: s.ToMerge

#10599 [#7594] design.md: update content and diagrams and remove unnecessary DTOs
  docs/design.md
  docs/images/CommonComponent.png
  docs/images/CommonComponent.pptx
  docs/images/E2EComponent.png
  docs/images/E2EComponent.pptx
  docs/images/StorageClassDiagram.png
  docs/images/StorageClassDiagram.pptx
  docs/images/StorageComponent.png
  docs/images/StorageComponent.pptx
  docs/images/UiComponent.png
  docs/images/UiComponent.pptx
  docs/images/dataTransferClasses.png
  docs/images/dataTransferClasses.pptx
  docs/images/highlevelArchitecture.png
  docs/images/highlevelArchitecture.pptx
  docs/images/packageDiagram.png
  docs/images/packageDiagram.pptx
  src/main/java/teammates/common/datatransfer/FeedbackSessionDetailsBundle.java
  src/main/java/teammates/common/datatransfer/FeedbackSessionStats.java
  src/main/java/teammates/common/datatransfer/StudentResultSummary.java
  src/main/java/teammates/common/datatransfer/TeamDetailsBundle.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetails.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/CoursesLogic.java
  src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
  src/main/java/teammates/logic/core/FeedbackResponseCommentsLogic.java
  src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/ui/webapi/action/GetSessionResponseStatsAction.java
  src/test/java/teammates/test/cases/logic/CoursesLogicTest.java
  src/test/java/teammates/test/cases/webapi/UpdateFeedbackQuestionActionTest.java
Labels: s.ToMerge

#10608 [#10584] [#10606] [#10607] Fix MSQ question settings and modal scroll
  src/main/java/teammates/common/datatransfer/questions/FeedbackMsqResponseDetails.java
  src/web/app/components/question-types/question-constraint/msq-question-constraint.component.html
  src/web/styles.scss
Labels: s.ToMerge

#10611 [#10593] Disable view/download session results button according to instructor privilege
  src/web/app/components/sessions-table/__snapshots__/sessions-table.component.spec.ts.snap
  src/web/app/components/sessions-table/sessions-table.component.html
  src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
Labels: s.ToMerge

#10617 [#10614][#10616] Fix session results page issues
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.scss
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts
Labels: s.ToMerge

#10521 [#9536] Instructor Feedback Sessions Page E2E Test
  .gitignore
  src/e2e/java/teammates/e2e/cases/e2e/BaseE2ETestCase.java
  src/e2e/java/teammates/e2e/cases/e2e/InstructorFeedbackSessionsPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/Browser.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackSessionsPage.java
  src/e2e/java/teammates/e2e/util/BackDoor.java
  src/e2e/java/teammates/e2e/util/EmailAccount.java
  src/e2e/java/teammates/e2e/util/TestProperties.java
  src/e2e/resources/data/InstructorFeedbackSessionsPageE2ETest.json
  src/e2e/resources/testng-e2e.xml
  src/main/java/teammates/ui/webapi/action/GetFeedbackSessionAction.java
  src/web/app/components/session-edit-form/session-edit-form.component.html
  src/web/app/components/sessions-recycle-bin-table/sessions-recycle-bin-table.component.html
  src/web/app/components/sessions-table/__snapshots__/sessions-table.component.spec.ts.snap
  src/web/app/components/sessions-table/resend-results-link-to-respondent-modal/resend-results-link-to-respondent-modal.component.html
  src/web/app/components/sessions-table/respondent-list-info-table/respondent-list-info-table.component.html
  src/web/app/components/sessions-table/send-reminders-to-respondents-modal/send-reminders-to-respondents-modal.component.html
  src/web/app/components/sessions-table/sessions-table.component.html
  src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-sessions-page/copy-from-other-sessions-modal/copy-from-other-sessions-modal.component.html
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.html
  src/web/app/pages-instructor/instructor-sessions-page/session-permanent-deletion-confirm-modal/session-permanent-deletion-confirm-modal.component.html
  src/web/app/pages-instructor/instructor-sessions-page/sessions-permanent-deletion-confirm-modal/sessions-permanent-deletion-confirm-modal.component.html
Labels: s.ToMerge

#10609 [#10604] in JsonUtils.java parse method could be static
  src/main/java/teammates/common/util/JsonUtils.java
Labels: s.ToMerge

#10620 [#10397] Create API for receiving all responses of a feedback question
  src/main/java/teammates/common/datatransfer/questions/FeedbackConstantSumQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackConstantSumResponseDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackContributionResponseDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackMcqQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackMcqResponseDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackMsqQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackMsqResponseDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackNumericalScaleQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackNumericalScaleResponseDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRankOptionsQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRankOptionsResponseDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRankQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRankRecipientsQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRankRecipientsResponseDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackResponseDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRubricResponseDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackTextQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackTextResponseDetails.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/ui/webapi/action/ActionFactory.java
  src/main/java/teammates/ui/webapi/action/BasicFeedbackSubmissionAction.java
  src/main/java/teammates/ui/webapi/action/CreateFeedbackResponseAction.java
  src/main/java/teammates/ui/webapi/action/DeleteFeedbackResponseAction.java
  src/main/java/teammates/ui/webapi/action/SubmitFeedbackResponsesAction.java
  src/main/java/teammates/ui/webapi/action/UpdateFeedbackResponseAction.java
  src/main/java/teammates/ui/webapi/endpoints/ResourceEndpoints.java
  src/main/java/teammates/ui/webapi/request/FeedbackResponseBasicRequest.java
  src/main/java/teammates/ui/webapi/request/FeedbackResponseCreateRequest.java
  src/main/java/teammates/ui/webapi/request/FeedbackResponseUpdateRequest.java
  src/main/java/teammates/ui/webapi/request/FeedbackResponsesRequest.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackConstantSumQuestionDetailsTest.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackMsqQuestionDetailsTest.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackMsqResponseDetailsTest.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackRubricQuestionDetailsTest.java
  src/test/java/teammates/test/cases/datatransfer/FeedbackRubricResponseDetailsTest.java
  src/test/java/teammates/test/cases/webapi/CreateFeedbackResponseActionTest.java
  src/test/java/teammates/test/cases/webapi/DeleteFeedbackResponseActionTest.java
  src/test/java/teammates/test/cases/webapi/UpdateFeedbackResponseActionTest.java
  src/web/app/components/question-types/question-additional-info/constsum-options-question-additional-info.component.html
  src/web/app/components/question-types/question-additional-info/constsum-recipients-question-additional-info.component.html
  src/web/app/components/question-types/question-edit-answer-form/constsum-options-question-edit-answer-form.component.ts
  src/web/app/components/question-types/question-edit-answer-form/constsum-recipients-question-edit-answer-form.component.html
  src/web/app/components/question-types/question-edit-answer-form/constsum-recipients-question-edit-answer-form.component.ts
  src/web/app/components/question-types/question-edit-answer-form/mcq-question-edit-answer-form.component.ts
  src/web/app/components/question-types/question-edit-answer-form/num-scale-question-edit-answer-form.component.ts
  src/web/app/components/question-types/question-edit-answer-form/rubric-question-edit-answer-form.component.ts
  src/web/app/components/question-types/question-instruction/constsum-options-question-instruction.component.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
  src/web/services/feedback-responses.service.ts
Labels: s.ToMerge

#10398 [#10397] Add frontend validation for feedback submission
  src/web/app/components/question-submission-form/question-submission-form-model.ts
  src/web/app/components/question-submission-form/question-submission-form.component.html
  src/web/app/components/question-submission-form/question-submission-form.component.ts
  src/web/app/components/question-types/question-constraint/constsum-recipients-question-constraint.component.html
  src/web/app/components/question-types/question-constraint/constsum-recipients-question-constraint.component.ts
  src/web/app/components/question-types/question-constraint/contribution-question-constraint.component.ts
  src/web/app/components/question-types/question-constraint/msq-question-constraint.component.ts
  src/web/app/components/question-types/question-constraint/num-scale-question-constraint.component.ts
  src/web/app/components/question-types/question-constraint/question-constraint.component.ts
  src/web/app/components/question-types/question-constraint/rank-recipients-question-constraint.component.ts
  src/web/app/components/question-types/question-constraint/text-question-constraint.component.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-data.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
Labels: s.ToMerge

#10639 [#10638] Add guard clause to recipient submission form model update
  src/web/app/components/question-submission-form/question-submission-form.component.ts
Labels: c.Bug, s.ToMerge

#10641 [#9936] Add logging and swap if condition order for expensive operation
  src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
Labels: c.Bug, s.ToMerge

#10636 [#10635] Remove extra comma from angular json
  angular.json
  package.json
Labels: c.Task, s.ToMerge

#10643 [#10642] Update developers.json
  src/web/data/developers.json
Labels: c.Task

#10644 [#10630] Typo mistake
  src/main/java/teammates/logic/api/EmailGenerator.java
Labels: c.Bug, s.ToMerge

#10602 [#10516] Features page: reduce indentation
  src/web/app/pages-static/features-page/features-page.component.html
  src/web/app/pages-static/features-page/features-page.component.scss
Labels: c.Bug, s.ToMerge

#10661 [#10647] Improve student results page statistics for self-evaluation
  src/main/java/teammates/ui/webapi/output/SessionResultsData.java
  src/web/app/components/question-types/question-statistics/num-scale-question-statistics.component.html
  src/web/app/components/question-types/question-statistics/rubric-question-statistics.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.html
  src/web/app/pages-session/session-result-page/session-result-page.component.html
Labels: s.ToMerge

#10660 [#10658] Do not reset feedback responses for question
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/ui/webapi/action/SubmitFeedbackResponsesAction.java
Labels: s.ToMerge

#10637 [#10634] Run component tests only once in CI
  build.gradle
  docs/CONTRIBUTING.md
  docs/development.md
  docs/glossary.md
  docs/process.md
  docs/troubleshooting-guide.md
  src/test/java/teammates/test/cases/automated/FeedbackSessionClosingRemindersActionTest.java
  src/test/java/teammates/test/cases/logic/AccountsLogicTest.java
  src/test/java/teammates/test/cases/logic/FeedbackSessionsLogicTest.java
  src/test/java/teammates/test/cases/storage/FeedbackQuestionsDbTest.java
  src/test/java/teammates/test/cases/storage/FeedbackResponsesDbTest.java
  src/test/java/teammates/test/cases/storage/FeedbackSessionsDbTest.java
  src/test/java/teammates/test/cases/storage/StudentsDbTest.java
Labels: c.Task, s.ToMerge
