Repository TEAMMATES/teammates, pull requests merged in 2021-01, with the labels that each got.

#10889 [#10590] Add template question: Animation not smooth
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
  src/web/styles.scss
Labels: c.Feature, s.ToMerge

#10899 [#10825] Remove Const.StatusMessages, Const.StudentsLogicConst, Const.StatusCodes
  src/e2e/java/teammates/e2e/cases/BaseE2ETestCase.java
  src/e2e/java/teammates/e2e/cases/StudentProfilePageE2ETest.java
  src/main/java/teammates/common/datatransfer/attributes/AccountAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/CourseAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/FeedbackQuestionAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/FeedbackResponseAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/FeedbackResponseCommentAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/InstructorAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/StudentAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/StudentProfileAttributes.java
  src/main/java/teammates/common/util/Assumption.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/logic/core/CoursesLogic.java
  src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/logic/core/InstructorsLogic.java
  src/main/java/teammates/logic/core/StudentsLogic.java
  src/main/java/teammates/storage/api/AccountsDb.java
  src/main/java/teammates/storage/api/CoursesDb.java
  src/main/java/teammates/storage/api/EntitiesDb.java
  src/main/java/teammates/storage/api/FeedbackQuestionsDb.java
  src/main/java/teammates/storage/api/FeedbackResponseCommentsDb.java
  src/main/java/teammates/storage/api/FeedbackResponsesDb.java
  src/main/java/teammates/storage/api/FeedbackSessionsDb.java
  src/main/java/teammates/storage/api/InstructorsDb.java
  src/main/java/teammates/storage/api/ProfilesDb.java
  src/main/java/teammates/storage/api/StudentsDb.java
  src/main/java/teammates/ui/webapi/Action.java
  src/main/java/teammates/ui/webapi/BasicCommentSubmissionAction.java
  src/main/java/teammates/ui/webapi/CreateFeedbackResponseCommentAction.java
  src/main/java/teammates/ui/webapi/PostStudentProfilePictureAction.java
  src/main/java/teammates/ui/webapi/UpdateFeedbackResponseCommentAction.java
  src/main/java/teammates/ui/webapi/UpdateStudentAction.java
  src/main/java/teammates/ui/webapi/UpdateStudentProfileAction.java
  src/test/java/teammates/logic/core/CoursesLogicTest.java
  src/test/java/teammates/logic/core/InstructorsLogicTest.java
  src/test/java/teammates/logic/core/StudentsLogicTest.java
  src/test/java/teammates/storage/api/AccountsDbTest.java
  src/test/java/teammates/storage/api/CoursesDbTest.java
  src/test/java/teammates/storage/api/EntitiesDbTest.java
  src/test/java/teammates/storage/api/FeedbackQuestionsDbTest.java
  src/test/java/teammates/storage/api/FeedbackResponseCommentsDbTest.java
  src/test/java/teammates/storage/api/FeedbackResponsesDbTest.java
  src/test/java/teammates/storage/api/FeedbackSessionsDbTest.java
  src/test/java/teammates/storage/api/InstructorsDbTest.java
  src/test/java/teammates/storage/api/ProfilesDbTest.java
  src/test/java/teammates/storage/api/StudentsDbTest.java
  src/test/java/teammates/test/AbstractBackDoor.java
  src/test/java/teammates/test/BaseComponentTestCase.java
  src/test/java/teammates/test/BaseTestCaseWithDatastoreAccess.java
  src/test/java/teammates/ui/webapi/CreateFeedbackResponseCommentActionTest.java
  src/test/java/teammates/ui/webapi/EnrollStudentsActionTest.java
  src/test/java/teammates/ui/webapi/RestoreCourseActionTest.java
  src/test/java/teammates/ui/webapi/RestoreFeedbackSessionActionTest.java
  src/test/java/teammates/ui/webapi/UpdateFeedbackResponseCommentActionTest.java
  src/test/java/teammates/ui/webapi/UpdateStudentActionTest.java
Labels: c.Task, s.ToMerge

#10906 [#10901] Skip 'closing soon' emails if already submitted
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
  src/test/java/teammates/logic/api/EmailGeneratorTest.java
  src/test/java/teammates/ui/webapi/FeedbackSessionClosingRemindersActionTest.java
Labels: c.Feature, s.ToMerge

#10904 [#10825] Remove Const.FeedbackQuestion, Const.FeedbackQuestionTypeNames, Const.SystemParams
  src/e2e/java/teammates/e2e/cases/BaseE2ETestCase.java
  src/e2e/java/teammates/e2e/cases/InstructorFeedbackSessionsPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/AppPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java
  src/e2e/java/teammates/e2e/pageobjects/StudentFeedbackResultsPage.java
  src/main/java/teammates/common/datatransfer/FeedbackParticipantType.java
  src/main/java/teammates/common/datatransfer/attributes/StudentAttributes.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackConstantSumQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackMcqQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackMsqQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackNumericalScaleQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRankOptionsQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackTextQuestionDetails.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/common/util/FieldValidator.java
  src/main/java/teammates/common/util/FileHelper.java
  src/main/java/teammates/common/util/HttpRequest.java
  src/main/java/teammates/common/util/SanitizationHelper.java
  src/main/java/teammates/common/util/TimeHelper.java
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/ui/endpoints/ResourceEndpoints.java
  src/main/java/teammates/ui/webapi/CreateAccountAction.java
  src/main/java/teammates/ui/webapi/DatastoreBackupAction.java
  src/main/java/teammates/ui/webapi/LegacyUrlMapper.java
  src/main/java/teammates/ui/webapi/PostStudentProfilePictureAction.java
  src/test/java/teammates/common/datatransfer/attributes/FeedbackQuestionAttributesTest.java
  src/test/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributesTest.java
  src/test/java/teammates/common/datatransfer/attributes/StudentAttributesTest.java
  src/test/java/teammates/common/datatransfer/questions/FeedbackMcqQuestionDetailsTest.java
  src/test/java/teammates/common/datatransfer/questions/FeedbackMsqQuestionDetailsTest.java
  src/test/java/teammates/common/datatransfer/questions/FeedbackNumericalScaleQuestionDetailsTest.java
  src/test/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetailsTest.java
  src/test/java/teammates/logic/api/EmailGeneratorTest.java
  src/test/java/teammates/logic/core/FeedbackQuestionsLogicTest.java
  src/test/java/teammates/storage/api/FeedbackQuestionsDbTest.java
  src/test/java/teammates/test/AbstractBackDoor.java
  src/test/java/teammates/ui/webapi/ActionFactoryTest.java
  src/test/java/teammates/ui/webapi/CreateAccountActionTest.java
  src/test/java/teammates/ui/webapi/LegacyUrlMapperTest.java
Labels: c.Task, s.ToMerge

#10912 [#10909] Update developers.json
  src/web/data/developers.json
Labels: c.Task

#10900 [#9536] Improve E2E test stability and add test for searching response comments
  src/e2e/java/teammates/e2e/cases/InstructorFeedbackResultsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorSearchPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/TimezoneSyncerTest.java
  src/e2e/java/teammates/e2e/pageobjects/AppPage.java
  src/e2e/java/teammates/e2e/pageobjects/Browser.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorSearchPage.java
  src/e2e/resources/data/InstructorSearchPageE2ETest.json
  src/web/app/components/comment-box/comment-row/comment-row.component.html
  src/web/app/pages-instructor/instructor-search-page/comment-result-table/comment-result-table.component.html
Labels: c.Task, s.ToMerge

#10911 [#10809] Instructor editing sessions: Remove 'Done Editing' button
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.html
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.html
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
Labels: c.Feature, s.ToMerge

#10897 [#10532] Instructor view results: tweak icon-buttons
  src/web/app/components/comment-box/comment-row/comment-row.component.html
  src/web/app/components/question-responses/grouped-responses/grouped-responses.component.html
Labels: s.ToMerge

#10923 [#10922] Added top padding to Add All Instructors button
  src/web/app/pages-admin/admin-home-page/__snapshots__/admin-home-page.component.spec.ts.snap
  src/web/app/pages-admin/admin-home-page/admin-home-page.component.html
Labels: s.ToMerge

#10894 [#10504] Uncaught promise in modals
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
Labels: c.Bug, s.ToMerge

#10934 [#10933] Update timezone information
  src/main/resources/tzdb.dat
  src/web/data/timezone.json
Labels: c.Bug

#10884 [#10564] Feedback session question options: unable to select text by dragging cursor
  src/web/app/components/question-types/question-edit-details-form/constsum-options-field/constsum-options-field.component.html
  src/web/app/components/question-types/question-edit-details-form/constsum-options-question-edit-details-form.component.html
  src/web/app/components/question-types/question-edit-details-form/constsum-options-question-edit-details-form.component.scss
  src/web/app/components/question-types/question-edit-details-form/rank-options-field/rank-options-field.component.html
  src/web/app/components/question-types/question-edit-details-form/rank-options-question-edit-details-form.component.html
  src/web/app/components/question-types/question-edit-details-form/rank-options-question-edit-details-form.component.scss
Labels: c.Bug, s.ToMerge

#10916 [#9480] Add unit tests for feedback-path.pipe.spec.ts and question-edit-form-component.spec.ts
  src/web/app/components/question-edit-form/feedback-path.pipe.spec.ts
  src/web/app/components/question-edit-form/question-edit-form.component.spec.ts
Labels: c.Feature, s.ToMerge

#10927 [#10527] Student view responses: tweak spacing
  src/web/app/components/question-submission-form/question-submission-form.component.html
  src/web/app/components/question-submission-form/question-submission-form.component.scss
Labels: c.Feature, s.ToMerge

#10940 [#10939] Update developers.json and tzdb.dat
  src/main/resources/tzdb.dat
  src/web/data/developers.json
Labels: c.Task
