Repository TEAMMATES/teammates, pull requests merged in 2021-04, with the labels that each got.

#11027 [#11003] LnP tests for batch processing
  src/lnp/java/teammates/lnp/cases/BaseLNPTestCase.java
  src/lnp/java/teammates/lnp/cases/InstructorStudentCascadingUpdateLNPTest.java
  src/lnp/java/teammates/lnp/util/JMeterElements.java
  src/lnp/java/teammates/lnp/util/TestProperties.java
  src/lnp/resources/test.template.properties
Labels: c.Task, s.ToMerge

#11076 [#10950] Filter logs by student name and change default behaviour of form
  src/main/java/teammates/logic/core/GoogleCloudLoggingService.java
  src/main/java/teammates/ui/constants/ApiConst.java
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.html
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.ts
Labels: s.ToMerge

#11082 [#10950] Merge track session endpoint into session logs endpoint
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/constants/ResourceEndpoints.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/test/java/teammates/ui/webapi/CreateFeedbackSessionLogActionTest.java
  src/web/services/log.service.ts
Labels: s.FinalReview

#11089 [#11084] Remove error highlighting on a new enrollment
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts
Labels: s.ToMerge

#10876 [#10623] Change design diagrams from Powerpoint to PlantUML
  docs/diagrams/ClientComponent.puml
  docs/diagrams/CommonComponent.puml
  docs/diagrams/DataTransferClasses.puml
  docs/diagrams/E2EComponent.puml
  docs/diagrams/LogicComponent.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/StorageComponent.puml
  docs/diagrams/TestDriverComponent.puml
  docs/diagrams/UiComponent.puml
  docs/diagrams/UiWorkflow.puml
  docs/diagrams/packageDiagram.puml
  docs/diagrams/style.puml
  docs/images/ClientComponent.png
  docs/images/ClientComponent.pptx
  docs/images/CommonComponent.png
  docs/images/CommonComponent.pptx
  docs/images/E2EComponent.png
  docs/images/E2EComponent.pptx
  docs/images/LogicComponent.png
  docs/images/LogicComponent.pptx
  docs/images/StorageClassDiagram.png
  docs/images/StorageClassDiagram.pptx
  docs/images/StorageComponent.png
  docs/images/StorageComponent.pptx
  docs/images/TestDriverComponent.png
  docs/images/TestDriverComponent.pptx
  docs/images/UiComponent.png
  docs/images/UiComponent.pptx
  docs/images/UiWorkflow.png
  docs/images/UiWorkflow.pptx
  docs/images/dataTransferClasses.png
  docs/images/dataTransferClasses.pptx
  docs/images/packageDiagram.png
  docs/images/packageDiagram.pptx
Labels: s.ToMerge

#11081 [#11079] Migrate remaining usages of internal App Engine APIs
  build.gradle
  src/e2e/java/teammates/e2e/cases/SystemErrorEmailReportE2ETest.java
  src/main/java/teammates/common/util/Config.java
  src/main/java/teammates/ui/webapi/ActionResult.java
  src/main/java/teammates/ui/webapi/AdminExceptionTestAction.java
  src/main/java/teammates/ui/webapi/DatastoreBackupAction.java
  src/main/java/teammates/ui/webapi/JsonResult.java
  src/main/java/teammates/ui/webapi/OriginCheckFilter.java
  src/main/java/teammates/ui/webapi/WebApiServlet.java
  src/test/java/teammates/ui/webapi/WebApiServletTest.java
Labels: s.ToReview

#11092 [#11085] Instructor edit questions: tweak option order for generating answers from teams
  src/web/app/components/question-types/question-edit-details-form/mcq-question-edit-details-form.component.ts
  src/web/app/components/question-types/question-edit-details-form/msq-question-edit-details-form.component.ts
Labels: s.ToMerge

#11072 [#11053] Refactor datepicker with today button as a component
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackSessionsPage.java
  src/web/app/app.module.ts
  src/web/app/components/datepicker/datepicker.component.html
  src/web/app/components/datepicker/datepicker.component.scss
  src/web/app/components/datepicker/datepicker.component.spec.ts
  src/web/app/components/datepicker/datepicker.component.ts
  src/web/app/components/datepicker/datepicker.module.ts
  src/web/app/components/session-edit-form/session-edit-form.component.html
  src/web/app/components/session-edit-form/session-edit-form.component.scss
  src/web/app/components/session-edit-form/session-edit-form.module.ts
Labels: c.Task, s.ToMerge

#11098 [#11097] Return a better message for conflicting course ids
  src/main/java/teammates/ui/webapi/CreateCourseAction.java
  src/test/java/teammates/ui/webapi/CreateCourseActionTest.java
  src/web/app/components/toast/toast.component.html
Labels: c.Feature, s.ToMerge

#10975 [#10917] Fix unexpected behaviour when reverting to template feedback path
  src/web/app/components/question-edit-form/question-edit-form.component.ts
Labels: c.Bug, s.ToMerge

#11035 [#5704] Standardize You vs I in UI
  src/e2e/java/teammates/e2e/cases/InstructorFeedbackEditPageE2ETest.java
  src/main/resources/InstructorSampleData.json
  src/web/data/template-questions.json
  src/web/data/template-sessions.json
Labels: c.Feature, s.ToMerge

#11059 [#10433] Instructor view results: Use fixed-width floating numbers
  src/web/app/components/question-types/question-statistics/mcq-question-statistics.component.ts
Labels: c.Feature, s.ToMerge

#11104 [#11096] Navigate to today date on click
  src/web/app/components/datepicker/datepicker.component.html
  src/web/app/components/datepicker/datepicker.component.ts
Labels: c.Bug, s.ToMerge

#11066 [#11030] Batch download for session-table component
  src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.ts
  src/web/app/pages-instructor/instructor-session-base-page.component.ts
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
  src/web/app/pages-instructor/instructor-session-modal-page.component.ts
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.ts
Labels: c.Feature, s.ToMerge

#11090 [#10969] Add frontend tests for audit logs page
  src/web/app/pages-instructor/instructor-audit-logs-page/__snapshots__/instructor-audit-logs-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.html
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.spec.ts
Labels: c.Task, s.ToMerge

#11110 [#11109] Update developers
  src/web/data/developers.json
Labels: c.Task
