Repository TEAMMATES/teammates, pull requests merged in 2021-12, with the labels that each got.

#11479 [#11122] Audit logs: student list is empty
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.html
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.spec.ts
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.ts
Labels: c.Bug, s.FinalReview

#11462 [#11456] Unable to upload Profile Pictures on Local Machine
  src/main/java/teammates/logic/core/LocalFileStorageService.java
Labels: s.ToMerge, c.DevOps

#11264 [#11157] Improve error message for mismatching google accounts
  src/web/app/pages-session/session-result-page/session-result-page.component.spec.ts
  src/web/app/pages-session/session-result-page/session-result-page.component.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.component.spec.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
Labels: s.ToMerge, c.Feature

#11469 [#11463] Add other teams/students in section as option in feedback paths
  src/e2e/java/teammates/e2e/pageobjects/AppPage.java
  src/e2e/java/teammates/e2e/pageobjects/FeedbackSubmitPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java
  src/main/java/teammates/common/datatransfer/FeedbackParticipantType.java
  src/main/java/teammates/logic/core/CoursesLogic.java
  src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
  src/main/java/teammates/logic/core/FeedbackResponsesLogic.java
  src/main/java/teammates/logic/core/StudentsLogic.java
  src/main/java/teammates/storage/api/StudentsDb.java
  src/main/java/teammates/ui/output/SessionResultsData.java
  src/main/java/teammates/ui/webapi/BasicFeedbackSubmissionAction.java
  src/web/app/components/feedback-path-panel/feedback-path-panel.component.html
  src/web/app/components/teammates-common/feedback-path.pipe.spec.ts
  src/web/app/components/teammates-common/feedback-path.pipe.ts
  src/web/app/components/visibility-messages/visibility-entity-name.pipe.ts
  src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
  src/web/services/feedback-questions.service.ts
  src/web/services/visibility-state-machine.ts
Labels: s.ToMerge, c.Feature

#11500 [#11491] Update tzdb version to 2021e
  src/main/resources/tzdb.dat
  src/web/data/timezone.json
Labels: s.ToMerge, c.Task

#11501 [#11498] Downloading results: 'Ranks received' must be the last column
  src/web/services/__snapshots__/session-result-csv.service.spec.ts.snap
  src/web/types/question-details-impl/feedback-rank-recipients-question-details.impl.ts
Labels: c.Bug, s.ToMerge
