Repository TEAMMATES/teammates, pull requests merged in 2021-05, with the labels that each got.

#11125 [#11118] Update timezone database version to 2021a
  src/e2e/java/teammates/e2e/cases/TimezoneSyncerTest.java
  src/main/resources/tzdb.dat
  src/web/data/timezone.json
Labels: c.Task, s.ToMerge

#11113 [#11102] Add student email to dropdown in audit logs
  src/web/app/pages-instructor/instructor-audit-logs-page/__snapshots__/instructor-audit-logs-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.html
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.spec.ts
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.ts
Labels: c.Feature, s.ToMerge

#11117 [#11100] Add padding to no activity message for audit logs
  src/web/app/pages-instructor/instructor-audit-logs-page/__snapshots__/instructor-audit-logs-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.html
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.scss
Labels: c.Feature, s.ToMerge

#11114 [#11087] Instructor deleting all students: show a spinner
  src/web/app/pages-instructor/instructor-course-details-page/__snapshots__/instructor-course-details-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.html
  src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.ts
Labels: s.ToReview

#11128 [#11127] Feedback path for new question not inheriting respondent number
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
Labels: c.Bug, s.ToMerge

#10926 [#10920] Improve Front-End Testing for Course Edit Page
  src/web/app/pages-instructor/instructor-course-edit-page/__snapshots__/instructor-course-edit-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.spec.ts
Labels: c.Task, s.ToMerge

#10689 [#10612] Improve Mobile UI
  src/web/app/components/question-submission-form/question-submission-form.component.scss
  src/web/app/components/question-types/question-edit-answer-form/text-question-edit-answer-form.component.scss
  src/web/app/components/rich-text-editor/rich-text-editor.component.ts
  src/web/app/page.component.scss
  src/web/app/pages-session/session-submission-page/session-submission-page.component.html
  src/web/app/pages-session/session-submission-page/session-submission-page.component.scss
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
Labels: c.Feature, s.ToMerge

#11136 [#2673] Student: view responses: show response statistics of 'constant sum' questions
  src/web/app/components/question-responses/single-statistics/single-statistics.component.ts
  src/web/app/components/question-types/question-statistics/constsum-options-question-statistics.component.html
  src/web/app/components/question-types/question-statistics/constsum-recipients-question-statistics.component.html
Labels: c.Feature, s.ToMerge

#11129 [#11124] Instructor downloading session results: course/session details are repeated for each question
  src/web/app/pages-instructor/instructor-session-base-page.component.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts
  src/web/services/__snapshots__/session-result-csv.service.spec.ts.snap
  src/web/services/session-result-csv.service.ts
Labels: c.Bug, s.ToMerge

#10856 [#10851] Ensure editing email does not trigger EnrollException
  src/main/java/teammates/ui/webapi/UpdateStudentAction.java
Labels: c.Bug, s.ToMerge

#11142 [#11141] Update developers
  src/web/data/developers.json
Labels: c.Task, s.ToMerge

#11095 [#10969] E2E tests for Audit Logs
  src/e2e/java/teammates/e2e/cases/InstructorAuditLogsPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorAuditLogsPage.java
  src/e2e/java/teammates/e2e/pageobjects/StudentFeedbackSubmissionPage.java
  src/e2e/resources/data/InstructorAuditLogsPageE2ETest.json
  src/e2e/resources/testng-e2e.xml
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/logic/core/LocalLoggingService.java
  src/web/app/pages-instructor/instructor-audit-logs-page/__snapshots__/instructor-audit-logs-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.html
Labels: c.Task, s.ToMerge

#11155 [#11144] Update session link recovery search duration
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/web/app/pages-help/session-links-recovery/session-links-recovery-page.component.html
Labels: c.Feature, s.ToMerge

#10783 [#10621] Add per receipient overall stats to weighted rubric
  src/e2e/java/teammates/e2e/pageobjects/StudentFeedbackResultsPage.java
  src/web/app/components/question-types/question-statistics/rubric-question-statistics.component.html
  src/web/app/components/question-types/question-statistics/rubric-question-statistics.component.ts
  src/web/services/__snapshots__/session-result-csv.service.spec.ts.snap
  src/web/types/question-details-impl/feedback-rubric-question-details.impl.ts
Labels: c.Feature, s.ToMerge

#11077 [#11071] Return HasResponses for all sessions in a course to reduce QPS
  src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
  src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/storage/api/FeedbackQuestionsDb.java
  src/main/java/teammates/ui/output/HasResponsesData.java
  src/main/java/teammates/ui/webapi/GetHasResponsesAction.java
  src/test/java/teammates/ui/webapi/GetHasResponsesActionTest.java
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts
  src/web/app/pages-student/student-home-page/__snapshots__/student-home-page.component.spec.ts.snap
  src/web/app/pages-student/student-home-page/student-home-page.component.spec.ts
  src/web/app/pages-student/student-home-page/student-home-page.component.ts
  src/web/services/feedback-sessions.service.ts
Labels: s.Ongoing

#11133 [#11103] Audit logs: right-align timestamps
  src/web/app/components/sortable-table/sortable-table.component.html
  src/web/app/components/sortable-table/sortable-table.component.ts
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.ts
Labels: s.FinalReview

#11140 [#10481] Remove video tour on home page
  src/web/app/pages-static/index-page/index-page.component.html
  src/web/app/pages-static/index-page/index-page.component.scss
Labels: s.Ongoing
