Repository TEAMMATES/teammates, pull requests merged in 2021-03, with the labels that each got.

#10989 [#10988] Fix encoding issue in Task Queue
  src/main/java/teammates/logic/core/TaskQueuesLogic.java
Labels: c.Bug, s.ToMerge

#10990 [#10974] Fix log compilation cron job
  src/main/java/teammates/ui/webapi/CompileLogsAction.java
Labels: c.Bug, s.ToMerge

#10918 [#9480] Add frontend tests to session result component
  src/web/app/pages-session/session-result-page/__snapshots__/session-result-page.component.spec.ts.snap
  src/web/app/pages-session/session-result-page/session-result-page.component.html
  src/web/app/pages-session/session-result-page/session-result-page.component.spec.ts
Labels: c.Task, s.ToMerge

#10991 [#10987] Open new tab for the contact page
  src/web/app/page.component.html
Labels: c.Bug, s.ToMerge

#10985 [#10950] Add logging endpoint for audit logs
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/constants/ResourceEndpoints.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/CreateFeedbackSessionLogAction.java
Labels: s.FinalReview

#10997 [#10996] Update developers
  src/web/data/developers.json
Labels: c.Task, s.ToMerge

#10951 [#10700] Handle CSRF token problem better
  src/web/app/components/error-report/__snapshots__/error-report.component.spec.ts.snap
  src/web/app/components/error-report/error-report.component.html
  src/web/app/components/error-report/error-report.component.ts
Labels: c.Feature, s.ToMerge

#10999 [#10998] Fix NPE from GoogleCloudStorageService
  src/main/java/teammates/logic/core/GoogleCloudStorageService.java
Labels: c.Bug, s.ToMerge

#10956 [#10955] Initial Objectify upgrade from v5 to v6
  build.gradle
  src/client/java/teammates/client/scripts/DataMigrationEntitiesBaseScript.java
  src/client/java/teammates/client/scripts/statistics/CursorIterator.java
  src/e2e/java/teammates/e2e/cases/BaseE2ETestCase.java
  src/main/java/teammates/common/util/Config.java
  src/main/java/teammates/storage/api/EntitiesDb.java
  src/main/java/teammates/storage/api/InstructorsDb.java
  src/main/java/teammates/storage/api/OfyHelper.java
  src/main/java/teammates/storage/entity/BaseEntity.java
  src/main/java/teammates/storage/entity/FeedbackQuestion.java
  src/main/resources/build.template.properties
  src/test/java/teammates/test/BaseTestCaseWithObjectifyAccess.java
  static-analysis/teammates-checkstyle.xml
Labels: s.ToMerge

#10980 [#10979] Highlight today date and add today button
  src/web/app/components/session-edit-form/session-edit-form.component.html
  src/web/app/components/session-edit-form/session-edit-form.component.scss
  src/web/app/components/session-edit-form/session-edit-form.component.ts
  src/web/styles.scss
Labels: c.Feature, s.ToMerge

#10890 [#8532] Sessions: instructor view results: stop showing a random identifier for anonymous responses
  src/web/app/components/comment-box/comment-edit-form/comment-edit-form.component.ts
  src/web/app/components/teammates-common/student-name/student-name-with-photo.component.ts
  src/web/services/string-helper.spec.ts
  src/web/services/string-helper.ts
Labels: c.Feature, s.ToMerge

#11009 [#11008] Add toJson with writer as input for JsonResult to reduce unnecessary
  src/main/java/teammates/common/util/JsonUtils.java
  src/main/java/teammates/ui/webapi/JsonResult.java
Labels: c.Feature, s.ToMerge

#11019 [#11001] Migrate App Engine Text datastore type
  src/main/java/teammates/storage/entity/FeedbackQuestion.java
  src/main/java/teammates/storage/entity/FeedbackResponseComment.java
  src/main/java/teammates/storage/entity/FeedbackSession.java
  src/main/java/teammates/storage/entity/Instructor.java
  src/main/java/teammates/storage/entity/StudentProfile.java
  src/test/java/teammates/architecture/ArchitectureTest.java
Labels: s.ToMerge

#10960 [#10959] Paginate frontend call to webapi for large course
  src/web/app/components/loader-bar/loader-bar.component.scss
  src/web/app/components/progress-bar/progress-bar.component.html
  src/web/app/components/progress-bar/progress-bar.component.spec.ts
  src/web/app/components/progress-bar/progress-bar.component.ts
  src/web/app/components/progress-bar/progress-bar.module.ts
  src/web/app/components/simple-modal/simple-modal-type.ts
  src/web/app/components/simple-modal/simple-modal.component.html
  src/web/app/components/simple-modal/simple-modal.component.scss
  src/web/app/components/simple-modal/simple-modal.component.spec.ts
  src/web/app/components/simple-modal/simple-modal.module.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts
  src/web/services/progress-bar.service.spec.ts
  src/web/services/progress-bar.service.ts
  src/web/services/simple-modal.service.ts
Labels: s.ToMerge

#11021 [#10929] Apply proxy pattern for logs and task queue
  .gitignore
  docs/design.md
  src/main/java/teammates/common/datatransfer/ErrorLogEntry.java
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/main/java/teammates/logic/api/EmailSender.java
  src/main/java/teammates/logic/api/LogsProcessor.java
  src/main/java/teammates/logic/api/TaskQueuer.java
  src/main/java/teammates/logic/core/EmailSenderService.java
  src/main/java/teammates/logic/core/GoogleCloudLoggingService.java
  src/main/java/teammates/logic/core/GoogleCloudTasksService.java
  src/main/java/teammates/logic/core/JavamailService.java
  src/main/java/teammates/logic/core/LocalLoggingService.java
  src/main/java/teammates/logic/core/LocalTaskQueueService.java
  src/main/java/teammates/logic/core/LogService.java
  src/main/java/teammates/logic/core/MailgunService.java
  src/main/java/teammates/logic/core/MailjetService.java
  src/main/java/teammates/logic/core/SendgridService.java
  src/main/java/teammates/logic/core/TaskQueueService.java
  src/main/java/teammates/logic/core/TaskQueuesLogic.java
  src/main/java/teammates/ui/webapi/Action.java
  src/main/java/teammates/ui/webapi/CompileLogsAction.java
  src/test/java/teammates/architecture/ArchitectureTest.java
  src/test/java/teammates/logic/api/EmailGeneratorTest.java
  src/test/java/teammates/test/BaseComponentTestCase.java
  src/test/java/teammates/test/FileHelper.java
  src/test/java/teammates/test/GaeSimulation.java
  src/test/java/teammates/test/MockEmailSender.java
  src/test/java/teammates/test/MockFileStorage.java
  src/test/java/teammates/test/MockLogsProcessor.java
  src/test/java/teammates/test/MockTaskQueuer.java
  src/test/java/teammates/ui/webapi/BaseActionTest.java
  src/test/java/teammates/ui/webapi/CompileLogsActionTest.java
  src/test/java/teammates/ui/webapi/CreateAccountActionTest.java
  src/test/java/teammates/ui/webapi/CreateInstructorActionTest.java
  src/test/java/teammates/ui/webapi/FeedbackSessionClosedRemindersActionTest.java
  src/test/java/teammates/ui/webapi/FeedbackSessionClosingRemindersActionTest.java
  src/test/java/teammates/ui/webapi/FeedbackSessionOpeningRemindersActionTest.java
  src/test/java/teammates/ui/webapi/FeedbackSessionPublishedEmailWorkerActionTest.java
  src/test/java/teammates/ui/webapi/FeedbackSessionPublishedRemindersActionTest.java
  src/test/java/teammates/ui/webapi/FeedbackSessionRemindEmailWorkerActionTest.java
  src/test/java/teammates/ui/webapi/FeedbackSessionRemindParticularUsersEmailWorkerActionTest.java
  src/test/java/teammates/ui/webapi/FeedbackSessionResendPublishedEmailWorkerActionTest.java
  src/test/java/teammates/ui/webapi/FeedbackSessionUnpublishedEmailWorkerActionTest.java
  src/test/java/teammates/ui/webapi/InstructorCourseJoinEmailWorkerActionTest.java
  src/test/java/teammates/ui/webapi/JoinCourseActionTest.java
  src/test/java/teammates/ui/webapi/RegenerateStudentCourseLinksActionTest.java
  src/test/java/teammates/ui/webapi/RemindFeedbackSessionResultActionTest.java
  src/test/java/teammates/ui/webapi/RemindFeedbackSessionSubmissionActionTest.java
  src/test/java/teammates/ui/webapi/SendJoinReminderEmailActionTest.java
  src/test/java/teammates/ui/webapi/SessionLinksRecoveryActionTest.java
  src/test/java/teammates/ui/webapi/StudentCourseJoinEmailWorkerActionTest.java
  src/test/java/teammates/ui/webapi/UnpublishFeedbackSessionActionTest.java
  src/test/java/teammates/ui/webapi/UpdateStudentActionTest.java
  src/test/resources/filestorage/.gitkeep
Labels: s.ToMerge

#11007 [#10569] Missing loading icons and bugs for session edit form
  src/web/app/components/session-edit-form/session-edit-form-model.ts
  src/web/app/components/session-edit-form/session-edit-form.component.html
  src/web/app/components/session-edit-form/session-edit-form.component.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-data.ts
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.ts
Labels: c.Feature, s.ToMerge

#10978 [#10950] Add base files for audit logs backend
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/output/FeedbackSessionLog.java
  src/main/java/teammates/ui/output/FeedbackSessionLogEntry.java
  src/main/java/teammates/ui/output/FeedbackSessionLogsData.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/GetFeedbackSessionLogsAction.java
Labels: s.ToReview

#11005 [#10950] Track student feedback session in frontend
  src/main/java/teammates/ui/constants/LogTypes.java
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
  src/web/services/log.service.spec.ts
  src/web/services/log.service.ts
Labels: s.ToReview

#11025 [#11001] Handle datastore exceptions using the new Google-provided SDK
  src/e2e/java/teammates/e2e/cases/SystemErrorEmailReportE2ETest.java
  src/main/java/teammates/ui/webapi/AdminExceptionTestAction.java
  src/main/java/teammates/ui/webapi/WebApiServlet.java
  src/test/java/teammates/ui/webapi/WebApiServletTest.java
Labels: s.ToMerge

#11028 [#11002] Separate emulator ports and include its setup into CI for tests
  .github/workflows/e2e.yml
  .github/workflows/lnp.yml
  src/e2e/java/teammates/e2e/cases/BaseE2ETestCase.java
  src/test/java/teammates/test/BaseTestCaseWithObjectifyAccess.java
  src/test/java/teammates/test/TestProperties.java
  src/test/resources/test.template.properties
Labels: s.ToMerge

#11034 [#11001] Final cleanup for Objectify V6 migration
  src/main/java/teammates/storage/entity/FeedbackQuestion.java
  src/main/java/teammates/storage/entity/FeedbackResponse.java
  src/main/java/teammates/storage/entity/FeedbackResponseComment.java
  src/main/java/teammates/storage/entity/FeedbackSession.java
Labels: s.ToMerge

#11036 [#10651] Broken Link on Instructor Help Page
  src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.html
  src/web/styles.scss
Labels: c.Bug, s.ToMerge

#10984 [#10950] Add logging functionality to backend
  src/main/java/teammates/common/datatransfer/FeedbackSessionLogEntry.java
  src/main/java/teammates/common/exception/LogServiceException.java
  src/main/java/teammates/logic/api/LogsProcessor.java
  src/main/java/teammates/logic/core/GoogleCloudLoggingService.java
  src/main/java/teammates/logic/core/LocalLoggingService.java
  src/main/java/teammates/logic/core/LogService.java
  src/main/java/teammates/ui/constants/LogType.java
  src/main/java/teammates/ui/constants/LogTypes.java
  src/main/java/teammates/ui/constants/ResourceEndpoints.java
  src/main/java/teammates/ui/output/FeedbackSessionLog.java
  src/main/java/teammates/ui/output/FeedbackSessionLogData.java
  src/main/java/teammates/ui/output/FeedbackSessionLogEntry.java
  src/main/java/teammates/ui/output/FeedbackSessionLogEntryData.java
  src/main/java/teammates/ui/output/FeedbackSessionLogsData.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/CreateFeedbackSessionLogAction.java
  src/main/java/teammates/ui/webapi/GetFeedbackSessionLogsAction.java
  src/test/java/teammates/ui/webapi/CreateFeedbackSessionLogActionTest.java
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
  src/web/services/log.service.ts
Labels: s.ToReview

#11006 [#10969] Search form for audit logs page
  src/web/app/components/session-edit-form/session-edit-form.module.ts
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.html
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.scss
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.spec.ts
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.ts
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.module.ts
  src/web/app/pages-instructor/instructor-page.component.ts
  src/web/app/pages-instructor/instructor-pages.module.ts
Labels: s.ToReview

#11052 [#11051] Update snapshots to fix component tests
  src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap
Labels: c.Task, s.ToMerge

#11057 [#11056] Mock timezones in new course form of instructor courses page
  src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.spec.ts
Labels: s.ToMerge

#11022 [#11018] Separate authentication and authorization steps for access control
  docs/design.md
  src/main/java/teammates/common/datatransfer/UserInfo.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/api/UserProvision.java
  src/main/java/teammates/ui/webapi/Action.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/BasicFeedbackSubmissionAction.java
  src/main/java/teammates/ui/webapi/CreateFeedbackResponseCommentAction.java
  src/main/java/teammates/ui/webapi/DeleteFeedbackResponseCommentAction.java
  src/main/java/teammates/ui/webapi/GateKeeper.java
  src/main/java/teammates/ui/webapi/GetAuthInfoAction.java
  src/main/java/teammates/ui/webapi/GetFeedbackQuestionsAction.java
  src/main/java/teammates/ui/webapi/GetFeedbackSessionAction.java
  src/main/java/teammates/ui/webapi/GetInstructorAction.java
  src/main/java/teammates/ui/webapi/GetSessionResultsAction.java
  src/main/java/teammates/ui/webapi/GetStudentProfileAction.java
  src/main/java/teammates/ui/webapi/GetStudentProfilePictureAction.java
  src/main/java/teammates/ui/webapi/LogoutServlet.java
  src/main/java/teammates/ui/webapi/UpdateFeedbackResponseCommentAction.java
  src/main/java/teammates/ui/webapi/WebApiServlet.java
  src/test/java/teammates/architecture/ArchitectureTest.java
  src/test/java/teammates/logic/api/UserProvisionTest.java
  src/test/java/teammates/test/GaeSimulation.java
  src/test/java/teammates/test/MockUserProvision.java
  src/test/java/teammates/ui/webapi/BaseActionTest.java
  src/test/java/teammates/ui/webapi/CreateFeedbackResponseCommentActionTest.java
  src/test/java/teammates/ui/webapi/GetAuthInfoActionTest.java
  src/test/java/teammates/ui/webapi/GetFeedbackQuestionRecipientsActionTest.java
  src/test/java/teammates/ui/webapi/GetLocalDateTimeInfoActionTest.java
  src/test/java/teammates/ui/webapi/GetRegkeyValidityActionTest.java
  src/test/java/teammates/ui/webapi/GetStudentActionTest.java
  src/test/java/teammates/ui/webapi/GetStudentProfilePictureActionTest.java
  src/test/java/teammates/ui/webapi/SendErrorReportActionTest.java
  src/test/java/teammates/ui/webapi/UpdateStudentProfileActionTest.java
Labels: s.ToMerge

#11050 [#10950] Refactor getting of error log entries
  src/main/java/teammates/logic/core/GoogleCloudLoggingService.java
Labels: s.ToMerge

#11060 [#11020] Remove searching response comments related features and search box at home page
  src/e2e/java/teammates/e2e/cases/BaseE2ETestCase.java
  src/e2e/java/teammates/e2e/cases/InstructorHomePageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorSearchPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorHomePage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorSearchPage.java
  src/e2e/java/teammates/e2e/util/TestProperties.java
  src/e2e/resources/data/InstructorSearchPageE2ETest.json
  src/e2e/resources/test.ci-chrome.properties
  src/e2e/resources/test.ci-firefox.properties
  src/e2e/resources/test.template.properties
  src/main/java/teammates/common/datatransfer/FeedbackResponseCommentSearchResultBundle.java
  src/main/java/teammates/common/datatransfer/attributes/FeedbackResponseCommentAttributes.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/common/util/StringHelper.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/DataBundleLogic.java
  src/main/java/teammates/logic/core/FeedbackResponseCommentsLogic.java
  src/main/java/teammates/storage/api/FeedbackResponseCommentsDb.java
  src/main/java/teammates/storage/search/FeedbackResponseCommentSearchDocument.java
  src/main/java/teammates/storage/search/FeedbackResponseCommentSearchQuery.java
  src/main/java/teammates/storage/search/SearchDocument.java
  src/main/java/teammates/ui/constants/ResourceEndpoints.java
  src/main/java/teammates/ui/output/CommentSearchResultData.java
  src/main/java/teammates/ui/output/CommentSearchResultsData.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/CreateAccountAction.java
  src/main/java/teammates/ui/webapi/SearchCommentsAction.java
  src/test/java/teammates/common/util/StringHelperTest.java
  src/test/java/teammates/storage/api/FeedbackResponseCommentsDbTest.java
  src/test/java/teammates/storage/search/FeedbackResponseCommentSearchTest.java
  src/test/java/teammates/test/BaseComponentTestCase.java
  src/test/java/teammates/test/BaseTestCaseWithDatastoreAccess.java
  src/test/java/teammates/test/TestProperties.java
  src/test/java/teammates/ui/webapi/SearchCommentsActionTest.java
  src/test/resources/test.template.properties
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-data.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.ts
  src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.ts
  src/web/app/pages-instructor/instructor-pages.module.ts
  src/web/app/pages-instructor/instructor-search-page/__snapshots__/instructor-search-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-search-page/comment-result-table/comment-result-table.component.html
  src/web/app/pages-instructor/instructor-search-page/comment-result-table/comment-result-table.component.scss
  src/web/app/pages-instructor/instructor-search-page/comment-result-table/comment-result-table.component.spec.ts
  src/web/app/pages-instructor/instructor-search-page/comment-result-table/comment-result-table.component.ts
  src/web/app/pages-instructor/instructor-search-page/instructor-search-bar/instructor-search-bar.component.html
  src/web/app/pages-instructor/instructor-search-page/instructor-search-bar/instructor-search-bar.component.ts
  src/web/app/pages-instructor/instructor-search-page/instructor-search-components.module.ts
  src/web/app/pages-instructor/instructor-search-page/instructor-search-page.component.html
  src/web/app/pages-instructor/instructor-search-page/instructor-search-page.component.ts
  src/web/app/pages-static/features-page/features-page.component.html
  src/web/services/search.service.ts
Labels: s.ToMerge

#11068 [#11065] Remove usage of App Engine Mail API
  docs/emails.md
  src/e2e/java/teammates/e2e/cases/InstructorCourseStudentDetailsEditPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/AdminSearchPage.java
  src/e2e/resources/test.template.properties
  src/main/java/teammates/logic/api/EmailSender.java
  src/main/java/teammates/logic/core/EmptyEmailService.java
  src/main/java/teammates/logic/core/JavamailService.java
  src/main/resources/build.template.properties
  src/test/java/teammates/logic/api/EmailSenderTest.java
  src/test/java/teammates/test/GaeSimulation.java
Labels: s.ToReview

#10943 [#10936] Show explicit enroll errors
  src/main/java/teammates/ui/output/EnrollStudentsData.java
  src/main/java/teammates/ui/webapi/EnrollStudentsAction.java
  src/test/java/teammates/ui/webapi/EnrollStudentsActionTest.java
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.html
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.scss
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts
  src/web/services/student.service.ts
Labels: c.Feature, s.ToMerge

#11067 [#11020] Make search service optional and remove App Engine Search API usage
  src/e2e/java/teammates/e2e/cases/AdminSearchPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/BaseE2ETestCase.java
  src/e2e/java/teammates/e2e/cases/InstructorSearchPageE2ETest.java
  src/e2e/java/teammates/e2e/util/TestProperties.java
  src/e2e/resources/test.ci-chrome.properties
  src/e2e/resources/test.ci-firefox.properties
  src/e2e/resources/test.template.properties
  src/main/java/teammates/common/exception/SearchNotImplementedException.java
  src/main/java/teammates/common/util/Config.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/InstructorsLogic.java
  src/main/java/teammates/logic/core/StudentsLogic.java
  src/main/java/teammates/storage/api/EntitiesDb.java
  src/main/java/teammates/storage/api/InstructorsDb.java
  src/main/java/teammates/storage/api/StudentsDb.java
  src/main/java/teammates/storage/search/InstructorSearchDocument.java
  src/main/java/teammates/storage/search/InstructorSearchQuery.java
  src/main/java/teammates/storage/search/SearchDocument.java
  src/main/java/teammates/storage/search/SearchManager.java
  src/main/java/teammates/storage/search/SearchManagerFactory.java
  src/main/java/teammates/storage/search/SearchManagerStarter.java
  src/main/java/teammates/storage/search/SearchQuery.java
  src/main/java/teammates/storage/search/StudentSearchDocument.java
  src/main/java/teammates/storage/search/StudentSearchQuery.java
  src/main/java/teammates/ui/webapi/SearchInstructorsAction.java
  src/main/java/teammates/ui/webapi/SearchStudentsAction.java
  src/main/resources/build.template.properties
  src/main/webapp/WEB-INF/web.xml
  src/test/java/teammates/architecture/ArchitectureTest.java
  src/test/java/teammates/storage/search/InstructorSearchTest.java
  src/test/java/teammates/storage/search/StudentSearchTest.java
  src/test/java/teammates/test/BaseTestCaseWithObjectifyAccess.java
  src/test/java/teammates/test/GaeSimulation.java
  src/test/java/teammates/test/TestProperties.java
  src/test/java/teammates/ui/webapi/SearchInstructorsActionTest.java
  src/test/java/teammates/ui/webapi/SearchStudentsActionTest.java
  src/test/resources/test.template.properties
Labels: s.ToReview

#11043 [#10981] Add team members as an option to generate values
  src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
  src/test/java/teammates/logic/core/FeedbackQuestionsLogicTest.java
  src/web/app/components/question-types/question-edit-details-form/mcq-question-edit-details-form.component.ts
  src/web/app/components/question-types/question-edit-details-form/msq-question-edit-details-form.component.ts
  src/web/app/components/teammates-common/generated-choice.pipe.ts
Labels: c.Feature, s.ToMerge

#11047 [#10969] Instructor Audit Logs Frontend
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/common/util/TimeHelper.java
  src/main/java/teammates/ui/webapi/GetFeedbackSessionLogsAction.java
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.html
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.scss
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.ts
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.module.ts
  src/web/app/pages-instructor/instructor-page.component.ts
  src/web/services/log.service.ts
  src/web/services/table-comparator.service.ts
  src/web/types/sort-properties.ts
Labels: s.ToMerge

#10968 [#10964] Paginate enroll calls for large courses (FE)
  src/main/java/teammates/ui/request/StudentsEnrollRequest.java
  src/test/java/teammates/ui/request/StudentsEnrollRequestTest.java
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.html
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.html
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts
  src/web/styles.scss
Labels: c.Feature, s.ToMerge

#11048 [#10950] Add backend tests for audit logs
  src/main/java/teammates/ui/output/FeedbackSessionLogData.java
  src/main/java/teammates/ui/webapi/CreateFeedbackSessionLogAction.java
  src/main/java/teammates/ui/webapi/GetFeedbackSessionLogsAction.java
  src/test/java/teammates/test/MockLogsProcessor.java
  src/test/java/teammates/ui/webapi/CompileLogsActionTest.java
  src/test/java/teammates/ui/webapi/CreateFeedbackSessionLogActionTest.java
  src/test/java/teammates/ui/webapi/GetFeedbackSessionLogsActionTest.java
Labels: s.ToMerge
