Repository TEAMMATES/teammates, pull requests merged in 2021-07, with the labels that each got.

#11209 [#11149] Students page: tweak text
  src/e2e/java/teammates/e2e/pageobjects/InstructorStudentListPage.java
  src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.html
Labels: s.ToMerge

#11214 [#11205] Fix for Checkbox not aligned with text when choosing from template question
  src/web/app/pages-instructor/instructor-session-edit-page/template-question-modal/template-question-modal.component.html
  src/web/app/pages-instructor/instructor-session-edit-page/template-question-modal/template-question-modal.component.scss
Labels: s.ToMerge

#11247 [#11227] Instructor home page: show spinner while copying sessions
  src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.ts
Labels: s.ToMerge

#11223 [#11148] Instructor home page: tweak session status tooltips
  src/web/app/components/sessions-table/publish-status-tooltip.pipe.ts
  src/web/app/components/sessions-table/submission-status-tooltip.pipe.ts
Labels: s.ToMerge

#11218 [#10569] Loading icons bugs for Session Edit Form (Copy Button)
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
Labels: s.ToMerge

#11250 [#11237] Feedback session table doesn't differentiate grace period and open status
  src/web/app/components/session-edit-form/submission-status-name.pipe.ts
  src/web/app/components/sessions-table/submission-status-tooltip.pipe.ts
  src/web/app/components/teammates-common/submission-status-name.pipe.ts
Labels: s.ToMerge

#11194 [#11193] [#11195] Create basic logs retrieval functionality
  src/main/java/teammates/common/datatransfer/GeneralLogEntry.java
  src/main/java/teammates/common/datatransfer/QueryLogsResults.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/logic/api/LogsProcessor.java
  src/main/java/teammates/logic/core/GoogleCloudLoggingService.java
  src/main/java/teammates/logic/core/LocalLoggingService.java
  src/main/java/teammates/logic/core/LogService.java
  src/main/java/teammates/ui/constants/ResourceEndpoints.java
  src/main/java/teammates/ui/output/GeneralLogsData.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/QueryLogsAction.java
  src/test/java/teammates/test/MockLogsProcessor.java
  src/test/java/teammates/ui/webapi/QueryLogsActionTest.java
  src/web/app/components/logs-table/logs-table-model.ts
  src/web/app/components/logs-table/logs-table.component.html
  src/web/app/components/logs-table/logs-table.component.scss
  src/web/app/components/logs-table/logs-table.component.spec.ts
  src/web/app/components/logs-table/logs-table.component.ts
  src/web/app/components/logs-table/logs-table.module.ts
  src/web/app/pages-admin/admin-pages.module.ts
  src/web/app/pages-logs/__snapshots__/logs-page.component.spec.ts.snap
  src/web/app/pages-logs/logs-page.component.html
  src/web/app/pages-logs/logs-page.component.scss
  src/web/app/pages-logs/logs-page.component.spec.ts
  src/web/app/pages-logs/logs-page.component.ts
  src/web/app/pages-logs/logs-page.module.ts
  src/web/services/log.service.ts
Labels: s.ToMerge

#11251 [#11246] Instructor audit logs: error in 'from' date for first day of the month
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.ts
Labels: s.ToMerge

#11241 [#11198] Improve error handling for search service
  src/main/java/teammates/common/exception/SearchNotImplementedException.java
  src/main/java/teammates/common/exception/SearchServiceException.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/InstructorsLogic.java
  src/main/java/teammates/logic/core/StudentsLogic.java
  src/main/java/teammates/storage/api/InstructorsDb.java
  src/main/java/teammates/storage/api/StudentsDb.java
  src/main/java/teammates/storage/search/InstructorSearchManager.java
  src/main/java/teammates/storage/search/SearchManager.java
  src/main/java/teammates/storage/search/StudentSearchManager.java
  src/main/java/teammates/ui/webapi/SearchInstructorsAction.java
  src/main/java/teammates/ui/webapi/SearchStudentsAction.java
  src/test/java/teammates/storage/search/InstructorSearchTest.java
  src/test/java/teammates/storage/search/StudentSearchTest.java
Labels: s.ToMerge

#11253 [#11240] [#11238] Support Docker compose for dependent service + deployment to GAE flex
  .github/workflows/component.yml
  .github/workflows/e2e.yml
  .github/workflows/lnp.yml
  .gitignore
  build.gradle
  datastore-dev/Dockerfile
  docker-compose.yml
  docs/development.md
  docs/search.md
  solr/Dockerfile
  solr/solr.sh
  src/e2e/java/teammates/e2e/cases/AdminAccountsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/AdminSessionsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/BaseE2ETestCase.java
  src/e2e/java/teammates/e2e/cases/FeedbackConstSumOptionQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackConstSumRecipientQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackContributionQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackMcqQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackMsqQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackNumScaleQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackRankOptionQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackRankRecipientQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackRubricQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorCoursesPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/TimezoneSyncerTest.java
  src/e2e/java/teammates/e2e/pageobjects/AppPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorCoursesPage.java
  src/e2e/java/teammates/e2e/pageobjects/StudentProfilePage.java
  src/e2e/resources/scripts/readTinyMCEContent.js
  src/e2e/resources/scripts/writeToTinyMCE.js
  src/main/appengine/app.template.yaml
  src/main/docker/Dockerfile
  src/main/java/teammates/common/util/Config.java
  src/main/java/teammates/logic/core/LocalTaskQueueService.java
  src/main/java/teammates/main/Application.java
  src/main/java/teammates/storage/api/DatastoreEmulatorRunner.java
  src/main/java/teammates/ui/webapi/HealthCheckServlet.java
  src/main/java/teammates/ui/webapi/WebPageServlet.java
  src/main/java/teammates/ui/webapi/WebSecurityHeaderFilter.java
  src/main/resources/build.template.properties
  src/main/webapp/WEB-INF/web.xml
  wait-for-server.sh
Labels: s.ToMerge

#11221 [#11146] Student viewing responses: show self-response as 'given' AND 'received'
  src/e2e/java/teammates/e2e/cases/StudentFeedbackResultsPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/StudentFeedbackResultsPage.java
  src/main/java/teammates/ui/output/SessionResultsData.java
  src/web/app/pages-session/session-result-page/__snapshots__/session-result-page.component.spec.ts.snap
  src/web/app/pages-session/session-result-page/session-result-page.component.html
  src/web/app/pages-session/session-result-page/session-result-page.component.ts
Labels: s.ToMerge

#11259 [#11252] Use different method to impose request timeout limit
  src/e2e/java/teammates/e2e/cases/SystemErrorEmailReportE2ETest.java
  src/main/java/teammates/common/exception/DeadlineExceededException.java
  src/main/java/teammates/common/util/RequestTracer.java
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/logic/core/StudentsLogic.java
  src/main/java/teammates/ui/webapi/AdminExceptionTestAction.java
  src/main/java/teammates/ui/webapi/EnrollStudentsAction.java
  src/main/java/teammates/ui/webapi/FeedbackSessionClosedRemindersAction.java
  src/main/java/teammates/ui/webapi/FeedbackSessionClosingRemindersAction.java
  src/main/java/teammates/ui/webapi/FeedbackSessionOpeningRemindersAction.java
  src/main/java/teammates/ui/webapi/FeedbackSessionPublishedRemindersAction.java
  src/main/java/teammates/ui/webapi/RequestTraceFilter.java
  src/main/java/teammates/ui/webapi/WebApiServlet.java
Labels: s.ToMerge

#11266 [#11265] Clean build on windows failing because of checkStyle ${basedir}
  build.gradle
  static-analysis/teammates-checkstyle.xml
Labels: c.Task, s.ToMerge

#11183 [#11177] Create new user role: maintainer
  src/main/java/teammates/common/datatransfer/UserInfo.java
  src/main/java/teammates/common/util/Config.java
  src/main/java/teammates/logic/api/UserProvision.java
  src/main/resources/build.template.properties
  src/web/app/pages-session/session-result-page/session-result-page.component.spec.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.component.spec.ts
Labels: c.Feature, s.ToMerge

#11224 [#11208] Distribute points among recipients: show average excluding self
  src/web/app/components/question-types/question-statistics/constsum-recipients-question-statistics.component.spec.ts
  src/web/app/components/question-types/question-statistics/constsum-recipients-question-statistics.component.ts
  src/web/app/components/question-types/question-statistics/question-statistics-calculation/constsum-recipients-question-statistics-calculation.ts
  src/web/types/sort-properties.ts
Labels: c.Feature, s.ToMerge

#11258 [#11248] Update instructor's privileges as the role is updated
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/InstructorsLogic.java
  src/main/java/teammates/ui/webapi/UpdateInstructorAction.java
  src/main/java/teammates/ui/webapi/UpdateInstructorPrivilegeAction.java
  src/test/java/teammates/logic/core/InstructorsLogicTest.java
  src/test/java/teammates/ui/webapi/UpdateInstructorActionTest.java
Labels: c.Bug, s.ToMerge

#11131 [#10920] Add front-end tests for Session Edit Page
  jest-setup.ts
  src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.html
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.spec.ts
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
Labels: s.ToMerge

#11257 [#11242] Fix duplicate copied sessions shown in instructor homepage
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.ts
Labels: s.ToMerge

#11268 [#11267] Logs interface: Support more filters
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/constants/ResourceEndpoints.java
  src/main/java/teammates/ui/output/ActionClasses.java
  src/web/app/components/logs-table/logs-table-model.ts
  src/web/app/components/logs-table/logs-table.component.html
  src/web/app/components/logs-table/logs-table.component.scss
  src/web/app/components/logs-table/logs-table.component.ts
  src/web/app/pages-admin/admin-page.component.ts
  src/web/app/pages-logs/__snapshots__/logs-page.component.spec.ts.snap
  src/web/app/pages-logs/logs-page.component.html
  src/web/app/pages-logs/logs-page.component.scss
  src/web/app/pages-logs/logs-page.component.spec.ts
  src/web/app/pages-logs/logs-page.component.ts
  src/web/services/log.service.ts
Labels: s.ToMerge

#11273 [#11267] Logs interface: Histogram view
  src/web/app/components/logs-histogram/logs-histogram-model.ts
  src/web/app/components/logs-histogram/logs-histogram.component.html
  src/web/app/components/logs-histogram/logs-histogram.component.scss
  src/web/app/components/logs-histogram/logs-histogram.component.spec.ts
  src/web/app/components/logs-histogram/logs-histogram.component.ts
  src/web/app/components/logs-histogram/logs-histogram.module.ts
  src/web/app/components/logs-table/logs-table-model.ts
  src/web/app/components/logs-table/logs-table.component.html
  src/web/app/components/logs-table/logs-table.component.scss
  src/web/app/pages-logs/__snapshots__/logs-page.component.spec.ts.snap
  src/web/app/pages-logs/logs-page.component.html
  src/web/app/pages-logs/logs-page.component.scss
  src/web/app/pages-logs/logs-page.component.spec.ts
  src/web/app/pages-logs/logs-page.component.ts
  src/web/app/pages-logs/logs-page.module.ts
Labels: s.ToMerge

#11269 [#11267] Logs interface: Support more filters (backend)
  src/main/java/teammates/common/datatransfer/QueryLogsParams.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/logic/api/LogsProcessor.java
  src/main/java/teammates/logic/core/GoogleCloudLoggingService.java
  src/main/java/teammates/logic/core/LocalLoggingService.java
  src/main/java/teammates/logic/core/LogService.java
  src/main/java/teammates/ui/output/ActionClasses.java
  src/main/java/teammates/ui/servlets/RequestTraceFilter.java
  src/main/java/teammates/ui/servlets/WebApiServlet.java
  src/main/java/teammates/ui/webapi/Action.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/GetActionClassesAction.java
  src/main/java/teammates/ui/webapi/QueryLogsAction.java
  src/test/java/teammates/test/MockLogsProcessor.java
  src/test/java/teammates/ui/webapi/GetActionClassesActionTest.java
  src/test/java/teammates/ui/webapi/QueryLogsActionTest.java
Labels: s.ToMerge

#11307 [#11304] Add fixes for existing test-related issues
  src/e2e/java/teammates/e2e/cases/BaseE2ETestCase.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/GetUserCookieAction.java
  src/test/java/teammates/test/AbstractBackDoor.java
  src/test/java/teammates/ui/webapi/GetActionClassesActionTest.java
  src/test/java/teammates/ui/webapi/SearchInstructorsActionTest.java
  src/test/java/teammates/ui/webapi/SearchStudentsActionTest.java
  src/web/services/timezone.service.spec.ts
Labels: c.Task, s.ToMerge

#11137 [#3530] Add tests for FeedbackResponseCommentsLogic::isResponseCommentVisibleForUser
  src/test/java/teammates/logic/core/FeedbackResponseCommentsLogicTest.java
Labels: s.FinalReview

#11232 [#11176] Use grey panel when there are no results in student activity logs search
  src/web/app/pages-instructor/instructor-audit-logs-page/__snapshots__/instructor-audit-logs-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.html
Labels: s.ToMerge

#11303 [#11267] Improve usability of logs interface page
  src/main/java/teammates/common/datatransfer/GeneralLogEntry.java
  src/main/java/teammates/common/util/HttpRequestHelper.java
  src/main/java/teammates/common/util/LogEvent.java
  src/main/java/teammates/common/util/Logger.java
  src/main/java/teammates/logic/core/GoogleCloudLoggingService.java
  src/main/java/teammates/ui/servlets/OriginCheckFilter.java
  src/main/java/teammates/ui/servlets/RequestTraceFilter.java
  src/main/java/teammates/ui/servlets/WebApiServlet.java
  src/main/java/teammates/ui/webapi/QueryLogsAction.java
  src/test/java/teammates/test/MockLogsProcessor.java
  src/web/app/components/logs-table/logs-table-model.ts
  src/web/app/components/logs-table/logs-table.component.html
  src/web/app/components/logs-table/logs-table.component.ts
  src/web/app/components/logs-table/logs-table.module.ts
  src/web/app/pages-logs/__snapshots__/logs-page.component.spec.ts.snap
  src/web/app/pages-logs/logs-page.component.html
  src/web/app/pages-logs/logs-page.component.spec.ts
  src/web/app/pages-logs/logs-page.component.ts
Labels: s.ToReview

#11311 [#11310] Logs Interface: Support fetching more logs for both "before" and "after"
  src/main/java/teammates/common/datatransfer/QueryLogsParams.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/logic/core/GoogleCloudLoggingService.java
  src/main/java/teammates/ui/webapi/QueryLogsAction.java
  src/web/app/pages-logs/__snapshots__/logs-page.component.spec.ts.snap
  src/web/app/pages-logs/logs-page.component.html
  src/web/app/pages-logs/logs-page.component.spec.ts
  src/web/app/pages-logs/logs-page.component.ts
  src/web/services/log.service.ts
Labels: c.Feature, s.ToMerge

#11312 [#11298] Fix course ID filter for student search result
  src/client/java/teammates/client/scripts/PopulateCourseSearchDocuments.java
  src/main/java/teammates/storage/search/InstructorSearchManager.java
  src/main/java/teammates/storage/search/SearchManager.java
  src/main/java/teammates/storage/search/StudentSearchManager.java
Labels: c.Bug

#11203 [#11010] Show students created/updated in-place in instructor enrollment page table
  src/e2e/java/teammates/e2e/pageobjects/InstructorCourseEnrollPage.java
  src/web/app/pages-instructor/instructor-course-enroll-page/enroll-status.ts
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.html
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.scss
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts
  src/web/styles.scss
Labels: s.ToMerge

#11297 [#11296] Logs Interface: Support simple local testing with pre-determined logs
  src/main/java/teammates/common/datatransfer/GeneralLogEntry.java
  src/main/java/teammates/common/datatransfer/QueryLogsParams.java
  src/main/java/teammates/common/datatransfer/QueryLogsResults.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/logic/core/GoogleCloudLoggingService.java
  src/main/java/teammates/logic/core/LocalLoggingService.java
  src/main/java/teammates/ui/output/GeneralLogsData.java
  src/main/java/teammates/ui/webapi/QueryLogsAction.java
  src/main/resources/logsForLocalDev.json
  src/test/java/teammates/test/MockLogsProcessor.java
  src/test/java/teammates/ui/webapi/QueryLogsActionTest.java
  src/web/app/pages-logs/__snapshots__/logs-page.component.spec.ts.snap
  src/web/app/pages-logs/logs-page.component.spec.ts
  src/web/app/pages-logs/logs-page.component.ts
  src/web/services/log.service.ts
Labels: c.Task, s.ToMerge
