Repository TEAMMATES/teammates, pull requests merged in 2021-02, with the labels that each got.

#10914 [#10902] Skip 'session closed' email if already submitted
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/test/java/teammates/logic/api/EmailGeneratorTest.java
  src/test/java/teammates/ui/webapi/FeedbackSessionClosedRemindersActionTest.java
Labels: c.Feature, s.ToMerge

#10948 [#10931] Adding a new question typo in save button
  src/web/app/components/question-edit-form/question-edit-form.component.html
Labels: c.Bug, s.ToMerge

#10905 [#10874] Finalize Migration to Github Actions
  .github/workflows/component.yml
  .github/workflows/e2e.yml
  .github/workflows/lnp.yml
  .travis.yml
  README.md
  appveyor.yml
  build.gradle
  docs/development.md
  docs/glossary.md
  docs/process.md
  src/e2e/resources/test.ci-chrome.properties
  src/e2e/resources/test.ci-firefox.properties
  src/e2e/resources/test.travis-chrome.properties
  src/e2e/resources/test.travis.properties
  src/lnp/java/teammates/lnp/cases/FeedbackSessionSubmitLNPTest.java
  src/lnp/java/teammates/lnp/cases/FeedbackSessionViewLNPTest.java
  src/lnp/java/teammates/lnp/cases/StudentProfileLNPTest.java
Labels: s.ToMerge

#10942 [#10920] Add frontend test for user join page component
  src/web/app/__snapshots__/user-join-page.component.spec.ts.snap
  src/web/app/user-join-page.component.spec.ts
Labels: c.Feature, s.ToMerge

#10883 [#10806] [UI issue][Help for instructor page][Questions section] non uniformity in the full stop at the end of the sentence
  src/web/app/pages-help/instructor-help-page/instructor-help-courses-section/instructor-help-courses-section.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.html
Labels: c.Bug, s.ToMerge

#10921 [#10885] Fixed unresponsive question tab in instructor help page
  src/web/app/pages-help/instructor-help-page/instructor-help-page.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-page.component.scss
Labels: c.Bug, s.ToMerge

#10925 [#10920] Add front-end tests for student home page component
  src/web/app/pages-student/student-home-page/__snapshots__/student-home-page.component.spec.ts.snap
  src/web/app/pages-student/student-home-page/student-home-page.component.html
  src/web/app/pages-student/student-home-page/student-home-page.component.spec.ts
Labels: c.Feature, s.ToMerge

#10842 [#10569] missing loading icons for Instructor Sessions Page
  src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-base-page.component.ts
  src/web/app/pages-instructor/instructor-session-modal-page.component.ts
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.html
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.ts
Labels: c.Feature, s.ToMerge

#10935 [#10920] Add front-end tests for instructor home page component
  src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.spec.ts
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.ts
Labels: c.Feature, s.ToMerge

#10957 [#10955] Configure CI for 'objectify-v6-migration' branch
  .github/workflows/component.yml
  .github/workflows/e2e.yml
  .github/workflows/lnp.yml
Labels: s.ToReview

#10947 [#10928] Add script to list active instructors within a period
  src/client/java/teammates/client/scripts/ListActiveInstructors.java
Labels: c.Feature, s.ToMerge

#10930 [#10929] Migrate Task Queue API and Logs API to GCP clients
  .codecov.yml
  build.gradle
  src/main/java/com/google/appengine/logging/v1/LogLine.java
  src/main/java/com/google/appengine/logging/v1/LogLineOrBuilder.java
  src/main/java/com/google/appengine/logging/v1/RequestLog.java
  src/main/java/com/google/appengine/logging/v1/RequestLogOrBuilder.java
  src/main/java/com/google/appengine/logging/v1/RequestLogProto.java
  src/main/java/com/google/appengine/logging/v1/SourceLocation.java
  src/main/java/com/google/appengine/logging/v1/SourceLocationOrBuilder.java
  src/main/java/com/google/appengine/logging/v1/SourceReference.java
  src/main/java/com/google/appengine/logging/v1/SourceReferenceOrBuilder.java
  src/main/java/teammates/common/util/Config.java
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/main/java/teammates/logic/core/TaskQueuesLogic.java
  src/main/java/teammates/ui/webapi/CompileLogsAction.java
  src/main/resources/build.template.properties
  src/test/java/teammates/architecture/ArchitectureTest.java
  src/test/java/teammates/logic/api/EmailGeneratorTest.java
  src/test/java/teammates/test/GaeSimulation.java
  static-analysis/teammates-checkstyle-suppressions.xml
  static-analysis/teammates-pmd.xml
  static-analysis/teammates-pmdMain.xml
  static-analysis/teammates-spotbugs-exclude.xml
Labels: c.Task, s.ToMerge

#10965 [#10963] Update developers.json
  src/web/data/developers.json
Labels: c.Task

#10961 [#10941] Copying questions requires scrolling the whole list of current questions
  src/web/app/pages-instructor/instructor-session-edit-page/copy-questions-from-other-sessions-modal/copy-questions-from-other-sessions-modal.component.scss
Labels: c.Feature, s.ToMerge

#10872 [#10788] Instructor view student list: incorrect state shown very briefly (student list page)
  src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.html
Labels: c.Bug, s.ToMerge

#10954 [#10953] Create mock course script
  src/client/java/teammates/client/scripts/MockCourseWithLargeResponseScript.java
Labels: c.Feature, s.ToMerge

#10895 [#8918] Instructor: view results: questions for ranking: show rank within team
  src/web/app/components/question-types/question-statistics/question-statistics-calculation/rank-recipients-question-statistics-calculation.ts
  src/web/app/components/question-types/question-statistics/rank-recipients-question-statistics.component.spec.ts
  src/web/app/components/question-types/question-statistics/rank-recipients-question-statistics.component.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-data.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.html
  src/web/services/__snapshots__/session-result-csv.service.spec.ts.snap
  src/web/services/table-comparator.service.ts
  src/web/types/question-details-impl/feedback-rank-recipients-question-details.impl.ts
  src/web/types/sort-properties.ts
Labels: c.Feature, s.ToMerge

#10967 [#10920] Add front-end tests for instructor courses page
  src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.html
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.spec.ts
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts
Labels: c.Task, s.ToMerge

#10945 [#10944] Migrate Blobstore API to Google Cloud Storage
  .gitignore
  build.gradle
  filestorage-dev/.gitkeep
  src/client/java/teammates/client/scripts/GoogleIdMigrationBaseScript.java
  src/e2e/resources/data/InstructorCourseStudentDetailsPageE2ETest.json
  src/e2e/resources/data/InstructorStudentRecordsPageE2ETest.json
  src/e2e/resources/data/StudentCourseDetailsPageE2ETest.json
  src/e2e/resources/data/StudentProfilePageE2ETest.json
  src/lnp/java/teammates/lnp/cases/StudentProfileLNPTest.java
  src/main/java/teammates/common/datatransfer/attributes/StudentProfileAttributes.java
  src/main/java/teammates/common/util/Config.java
  src/main/java/teammates/common/util/GoogleCloudStorageHelper.java
  src/main/java/teammates/logic/api/FileStorage.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/FileStorageService.java
  src/main/java/teammates/logic/core/GoogleCloudStorageService.java
  src/main/java/teammates/logic/core/LocalFileStorageService.java
  src/main/java/teammates/logic/core/ProfilesLogic.java
  src/main/java/teammates/storage/api/ProfilesDb.java
  src/main/java/teammates/storage/entity/StudentProfile.java
  src/main/java/teammates/ui/output/StudentProfilePictureResults.java
  src/main/java/teammates/ui/webapi/Action.java
  src/main/java/teammates/ui/webapi/DeleteAccountAction.java
  src/main/java/teammates/ui/webapi/DeleteStudentProfilePictureAction.java
  src/main/java/teammates/ui/webapi/GetStudentProfilePictureAction.java
  src/main/java/teammates/ui/webapi/ImageResult.java
  src/main/java/teammates/ui/webapi/PostStudentProfilePictureAction.java
  src/main/java/teammates/ui/webapi/ResetAccountAction.java
  src/main/java/teammates/ui/webapi/UpdateStudentProfileAction.java
  src/main/resources/InstructorSampleData.json
  src/test/java/teammates/architecture/ArchitectureTest.java
  src/test/java/teammates/common/datatransfer/attributes/StudentProfileAttributesTest.java
  src/test/java/teammates/common/util/BuildPropertiesTest.java
  src/test/java/teammates/logic/core/ProfilesLogicTest.java
  src/test/java/teammates/storage/api/ProfilesDbTest.java
  src/test/java/teammates/test/BaseComponentTestCase.java
  src/test/java/teammates/test/BaseTestCase.java
  src/test/java/teammates/test/EmailChecker.java
  src/test/java/teammates/test/EmailCheckerTest.java
  src/test/java/teammates/test/FileHelper.java
  src/test/java/teammates/test/GaeSimulation.java
  src/test/java/teammates/test/MockFileStorage.java
  src/test/java/teammates/ui/webapi/DeleteStudentProfilePictureActionTest.java
  src/test/java/teammates/ui/webapi/GetStudentProfilePictureActionTest.java
  src/test/java/teammates/ui/webapi/PostStudentProfilePictureActionTest.java
  src/test/resources/data/FeedbackSessionResultsBundleTest.json
  src/test/resources/data/FeedbackSessionsLogicTest.json
  src/test/resources/data/typicalDataBundle.json
  src/test/resources/filestorage/.gitkeep
  src/test/resources/images/profile_pic_default.png
  src/web/app/pages-student/student-profile-page/student-profile-page.component.spec.ts
  src/web/app/pages-student/student-profile-page/student-profile-page.component.ts
  src/web/services/student-profile.service.ts
Labels: s.FinalReview
