Repository TEAMMATES/teammates, pull requests merged in 2021-11, with the labels that each got.

#11324 [#11302] Increase search result limit with message prompt when limit is reached
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/storage/search/SearchManager.java
  src/main/java/teammates/ui/constants/ApiConst.java
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.ts
  src/web/app/pages-instructor/instructor-search-page/instructor-search-page.component.ts
Labels: c.Bug, s.ToMerge

#11453 [#11450] 'Session opening soon' alerts to instructors: Also give the join link if applicable
  src/main/java/teammates/common/util/Templates.java
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/main/resources/ownerEmailFragment-editDetails.html
  src/main/resources/ownerEmailFragment-joinCourseBeforeEditDetails.html
  src/main/resources/ownerEmailTemplate-sessionOpeningSoon.html
  src/test/java/teammates/logic/api/EmailGeneratorTest.java
  src/test/resources/emails/sessionOpeningSoonEmailForCoOwnerJoined.html
  src/test/resources/emails/sessionOpeningSoonEmailForCoOwnerNotJoined.html
Labels: s.ToMerge, c.Feature

#11471 [#11468] Fix instructor view all records not showing results
  src/web/app/pages-instructor/instructor-student-records-page/instructor-student-records-page.component.ts
Labels: s.ToMerge

#11473 [#11470] Add exclusion for generating missing responses for teams
  src/main/java/teammates/common/datatransfer/questions/FeedbackQuestionDetails.java
  src/test/java/teammates/logic/core/FeedbackResponsesLogicTest.java
Labels: s.ToMerge

#11480 [#11474] Fix feedback path event bubbleup error
  .github/workflows/e2e-cross.yml
  .github/workflows/e2e.yml
  src/web/app/components/feedback-path-panel/feedback-path-panel.component.html
  src/web/app/components/feedback-path-panel/feedback-path-panel.component.ts
  src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap
  src/web/app/components/question-edit-form/question-edit-form.component.html
  src/web/app/components/question-edit-form/question-edit-form.component.ts
Labels: c.Bug, s.ToMerge
