Repository TEAMMATES/teammates, pull requests merged in 2021-06, with the labels that each got.

#11151 [#11126] Expand empty search results for feedback session logs
  src/e2e/java/teammates/e2e/pageobjects/InstructorAuditLogsPage.java
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.ts
Labels: s.ToMerge

#11112 [#11099] Audit logs: restrict viewing and searching permissions to course owners
  src/main/java/teammates/ui/webapi/GetFeedbackSessionLogsAction.java
  src/test/java/teammates/ui/webapi/GetFeedbackSessionLogsActionTest.java
  src/web/app/pages-instructor/instructor-audit-logs-page/__snapshots__/instructor-audit-logs-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.html
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.spec.ts
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.ts
Labels: s.ToMerge

#11158 [#11139] Support tracking of result view by instructors
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/logic/api/LogsProcessor.java
  src/main/java/teammates/logic/core/GoogleCloudLoggingService.java
  src/main/java/teammates/logic/core/LocalLoggingService.java
  src/main/java/teammates/logic/core/LogService.java
  src/main/java/teammates/ui/constants/LogType.java
  src/main/java/teammates/ui/webapi/CreateFeedbackSessionLogAction.java
  src/main/java/teammates/ui/webapi/GetFeedbackSessionLogsAction.java
  src/test/java/teammates/test/MockLogsProcessor.java
  src/web/app/components/sortable-table/sortable-table.component.html
  src/web/app/components/sortable-table/sortable-table.component.ts
  src/web/app/pages-instructor/instructor-audit-logs-page/__snapshots__/instructor-audit-logs-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.ts
  src/web/app/pages-instructor/instructor-pages.module.ts
  src/web/app/pages-instructor/instructor-track-view-page/__snapshots__/instructor-track-view-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-track-view-page/instructor-track-view-page.component.html
  src/web/app/pages-instructor/instructor-track-view-page/instructor-track-view-page.component.scss
  src/web/app/pages-instructor/instructor-track-view-page/instructor-track-view-page.component.spec.ts
  src/web/app/pages-instructor/instructor-track-view-page/instructor-track-view-page.component.ts
  src/web/app/pages-instructor/instructor-track-view-page/instructor-track-view-page.module.ts
  src/web/app/pages-session/session-result-page/__snapshots__/session-result-page.component.spec.ts.snap
  src/web/app/pages-session/session-result-page/session-result-page.component.spec.ts
  src/web/app/pages-session/session-result-page/session-result-page.component.ts
  src/web/services/log.service.ts
  src/web/services/table-comparator.service.ts
  src/web/types/sort-properties.ts
Labels: s.FinalReview

#11165 [#11152] Fix bug that caused SVGs to fail to render
  src/main/java/teammates/logic/core/LocalFileStorageService.java
  src/main/java/teammates/ui/webapi/ImageResult.java
Labels: s.ToMerge

#11172 [#10597] Instructor edit session page: page refreshes by itself on first loading
  src/web/app/components/sessions-table/__snapshots__/sessions-table.component.spec.ts.snap
  src/web/app/components/sessions-table/sessions-table.component.html
  src/web/app/components/sessions-table/sessions-table.component.ts
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.ts
  src/web/app/pages-instructor/instructor-session-base-page.component.ts
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.html
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.ts
Labels: s.FinalReview

#11130 [#1501] Add unit test for FeedbackContributionQuestionDetail
  src/test/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetailsTest.java
  src/test/resources/data/FeedbackContributionQuestionTest.json
Labels: s.FinalReview

#11174 [#11135] Audit logs: sort student names alphabetically
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.ts
Labels: s.FinalReview

#11186 [#10449] Tweak layout for team contribution question
  src/web/app/components/question-submission-form/question-submission-form.component.html
  src/web/app/components/question-submission-form/question-submission-form.component.scss
Labels: s.FinalReview

#11184 [#11182] Proof-of-submission file: Add a warning if no answers were saved
  src/web/app/pages-session/session-submission-page/saving-complete-modal/saving-complete-modal.component.html
  src/web/app/pages-session/session-submission-page/saving-complete-modal/saving-complete-modal.component.ts
Labels: s.ToMerge

#10949 [#10920] Add snapshot tests for admin search page
  src/web/app/pages-admin/admin-search-page/__snapshots__/admin-search-page.component.spec.ts.snap
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.html
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.spec.ts
Labels: s.FinalReview

#11192 [#11191] Instructor editing session: Save button is missing a space between icon and label
  src/web/app/components/session-edit-form/session-edit-form.component.html
Labels: s.FinalReview

#11181 [#11180] Convert event-based log message to structured logs
  src/main/java/teammates/common/util/EmailWrapper.java
  src/main/java/teammates/common/util/HttpRequestHelper.java
  src/main/java/teammates/common/util/LogEvent.java
  src/main/java/teammates/common/util/Logger.java
  src/main/java/teammates/common/util/RequestTracer.java
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/main/java/teammates/logic/api/EmailSender.java
  src/main/java/teammates/logic/api/LogsProcessor.java
  src/main/java/teammates/logic/core/EmptyEmailService.java
  src/main/java/teammates/ui/webapi/CreateFeedbackSessionLogAction.java
  src/main/java/teammates/ui/webapi/JsonResult.java
  src/main/java/teammates/ui/webapi/OriginCheckFilter.java
  src/main/java/teammates/ui/webapi/RequestTraceFilter.java
  src/main/java/teammates/ui/webapi/WebApiServlet.java
Labels: s.ToMerge

#11200 [#11196] Fix incorrect display of average value for rubric question stats
  src/web/app/components/question-types/question-statistics/question-statistics-calculation/rubric-question-statistics-calculation.ts
  src/web/app/components/question-types/question-statistics/rubric-question-statistics.component.ts
  src/web/services/__snapshots__/session-result-csv.service.spec.ts.snap
  src/web/types/question-details-impl/feedback-rubric-question-details.impl.ts
Labels: c.Bug, s.ToMerge

#11204 [#10569] Missing loading icon when adding new question from template
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.html
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
Labels: c.Feature, s.ToMerge

#11044 [#10920] Add session submission page tests
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
  src/web/app/pages-session/session-submission-page/session-submission-page.component.spec.ts
Labels: c.Task, s.ToMerge

#10893 [#10682] Instructor copying sessions: show spinner while copying is in progress
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
Labels: s.ToMerge

#11189 [#11161] Fix modal cancel loading bug
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.ts
Labels: s.ToMerge

#11187 [#1501] Add tests for feedback text question
  src/test/java/teammates/common/datatransfer/questions/FeedbackTextQuestionDetailsTest.java
Labels: s.ToMerge

#11201 [#10569] Missing loading icons for Question Edit Form
  src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap
  src/web/app/components/question-edit-form/question-edit-form-model.ts
  src/web/app/components/question-edit-form/question-edit-form.component.html
  src/web/app/components/question-edit-form/question-edit-form.component.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-data.ts
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
  src/web/app/pages-instructor/instructor-session-edit-page/template-question-modal/template-question-modal.component.ts
Labels: s.ToMerge

#11207 [#11206] Remove admin information from user cookie
  docs/development.md
  src/e2e/java/teammates/e2e/cases/BaseE2ETestCase.java
  src/e2e/java/teammates/e2e/cases/BaseFeedbackQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackConstSumOptionQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackConstSumRecipientQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackContributionQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackMcqQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackMsqQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackNumScaleQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackRankOptionQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackRankRecipientQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackRubricQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackSubmitPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackTextQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorAuditLogsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorCourseDetailsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorCourseEditPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorCourseEnrollPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorCourseJoinConfirmationPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorCourseStudentDetailsEditPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorCourseStudentDetailsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorCoursesPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorFeedbackEditPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorFeedbackResultsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorFeedbackSessionsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorHomePageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorSearchPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorStudentListPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorStudentRecordsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/StudentCourseDetailsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/StudentCourseJoinConfirmationPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/StudentFeedbackResultsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/StudentHomePageE2ETest.java
  src/e2e/java/teammates/e2e/cases/StudentProfilePageE2ETest.java
  src/e2e/java/teammates/e2e/cases/TimezoneSyncerTest.java
  src/e2e/java/teammates/e2e/pageobjects/Browser.java
  src/e2e/java/teammates/e2e/pageobjects/DevServerLoginPage.java
  src/e2e/java/teammates/e2e/util/TestProperties.java
  src/e2e/resources/test.ci-chrome.properties
  src/e2e/resources/test.ci-firefox.properties
  src/e2e/resources/test.template.properties
  src/main/java/teammates/common/datatransfer/UserInfoCookie.java
  src/main/java/teammates/logic/api/UserProvision.java
  src/main/java/teammates/ui/webapi/DevServerLoginServlet.java
  src/main/java/teammates/ui/webapi/OAuth2CallbackServlet.java
  src/main/resources/devServerLoginPage.html
  src/test/java/teammates/logic/api/UserProvisionTest.java
  src/test/java/teammates/ui/webapi/BaseActionTest.java
Labels: s.ToMerge
