Repository TEAMMATES/teammates, pull requests merged in 2021-08, with the labels that each got.

#11168 [#10938] Support copying courses
  src/e2e/java/teammates/e2e/cases/InstructorCoursesPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorCoursesPage.java
  src/e2e/resources/data/InstructorCoursesPageE2ETest.json
  src/main/java/teammates/ui/request/FeedbackSessionCreateRequest.java
  src/main/java/teammates/ui/webapi/CreateFeedbackSessionAction.java
  src/test/java/teammates/ui/webapi/CreateFeedbackSessionActionTest.java
  src/web/app/components/copy-course-modal/__snapshots__/copy-course-modal.component.spec.ts.snap
  src/web/app/components/copy-course-modal/copy-course-modal-model.ts
  src/web/app/components/copy-course-modal/copy-course-modal.component.html
  src/web/app/components/copy-course-modal/copy-course-modal.component.scss
  src/web/app/components/copy-course-modal/copy-course-modal.component.spec.ts
  src/web/app/components/copy-course-modal/copy-course-modal.component.ts
  src/web/app/components/copy-course-modal/copy-course-modal.module.ts
  src/web/app/components/copy-session-modal/copy-session-modal-model.ts
  src/web/app/components/copy-session-modal/copy-session-modal.component.ts
  src/web/app/components/sessions-table/sessions-table-model.ts
  src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-courses-page/add-course-form/__snapshots__/add-course-form.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-courses-page/add-course-form/add-course-form.component.html
  src/web/app/pages-instructor/instructor-courses-page/add-course-form/add-course-form.component.spec.ts
  src/web/app/pages-instructor/instructor-courses-page/add-course-form/add-course-form.component.ts
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.html
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.spec.ts
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.module.ts
  src/web/app/pages-instructor/instructor-session-base-page.component.ts
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.spec.ts
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.ts
  src/web/types/field-validator.ts
Labels: s.ToMerge

#11320 [#11319] Logs Interface: Support more filters + better exception tracing
  src/e2e/java/teammates/e2e/cases/BaseE2ETestCase.java
  src/main/java/teammates/common/datatransfer/ErrorLogEntry.java
  src/main/java/teammates/common/datatransfer/QueryLogsParams.java
  src/main/java/teammates/common/exception/TeammatesException.java
  src/main/java/teammates/common/util/Config.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/common/util/LogEvent.java
  src/main/java/teammates/common/util/Logger.java
  src/main/java/teammates/common/util/StringHelper.java
  src/main/java/teammates/common/util/ThreadHelper.java
  src/main/java/teammates/common/util/TimeHelper.java
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/main/java/teammates/logic/api/EmailSender.java
  src/main/java/teammates/logic/api/UserProvision.java
  src/main/java/teammates/logic/core/AccountsLogic.java
  src/main/java/teammates/logic/core/CoursesLogic.java
  src/main/java/teammates/logic/core/GoogleCloudLoggingService.java
  src/main/java/teammates/logic/core/GoogleCloudTasksService.java
  src/main/java/teammates/logic/core/GoogleRecaptchaService.java
  src/main/java/teammates/logic/core/LocalFileStorageService.java
  src/main/java/teammates/logic/core/LocalLoggingService.java
  src/main/java/teammates/logic/core/LocalTaskQueueService.java
  src/main/java/teammates/logic/core/MailgunService.java
  src/main/java/teammates/storage/search/SearchManager.java
  src/main/java/teammates/ui/servlets/WebApiServlet.java
  src/main/java/teammates/ui/servlets/WebPageServlet.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/FeedbackSessionClosedRemindersAction.java
  src/main/java/teammates/ui/webapi/FeedbackSessionClosingRemindersAction.java
  src/main/java/teammates/ui/webapi/FeedbackSessionOpeningRemindersAction.java
  src/main/java/teammates/ui/webapi/FeedbackSessionPublishedEmailWorkerAction.java
  src/main/java/teammates/ui/webapi/FeedbackSessionRemindEmailWorkerAction.java
  src/main/java/teammates/ui/webapi/FeedbackSessionRemindParticularUsersEmailWorkerAction.java
  src/main/java/teammates/ui/webapi/FeedbackSessionResendPublishedEmailWorkerAction.java
  src/main/java/teammates/ui/webapi/FeedbackSessionUnpublishedEmailWorkerAction.java
  src/main/java/teammates/ui/webapi/QueryLogsAction.java
  src/main/resources/logsForLocalDev.json
  src/main/resources/severeErrorLogLine.html
  src/test/java/teammates/logic/api/EmailGeneratorTest.java
  src/test/java/teammates/logic/api/MockLogsProcessor.java
  src/test/java/teammates/test/BaseTestCaseWithLocalDatabaseAccess.java
  src/test/java/teammates/ui/webapi/CompileLogsActionTest.java
  src/test/resources/emails/severeLogsCompilationEmail.html
  src/web/app/components/logs-table/logs-table-model.ts
  src/web/app/components/logs-table/logs-table.component.html
  src/web/app/components/logs-table/logs-table.component.ts
  src/web/app/pages-logs/logs-page.component.html
  src/web/app/pages-logs/logs-page.component.ts
  src/web/services/log.service.ts
Labels: c.Feature, s.ToMerge

#11315 [#11020] Delegate search indexing to cloud task queue
  src/client/java/teammates/client/scripts/GoogleIdMigrationBaseScript.java
  src/main/appengine/queue.yaml
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/api/TaskQueuer.java
  src/main/java/teammates/logic/core/DataBundleLogic.java
  src/main/java/teammates/logic/core/InstructorsLogic.java
  src/main/java/teammates/logic/core/StudentsLogic.java
  src/main/java/teammates/storage/api/InstructorsDb.java
  src/main/java/teammates/storage/api/StudentsDb.java
  src/main/java/teammates/storage/search/SearchManager.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/CreateAccountAction.java
  src/main/java/teammates/ui/webapi/CreateInstructorAction.java
  src/main/java/teammates/ui/webapi/EnrollStudentsAction.java
  src/main/java/teammates/ui/webapi/InstructorSearchIndexingWorkerAction.java
  src/main/java/teammates/ui/webapi/PutDataBundleDocumentsAction.java
  src/main/java/teammates/ui/webapi/StudentSearchIndexingWorkerAction.java
  src/main/java/teammates/ui/webapi/UpdateInstructorAction.java
  src/main/java/teammates/ui/webapi/UpdateStudentAction.java
  src/test/java/teammates/storage/search/InstructorSearchTest.java
  src/test/java/teammates/storage/search/StudentSearchTest.java
  src/test/java/teammates/ui/webapi/CreateAccountActionTest.java
  src/test/java/teammates/ui/webapi/CreateInstructorActionTest.java
  src/test/java/teammates/ui/webapi/EnrollStudentsActionTest.java
  src/test/java/teammates/ui/webapi/GetActionClassesActionTest.java
  src/test/java/teammates/ui/webapi/InstructorSearchIndexingWorkerActionTest.java
  src/test/java/teammates/ui/webapi/StudentSearchIndexingWorkerActionTest.java
  src/test/java/teammates/ui/webapi/UpdateInstructorActionTest.java
  src/test/java/teammates/ui/webapi/UpdateStudentActionTest.java
Labels: s.ToReview

#11323 [#2917] Modify Solr to not use auto-created fields to prevent unnecessary tokenization
  solr/solr.sh
  src/main/java/teammates/storage/search/InstructorSearchDocument.java
  src/main/java/teammates/storage/search/StudentSearchDocument.java
  src/main/java/teammates/storage/search/StudentSearchManager.java
Labels: c.Task, s.ToMerge

#11322 [#11039] [#10677] [#9083] Remove fake google ID in sample students + add migration scripts
  src/client/java/teammates/client/scripts/DataMigrationForConstSumForceUnevenDistribution.java
  src/client/java/teammates/client/scripts/DataMigrationForNullCommentGiverType.java
  src/client/java/teammates/client/scripts/DataMigrationForSampleGoogleIdInStudentAttributes.java
  src/client/java/teammates/client/scripts/DataMigrationForTextQuestionRecommendedLength.java
  src/main/java/teammates/common/datatransfer/attributes/InstructorAttributes.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackQuestionType.java
  src/main/java/teammates/storage/entity/Instructor.java
  src/main/java/teammates/ui/output/FeedbackQuestionData.java
  src/main/java/teammates/ui/request/FeedbackQuestionBasicRequest.java
  src/main/resources/InstructorSampleData.json
  src/test/java/teammates/common/datatransfer/attributes/InstructorAttributesTest.java
Labels: c.Task, s.ToMerge

#11290 [#11284] Fix exception checking in CreateAccountActionTest
  src/test/java/teammates/ui/webapi/CreateAccountActionTest.java
Labels: s.ToMerge

#11313 [#11309] Drop downs for further actions in tables expands by adding scrolling to table
  src/e2e/java/teammates/e2e/pageobjects/InstructorHomePage.java
  src/web/app/components/sessions-table/__snapshots__/sessions-table.component.spec.ts.snap
  src/web/app/components/sessions-table/sessions-table.component.html
  src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
Labels: s.ToMerge

#11256 [#10952] Submission links sent to instructors: Also give join link if not joined yet
  src/main/java/teammates/common/util/Templates.java
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/main/resources/instructorEmailFragment-reminderToJoinCourseBeforeSubmittingResponse.html
  src/main/resources/userEmailTemplate-feedbackSession.html
  src/test/java/teammates/logic/api/EmailGeneratorTest.java
  src/test/resources/emails/sessionReminderEmailForInstructorNotJoinedYet.html
Labels: s.ToMerge

#11188 [#1501] Add tests for FeedbackRankRecipientsQuestionDetails
  src/test/java/teammates/common/datatransfer/questions/FeedbackRankRecipientsQuestionDetailsTest.java
Labels: s.ToMerge, c.Task

#11277 [#4552] Increase course ID, course name, and session name max length
  src/main/java/teammates/common/util/FieldValidator.java
  src/test/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributesTest.java
  src/test/java/teammates/common/util/FieldValidatorTest.java
  src/test/java/teammates/logic/core/CoursesLogicTest.java
  src/test/java/teammates/ui/webapi/CreateFeedbackSessionActionTest.java
  src/web/app/components/copy-course-modal/__snapshots__/copy-course-modal.component.spec.ts.snap
  src/web/app/components/copy-session-modal/__snapshots__/copy-session-modal.component.spec.ts.snap
  src/web/app/components/copy-session-modal/copy-session-modal.component.html
  src/web/app/components/session-edit-form/session-edit-form.component.html
  src/web/app/components/sessions-recycle-bin-table/sessions-recycle-bin-table.component.html
  src/web/app/components/sessions-table/__snapshots__/sessions-table.component.spec.ts.snap
  src/web/app/components/sessions-table/sessions-table.component.html
  src/web/app/pages-admin/admin-accounts-page/admin-accounts-page.component.html
  src/web/app/pages-admin/admin-search-page/__snapshots__/admin-search-page.component.spec.ts.snap
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.html
  src/web/app/pages-admin/admin-sessions-page/admin-sessions-page.component.html
  src/web/app/pages-instructor/instructor-audit-logs-page/__snapshots__/instructor-audit-logs-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.html
  src/web/app/pages-instructor/instructor-course-details-page/__snapshots__/instructor-course-details-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.html
  src/web/app/pages-instructor/instructor-course-edit-page/__snapshots__/instructor-course-edit-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-course-edit-page/custom-privilege-setting-panel/custom-privilege-setting-panel.component.html
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.html
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-edit-panel/instructor-edit-panel.component.html
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.html
  src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-courses-page/add-course-form/__snapshots__/add-course-form.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-courses-page/add-course-form/add-course-form.component.html
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.html
  src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
  src/web/app/pages-instructor/instructor-search-page/__snapshots__/instructor-search-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-search-page/student-result-table/student-result-table.component.html
  src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-edit-page/copy-questions-from-other-sessions-modal/copy-questions-from-other-sessions-modal.component.html
  src/web/app/pages-instructor/instructor-sessions-page/copy-from-other-sessions-modal/copy-from-other-sessions-modal.component.html
  src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.html
  src/web/app/pages-instructor/instructor-student-records-page/__snapshots__/instructor-student-records-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-student-records-page/instructor-student-records-page.component.html
  src/web/app/pages-instructor/instructor-track-view-page/instructor-track-view-page.component.html
  src/web/app/pages-instructor/student-profile/course-related-info/course-related-info.component.html
  src/web/app/pages-session/session-result-page/__snapshots__/session-result-page.component.spec.ts.snap
  src/web/app/pages-session/session-result-page/session-result-page.component.html
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
  src/web/app/pages-session/session-submission-page/session-submission-page.component.html
  src/web/app/pages-session/session-submission-page/session-submission-page.component.scss
  src/web/app/pages-student/student-course-details-page/__snapshots__/student-course-details-page.component.spec.ts.snap
  src/web/app/pages-student/student-course-details-page/student-course-details-page.component.html
  src/web/app/pages-student/student-home-page/__snapshots__/student-home-page.component.spec.ts.snap
  src/web/app/pages-student/student-home-page/student-home-page.component.html
  src/web/styles.scss
Labels: s.ToMerge, c.Feature

#11328 [#11299] Remove previous results if search encounters error
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.ts
  src/web/app/pages-instructor/instructor-search-page/instructor-search-page.component.ts
Labels: c.Bug, s.ToMerge

#11317 [#10785] Sort all team names by natural ordering
  src/web/services/table-comparator.service.ts
Labels: s.ToMerge, c.Feature

#11321 [#11239] Update Java requirement to Java 11
  .github/workflows/component.yml
  .github/workflows/e2e.yml
  .github/workflows/lnp.yml
  build.gradle
  docs/setting-up.md
  gradle.template.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: s.ToMerge, c.DevOps

#11343 [#11329] Release V8.0.0
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  build.gradle
  docs/design.md
  docs/development.md
  docs/e2e-testing.md
  docs/performance-testing.md
  docs/setting-up.md
  src/client/resources/client.template.properties
  src/e2e/resources/test.template.properties
  src/lnp/java/teammates/lnp/cases/FeedbackQuestionUpdateLNPTest.java
  src/lnp/java/teammates/lnp/cases/FeedbackSessionSubmitLNPTest.java
  src/lnp/java/teammates/lnp/cases/FeedbackSessionViewLNPTest.java
  src/lnp/java/teammates/lnp/cases/InstructorSessionResultLNPTest.java
  src/lnp/java/teammates/lnp/cases/InstructorUpdateLNPTest.java
  src/lnp/java/teammates/lnp/cases/StudentEmailUpdateLNPTest.java
  src/lnp/java/teammates/lnp/cases/StudentSectionUpdateLNPTest.java
  src/lnp/java/teammates/lnp/cases/StudentTeamUpdateLNPTest.java
  src/lnp/resources/test.template.properties
  src/main/java/teammates/storage/search/SearchManager.java
  src/main/java/teammates/ui/servlets/WebSecurityHeaderFilter.java
  src/main/resources/build.template.properties
  src/web/app/pages-instructor/instructor-search-page/__snapshots__/instructor-search-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-search-page/instructor-search-page.component.html
  src/web/app/pages-instructor/instructor-search-page/instructor-search-page.component.ts
  src/web/data/developers.json
  src/web/environments/config.template.ts
Labels: s.ToMerge, c.Release

#11344 [#11334] Remove code tailored for legacy data format
  src/client/java/teammates/client/scripts/DataMigrationForConstSumForceUnevenDistribution.java
  src/client/java/teammates/client/scripts/DataMigrationForTeamNameInResponseGiver.java
  src/client/java/teammates/client/scripts/DataMigrationForTextQuestionDetailsFormat.java
  src/client/java/teammates/client/scripts/DataMigrationForTextQuestionRecommendedLength.java
  src/main/java/teammates/common/datatransfer/attributes/FeedbackQuestionAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/FeedbackResponseAttributes.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackResponseDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackTextResponseDetails.java
  src/main/java/teammates/logic/core/FeedbackResponsesLogic.java
  src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/storage/api/FeedbackQuestionsDb.java
  src/main/java/teammates/storage/api/FeedbackResponsesDb.java
  src/main/java/teammates/storage/entity/FeedbackQuestion.java
  src/main/java/teammates/storage/entity/FeedbackResponse.java
  src/main/java/teammates/storage/entity/FeedbackResponseComment.java
  src/main/java/teammates/storage/entity/Instructor.java
  src/main/java/teammates/ui/output/FeedbackQuestionData.java
  src/main/java/teammates/ui/output/SessionResultsData.java
  src/test/java/teammates/common/datatransfer/attributes/FeedbackQuestionAttributesTest.java
  src/test/java/teammates/common/datatransfer/attributes/FeedbackResponseAttributesTest.java
  src/test/java/teammates/logic/core/FeedbackResponsesLogicTest.java
  src/test/java/teammates/logic/core/FeedbackSessionsLogicTest.java
  src/test/java/teammates/storage/api/AccountsDbTest.java
  src/test/resources/data/EmailGeneratorTest.json
  src/test/resources/data/FeedbackSessionResultsTest.json
  src/test/resources/data/FeedbackSessionsLogicTest.json
  src/test/resources/data/SpecialCharacterTest.json
  src/test/resources/data/typicalDataBundle.json
Labels: c.Task

#11349 [#11346] [#11348] Fix NPE/array OOB in logs and OOM in session published email cron job
  src/main/appengine/index.yaml
  src/main/java/teammates/common/util/Logger.java
  src/main/java/teammates/logic/core/GoogleCloudLoggingService.java
  src/main/java/teammates/storage/api/FeedbackSessionsDb.java
  src/main/java/teammates/storage/entity/FeedbackSession.java
  src/test/java/teammates/storage/api/FeedbackSessionsDbTest.java
  src/test/java/teammates/storage/search/StudentSearchTest.java
  src/test/java/teammates/ui/webapi/FeedbackSessionPublishedRemindersActionTest.java
  src/test/resources/emails/sessionReminderEmailForInstructorNotJoinedYet.html
Labels: c.Bug, s.ToMerge

#11353 [#11352] Logging in does not preserve query parameters other than the first one
  src/client/java/teammates/client/scripts/DataMigrationForTextQuestionDetailsFormat.java
  src/client/java/teammates/client/scripts/IndexFeedbackSessionFields.java
  src/main/java/teammates/storage/entity/FeedbackSession.java
  src/main/java/teammates/ui/servlets/DevServerLoginServlet.java
  src/main/java/teammates/ui/servlets/LoginServlet.java
  src/web/app/pages-session/session-result-page/session-result-page.component.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
  src/web/app/public-page.component.ts
  src/web/app/user-join-page.component.ts
Labels: c.Bug, s.ToMerge

#11355 [#11354] Empty results in instructor audit logs and results view tracking
  src/main/java/teammates/logic/core/GoogleCloudLoggingService.java
  src/main/java/teammates/ui/webapi/QueryLogsAction.java
Labels: c.Bug, s.ToMerge

#11274 [#10823] student accessing an awaiting session: error message not shown
  src/web/app/pages-session/session-submission-page/session-submission-page.component.spec.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
Labels: s.ToMerge

#11301 [#10824] Fix for Admin searching for students: also show awaiting sessions
  src/web/app/pages-admin/admin-search-page/__snapshots__/admin-search-page.component.spec.ts.snap
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.html
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.spec.ts
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.ts
  src/web/app/pages-student/student-home-page/student-home-page.component.ts
  src/web/services/feedback-sessions.service.ts
  src/web/services/search.service.ts
Labels: s.ToMerge

#11335 [#11244] Add save and loading icons to instructor's student edit page
  src/web/app/pages-instructor/instructor-course-student-edit-page/__snapshots__/instructor-course-student-edit-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.html
  src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.ts
Labels: s.ToMerge

#11359 [#11202] Instructor checking activity logs: start time is not used correctly
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.spec.ts
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.ts
Labels: s.ToMerge

#11365 [#11364] Track version of web front-end used to call APIs
  src/main/java/teammates/common/datatransfer/logs/RequestLogDetails.java
  src/main/java/teammates/common/util/Logger.java
  src/main/java/teammates/ui/servlets/OriginCheckFilter.java
  src/main/resources/logsForLocalDev.json
  src/test/java/teammates/ui/webapi/QueryLogsActionTest.java
  src/web/services/http-request.service.ts
Labels: s.ToMerge

#11280 [#10920] Add tests for calculating statistics for constsum-options-questions component
  src/web/app/components/question-types/question-statistics/constsum-options-question-statistics.component.spec.ts
  src/web/app/components/question-types/question-statistics/test-data/constsumOptionQuestionResponses.json
Labels: s.ToMerge, c.Task

#11363 [#11362] Add institute field to Course object
  src/client/java/teammates/client/scripts/DataMigrationForCourseInstitutes.java
  src/main/java/teammates/common/datatransfer/attributes/CourseAttributes.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/logic/core/AccountsLogic.java
  src/main/java/teammates/storage/api/CoursesDb.java
  src/main/java/teammates/storage/entity/Course.java
  src/main/java/teammates/ui/webapi/CreateAccountAction.java
  src/main/java/teammates/ui/webapi/CreateCourseAction.java
  src/main/java/teammates/ui/webapi/GetOngoingSessionsAction.java
  src/main/java/teammates/ui/webapi/SearchInstructorsAction.java
  src/main/java/teammates/ui/webapi/SearchStudentsAction.java
  src/main/resources/InstructorSampleData.json
  src/test/java/teammates/common/datatransfer/attributes/CourseAttributesTest.java
  src/test/java/teammates/logic/core/AccountsLogicTest.java
  src/test/java/teammates/ui/webapi/CreateAccountActionTest.java
  src/test/java/teammates/ui/webapi/CreateCourseActionTest.java
Labels: s.ToMerge, c.Task

#11368 [#11367] Create exception wrapper for 409 errors
  src/main/java/teammates/common/exception/InstructorUpdateException.java
  src/main/java/teammates/common/exception/InvalidOperationException.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/AccountsLogic.java
  src/main/java/teammates/logic/core/InstructorsLogic.java
  src/main/java/teammates/ui/servlets/WebApiServlet.java
  src/main/java/teammates/ui/webapi/BasicCommentSubmissionAction.java
  src/main/java/teammates/ui/webapi/CreateCourseAction.java
  src/main/java/teammates/ui/webapi/CreateFeedbackResponseCommentAction.java
  src/main/java/teammates/ui/webapi/CreateFeedbackSessionAction.java
  src/main/java/teammates/ui/webapi/CreateInstructorAction.java
  src/main/java/teammates/ui/webapi/DeleteInstructorAction.java
  src/main/java/teammates/ui/webapi/JoinCourseAction.java
  src/main/java/teammates/ui/webapi/RemindFeedbackSessionResultAction.java
  src/main/java/teammates/ui/webapi/RemindFeedbackSessionSubmissionAction.java
  src/main/java/teammates/ui/webapi/SubmitFeedbackResponsesAction.java
  src/main/java/teammates/ui/webapi/UpdateInstructorAction.java
  src/main/java/teammates/ui/webapi/UpdateInstructorPrivilegeAction.java
  src/main/java/teammates/ui/webapi/UpdateStudentAction.java
  src/test/java/teammates/logic/core/InstructorsLogicTest.java
  src/test/java/teammates/ui/webapi/BaseActionTest.java
  src/test/java/teammates/ui/webapi/CreateCourseActionTest.java
  src/test/java/teammates/ui/webapi/CreateFeedbackResponseCommentActionTest.java
  src/test/java/teammates/ui/webapi/CreateFeedbackSessionActionTest.java
  src/test/java/teammates/ui/webapi/CreateInstructorActionTest.java
  src/test/java/teammates/ui/webapi/DeleteInstructorActionTest.java
  src/test/java/teammates/ui/webapi/JoinCourseActionTest.java
  src/test/java/teammates/ui/webapi/RemindFeedbackSessionResultActionTest.java
  src/test/java/teammates/ui/webapi/RemindFeedbackSessionSubmissionActionTest.java
  src/test/java/teammates/ui/webapi/UpdateInstructorActionTest.java
  src/test/java/teammates/ui/webapi/UpdateStudentActionTest.java
Labels: s.ToMerge, c.Task

#11342 [#11341] Update example box spacing
  src/web/app/pages-instructor/instructor-search-page/instructor-search-bar/instructor-search-bar.component.scss
Labels: s.ToMerge, c.Feature

#11338 [#11337] Home page header misaligned
  src/web/app/pages-static/index-page/index-page.component.html
  src/web/app/pages-static/index-page/index-page.component.scss
Labels: s.ToMerge, c.Feature

#11373 [#11372] Add more system logs
  src/lnp/java/teammates/lnp/cases/FeedbackQuestionUpdateLNPTest.java
  src/lnp/java/teammates/lnp/cases/FeedbackSessionSubmitLNPTest.java
  src/lnp/java/teammates/lnp/cases/InstructorCourseUpdateLNPTest.java
  src/lnp/java/teammates/lnp/cases/InstructorStudentCascadingUpdateLNPTest.java
  src/lnp/java/teammates/lnp/cases/InstructorStudentEnrollmentLNPTest.java
  src/lnp/java/teammates/lnp/cases/InstructorUpdateLNPTest.java
  src/lnp/java/teammates/lnp/cases/StudentEmailUpdateLNPTest.java
  src/lnp/java/teammates/lnp/cases/StudentSectionUpdateLNPTest.java
  src/lnp/java/teammates/lnp/cases/StudentTeamUpdateLNPTest.java
  src/main/java/teammates/common/datatransfer/logs/InstanceLogDetails.java
  src/main/java/teammates/common/datatransfer/logs/LogEvent.java
  src/main/java/teammates/common/datatransfer/logs/RequestLogDetails.java
  src/main/java/teammates/common/util/Config.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/common/util/HttpRequestHelper.java
  src/main/java/teammates/common/util/Logger.java
  src/main/java/teammates/main/Application.java
  src/main/java/teammates/ui/servlets/LegacyUrlMapper.java
  src/main/java/teammates/ui/servlets/LoginServlet.java
  src/main/java/teammates/ui/servlets/LogoutServlet.java
  src/main/java/teammates/ui/servlets/OAuth2CallbackServlet.java
  src/main/java/teammates/ui/servlets/OriginCheckFilter.java
  src/main/java/teammates/ui/webapi/Action.java
  src/main/resources/logsForLocalDev.json
  src/main/webapp/WEB-INF/web.xml
  src/test/java/teammates/test/AbstractBackDoor.java
  src/test/java/teammates/ui/servlets/OriginCheckFilterTest.java
  src/test/java/teammates/ui/webapi/ActionFactoryTest.java
  src/web/app/pages-logs/__snapshots__/logs-page.component.spec.ts.snap
  src/web/app/pages-logs/logs-page.component.ts
  src/web/robots.txt
Labels: s.ToMerge, c.DevOps

#11340 [#11339] Update modal header to be more consistent
  src/web/app/pages-instructor/student-profile/more-info/more-info.component.ts
Labels: s.ToMerge, c.Feature

#11379 [#11372] Add more system logs
  src/main/java/teammates/common/datatransfer/logs/RequestLogDetails.java
  src/main/java/teammates/common/util/Logger.java
Labels: s.ToMerge, c.DevOps

#11325 [#11270] Fixed Alignment Issue with Checkboxes in Template Questions Modal
  src/web/app/pages-instructor/instructor-session-edit-page/template-question-modal/template-question-modal.component.scss
Labels: s.ToMerge

#11171 [#3530] Create tests for FeedbackResponseCommentsLogicTest::isNameVisibleToUser
  src/main/java/teammates/common/datatransfer/attributes/FeedbackResponseCommentAttributes.java
  src/test/java/teammates/logic/core/FeedbackResponseCommentsLogicTest.java
  src/test/resources/data/CourseRosterDataBundle.json
Labels: s.ToMerge

#11376 [#11375] Registration keys should be encrypted only before inserted into DB
  src/client/java/teammates/client/scripts/DataMigrationForUnencryptedKeyForInstructors.java
  src/client/java/teammates/client/scripts/DataMigrationForUnencryptedKeyForStudents.java
  src/e2e/java/teammates/e2e/cases/InstructorCourseJoinConfirmationPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/StudentCourseJoinConfirmationPageE2ETest.java
  src/main/java/teammates/common/datatransfer/attributes/InstructorAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/StudentAttributes.java
  src/main/java/teammates/common/exception/RegenerateStudentException.java
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/AccountsLogic.java
  src/main/java/teammates/logic/core/InstructorsLogic.java
  src/main/java/teammates/logic/core/StudentsLogic.java
  src/main/java/teammates/storage/api/EntitiesDb.java
  src/main/java/teammates/storage/api/InstructorsDb.java
  src/main/java/teammates/storage/api/StudentsDb.java
  src/main/java/teammates/storage/entity/CourseStudent.java
  src/main/java/teammates/storage/entity/Instructor.java
  src/main/java/teammates/ui/output/InstructorData.java
  src/main/java/teammates/ui/output/StudentData.java
  src/main/java/teammates/ui/webapi/CreateAccountAction.java
  src/main/java/teammates/ui/webapi/GetInstructorsAction.java
  src/main/java/teammates/ui/webapi/GetStudentAction.java
  src/main/java/teammates/ui/webapi/RegenerateStudentCourseLinksAction.java
  src/main/java/teammates/ui/webapi/SearchInstructorsAction.java
  src/main/java/teammates/ui/webapi/SearchStudentsAction.java
  src/test/java/teammates/logic/api/EmailGeneratorTest.java
  src/test/java/teammates/logic/core/AccountsLogicTest.java
  src/test/java/teammates/logic/core/InstructorsLogicTest.java
  src/test/java/teammates/logic/core/StudentsLogicTest.java
  src/test/java/teammates/storage/api/InstructorsDbTest.java
  src/test/java/teammates/storage/api/StudentsDbTest.java
  src/test/java/teammates/test/EmailChecker.java
  src/test/java/teammates/ui/webapi/CreateAccountActionTest.java
  src/test/java/teammates/ui/webapi/GetCourseJoinStatusActionTest.java
  src/test/java/teammates/ui/webapi/GetFeedbackQuestionRecipientsActionTest.java
  src/test/java/teammates/ui/webapi/GetRegkeyValidityActionTest.java
  src/test/java/teammates/ui/webapi/GetSessionResultsActionTest.java
  src/test/java/teammates/ui/webapi/GetStudentActionTest.java
  src/test/java/teammates/ui/webapi/JoinCourseActionTest.java
Labels: s.ToMerge, c.Task

#11350 [#11327] Compare table elements that are expected to be numbers numerically
  src/web/services/table-comparator.service.ts
Labels: s.ToMerge

#11271 [#11260] Instructor viewing students: incorrect message flashed before populating the page
  src/web/app/pages-instructor/instructor-course-details-page/__snapshots__/instructor-course-details-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.ts
Labels: s.ToMerge

#11272 [#11254] Instructor Feedback Session Results: Session Duration formatting
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackResultsPage.java
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.html
Labels: s.ToMerge

#11229 [#11219] Fix autoscrolling when viewing session result
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
Labels: s.ToMerge

#11378 [#11369] Prevent premature fetch copy course
  src/web/app/components/copy-course-modal/__snapshots__/copy-course-modal.component.spec.ts.snap
  src/web/app/components/copy-course-modal/copy-course-modal.component.html
  src/web/app/components/copy-course-modal/copy-course-modal.component.ts
  src/web/app/pages-instructor/instructor-courses-page/add-course-form/add-course-form.component.spec.ts
  src/web/app/pages-instructor/instructor-courses-page/add-course-form/add-course-form.component.ts
Labels: s.ToMerge

#11291 [#10920] Add tests for calculating statistics
  src/web/app/components/question-types/question-statistics/mcq-question-statistics.component.spec.ts
  src/web/app/components/question-types/question-statistics/msq-question-statistics.component.spec.ts
  src/web/app/components/question-types/question-statistics/num-scale-question-statistics.component.spec.ts
  src/web/app/components/question-types/question-statistics/rank-options-question-statistics.component.spec.ts
  src/web/app/components/question-types/question-statistics/rubric-question-statistics.component.spec.ts
  src/web/app/components/question-types/question-statistics/test-data/mcqQuestionResponses.json
  src/web/app/components/question-types/question-statistics/test-data/msqQuestionResponses.json
  src/web/app/components/question-types/question-statistics/test-data/numScaleQuestionResponses.json
  src/web/app/components/question-types/question-statistics/test-data/rankOptionQuestionResponses.json
  src/web/app/components/question-types/question-statistics/test-data/rubricQuestionResponses.json
Labels: s.ToMerge

#11361 [#9117] Delete course/session: remove the term 'soft-delete' from UI
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.html
Labels: s.ToMerge
