Repository TEAMMATES/teammates, pull requests merged in 2022-08, with the labels that each got.

#11915 [#11913] Update backend dependencies
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/client/java/teammates/client/scripts/statistics/FileStore.java
  src/e2e/java/teammates/e2e/pageobjects/FeedbackResultsPage.java
  src/e2e/java/teammates/e2e/pageobjects/FeedbackSubmitPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorCourseEditPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackResultsPage.java
  src/lnp/java/teammates/lnp/util/LNPSpecification.java
  src/main/java/teammates/common/datatransfer/AttributesDeletionQuery.java
  src/main/java/teammates/common/datatransfer/attributes/AccountAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/AccountRequestAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/CourseAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/DeadlineExtensionAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/FeedbackQuestionAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/FeedbackResponseAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/FeedbackResponseCommentAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/InstructorAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/NotificationAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/StudentAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/StudentProfileAttributes.java
  src/main/java/teammates/common/datatransfer/logs/QueryLogsParams.java
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/test/java/teammates/ui/webapi/UpdateFeedbackSessionActionTest.java
Labels: s.ToMerge, c.Task

#11922 [#11586] Fix errors due to missed instances of trimming of `@gmail.com`
  src/main/java/teammates/storage/api/AccountsDb.java
  src/main/java/teammates/storage/api/InstructorsDb.java
  src/main/java/teammates/storage/api/StudentsDb.java
Labels: c.Bug, s.ToMerge

#11923 [#11586] Remove trailing `@gmail.com` when checking for user ID equality
  src/main/java/teammates/ui/webapi/Action.java
  src/main/java/teammates/ui/webapi/BasicFeedbackSubmissionAction.java
  src/main/java/teammates/ui/webapi/DeleteStudentProfilePictureAction.java
  src/main/java/teammates/ui/webapi/GetRegkeyValidityAction.java
Labels: c.Bug, s.ToReview

#11926 [#11924] Fix bug where Course Enroll Page highlights the wrong rows
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts
Labels: c.Bug, s.ToMerge

#11930 [#9534] Deleting the last instructor in the course leaves a dangling course object in the database
  src/e2e/resources/data/AdminAccountsPageE2ETest.json
  src/main/java/teammates/ui/webapi/DeleteInstructorAction.java
  src/test/java/teammates/ui/webapi/DeleteInstructorActionTest.java
Labels: s.ToMerge, c.Task

#11940 [#11935] Fix instructors with custom permissions cannot view student list
  src/main/java/teammates/common/datatransfer/InstructorPrivileges.java
  src/main/java/teammates/common/datatransfer/attributes/InstructorAttributes.java
  src/main/java/teammates/ui/webapi/GateKeeper.java
  src/main/java/teammates/ui/webapi/GetStudentsAction.java
Labels: s.ToMerge

#11932 [#11839] Fix unusual feedback path causing an assertion failure when downloading results
  src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
Labels: s.ToMerge

#11937 [#10920] Add front-end tests for Instructor Session Page
  src/web/app/pages-instructor/instructor-sessions-page/__snapshots__/instructor-sessions-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.html
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.spec.ts
Labels: s.ToMerge, c.Task
