Repository TEAMMATES/teammates, pull requests merged in 2022-05, with the labels that each got.

#11775 [#11759] Instructor editing questions: tweak the confirmation dialog for cancelling an edit
  src/web/app/components/question-edit-form/question-edit-form.component.ts
Labels: c.Bug, s.ToMerge

#11777 [#11776] Refactor front-end tests to make TZ=UTC env unnecessary
  package.json
  src/web/app/components/notification-banner/notification-banner.component.spec.ts
  src/web/app/components/user-notifications-list/__snapshots__/user-notifications-list.component.spec.ts.snap
  src/web/app/components/user-notifications-list/user-notifications-list.component.spec.ts
  src/web/app/components/user-notifications-list/user-notifications-list.component.ts
  src/web/app/pages-admin/admin-notifications-page/__snapshots__/admin-notifications-page.component.spec.ts.snap
  src/web/app/pages-admin/admin-notifications-page/admin-notifications-page.component.spec.ts
  src/web/app/pages-admin/admin-notifications-page/notifications-table/notifications-table.component.spec.ts
  src/web/app/pages-instructor/instructor-notifications-page/__snapshots__/instructor-notifications-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-notifications-page/instructor-notifications-page.component.html
  src/web/app/pages-instructor/instructor-notifications-page/instructor-notifications-page.component.spec.ts
  src/web/app/pages-instructor/instructor-notifications-page/instructor-notifications-page.component.ts
  src/web/app/pages-student/student-notifications-page/__snapshots__/student-notifications-page.component.spec.ts.snap
  src/web/app/pages-student/student-notifications-page/student-notifications-page.component.html
  src/web/app/pages-student/student-notifications-page/student-notifications-page.component.spec.ts
  src/web/app/pages-student/student-notifications-page/student-notifications-page.component.ts
Labels: s.ToMerge, c.Task

#11792 [#11702] Update tzdb version to 2022a
  src/main/resources/tzdb.dat
  src/web/data/timezone.json
Labels: s.ToMerge, c.Task

#11798 [#8529] Instructor: remind particular students: give a 'send me a copy' tick box
  src/main/java/teammates/logic/api/TaskQueuer.java
  src/main/java/teammates/ui/request/FeedbackSessionRemindRequest.java
  src/main/java/teammates/ui/request/FeedbackSessionRespondentRemindRequest.java
  src/main/java/teammates/ui/webapi/FeedbackSessionRemindParticularUsersEmailWorkerAction.java
  src/main/java/teammates/ui/webapi/RemindFeedbackSessionSubmissionAction.java
  src/test/java/teammates/ui/webapi/FeedbackSessionRemindParticularUsersEmailWorkerActionTest.java
  src/test/java/teammates/ui/webapi/FeedbackSessionResendPublishedEmailWorkerActionTest.java
  src/web/app/components/sessions-table/send-reminders-to-respondents-modal/send-reminders-to-respondents-modal.component.html
  src/web/app/components/sessions-table/send-reminders-to-respondents-modal/send-reminders-to-respondents-modal.component.ts
  src/web/app/components/sessions-table/send-reminders-to-respondents-modal/send-reminders-to-respondents-model.ts
  src/web/app/pages-instructor/instructor-session-modal-page.component.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts
Labels: s.FinalReview, c.Feature

#11799 [#11724] Admin page header tabs do not fit header at certain screen sizes
  src/web/app/page.component.scss
  src/web/app/pages-admin/admin-page.component.ts
Labels: c.Bug, s.ToMerge

#11795 [#11794] Update instructor help page
  src/web/app/pages-help/instructor-help-page/instructor-help-courses-section/instructor-help-courses-section.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-getting-started/instructor-help-getting-started.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-page.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/sessions-section-questions.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.html
Labels: s.ToMerge, c.Feature

#11801 [#3530] Instructor: view results: add comprehensive tests for the different visibility options
  src/main/java/teammates/logic/core/FeedbackResponsesLogic.java
  src/test/java/teammates/logic/core/FeedbackResponsesLogicTest.java
  src/test/resources/data/FeedbackResponseVisibilityTest.json
Labels: s.ToMerge, c.Task

#11815 [#2488] Change STUDENTS and TEAMS to *_EXCLUDING_SELF for feedback paths
  src/client/java/teammates/client/scripts/DataMigrationForStudentsAndTeamsRecipientType.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java
  src/e2e/resources/data/FeedbackConstSumRecipientQuestionE2ETest.json
  src/e2e/resources/data/FeedbackMsqQuestionE2ETest.json
  src/e2e/resources/data/FeedbackNumScaleQuestionE2ETest.json
  src/e2e/resources/data/FeedbackRankOptionQuestionE2ETest.json
  src/e2e/resources/data/InstructorFeedbackEditPageE2ETest.json
  src/main/java/teammates/common/datatransfer/FeedbackParticipantType.java
  src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
  src/main/java/teammates/ui/webapi/BasicFeedbackSubmissionAction.java
  src/web/app/components/feedback-path-panel/feedback-path-panel.component.html
  src/web/app/components/question-edit-form/question-edit-form.component.ts
  src/web/app/components/teammates-common/feedback-path.pipe.spec.ts
  src/web/app/components/teammates-common/feedback-path.pipe.ts
  src/web/app/components/teammates-common/teammates-common.module.ts
  src/web/app/components/visibility-panel/visibility-panel.component.ts
  src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
  src/web/services/feedback-questions.service.ts
  src/web/services/visibility-state-machine.ts
Labels: s.ToMerge, c.Task

#11807 [#11669] Student prompted to login if session is not yet open
  src/main/java/teammates/ui/webapi/BasicFeedbackSubmissionAction.java
  src/web/app/pages-session/session-submission-page/session-submission-page.component.spec.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
  src/web/services/simple-modal.service.ts
Labels: c.Bug, s.ToMerge

#11806 [#11766] Admin search page: differentiate binned courses
  src/web/app/pages-admin/admin-home-page/admin-home-page.component.spec.ts
  src/web/app/pages-admin/admin-search-page/__snapshots__/admin-search-page.component.spec.ts.snap
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.html
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.scss
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.spec.ts
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.spec.ts
  src/web/services/search.service.ts
Labels: s.ToMerge, c.Feature

#11809 [#10645] Admin search results: show more info
  src/web/app/pages-admin/admin-search-page/__snapshots__/admin-search-page.component.spec.ts.snap
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.html
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.spec.ts
  src/web/services/link.service.spec.ts
  src/web/services/link.service.ts
  src/web/services/search.service.spec.ts
  src/web/services/search.service.ts
Labels: s.ToMerge, c.Feature

#11757 [#11706] Allow overriding of values in `build.properties` in dev server
  .gitignore
  build.gradle
  src/main/java/teammates/common/util/Config.java
  src/main/java/teammates/common/util/HttpRequestHelper.java
  src/main/java/teammates/common/util/Logger.java
  src/main/java/teammates/logic/api/EmailSender.java
  src/main/java/teammates/logic/api/FileStorage.java
  src/main/java/teammates/logic/api/LogsProcessor.java
  src/main/java/teammates/logic/api/RecaptchaVerifier.java
  src/main/java/teammates/logic/api/TaskQueuer.java
  src/main/java/teammates/storage/api/OfyHelper.java
  src/main/java/teammates/storage/search/SearchManager.java
  src/main/java/teammates/ui/servlets/AuthServlet.java
  src/main/java/teammates/ui/servlets/OriginCheckFilter.java
  src/main/java/teammates/ui/servlets/WebSecurityHeaderFilter.java
  src/main/java/teammates/ui/webapi/AdminExceptionTestAction.java
  src/main/java/teammates/ui/webapi/DatastoreBackupAction.java
  src/main/java/teammates/ui/webapi/DeleteDataBundleAction.java
  src/main/java/teammates/ui/webapi/GetDeadlineExtensionAction.java
  src/main/java/teammates/ui/webapi/JsonResult.java
  src/main/java/teammates/ui/webapi/PutDataBundleAction.java
  src/main/java/teammates/ui/webapi/PutDataBundleDocumentsAction.java
  src/main/resources/build-dev.template.properties
  src/main/resources/build.template.properties
  src/test/java/teammates/common/util/BuildPropertiesTest.java
  src/test/java/teammates/ui/servlets/OriginCheckFilterTest.java
Labels: s.ToMerge, c.DevOps

#11816 [#2874] Instructor help page revamp
  src/web/app/pages-help/instructor-help-page/instructor-help-getting-started/instructor-help-getting-started.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-page.module.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.scss
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.spec.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/sessions-section-questions.ts
Labels: s.ToMerge, c.Feature

#11820 [#11784] instructor viewing the 'Students' page: sort chronologically by default
  src/web/app/pages-instructor/instructor-student-list-page/__snapshots__/instructor-student-list-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.html
  src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts
Labels: s.ToMerge, c.Feature

#11836 [#11835] BaseE2ETestCase: logout() does not work properly when frontend and backend URLs are different
  src/e2e/java/teammates/e2e/cases/BaseE2ETestCase.java
Labels: s.ToMerge, c.Task
