Repository TEAMMATES/teammates, pull requests merged in 2022-02, with the labels that each got.

#11538 [#11235] Instructor audit logs: ensure end date is not before start date
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.html
Labels: c.Bug, s.ToMerge

#11541 [#11539] Feedback response submission: Requests sent to backend despite invalid response
  src/web/app/pages-session/session-submission-page/session-submission-page.component.spec.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
Labels: c.Bug, s.ToMerge

#11396 [#11371] Instructor sample data: defer until instructor joins
  src/e2e/java/teammates/e2e/cases/AdminHomePageE2ETest.java
  src/e2e/java/teammates/e2e/cases/BaseE2ETestCase.java
  src/e2e/java/teammates/e2e/cases/InstructorCourseJoinConfirmationPageE2ETest.java
  src/e2e/resources/data/InstructorCourseJoinConfirmationPageE2ETest.json
  src/main/java/teammates/common/datatransfer/DataBundle.java
  src/main/java/teammates/common/datatransfer/attributes/AccountRequestAttributes.java
  src/main/java/teammates/common/util/AppUrl.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/AccountRequestsLogic.java
  src/main/java/teammates/logic/core/DataBundleLogic.java
  src/main/java/teammates/storage/api/AccountRequestsDb.java
  src/main/java/teammates/storage/api/OfyHelper.java
  src/main/java/teammates/storage/entity/AccountRequest.java
  src/main/java/teammates/ui/constants/ResourceEndpoints.java
  src/main/java/teammates/ui/output/AccountRequestData.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/CreateAccountAction.java
  src/main/java/teammates/ui/webapi/CreateAccountRequestAction.java
  src/main/java/teammates/ui/webapi/DeleteAccountRequestAction.java
  src/main/java/teammates/ui/webapi/GetAccountRequestAction.java
  src/main/java/teammates/ui/webapi/GetCourseJoinStatusAction.java
  src/test/java/teammates/common/datatransfer/attributes/AccountRequestAttributesTest.java
  src/test/java/teammates/logic/core/AccountRequestsLogicTest.java
  src/test/java/teammates/storage/api/AccountRequestsDbTest.java
  src/test/java/teammates/test/AbstractBackDoor.java
  src/test/java/teammates/test/BaseTestCaseWithDatabaseAccess.java
  src/test/java/teammates/test/BaseTestCaseWithLocalDatabaseAccess.java
  src/test/java/teammates/ui/webapi/CreateAccountActionTest.java
  src/test/java/teammates/ui/webapi/CreateAccountRequestActionTest.java
  src/test/java/teammates/ui/webapi/DeleteAccountRequestActionTest.java
  src/test/java/teammates/ui/webapi/GetAccountRequestActionTest.java
  src/test/java/teammates/ui/webapi/GetActionClassesActionTest.java
  src/test/java/teammates/ui/webapi/GetCourseJoinStatusActionTest.java
  src/test/resources/data/typicalDataBundle.json
  src/web/app/__snapshots__/user-join-page.component.spec.ts.snap
  src/web/app/pages-admin/admin-home-page/admin-home-page.component.spec.ts
  src/web/app/pages-admin/admin-home-page/admin-home-page.component.ts
  src/web/app/user-join-page.component.html
  src/web/app/user-join-page.component.spec.ts
  src/web/app/user-join-page.component.ts
  src/web/app/user-join-page.module.ts
  src/web/services/account.service.spec.ts
  src/web/services/account.service.ts
  src/web/services/course.service.spec.ts
  src/web/services/course.service.ts
Labels: s.ToMerge, c.Feature

#11488 [#11357] Allow access to submission/results page for unregistered instructors
  src/main/java/teammates/common/util/Templates.java
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/main/java/teammates/ui/webapi/Action.java
  src/main/java/teammates/ui/webapi/BasicFeedbackSubmissionAction.java
  src/main/java/teammates/ui/webapi/GetFeedbackSessionAction.java
  src/main/java/teammates/ui/webapi/GetInstructorAction.java
  src/main/java/teammates/ui/webapi/GetRegkeyValidityAction.java
  src/main/java/teammates/ui/webapi/GetSessionResultsAction.java
  src/main/resources/instructorEmailFragment-courseJoin.html
  src/main/resources/instructorEmailFragment-reminderToJoinCourseBeforeSubmittingResponse.html
  src/main/resources/userEmailTemplate-feedbackSession.html
  src/test/java/teammates/logic/api/EmailGeneratorTest.java
  src/test/java/teammates/ui/webapi/GetFeedbackSessionActionTest.java
  src/test/java/teammates/ui/webapi/GetInstructorActionTest.java
  src/test/java/teammates/ui/webapi/GetRegkeyValidityActionTest.java
  src/test/java/teammates/ui/webapi/GetSessionResultsActionTest.java
  src/test/resources/emails/instructorCourseJoinEmail.html
  src/test/resources/emails/instructorCourseJoinEmailTestingSanitization.html
  src/test/resources/emails/sessionClosedEmailTestingSanitizationForStudent.html
  src/test/resources/emails/sessionClosingEmailForStudent.html
  src/test/resources/emails/sessionLinksRecoveryOpenedOrClosedAndpublishedSessions.html
  src/test/resources/emails/sessionLinksRecoveryOpenedOrClosedButUnpublishedSessions.html
  src/test/resources/emails/sessionOpeningEmailForStudent.html
  src/test/resources/emails/sessionOpeningEmailTestingSanitzationForStudent.html
  src/test/resources/emails/sessionOpeningSoonEmailForCoOwnerNotJoined.html
  src/test/resources/emails/sessionPublishedEmailForStudent.html
  src/test/resources/emails/sessionReminderEmailForInstructor.html
  src/test/resources/emails/sessionReminderEmailForInstructorNotJoinedYet.html
  src/test/resources/emails/sessionReminderEmailForStudent.html
  src/test/resources/emails/summaryOfFeedbackSessionsOfCourseEmailForRegeneratedInstructor.html
  src/test/resources/emails/summaryOfFeedbackSessionsOfCourseEmailForRegeneratedStudent.html
  src/test/resources/emails/summaryOfFeedbackSessionsOfCourseEmailForRegeneratedUnregisteredInstructor.html
  src/test/resources/emails/summaryOfFeedbackSessionsOfCourseEmailForRegeneratedUnregisteredStudent.html
  src/test/resources/emails/summaryOfFeedbackSessionsOfCourseEmailForStudent.html
  src/test/resources/emails/summaryOfFeedbackSessionsOfCourseEmailForUnregisteredStudent.html
  src/test/resources/emails/summaryOfFeedbackSessionsOfCourseEmailTestingSanitizationForStudent.html
  src/web/app/pages-admin/admin-search-page/__snapshots__/admin-search-page.component.spec.ts.snap
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.html
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.spec.ts
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.ts
  src/web/app/pages-session/session-result-page/__snapshots__/session-result-page.component.spec.ts.snap
  src/web/app/pages-session/session-result-page/session-result-page.component.html
  src/web/app/pages-session/session-result-page/session-result-page.component.ts
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
  src/web/app/pages-session/session-submission-page/session-submission-page.component.html
  src/web/app/pages-session/session-submission-page/session-submission-page.component.spec.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
  src/web/app/public-page.component.ts
  src/web/services/link.service.spec.ts
  src/web/services/link.service.ts
  src/web/services/search.service.spec.ts
  src/web/services/search.service.ts
Labels: s.ToMerge

#11550 [#11152] Student update profile: profile image does not display correctly when certain formats are used
  src/web/app/pages-student/student-profile-page/__snapshots__/student-profile-page.component.spec.ts.snap
  src/web/app/pages-student/student-profile-page/student-profile-page.component.html
  src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.html
  src/web/app/pages-student/student-profile-page/upload-edit-profile-picture-modal/upload-edit-profile-picture-modal.component.ts
Labels: c.Bug, s.ToMerge

#11560 [#11553] Make account requests searchable in admin search page
  solr/solr.sh
  src/e2e/java/teammates/e2e/cases/AdminSearchPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/AdminSearchPage.java
  src/e2e/java/teammates/e2e/util/TestDataValidityTest.java
  src/e2e/resources/data/AdminSearchPageE2ETest.json
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/api/TaskQueuer.java
  src/main/java/teammates/logic/core/AccountRequestsLogic.java
  src/main/java/teammates/logic/core/DataBundleLogic.java
  src/main/java/teammates/storage/api/AccountRequestsDb.java
  src/main/java/teammates/storage/search/AccountRequestSearchDocument.java
  src/main/java/teammates/storage/search/AccountRequestSearchManager.java
  src/main/java/teammates/storage/search/SearchManagerFactory.java
  src/main/java/teammates/storage/search/SearchManagerStarter.java
  src/main/java/teammates/ui/constants/ResourceEndpoints.java
  src/main/java/teammates/ui/output/AccountRequestData.java
  src/main/java/teammates/ui/output/AccountRequestsData.java
  src/main/java/teammates/ui/webapi/AccountRequestSearchIndexingWorkerAction.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/CreateAccountRequestAction.java
  src/main/java/teammates/ui/webapi/SearchAccountRequestsAction.java
  src/test/java/teammates/architecture/ArchitectureTest.java
  src/test/java/teammates/storage/search/AccountRequestSearchTest.java
  src/test/java/teammates/test/BaseTestCaseWithLocalDatabaseAccess.java
  src/test/java/teammates/ui/webapi/AccountRequestSearchIndexingWorkerActionTest.java
  src/test/java/teammates/ui/webapi/CreateAccountRequestActionTest.java
  src/test/java/teammates/ui/webapi/GetActionClassesActionTest.java
  src/test/java/teammates/ui/webapi/SearchAccountRequestsActionTest.java
  src/web/app/pages-admin/admin-search-page/__snapshots__/admin-search-page.component.spec.ts.snap
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.html
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.spec.ts
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.ts
  src/web/services/link.service.spec.ts
  src/web/services/link.service.ts
  src/web/services/search.service.spec.ts
  src/web/services/search.service.ts
Labels: s.ToMerge

#11557 [#8787] New instructors: set the time zone of the sample course to match user
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/webapi/CreateAccountAction.java
  src/test/java/teammates/storage/search/AccountRequestSearchTest.java
  src/test/java/teammates/ui/webapi/CreateAccountActionTest.java
  src/test/resources/data/typicalDataBundle.json
  src/web/app/__snapshots__/user-join-page.component.spec.ts.snap
  src/web/app/user-join-page.component.spec.ts
  src/web/app/user-join-page.component.ts
  src/web/services/account.service.spec.ts
  src/web/services/account.service.ts
Labels: s.ToMerge

#11510 [#11466] Add remind sub-menu to UI
  src/e2e/java/teammates/e2e/cases/InstructorFeedbackSessionsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorHomePageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackSessionsPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorHomePage.java
  src/e2e/resources/data/InstructorFeedbackSessionsPageE2ETest.json
  src/web/app/components/sessions-table/__snapshots__/sessions-table.component.spec.ts.snap
  src/web/app/components/sessions-table/send-reminders-to-respondents-modal/send-reminders-to-respondents-modal.component.ts
  src/web/app/components/sessions-table/sessions-table.component.html
  src/web/app/components/sessions-table/sessions-table.component.scss
  src/web/app/components/sessions-table/sessions-table.component.ts
  src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
  src/web/app/pages-instructor/instructor-session-modal-page.component.ts
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.html
Labels: s.ToMerge, c.Feature

#11546 [#9031] Allow adding of comment to MSQ questions
  src/e2e/java/teammates/e2e/cases/FeedbackResultsPageE2ETest.java
  src/e2e/resources/data/FeedbackResultsPageE2ETest.json
  src/main/java/teammates/common/datatransfer/questions/FeedbackMsqQuestionDetails.java
  src/main/java/teammates/ui/webapi/BasicCommentSubmissionAction.java
  src/main/java/teammates/ui/webapi/GetFeedbackResponsesAction.java
  src/test/java/teammates/common/datatransfer/questions/FeedbackMsqQuestionDetailsTest.java
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
  src/web/app/pages-session/session-submission-page/session-submission-page.component.spec.ts
  src/web/services/__snapshots__/session-result-csv.service.spec.ts.snap
  src/web/services/feedback-questions.service.ts
  src/web/services/session-result-csv.service.ts
  src/web/services/test-data/feedbackSessionResultsMsqResults.json
  src/web/types/question-details-impl/feedback-msq-question-details.impl.ts
Labels: s.ToMerge, c.Feature

#11549 [#11548] Add edit functionality for admins adding new instructors
  src/web/app/pages-admin/admin-home-page/__snapshots__/admin-home-page.component.spec.ts.snap
  src/web/app/pages-admin/admin-home-page/admin-home-page.component.html
  src/web/app/pages-admin/admin-home-page/admin-home-page.component.spec.ts
  src/web/app/pages-admin/admin-home-page/admin-home-page.component.ts
  src/web/app/pages-admin/admin-home-page/admin-home-page.module.ts
  src/web/app/pages-admin/admin-home-page/instructor-data.ts
  src/web/app/pages-admin/admin-home-page/new-instructor-data-row/__snapshots__/new-instructor-data-row.component.spec.ts.snap
  src/web/app/pages-admin/admin-home-page/new-instructor-data-row/new-instructor-data-row.component.html
  src/web/app/pages-admin/admin-home-page/new-instructor-data-row/new-instructor-data-row.component.scss
  src/web/app/pages-admin/admin-home-page/new-instructor-data-row/new-instructor-data-row.component.spec.ts
  src/web/app/pages-admin/admin-home-page/new-instructor-data-row/new-instructor-data-row.component.ts
Labels: s.ToMerge, c.Feature

#11563 [#11551] Fix incorrect message for student home page
  src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts
  src/web/app/pages-student/student-home-page/__snapshots__/student-home-page.component.spec.ts.snap
  src/web/app/pages-student/student-home-page/student-home-page.component.html
  src/web/app/pages-student/student-home-page/student-home-page.component.ts
Labels: c.Bug, s.ToMerge

#11542 [#11487] Disable mouse wheel events for number inputs
  src/web/app/components/question-types/question-edit-answer-form/constsum-options-question-edit-answer-form.component.html
  src/web/app/components/question-types/question-edit-answer-form/constsum-recipients-question-edit-answer-form.component.html
  src/web/app/components/question-types/question-edit-answer-form/num-scale-question-edit-answer-form.component.html
  src/web/app/components/question-types/question-edit-answer-form/question-edit-answer-form.module.ts
  src/web/app/components/wheel-disabler/wheel-disabler.directive.ts
  src/web/app/components/wheel-disabler/wheel-disabler.module.ts
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
Labels: c.Bug, s.ToMerge

#11580 [#9152] Add more SpotBugs rules
  build.gradle
  src/client/java/teammates/client/scripts/DataBundleRegenerator.java
  src/client/java/teammates/client/scripts/DataMigrationEntitiesBaseScript.java
  src/client/java/teammates/client/scripts/statistics/FileStore.java
  src/e2e/java/teammates/e2e/pageobjects/AdminSearchPage.java
  src/e2e/java/teammates/e2e/util/GmailServiceMaker.java
  src/e2e/java/teammates/e2e/util/TestDataValidityTest.java
  src/lnp/java/teammates/lnp/cases/BaseLNPTestCase.java
  src/lnp/java/teammates/lnp/cases/InstructorStudentCascadingUpdateLNPTest.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetails.java
  src/main/java/teammates/common/util/Config.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/common/util/SanitizationHelper.java
  src/main/java/teammates/common/util/StringHelper.java
  src/main/java/teammates/logic/core/GoogleCloudTasksService.java
  src/main/java/teammates/logic/core/LocalTaskQueueService.java
  src/main/java/teammates/ui/servlets/DevServerLoginServlet.java
  src/main/java/teammates/ui/servlets/LoginServlet.java
  src/main/java/teammates/ui/servlets/OAuth2CallbackServlet.java
  src/main/java/teammates/ui/webapi/DatastoreBackupAction.java
  src/main/java/teammates/ui/webapi/DeleteFeedbackResponseCommentAction.java
  src/main/java/teammates/ui/webapi/GetAuthInfoAction.java
  src/main/java/teammates/ui/webapi/GetHasResponsesAction.java
  src/main/java/teammates/ui/webapi/UpdateFeedbackResponseCommentAction.java
  src/test/java/teammates/common/datatransfer/questions/FeedbackQuestionDetailsTest.java
  src/test/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetailsTest.java
  src/test/java/teammates/common/util/StringHelperTest.java
  src/test/java/teammates/test/AbstractBackDoor.java
  src/test/java/teammates/test/MockHttpServletRequest.java
  src/test/java/teammates/test/MockHttpServletResponse.java
  static-analysis/teammates-spotbugs.xml
Labels: s.ToMerge, c.Task

#11581 [#11578] Make user cookie time sensitive
  src/main/java/teammates/common/datatransfer/UserInfoCookie.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/servlets/AuthServlet.java
  src/test/java/teammates/common/datatransfer/UserInfoCookieTest.java
Labels: s.ToMerge, c.Feature

#11593 [#11592] Wrong argument order in populateFieldsToGenerateInQuestion causes NPE
  src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
  src/test/java/teammates/logic/core/FeedbackQuestionsLogicTest.java
Labels: c.Bug, s.ToMerge

#11584 [#11583] Add account request entity to storage component diagram
  docs/diagrams/StorageComponent.puml
  docs/diagrams/style.puml
  docs/images/StorageComponent.png
Labels: s.ToMerge, c.Task
