Repository TEAMMATES/teammates, pull requests merged in 2022-01, with the labels that each got.

#11486 [#11147] Student view profile: preserve proportions of the profile image
  src/e2e/java/teammates/e2e/cases/StudentProfilePageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/StudentProfilePage.java
  src/test/resources/images/profile_pic_too_tall.jpg
  src/test/resources/images/profile_pic_too_wide.jpg
  src/web/app/pages-student/student-profile-page/student-profile-page.component.scss
Labels: c.Bug, s.ToMerge

#11515 [#11513] When the wrong Google account is used, include the account name in the error message
  src/web/app/page.component.html
Labels: s.ToMerge, c.Feature

#11517 [#11516] Use different messages for different auth callback problems
  src/main/java/teammates/ui/servlets/OAuth2CallbackServlet.java
Labels: s.ToMerge, c.Task

#11523 [#11492] Support configuring separate front-end URL for E2E testing
  src/e2e/java/teammates/e2e/cases/AdminAccountsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/AdminHomePageE2ETest.java
  src/e2e/java/teammates/e2e/cases/AdminSearchPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/AdminSessionsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/BaseE2ETestCase.java
  src/e2e/java/teammates/e2e/cases/BaseFeedbackQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackResultsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackSubmitPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorAuditLogsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorCourseDetailsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorCourseEditPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorCourseEnrollPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorCourseJoinConfirmationPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorCourseStudentDetailsEditPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorCourseStudentDetailsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorCoursesPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorFeedbackEditPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorFeedbackReportPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorFeedbackSessionsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorHomePageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorSearchPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorStudentListPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorStudentRecordsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/StudentCourseDetailsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/StudentCourseJoinConfirmationPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/StudentHomePageE2ETest.java
  src/e2e/java/teammates/e2e/cases/StudentProfilePageE2ETest.java
  src/e2e/java/teammates/e2e/cases/SystemErrorEmailReportE2ETest.java
  src/e2e/java/teammates/e2e/cases/TimezoneSyncerTest.java
  src/e2e/java/teammates/e2e/util/BackDoor.java
  src/e2e/java/teammates/e2e/util/TestProperties.java
  src/e2e/java/teammates/e2e/util/TestPropertiesTest.java
  src/e2e/resources/test.ci-chrome.properties
  src/e2e/resources/test.ci-edge.properties
  src/e2e/resources/test.ci-firefox.properties
  src/e2e/resources/test.template.properties
Labels: s.ToMerge, c.DevOps

#11496 [#11478] Include a list of non-submitters in the downloaded results
  src/e2e/java/teammates/e2e/cases/InstructorFeedbackReportPageE2ETest.java
  src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.ts
  src/web/app/pages-instructor/instructor-session-base-page.component.ts
  src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
  src/web/app/pages-instructor/instructor-session-modal-page.component.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.ts
  src/web/services/feedback-session-actions.service.ts
  src/web/services/feedback-sessions.service.ts
  src/web/services/session-result-csv.service.ts
Labels: s.ToMerge, c.Feature

#11482 [#8607] Student: edit submission: show evaluees in alphabetical order
  src/web/app/components/question-submission-form/question-submission-form.component.spec.ts
  src/web/app/components/question-submission-form/question-submission-form.component.ts
Labels: s.ToMerge, c.Feature

#11514 [#11528] Grammatical change on the contact us page
  src/web/app/pages-static/contact-page/contact-page.component.html
Labels: s.ToMerge, c.Task

#11505 [#11504] Update Dependencies
  build.gradle
Labels: s.Ongoing

#11512 [#11388] Remove numOf fields from question details structure
  src/e2e/java/teammates/e2e/cases/FeedbackConstSumOptionQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackMcqQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackRubricQuestionE2ETest.java
  src/e2e/resources/data/FeedbackConstSumOptionQuestionE2ETest.json
  src/e2e/resources/data/FeedbackConstSumRecipientQuestionE2ETest.json
  src/e2e/resources/data/FeedbackMcqQuestionE2ETest.json
  src/e2e/resources/data/FeedbackResultsPageE2ETest.json
  src/e2e/resources/data/FeedbackRubricQuestionE2ETest.json
  src/e2e/resources/data/FeedbackSubmitPageE2ETest.json
  src/e2e/resources/data/InstructorFeedbackReportPageE2ETest.json
  src/main/java/teammates/common/datatransfer/questions/FeedbackConstantSumQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackMcqQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetails.java
  src/main/java/teammates/ui/constants/QuestionTypeStructures.java
  src/main/resources/InstructorSampleData.json
  src/test/java/teammates/common/datatransfer/questions/FeedbackMcqQuestionDetailsTest.java
  src/test/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetailsTest.java
  src/test/resources/data/FeedbackResponseCommentCRUDTest.json
  src/test/resources/data/FeedbackSessionQuestionTypeTest.json
  src/web/app/components/question-text-with-info/question-text-with-info.component.spec.ts
  src/web/app/components/question-types/question-additional-info/mcq-question-additional-info.component.spec.ts
  src/web/app/components/question-types/question-edit-answer-form/mcq-question-edit-answer-form.component.ts
  src/web/app/components/question-types/question-edit-answer-form/rubric-question-edit-answer-form.component.ts
  src/web/app/components/question-types/question-edit-details-form/constsum-options-question-edit-details-form.component.ts
  src/web/app/components/question-types/question-edit-details-form/mcq-question-edit-details-form.component.html
  src/web/app/components/question-types/question-edit-details-form/mcq-question-edit-details-form.component.ts
  src/web/app/components/question-types/question-edit-details-form/rubric-question-edit-details-form.component.html
  src/web/app/components/question-types/question-edit-details-form/rubric-question-edit-details-form.component.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-data.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-data.ts
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.spec.ts
  src/web/app/pages-session/session-result-page/session-result-page.component.spec.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.component.spec.ts
  src/web/services/feedback-questions.service.ts
  src/web/services/test-data/feedbackSessionResultsConstsumResults.json
  src/web/services/test-data/feedbackSessionResultsConstsumResultsInstructorNoPrivilege.json
  src/web/services/test-data/feedbackSessionResultsMcqResults.json
  src/web/services/test-data/feedbackSessionResultsRubricResults.json
  src/web/services/test-data/feedbackSessionResultsStatistics.json
  src/web/types/question-details-impl/feedback-constsum-options-question-details.impl.ts
  src/web/types/question-details-impl/feedback-constsum-recipient-question-details.impl.ts
  src/web/types/question-details-impl/feedback-mcq-question-details.impl.ts
  src/web/types/question-details-impl/feedback-rubric-question-details.impl.ts
Labels: s.ToMerge, c.Task

#11530 [#11520] Infinite loop when logging in using Google account on a Chromium-based browser
  src/main/java/teammates/ui/servlets/AuthServlet.java
Labels: c.Bug, s.ToMerge

#11521 [#11295] Distribute points among options question: negative points allowed on frontend
  src/main/java/teammates/common/datatransfer/questions/FeedbackConstantSumQuestionDetails.java
  src/web/app/components/question-types/question-constraint/constsum-recipients-question-constraint.component.html
  src/web/app/components/question-types/question-constraint/constsum-recipients-question-constraint.component.ts
  src/web/app/components/question-types/question-edit-answer-form/constsum-options-question-edit-answer-form.component.html
  src/web/app/components/question-types/question-edit-answer-form/constsum-options-question-edit-answer-form.component.ts
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
Labels: c.Bug, s.ToMerge

#11518 [#11402] Submission status stays as pending for team submissions
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
  src/main/java/teammates/logic/core/FeedbackResponsesLogic.java
  src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/storage/api/FeedbackResponsesDb.java
  src/main/java/teammates/storage/entity/FeedbackResponse.java
  src/main/java/teammates/ui/webapi/FeedbackSessionRemindEmailWorkerAction.java
  src/main/java/teammates/ui/webapi/GetHasResponsesAction.java
  src/test/java/teammates/logic/core/FeedbackSessionsLogicTest.java
  src/test/java/teammates/ui/webapi/GetHasResponsesActionTest.java
  src/test/resources/data/FeedbackSessionsLogicTest.json
Labels: c.Bug, s.ToMerge
