Repository TEAMMATES/teammates, pull requests merged in 2022-12, with the labels that each got.

#11984 [#11210] Feedback Rubric Question: Suggestion for Statistics Per Recipient
  src/web/app/components/question-types/question-statistics/question-statistics-calculation/rubric-question-statistics-calculation.ts
  src/web/app/components/question-types/question-statistics/rubric-question-statistics.component.ts
  src/web/app/components/question-types/question-statistics/test-data/rubricQuestionResponses.json
  src/web/services/__snapshots__/session-result-csv.service.spec.ts.snap
  src/web/types/question-details-impl/feedback-rubric-question-details.impl.ts
  src/web/types/sort-properties.ts
Labels: s.ToMerge

#11995 [#11991] Student submitting fewer responses than allowed: show empty responses at the bottom when reloading the submission page
  src/web/app/components/question-submission-form/question-submission-form.component.ts
Labels: c.Bug, s.ToMerge

#11998 [#11993] Diagrams in the developer documentation are not being displayed
  docs/diagrams/Actors.puml
  docs/diagrams/ClientComponent.puml
  docs/diagrams/CommonComponent.puml
  docs/diagrams/DataTransferClasses.puml
  docs/diagrams/E2EComponent.puml
  docs/diagrams/IssueLifecycle.puml
  docs/diagrams/LogicComponent.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/StorageComponent.puml
  docs/diagrams/TestDriverComponent.puml
  docs/diagrams/UiComponent.puml
  docs/diagrams/UiWorkflow.puml
  docs/diagrams/highlevelArchitecture.puml
  docs/diagrams/packageDiagram.puml
Labels: s.ToMerge

#11887 [#8867] Student: submit responses: use a more friendly way to choose evaluee
  src/main/java/teammates/common/datatransfer/FeedbackQuestionRecipient.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
  src/main/java/teammates/ui/output/FeedbackQuestionRecipientData.java
  src/main/java/teammates/ui/output/FeedbackQuestionRecipientsData.java
  src/main/java/teammates/ui/webapi/GetFeedbackQuestionRecipientsAction.java
  src/main/java/teammates/ui/webapi/SubmitFeedbackResponsesAction.java
  src/test/java/teammates/logic/core/FeedbackQuestionsLogicTest.java
  src/web/app/components/question-submission-form/question-submission-form-model.ts
  src/web/app/components/question-submission-form/question-submission-form.component.html
  src/web/app/components/question-submission-form/question-submission-form.component.ts
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
Labels: s.FinalReview

#11977 [#10480] Highlight text on search in Admin Search Page
  src/e2e/java/teammates/e2e/pageobjects/AdminSearchPage.java
  src/web/app/pages-admin/admin-search-page/__snapshots__/admin-search-page.component.spec.ts.snap
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.html
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.scss
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.spec.ts
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.ts
  src/web/app/pages-admin/admin-search-page/admin-search-page.module.ts
Labels: s.ToMerge

#12008 [#11876] Improve UX of Progress Bars
  src/web/app/components/progress-bar/progress-bar.component.ts
Labels: s.ToMerge, c.Feature

#11942 [#11869] Student: Enhance UX when submitting response for a feedback question
  src/web/app/components/question-submission-form/question-submission-form.component.html
  src/web/app/components/question-submission-form/question-submission-form.component.ts
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
  src/web/app/pages-session/session-submission-page/session-submission-page.component.html
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
Labels: s.ToMerge, c.Feature

#12012 [#12009] Release V8.20.0
  src/web/data/developers.json
Labels: s.ToMerge, c.Release
