Repository TEAMMATES/teammates, pull requests merged in 2022-07, with the labels that each got.

#11894 [#11511] Emailing submission links: Mention the proof-of-submission feature
  src/main/resources/userEmailTemplate-deadlineExtension.html
  src/main/resources/userEmailTemplate-feedbackSession.html
  src/main/resources/userEmailTemplateFragment-feedbackSessionResendAllLinks.html
  src/test/resources/emails/deadlineExtensionGivenInstructor.html
  src/test/resources/emails/deadlineExtensionGivenStudent.html
  src/test/resources/emails/deadlineExtensionRevokedInstructor.html
  src/test/resources/emails/deadlineExtensionRevokedStudent.html
  src/test/resources/emails/deadlineExtensionUpdatedInstructor.html
  src/test/resources/emails/deadlineExtensionUpdatedStudent.html
  src/test/resources/emails/sessionClosingEmailCopyToInstructor.html
  src/test/resources/emails/sessionClosingEmailForInstructor.html
  src/test/resources/emails/sessionClosingEmailForInstructorWithExtension.html
  src/test/resources/emails/sessionClosingEmailForStudent.html
  src/test/resources/emails/sessionClosingEmailForStudentWithExtension.html
  src/test/resources/emails/sessionClosingEmailTestingSanitizationCopyToInstructor.html
  src/test/resources/emails/sessionClosingEmailTestingSanitizationForStudent.html
  src/test/resources/emails/sessionOpeningEmailCopyToInstructor.html
  src/test/resources/emails/sessionOpeningEmailForInstructor.html
  src/test/resources/emails/sessionOpeningEmailForStudent.html
  src/test/resources/emails/sessionOpeningEmailTestingSanitizationCopyToInstructor.html
  src/test/resources/emails/sessionOpeningEmailTestingSanitizationForStudent.html
  src/test/resources/emails/sessionReminderEmailCopyToInstructor.html
  src/test/resources/emails/sessionReminderEmailForInstructor.html
  src/test/resources/emails/sessionReminderEmailForStudent.html
  src/test/resources/emails/summaryOfFeedbackSessionsOfCourseEmailForRegeneratedInstructor.html
  src/test/resources/emails/summaryOfFeedbackSessionsOfCourseEmailForRegeneratedStudent.html
  src/test/resources/emails/summaryOfFeedbackSessionsOfCourseEmailForRegeneratedUnregisteredInstructor.html
  src/test/resources/emails/summaryOfFeedbackSessionsOfCourseEmailForRegeneratedUnregisteredStudent.html
  src/test/resources/emails/summaryOfFeedbackSessionsOfCourseEmailForStudent.html
  src/test/resources/emails/summaryOfFeedbackSessionsOfCourseEmailForUnregisteredStudent.html
  src/test/resources/emails/summaryOfFeedbackSessionsOfCourseEmailTestingSanitizationForStudent.html
Labels: s.ToMerge, c.Feature

#11892 [#11883] Admin/maintainer logs: Fix UI for small screen sizes
  src/web/app/pages-monitoring/logs-page/__snapshots__/logs-page.component.spec.ts.snap
  src/web/app/pages-monitoring/logs-page/logs-page.component.html
Labels: c.Bug, s.ToMerge

#11886 [#11885] Admin/Maintainer Logs: Fix extendStartTime function
  src/web/app/pages-monitoring/logs-page/logs-page.component.ts
Labels: c.Bug, s.ToMerge

#11880 [#11694] Admin/Maintainer Logs: Two loading spinner
  src/web/app/pages-monitoring/logs-page/__snapshots__/logs-page.component.spec.ts.snap
  src/web/app/pages-monitoring/logs-page/logs-page.component.html
  src/web/app/pages-monitoring/logs-page/logs-page.component.ts
Labels: c.Bug, s.ToMerge

#11881 [#11764] Give an easy way to extend deadline for non-submitters
  src/web/app/components/session-edit-form/session-edit-form.component.html
  src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-individual-extension-page/__snapshots__/instructor-session-individual-extension-page.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-individual-extension-page/instructor-session-individual-extension-page.component.ts
  src/web/app/pages-instructor/instructor-session-individual-extension-page/instructor-session-individual-extension-page.spec.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.spec.ts
Labels: s.ToMerge, c.Feature

#11849 [#7225] Instructor: support copying of instructors from existing courses
  src/e2e/java/teammates/e2e/cases/InstructorCourseEditPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorCourseEditPage.java
  src/e2e/resources/data/InstructorCourseEditPageE2ETest.json
  src/web/app/components/loading-retry/loading-retry.component.html
  src/web/app/components/loading-retry/loading-retry.component.ts
  src/web/app/pages-instructor/instructor-course-edit-page/__snapshots__/instructor-course-edit-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-course-edit-page/copy-instructors-from-other-courses-modal/__snapshots__/copy-instructors-from-other-courses-modal.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-course-edit-page/copy-instructors-from-other-courses-modal/copy-instructors-from-other-courses-modal-model.ts
  src/web/app/pages-instructor/instructor-course-edit-page/copy-instructors-from-other-courses-modal/copy-instructors-from-other-courses-modal.component.html
  src/web/app/pages-instructor/instructor-course-edit-page/copy-instructors-from-other-courses-modal/copy-instructors-from-other-courses-modal.component.scss
  src/web/app/pages-instructor/instructor-course-edit-page/copy-instructors-from-other-courses-modal/copy-instructors-from-other-courses-modal.component.spec.ts
  src/web/app/pages-instructor/instructor-course-edit-page/copy-instructors-from-other-courses-modal/copy-instructors-from-other-courses-modal.component.ts
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.html
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.scss
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.spec.ts
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.ts
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.module.ts
  src/web/services/table-comparator.service.ts
  src/web/types/sort-properties.ts
Labels: s.ToMerge, c.Feature

#11827 [#11772] team contribution questions: force submissions to be zero-sum
  src/e2e/java/teammates/e2e/cases/InstructorFeedbackEditPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/FeedbackSubmitPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java
  src/e2e/resources/data/FeedbackContributionQuestionE2ETest.json
  src/main/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetails.java
  src/test/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetailsTest.java
  src/test/java/teammates/ui/webapi/CreateFeedbackQuestionActionTest.java
  src/test/java/teammates/ui/webapi/UpdateFeedbackQuestionActionTest.java
  src/web/app/components/question-submission-form/question-submission-form.component.html
  src/web/app/components/question-types/question-constraint/contribution-question-constraint.component.html
  src/web/app/components/question-types/question-constraint/contribution-question-constraint.component.ts
  src/web/app/components/question-types/question-edit-answer-form/contribution-question-edit-answer-form.component.html
  src/web/app/components/question-types/question-edit-details-form/contribution-question-edit-details-form.component.html
  src/web/app/components/question-types/question-edit-details-form/contribution-question-edit-details-form.component.spec.ts
  src/web/app/components/question-types/question-edit-details-form/contribution-question-edit-details-form.component.ts
  src/web/app/components/question-types/question-edit-details-form/question-edit-details-form.module.ts
  src/web/app/components/question-types/question-instruction/contribution-question-instruction.component.html
  src/web/app/components/question-types/question-instruction/contribution-question-instruction.component.scss
  src/web/app/components/question-types/question-instruction/contribution-question-instruction.component.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.scss
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
  src/web/data/template-questions.json
  src/web/data/template-sessions.json
  src/web/types/question-details-impl/feedback-contribution-question-details.impl.ts
Labels: s.ToMerge, c.Feature

#11873 [#11868] Changes to team contribution question
  src/web/app/components/question-types/question-edit-answer-form/contribution-question-edit-answer-form.component.html
  src/web/app/components/question-types/question-edit-answer-form/contribution-question-edit-answer-form.component.scss
  src/web/app/components/question-types/question-edit-answer-form/contribution-question-edit-answer-form.component.ts
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
Labels: s.ToMerge, c.Feature

#11898 [#11772] Set `FeedbackContributionQuestionDetails.isZeroSum` of old questions to `false`
  src/client/java/teammates/client/scripts/DataMigrationForContributionQuestionDetailsIsZeroSum.java
Labels: s.ToReview

#11909 [#11908] Update Datastore emulator JRE version
  datastore-dev/Dockerfile
Labels: s.ToMerge, c.Task

#11902 [#11888] Fix Evaluee/Recipient being labelled as `Unknown`
  src/web/app/components/question-submission-form/recipient-type-name.pipe.ts
Labels: c.Bug, s.ToMerge

#11903 [#11586] Remove trimming of gmail.com for user accounts
  src/client/java/teammates/client/scripts/DataMigrationForGoogleIdToGmail.java
  src/main/java/teammates/common/util/FieldValidator.java
  src/main/java/teammates/common/util/SanitizationHelper.java
  src/main/java/teammates/storage/api/InstructorsDb.java
  src/main/java/teammates/storage/api/StudentsDb.java
  src/main/java/teammates/ui/servlets/DevServerLoginServlet.java
  src/main/java/teammates/ui/servlets/OAuth2CallbackServlet.java
  src/test/java/teammates/common/util/FieldValidatorTest.java
  src/test/java/teammates/common/util/SanitizationHelperTest.java
Labels: s.ToMerge, c.Task

#11914 [#11911] Instructor copying course: Progress bar does not load when no feedback sessions are copied
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts
Labels: c.Bug, s.ToMerge

#11893 [#11774] Fix error when copying feedback question
  src/main/java/teammates/ui/webapi/CreateFeedbackSessionAction.java
Labels: s.ToMerge

#11874 [#11825] Warn user before deleting last course
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts
Labels: a-UIX, s.ToMerge, c.Feature

#11918 [#11917] `QuestionSubmissionFormComponent` sorts `recipientList` and `recipientSubmissionForms` before being loaded
  src/web/app/components/question-submission-form/question-submission-form.component.spec.ts
  src/web/app/components/question-submission-form/question-submission-form.component.ts
Labels: c.Bug, s.ToMerge
