Repository TEAMMATES/teammates, pull requests merged in 2022-04, with the labels that each got.

#11663 [#11572] Notification feature - Admin page update (edit) feature
  src/web/app/pages-admin/admin-notifications-page/admin-notifications-page.component.html
  src/web/app/pages-admin/admin-notifications-page/admin-notifications-page.component.ts
  src/web/app/pages-admin/admin-notifications-page/notification-edit-form/notification-edit-form-model.ts
  src/web/app/pages-admin/admin-notifications-page/notification-edit-form/notification-edit-form.component.html
  src/web/app/pages-admin/admin-notifications-page/notification-edit-form/notification-edit-form.component.scss
  src/web/app/pages-admin/admin-notifications-page/notification-edit-form/notification-edit-form.component.ts
  src/web/app/pages-admin/admin-notifications-page/notifications-table/notifications-table-model.ts
  src/web/app/pages-admin/admin-notifications-page/notifications-table/notifications-table.component.html
  src/web/app/pages-admin/admin-notifications-page/notifications-table/notifications-table.component.ts
  src/web/services/notification.service.ts
Labels: s.FinalReview

#11698 [#11697] Remove projection query without index
  src/main/java/teammates/storage/api/InstructorsDb.java
Labels: c.Bug, s.ToMerge

#11691 [#11618] Usage statistics page for maintainers
  src/client/java/teammates/client/scripts/GenerateUsageStatisticsObjects.java
  src/main/java/teammates/ui/webapi/GetTimeZonesAction.java
  src/web/app/pages-admin/admin-page.component.ts
  src/web/app/pages-admin/admin-pages.module.ts
  src/web/app/pages-maintainer/maintainer-page.component.ts
  src/web/app/pages-maintainer/maintainer-page.module.ts
  src/web/app/pages-monitoring/logs-page/__snapshots__/logs-page.component.spec.ts.snap
  src/web/app/pages-monitoring/logs-page/logs-page.component.html
  src/web/app/pages-monitoring/logs-page/logs-page.component.scss
  src/web/app/pages-monitoring/logs-page/logs-page.component.spec.ts
  src/web/app/pages-monitoring/logs-page/logs-page.component.ts
  src/web/app/pages-monitoring/logs-page/logs-page.module.ts
  src/web/app/pages-monitoring/timezone-page/timezone-page.component.html
  src/web/app/pages-monitoring/timezone-page/timezone-page.component.scss
  src/web/app/pages-monitoring/timezone-page/timezone-page.component.spec.ts
  src/web/app/pages-monitoring/timezone-page/timezone-page.component.ts
  src/web/app/pages-monitoring/timezone-page/timezone-page.module.ts
  src/web/app/pages-monitoring/usage-stats-page/__snapshots__/usage-statistics-page.component.spec.ts.snap
  src/web/app/pages-monitoring/usage-stats-page/stats-line-chart/stats-line-chart.component.html
  src/web/app/pages-monitoring/usage-stats-page/stats-line-chart/stats-line-chart.component.scss
  src/web/app/pages-monitoring/usage-stats-page/stats-line-chart/stats-line-chart.component.spec.ts
  src/web/app/pages-monitoring/usage-stats-page/stats-line-chart/stats-line-chart.component.ts
  src/web/app/pages-monitoring/usage-stats-page/usage-statistics-page.component.html
  src/web/app/pages-monitoring/usage-stats-page/usage-statistics-page.component.scss
  src/web/app/pages-monitoring/usage-stats-page/usage-statistics-page.component.spec.ts
  src/web/app/pages-monitoring/usage-stats-page/usage-statistics-page.component.ts
  src/web/app/pages-monitoring/usage-stats-page/usage-statistics-page.module.ts
  src/web/services/usage-statistics.service.spec.ts
  src/web/services/usage-statistics.service.ts
Labels: s.ToMerge, c.Feature

#11699 [#11693] Student submitting MCQ question: comments are not loading
  src/web/app/components/comment-box/comment-row/comment-row.component.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.component.spec.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
Labels: c.Bug, s.ToMerge

#11700 [#11572] Notification feature - Fix edit button and move style demo to the side
  src/web/app/pages-admin/admin-notifications-page/admin-notifications-page.component.ts
  src/web/app/pages-admin/admin-notifications-page/notification-edit-form/notification-edit-form.component.html
  src/web/app/pages-admin/admin-notifications-page/notification-edit-form/notification-edit-form.component.ts
Labels: s.ToMerge

#11701 [#11572] Notification feature - Add tests PUT and DELETE route
  src/main/java/teammates/ui/webapi/DeleteNotificationAction.java
  src/test/java/teammates/ui/webapi/CreateNotificationActionTest.java
  src/test/java/teammates/ui/webapi/DeleteNotificationActionTest.java
  src/test/java/teammates/ui/webapi/UpdateNotificationActionTest.java
Labels: s.ToMerge

#11696 [#11572] Notification Feature - Notification Logic Tests
  src/test/java/teammates/logic/core/NotificationsLogicTest.java
  src/test/java/teammates/storage/api/NotificationsDbTest.java
Labels: s.ToMerge

#11695 [#11572] Notification Feature - E2E tests for admin features
  src/e2e/java/teammates/e2e/cases/AdminNotificationsPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/AdminNotificationsPage.java
  src/e2e/resources/data/AdminNotificationsPageE2ETest.json
  src/e2e/resources/testng-e2e.xml
  src/main/java/teammates/common/util/Const.java
  src/test/java/teammates/test/AbstractBackDoor.java
  src/test/java/teammates/test/BaseTestCaseWithDatabaseAccess.java
  src/test/resources/data/typicalDataBundle.json
  src/web/app/pages-admin/admin-notifications-page/admin-notifications-page.component.html
  src/web/app/pages-admin/admin-notifications-page/admin-notifications-page.component.ts
  src/web/app/pages-admin/admin-notifications-page/notification-edit-form/notification-edit-form.component.html
  src/web/app/pages-admin/admin-notifications-page/notification-edit-form/notification-edit-form.component.ts
  src/web/app/pages-admin/admin-notifications-page/notifications-table/notifications-table.component.html
  src/web/app/pages-admin/admin-notifications-page/notifications-table/notifications-table.component.ts
Labels: s.ToMerge

#11686 [#11591] Fix E2E Tests (Firefox) Failing Consistently
  .github/workflows/e2e.yml
  build.gradle
  src/e2e/java/teammates/e2e/pageobjects/AdminHomePage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackResultsPage.java
Labels: s.ToMerge, c.Task

#11605 [#11245] Support running client scripts via Gradle
  build.gradle
Labels: s.ToMerge

#11643 [#11572] Notification feature - Add read notifications to Account entity
  src/e2e/resources/data/AdminAccountsPageE2ETest.json
  src/e2e/resources/data/AdminSearchPageE2ETest.json
  src/e2e/resources/data/AdminSessionsPageE2ETest.json
  src/e2e/resources/data/AutomatedSessionRemindersE2ETest.json
  src/e2e/resources/data/FeedbackConstSumOptionQuestionE2ETest.json
  src/e2e/resources/data/FeedbackConstSumRecipientQuestionE2ETest.json
  src/e2e/resources/data/FeedbackContributionQuestionE2ETest.json
  src/e2e/resources/data/FeedbackMcqQuestionE2ETest.json
  src/e2e/resources/data/FeedbackMsqQuestionE2ETest.json
  src/e2e/resources/data/FeedbackNumScaleQuestionE2ETest.json
  src/e2e/resources/data/FeedbackRankOptionQuestionE2ETest.json
  src/e2e/resources/data/FeedbackRankRecipientQuestionE2ETest.json
  src/e2e/resources/data/FeedbackResultsPageE2ETest.json
  src/e2e/resources/data/FeedbackRubricQuestionE2ETest.json
  src/e2e/resources/data/FeedbackSubmitPageE2ETest.json
  src/e2e/resources/data/FeedbackTextQuestionE2ETest.json
  src/e2e/resources/data/InstructorAuditLogsPageE2ETest.json
  src/e2e/resources/data/InstructorCourseDetailsPageE2ETest.json
  src/e2e/resources/data/InstructorCourseEditPageE2ETest.json
  src/e2e/resources/data/InstructorCourseEnrollPageE2ETest.json
  src/e2e/resources/data/InstructorCourseJoinConfirmationPageE2ETest.json
  src/e2e/resources/data/InstructorCourseStudentDetailsEditPageE2ETest.json
  src/e2e/resources/data/InstructorCourseStudentDetailsPageE2ETest.json
  src/e2e/resources/data/InstructorCoursesPageE2ETest.json
  src/e2e/resources/data/InstructorFeedbackEditPageE2ETest.json
  src/e2e/resources/data/InstructorFeedbackReportPageE2ETest.json
  src/e2e/resources/data/InstructorFeedbackSessionsPageE2ETest.json
  src/e2e/resources/data/InstructorHomePageE2ETest.json
  src/e2e/resources/data/InstructorSearchPageE2ETest.json
  src/e2e/resources/data/InstructorStudentListPageE2ETest.json
  src/e2e/resources/data/InstructorStudentRecordsPageE2ETest.json
  src/e2e/resources/data/StudentCourseDetailsPageE2ETest.json
  src/e2e/resources/data/StudentCourseJoinConfirmationPageE2ETest.json
  src/e2e/resources/data/StudentHomePageE2ETest.json
  src/e2e/resources/data/StudentProfilePageE2ETest.json
  src/main/java/teammates/common/datatransfer/attributes/AccountAttributes.java
  src/main/java/teammates/storage/api/AccountsDb.java
  src/main/java/teammates/storage/entity/Account.java
  src/main/java/teammates/ui/output/AccountData.java
  src/test/java/teammates/common/datatransfer/attributes/AccountAttributesTest.java
  src/test/java/teammates/storage/api/AccountsDbTest.java
  src/test/java/teammates/ui/webapi/GetAccountActionTest.java
  src/test/resources/data/EmailGeneratorTest.json
  src/test/resources/data/FeedbackContributionQuestionTest.json
  src/test/resources/data/FeedbackResponseCommentCRUDTest.json
  src/test/resources/data/FeedbackSessionQuestionTypeTest.json
  src/test/resources/data/FeedbackSessionResultsBundleTest.json
  src/test/resources/data/FeedbackSessionResultsTest.json
  src/test/resources/data/FeedbackSessionsLogicTest.json
  src/test/resources/data/GetCoursesActionTest.json
  src/test/resources/data/GetFeedbackQuestionRecipientsActionTest.json
  src/test/resources/data/SpecialCharacterTest.json
  src/test/resources/data/typicalDataBundle.json
  src/web/app/pages-admin/admin-accounts-page/admin-accounts-page.component.ts
  src/web/app/pages-admin/admin-home-page/admin-home-page.component.spec.ts
Labels: s.ToMerge

#11679 [#11150] Search page: Remove unnecessary panel
  src/web/app/pages-instructor/instructor-search-page/__snapshots__/instructor-search-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-search-page/instructor-search-bar/instructor-search-bar.component.html
  src/web/app/pages-instructor/instructor-search-page/student-result-table/student-result-table.component.html
Labels: c.Bug, s.ToMerge

#11713 [#11710] Instructor Help Page: Outdated search bar documentation
  src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.html
Labels: c.Bug, s.ToMerge

#11678 [#11572] Notification feature: Frontend test for admin features
  package.json
  src/web/app/pages-admin/admin-notifications-page/__snapshots__/admin-notifications-page.component.spec.ts.snap
  src/web/app/pages-admin/admin-notifications-page/admin-notifications-page.component.spec.ts
  src/web/app/pages-admin/admin-notifications-page/admin-notifications-page.component.ts
  src/web/app/pages-admin/admin-notifications-page/notification-edit-form/__snapshots__/notification-edit-form.component.spec.ts.snap
  src/web/app/pages-admin/admin-notifications-page/notification-edit-form/notification-edit-form.component.spec.ts
  src/web/app/pages-admin/admin-notifications-page/notifications-table/__snapshots__/notifications-table.component.spec.ts.snap
  src/web/app/pages-admin/admin-notifications-page/notifications-table/notifications-table.component.spec.ts
  src/web/services/notification.service.spec.ts
Labels: s.ToMerge

#11714 [#11497] Fix server error when retrieving log entries from cloud logging
  src/main/java/teammates/logic/external/GoogleCloudLoggingService.java
Labels: c.Bug, s.ToMerge

#11716 [#11715] Selective Deadline Extension - Error in getting deadline extension entities possibly needing closing email
  src/main/appengine/index.yaml
Labels: s.ToMerge

#11653 [#11572] Notification feature - User notification page
  src/main/appengine/index.yaml
  src/web/app/components/user-notifications-list/user-notifications-list.component.html
  src/web/app/components/user-notifications-list/user-notifications-list.component.scss
  src/web/app/components/user-notifications-list/user-notifications-list.component.spec.ts
  src/web/app/components/user-notifications-list/user-notifications-list.component.ts
  src/web/app/components/user-notifications-list/user-notifications-list.module.ts
  src/web/app/pages-instructor/instructor-notifications-page/instructor-notifications-page.component.html
  src/web/app/pages-instructor/instructor-notifications-page/instructor-notifications-page.component.scss
  src/web/app/pages-instructor/instructor-notifications-page/instructor-notifications-page.component.spec.ts
  src/web/app/pages-instructor/instructor-notifications-page/instructor-notifications-page.component.ts
  src/web/app/pages-instructor/instructor-notifications-page/instructor-notifications-page.module.ts
  src/web/app/pages-instructor/instructor-page.component.ts
  src/web/app/pages-instructor/instructor-pages.module.ts
  src/web/app/pages-student/student-notifications-page/student-notifications-page.component.html
  src/web/app/pages-student/student-notifications-page/student-notifications-page.component.scss
  src/web/app/pages-student/student-notifications-page/student-notifications-page.component.spec.ts
  src/web/app/pages-student/student-notifications-page/student-notifications-page.component.ts
  src/web/app/pages-student/student-notifications-page/student-notifications-page.module.ts
  src/web/app/pages-student/student-page.component.ts
  src/web/app/pages-student/student-pages.module.ts
  src/web/services/notification.service.ts
Labels: s.ToMerge

#11723 [#11721] Selective deadline extension - NPE when submitting feedback responses
  src/main/java/teammates/ui/webapi/SubmitFeedbackResponsesAction.java
Labels: s.ToMerge

#11661 [#11572] Notification Feature - Add mark as read to notification GET API
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/AccountsLogic.java
  src/main/java/teammates/ui/output/NotificationData.java
  src/main/java/teammates/ui/webapi/Action.java
  src/main/java/teammates/ui/webapi/GetNotificationsAction.java
  src/test/java/teammates/ui/webapi/GetNotificationsActionTest.java
  src/test/resources/data/typicalDataBundle.json
Labels: s.ToMerge, c.Task

#11680 [#11683] MarkBind website for developer docs
  .github/workflows/dev-docs.yml
  .gitignore
  docs/CONTRIBUTING.md
  docs/SUPPORT.md
  docs/_markbind/layouts/default.md
  docs/_markbind/variables.md
  docs/best-practices/coding.md
  docs/best-practices/data-migration.md
  docs/best-practices/testing.md
  docs/best-practices/ui-design.md
  docs/captcha.md
  docs/contributing-doc.md
  docs/design.md
  docs/development.md
  docs/diagrams/ClientComponent.puml
  docs/diagrams/CommonComponent.puml
  docs/diagrams/DataTransferClasses.puml
  docs/diagrams/E2EComponent.puml
  docs/diagrams/LogicComponent.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/StorageComponent.puml
  docs/diagrams/TestDriverComponent.puml
  docs/diagrams/UiComponent.puml
  docs/diagrams/UiWorkflow.puml
  docs/diagrams/packageDiagram.puml
  docs/documentation.md
  docs/e2e-testing.md
  docs/emails.md
  docs/glossary.md
  docs/images/ClientComponent.png
  docs/images/CommonComponent.png
  docs/images/E2EComponent.png
  docs/images/LogicComponent.png
  docs/images/StorageClassDiagram.png
  docs/images/StorageComponent.png
  docs/images/TestDriverComponent.png
  docs/images/UiComponent.png
  docs/images/UiWorkflow.png
  docs/images/dataTransferClasses.png
  docs/images/packageDiagram.png
  docs/images/saucelabs.png
  docs/images/teammatesIcon.png
  docs/images/teammateslogo.png
  docs/images/yklogo.png
  docs/index.md
  docs/issues.md
  docs/overview.md
  docs/package-lock.json
  docs/package.json
  docs/performance-testing.md
  docs/process.md
  docs/search.md
  docs/setting-up.md
  docs/site.json
  docs/snapshot-testing.md
  docs/static-analysis.md
  docs/stylesheets/main.css
  docs/troubleshooting-guide.md
Labels: s.ToMerge, c.Feature

#11664 [#11572] Notification Feature - POST API for readNotifications in AccountEntity
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/AccountsLogic.java
  src/main/java/teammates/logic/core/NotificationsLogic.java
  src/main/java/teammates/storage/api/NotificationsDb.java
  src/main/java/teammates/ui/constants/ResourceEndpoints.java
  src/main/java/teammates/ui/request/MarkNotificationAsReadRequest.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/CreateFeedbackQuestionAction.java
  src/main/java/teammates/ui/webapi/MarkNotificationAsReadAction.java
  src/test/java/teammates/logic/core/AccountsLogicTest.java
  src/test/java/teammates/logic/core/NotificationsLogicTest.java
  src/test/java/teammates/storage/api/NotificationsDbTest.java
  src/test/java/teammates/ui/webapi/GetActionClassesActionTest.java
  src/test/java/teammates/ui/webapi/MarkNotificationAsReadActionTest.java
  src/test/resources/data/typicalDataBundle.json
Labels: s.ToMerge, c.Feature

#11720 [#11572] Notification Feature - Notification Banner
  src/e2e/java/teammates/e2e/cases/AdminNotificationsPageE2ETest.java
  src/main/java/teammates/common/util/FieldValidator.java
  src/main/java/teammates/ui/webapi/GetNotificationsAction.java
  src/web/app/app.module.ts
  src/web/app/components/notification-banner/notification-banner.component.html
  src/web/app/components/notification-banner/notification-banner.component.scss
  src/web/app/components/notification-banner/notification-banner.component.spec.ts
  src/web/app/components/notification-banner/notification-banner.component.ts
  src/web/app/components/notification-banner/notification-banner.module.ts
  src/web/app/components/teammates-common/notification-style-class.pipe.ts
  src/web/app/components/user-notifications-list/user-notifications-list.component.ts
  src/web/app/page.component.html
  src/web/app/page.component.spec.ts
  src/web/app/page.component.ts
  src/web/app/pages-admin/admin-notifications-page/__snapshots__/admin-notifications-page.component.spec.ts.snap
  src/web/app/pages-admin/admin-notifications-page/notification-edit-form/__snapshots__/notification-edit-form.component.spec.ts.snap
  src/web/app/pages-admin/admin-notifications-page/notifications-table/__snapshots__/notifications-table.component.spec.ts.snap
  src/web/app/pages-admin/admin-page.component.spec.ts
  src/web/app/pages-instructor/instructor-page.component.html
  src/web/app/pages-instructor/instructor-page.component.spec.ts
  src/web/app/pages-instructor/instructor-page.component.ts
  src/web/app/pages-maintainer/maintainer-page.component.spec.ts
  src/web/app/pages-static/static-page.component.spec.ts
  src/web/app/pages-student/student-page.component.html
  src/web/app/pages-student/student-page.component.spec.ts
  src/web/app/pages-student/student-page.component.ts
  src/web/app/public-page.component.spec.ts
  src/web/services/notification.service.ts
Labels: s.ToMerge, c.Feature

#11734 [#11732] Broken PUML diagrams in developer guide
  .github/workflows/dev-docs.yml
  docs/documentation.md
Labels: c.Bug, s.ToMerge

#11730 [#11729] Update supported browsers list + add IE deprecation warning
  src/web/app/page.component.html
  src/web/app/page.component.ts
Labels: s.ToMerge, c.Task

#11731 [#11572] Notification Feature - Add Mark As Read to Past Notification Page
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/AccountsLogic.java
  src/main/java/teammates/ui/output/ReadNotificationsData.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/GetReadNotificationsAction.java
  src/main/java/teammates/ui/webapi/MarkNotificationAsReadAction.java
  src/test/java/teammates/logic/core/AccountsLogicTest.java
  src/test/java/teammates/ui/webapi/GetActionClassesActionTest.java
  src/test/java/teammates/ui/webapi/GetReadNotificationsActionTest.java
  src/test/java/teammates/ui/webapi/MarkNotificationAsReadActionTest.java
  src/web/app/components/notification-banner/notification-banner.component.ts
  src/web/app/components/user-notifications-list/user-notifications-list.component.html
  src/web/app/components/user-notifications-list/user-notifications-list.component.ts
  src/web/app/page.component.html
  src/web/app/page.component.ts
  src/web/services/notification.service.ts
Labels: s.ToMerge, c.Feature

#11738 [#11572] Notification Feature - Add test for GetNotificationAction and fix comments
  src/main/java/teammates/common/datatransfer/attributes/NotificationAttributes.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/storage/api/NotificationsDb.java
  src/main/java/teammates/ui/output/NotificationData.java
  src/main/java/teammates/ui/webapi/GetNotificationAction.java
  src/test/java/teammates/test/AbstractBackDoor.java
  src/test/java/teammates/ui/webapi/GetNotificationActionTest.java
  src/test/java/teammates/ui/webapi/GetNotificationsActionTest.java
  src/web/app/pages-admin/admin-notifications-page/__snapshots__/admin-notifications-page.component.spec.ts.snap
  src/web/app/pages-admin/admin-notifications-page/admin-notifications-page.component.spec.ts
  src/web/app/pages-admin/admin-notifications-page/notification-edit-form/__snapshots__/notification-edit-form.component.spec.ts.snap
  src/web/app/pages-admin/admin-notifications-page/notification-edit-form/notification-edit-form.component.html
  src/web/app/pages-admin/admin-notifications-page/notifications-table/notifications-table.component.spec.ts
Labels: s.ToMerge, c.Task

#11739 [#11572] Notification feature - Fix permission problem for instructors
  src/main/java/teammates/ui/webapi/GetNotificationsAction.java
  src/web/app/components/user-notifications-list/user-notifications-list.component.html
  src/web/app/page.component.html
Labels: c.Bug, s.ToReview

#11743 [#11572] Notification Feature - Add warning if admin edits shown notifications
  src/web/app/pages-admin/admin-notifications-page/__snapshots__/admin-notifications-page.component.spec.ts.snap
  src/web/app/pages-admin/admin-notifications-page/notification-edit-form/__snapshots__/notification-edit-form.component.spec.ts.snap
  src/web/app/pages-admin/admin-notifications-page/notification-edit-form/notification-edit-form.component.html
  src/web/app/pages-admin/admin-notifications-page/notification-edit-form/notification-edit-form.component.spec.ts
Labels: s.ToMerge, c.Feature

#11628 [#8000] GetStudentsAction: prevent access by instructors without view students privileges
  src/e2e/java/teammates/e2e/cases/InstructorStudentListPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorStudentListPage.java
  src/main/java/teammates/ui/webapi/GetStudentsAction.java
  src/test/java/teammates/ui/webapi/GetStudentsActionTest.java
  src/web/app/pages-instructor/instructor-student-list-page/__snapshots__/instructor-student-list-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.html
  src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.spec.ts
  src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.ts
Labels: c.Bug, s.ToMerge

#11567 [#11015] break down question result fetch by section
  src/main/java/teammates/common/datatransfer/FeedbackResultFetchType.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/FeedbackResponsesLogic.java
  src/main/java/teammates/storage/api/FeedbackResponsesDb.java
  src/main/java/teammates/ui/webapi/GetSessionResultsAction.java
  src/test/java/teammates/logic/core/FeedbackResponsesLogicTest.java
  src/test/java/teammates/storage/api/FeedbackResponsesDbTest.java
  src/test/java/teammates/ui/webapi/GetSessionResultsActionTest.java
  src/web/app/components/question-types/question-statistics/question-statistics.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts
  src/web/services/feedback-sessions.service.ts
Labels: s.ToMerge, c.Task

#11747 [#11572] Notification Feature - Remove notif banner sticky behaviour
  src/web/app/components/notification-banner/notification-banner.component.scss
  src/web/app/page.component.html
Labels: c.Bug, s.ToMerge

#11718 [#11717] Broken link in acknowledgements section
  README.md
  src/web/app/pages-static/about-page/about-page.component.html
Labels: c.Bug, s.ToMerge

#11704 [#11571] Selective Deadline Extensions - Add danger modal for session end time
  src/web/app/components/extension-confirm-modal/__snapshots__/extension-confirm-modal.component.spec.ts.snap
  src/web/app/components/extension-confirm-modal/extension-confirm-modal.component.html
  src/web/app/components/extension-confirm-modal/extension-confirm-modal.component.scss
  src/web/app/components/extension-confirm-modal/extension-confirm-modal.component.spec.ts
  src/web/app/components/extension-confirm-modal/extension-confirm-modal.component.ts
  src/web/app/components/extension-confirm-modal/extension-confirm-modal.module.ts
  src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.html
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.spec.ts
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.module.ts
  src/web/app/pages-instructor/instructor-session-individual-extension-page/instructor-session-individual-extension-page.component.ts
  src/web/app/pages-instructor/instructor-session-individual-extension-page/instructor-session-individual-extension-page.module.ts
  src/web/services/deadline-extension-helper.spec.ts
  src/web/services/deadline-extension-helper.ts
Labels: s.ToMerge, c.Feature

#11742 [#11572] Notification Feature - E2E Tests for User Notifications Page
  src/e2e/java/teammates/e2e/cases/AdminNotificationsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorNotificationsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/StudentNotificationsPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorNotificationsPage.java
  src/e2e/java/teammates/e2e/pageobjects/StudentNotificationsPage.java
  src/e2e/java/teammates/e2e/pageobjects/UserNotificationsPage.java
  src/e2e/java/teammates/e2e/util/TestDataValidityTest.java
  src/e2e/resources/data/AdminNotificationsPageE2ETest.json
  src/e2e/resources/data/InstructorNotificationsPageE2ETest.json
  src/e2e/resources/data/StudentNotificationsPageE2ETest.json
  src/e2e/resources/testng-e2e.xml
  src/main/java/teammates/common/util/Const.java
  src/test/java/teammates/test/AbstractBackDoor.java
  src/test/resources/data/typicalDataBundle.json
  src/web/app/components/user-notifications-list/user-notifications-list.component.html
Labels: s.ToMerge, c.Task

#11709 [#11571] Selective deadline extension: E2E Tests
  src/e2e/java/teammates/e2e/cases/BaseE2ETestCase.java
  src/e2e/java/teammates/e2e/cases/InstructorSessionIndividualExtensionPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorSessionIndividualExtensionPage.java
  src/e2e/java/teammates/e2e/util/TestDataValidityTest.java
  src/e2e/resources/data/InstructorSessionIndividualExtensionPageE2ETest.json
  src/e2e/resources/testng-e2e.xml
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/output/DeadlineExtensionData.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/GetDeadlineExtensionAction.java
  src/test/java/teammates/test/AbstractBackDoor.java
  src/test/java/teammates/ui/webapi/GetActionClassesActionTest.java
  src/test/java/teammates/ui/webapi/GetDeadlineExtensionActionTest.java
  src/web/app/pages-instructor/instructor-session-individual-extension-page/__snapshots__/instructor-session-individual-extension-page.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-individual-extension-page/individual-extension-date-modal/__snapshots__/individual-extension-date-modal.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-individual-extension-page/individual-extension-date-modal/individual-extension-date-modal.component.html
  src/web/app/pages-instructor/instructor-session-individual-extension-page/instructor-session-individual-extension-page.component.html
Labels: s.ToMerge, c.Task

#11735 [#11571] Rename sanitize methods
  src/main/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributes.java
  src/main/java/teammates/ui/webapi/CreateFeedbackResponseCommentAction.java
  src/main/java/teammates/ui/webapi/DeleteFeedbackResponseCommentAction.java
  src/main/java/teammates/ui/webapi/GetFeedbackSessionAction.java
  src/main/java/teammates/ui/webapi/GetFeedbackSessionsAction.java
  src/main/java/teammates/ui/webapi/SubmitFeedbackResponsesAction.java
  src/main/java/teammates/ui/webapi/UpdateFeedbackResponseCommentAction.java
  src/test/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributesTest.java
  src/test/java/teammates/ui/webapi/GetFeedbackSessionsActionTest.java
Labels: s.ToMerge, c.Task

#11745 [#11571] Selective Deadline Extensions - Add extension-related tooltips for students
  src/main/java/teammates/ui/webapi/GetFeedbackSessionsAction.java
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
  src/web/app/pages-student/student-home-page/__snapshots__/student-home-page.component.spec.ts.snap
  src/web/app/pages-student/student-home-page/student-home-page.component.html
  src/web/app/pages-student/student-home-page/student-home-page.component.spec.ts
  src/web/app/pages-student/student-home-page/student-home-page.component.ts
  src/web/app/pipes/session-submission-status.pipe.ts
  src/web/services/deadline-extension-helper.ts
Labels: s.ToMerge, c.Task

#11726 [#11725] [#11744] Update logs compilation function + version filter
  build.gradle
  src/main/java/com/google/appengine/logging/v1/LogLine.java
  src/main/java/com/google/appengine/logging/v1/LogLineOrBuilder.java
  src/main/java/com/google/appengine/logging/v1/RequestLog.java
  src/main/java/com/google/appengine/logging/v1/RequestLogOrBuilder.java
  src/main/java/com/google/appengine/logging/v1/RequestLogProto.java
  src/main/java/com/google/appengine/logging/v1/SourceLocation.java
  src/main/java/com/google/appengine/logging/v1/SourceLocationOrBuilder.java
  src/main/java/com/google/appengine/logging/v1/SourceReference.java
  src/main/java/com/google/appengine/logging/v1/SourceReferenceOrBuilder.java
  src/main/java/teammates/common/datatransfer/ErrorLogEntry.java
  src/main/java/teammates/common/util/EmailWrapper.java
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/main/java/teammates/logic/api/EmailSender.java
  src/main/java/teammates/logic/api/LogsProcessor.java
  src/main/java/teammates/logic/external/GoogleCloudLoggingService.java
  src/main/java/teammates/logic/external/LocalLoggingService.java
  src/main/java/teammates/logic/external/LogService.java
  src/main/java/teammates/ui/webapi/CompileLogsAction.java
  src/test/java/teammates/architecture/ArchitectureTest.java
  src/test/java/teammates/common/datatransfer/ErrorLogEntryTest.java
  src/test/java/teammates/logic/api/MockLogsProcessor.java
  src/test/java/teammates/ui/webapi/CompileLogsActionTest.java
  src/test/java/teammates/ui/webapi/QueryLogsActionTest.java
  static-analysis/teammates-checkstyle-suppressions.xml
  static-analysis/teammates-checkstyle.xml
  static-analysis/teammates-pmd.xml
  static-analysis/teammates-pmdMain.xml
  static-analysis/teammates-spotbugs-exclude.xml
Labels: s.ToMerge, c.Feature

#11749 [#11572] Add notification banner E2E test (E2E in individual pages)
  src/e2e/java/teammates/e2e/cases/InstructorHomePageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorNotificationsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/NotificationBannerE2ETest.java
  src/e2e/java/teammates/e2e/cases/StudentHomePageE2ETest.java
  src/e2e/java/teammates/e2e/cases/StudentNotificationsPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/AppPage.java
  src/e2e/java/teammates/e2e/pageobjects/StudentHomePage.java
  src/e2e/java/teammates/e2e/util/TestDataValidityTest.java
  src/e2e/resources/data/InstructorHomePageE2ETest.json
  src/e2e/resources/data/NotificationBannerE2ETest.json
  src/e2e/resources/data/StudentHomePageE2ETest.json
  src/e2e/resources/testng-e2e.xml
Labels: s.ToMerge, c.Task

#11524 [#11236] Uninformative error message for incorrectly typed date input
  src/e2e/java/teammates/e2e/cases/AdminNotificationsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorFeedbackEditPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorFeedbackSessionsPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/AdminNotificationsPage.java
  src/e2e/java/teammates/e2e/pageobjects/AppPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorAuditLogsPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackSessionsPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorSessionIndividualExtensionPage.java
  src/main/java/teammates/ui/request/FeedbackSessionBasicRequest.java
  src/web/app/components/datepicker/datepicker.component.html
  src/web/app/components/datepicker/datepicker.component.scss
  src/web/app/pages-admin/admin-notifications-page/__snapshots__/admin-notifications-page.component.spec.ts.snap
  src/web/app/pages-admin/admin-notifications-page/notification-edit-form/__snapshots__/notification-edit-form.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-audit-logs-page/__snapshots__/instructor-audit-logs-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.html
  src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.scss
  src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-individual-extension-page/individual-extension-date-modal/__snapshots__/individual-extension-date-modal.component.spec.ts.snap
Labels: c.Bug, s.ToMerge

#11614 [#11494] Make 'Download proof of submission' button more prominent
  src/web/app/pages-session/session-submission-page/saving-complete-modal/saving-complete-modal.component.html
Labels: s.ToMerge, c.Feature

#11741 [#11572] Notification feature - User frontend tests
  src/web/app/components/notification-banner/__snapshots__/notification-banner.component.spec.ts.snap
  src/web/app/components/notification-banner/notification-banner.component.html
  src/web/app/components/notification-banner/notification-banner.component.spec.ts
  src/web/app/components/user-notifications-list/__snapshots__/user-notifications-list.component.spec.ts.snap
  src/web/app/components/user-notifications-list/user-notifications-list.component.spec.ts
  src/web/app/components/user-notifications-list/user-notifications-list.component.ts
  src/web/app/pages-admin/admin-notifications-page/admin-notifications-page.component.spec.ts
  src/web/app/pages-instructor/instructor-notifications-page/__snapshots__/instructor-notifications-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-notifications-page/instructor-notifications-page.component.spec.ts
  src/web/app/pages-student/student-notifications-page/__snapshots__/student-notifications-page.component.spec.ts.snap
  src/web/app/pages-student/student-notifications-page/student-notifications-page.component.spec.ts
Labels: s.ToMerge, c.Task

#11629 [#10920] Add front-end unit tests for FeedbackResponsesService
  src/web/services/feedback-responses.service.spec.ts
Labels: s.ToMerge, c.Task

#11752 [#11751] Deadline extensions in FeedbackSession entity have unnecessary constraint
  src/main/java/teammates/storage/entity/FeedbackSession.java
Labels: c.Bug, s.ToMerge

#11750 [#11551] Fix incorrect loading message (rework)
  src/web/app/pages-student/student-home-page/__snapshots__/student-home-page.component.spec.ts.snap
  src/web/app/pages-student/student-home-page/student-home-page.component.html
  src/web/app/pages-student/student-home-page/student-home-page.component.spec.ts
  src/web/app/pages-student/student-home-page/student-home-page.component.ts
Labels: c.Bug, s.ToMerge

#11758 [#11756] Session closing email contains no information about extended deadline
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/test/resources/data/EmailGeneratorTest.json
  src/test/resources/emails/sessionClosingEmailForInstructorWithExtension.html
  src/test/resources/emails/sessionClosingEmailForStudentWithExtension.html
Labels: c.Bug, s.ToMerge

#11769 [#11761] Use GitHub Actions wrapper for Codecov
  .github/workflows/component.yml
Labels: s.ToMerge, c.DevOps
