Repository TEAMMATES/teammates, pull requests merged in 2022-03, with the labels that each got.

#11601 [#11598] Outdated link in Solr documentation
  docs/search.md
Labels: s.ToMerge, c.Task

#11616 [#11579] [#11610] Update front page data + remove usermap page
  package-lock.json
  package.json
  sort-usermap.js
  src/web/app/pages-static/index-page/index-page.component.html
  src/web/app/pages-static/static-pages.module.ts
  src/web/app/pages-static/usermap-page/usermap-page.component.html
  src/web/app/pages-static/usermap-page/usermap-page.component.scss
  src/web/app/pages-static/usermap-page/usermap-page.component.spec.ts
  src/web/app/pages-static/usermap-page/usermap-page.component.ts
  src/web/app/pages-static/usermap-page/usermap-page.module.ts
  src/web/data/developers.json
  src/web/data/index.json
  src/web/data/userMapData.json
  src/web/data/worldTopo.json
  src/web/styles.scss
  src/web/typings.d.ts
Labels: c.Task

#11620 [#11572] Notification Feature - POST route
  src/main/java/teammates/common/datatransfer/attributes/NotificationAttributes.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/common/util/FieldValidator.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/NotificationsLogic.java
  src/main/java/teammates/ui/constants/ResourceEndpoints.java
  src/main/java/teammates/ui/request/CreateNotificationRequest.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/CreateNotificationAction.java
  src/test/java/teammates/ui/webapi/GetActionClassesActionTest.java
Labels: s.ToMerge

#11566 [#11370] Copying question from another session: optimize fetching of available questions
  src/e2e/java/teammates/e2e/cases/InstructorFeedbackEditPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java
  src/web/app/pages-instructor/instructor-session-edit-page/copy-questions-from-other-sessions-modal/__snapshots__/copy-questions-from-other-sessions-modal.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-edit-page/copy-questions-from-other-sessions-modal/copy-questions-from-other-sessions-modal-model.ts
  src/web/app/pages-instructor/instructor-session-edit-page/copy-questions-from-other-sessions-modal/copy-questions-from-other-sessions-modal.component.html
  src/web/app/pages-instructor/instructor-session-edit-page/copy-questions-from-other-sessions-modal/copy-questions-from-other-sessions-modal.component.scss
  src/web/app/pages-instructor/instructor-session-edit-page/copy-questions-from-other-sessions-modal/copy-questions-from-other-sessions-modal.component.spec.ts
  src/web/app/pages-instructor/instructor-session-edit-page/copy-questions-from-other-sessions-modal/copy-questions-from-other-sessions-modal.component.ts
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.module.ts
Labels: s.ToMerge, c.Task

#11604 [#11588] Fix incorrect loading for student result page
  src/web/app/pages-session/session-result-page/__snapshots__/session-result-page.component.spec.ts.snap
  src/web/app/pages-session/session-result-page/session-result-page.component.html
  src/web/app/pages-session/session-result-page/session-result-page.component.spec.ts
  src/web/app/pages-session/session-result-page/session-result-page.component.ts
Labels: c.Bug, s.ToMerge

#11595 [#10843] Instructor viewing results: incorrect state shown briefly when expanding the non-submitters panel
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.spec.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts
Labels: c.Bug, s.ToMerge

#11627 [#11626] New instructors: set the session timestamps of the sample course to match user
  src/main/java/teammates/ui/webapi/CreateAccountAction.java
  src/main/resources/InstructorSampleData.json
Labels: s.ToMerge, c.Feature

#11582 [#11433] Admin: Give a way to remove unregistered instructors and their data
  src/e2e/java/teammates/e2e/cases/AdminSearchPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/AdminSearchPage.java
  src/main/java/teammates/ui/webapi/DeleteAccountRequestAction.java
  src/test/java/teammates/ui/webapi/DeleteAccountRequestActionTest.java
  src/web/app/pages-admin/admin-search-page/__snapshots__/admin-search-page.component.spec.ts.snap
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.html
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.spec.ts
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.ts
  src/web/services/account.service.spec.ts
  src/web/services/account.service.ts
  src/web/services/search.service.spec.ts
  src/web/services/search.service.ts
Labels: s.ToMerge, c.Feature

#11625 [#11572] Notification Feature - GET route
  src/main/java/teammates/common/datatransfer/NotificationTargetUser.java
  src/main/java/teammates/common/datatransfer/NotificationType.java
  src/main/java/teammates/common/datatransfer/attributes/NotificationAttributes.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/common/util/FieldValidator.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/NotificationsLogic.java
  src/main/java/teammates/storage/api/NotificationsDb.java
  src/main/java/teammates/storage/entity/Notification.java
  src/main/java/teammates/ui/output/NotificationData.java
  src/main/java/teammates/ui/output/NotificationsData.java
  src/main/java/teammates/ui/request/CreateNotificationRequest.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/GetNotificationAction.java
  src/test/java/teammates/ui/webapi/GetActionClassesActionTest.java
Labels: s.FinalReview

#11634 [#11633] Remove overridden text-break class
  src/web/styles.scss
Labels: s.ToMerge

#11646 [#11585] Remove unnecessary data read
  src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
  src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/storage/api/FeedbackResponsesDb.java
  src/main/java/teammates/storage/api/FeedbackSessionsDb.java
  src/main/java/teammates/storage/api/StudentsDb.java
  src/test/java/teammates/logic/core/FeedbackQuestionsLogicTest.java
  src/test/java/teammates/logic/core/FeedbackSessionsLogicTest.java
  src/test/java/teammates/storage/api/FeedbackSessionsDbTest.java
  src/test/resources/data/typicalDataBundle.json
Labels: s.ToMerge, c.Task

#11159 [#11143] Refactor session link recovery logic
  src/main/appengine/index.yaml
  src/main/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributes.java
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/storage/api/FeedbackSessionsDb.java
  src/test/java/teammates/logic/core/CoursesLogicTest.java
  src/test/resources/data/typicalDataBundle.json
  src/web/app/pages-help/session-links-recovery/session-links-recovery-page.component.html
Labels: s.ToMerge, c.Task

#11555 [#11547] Remove outdated instructor help information
  src/web/app/pages-help/instructor-help-page/instructor-help-getting-started/instructor-help-getting-started.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-students-section/students-section-questions.ts
Labels: c.Bug, s.ToMerge

#11645 [#11644] Remove webmaster/webtool files from source control
  .gitignore
  angular.json
  build.gradle
  src/web/BingSiteAuth.xml
  src/web/google8c7ef1e995031e09.html
  src/web/robots.txt
  src/web/sitemap.xml
  src/web/webtools/.gitkeep
Labels: s.ToMerge, c.Task

#11642 [#11640] Apply lazy-loading of question contents in session submission page
  src/e2e/java/teammates/e2e/cases/FeedbackConstSumOptionQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackConstSumRecipientQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackContributionQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackMcqQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackMsqQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackNumScaleQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackRankOptionQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackRankRecipientQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackRubricQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackSubmitPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/FeedbackTextQuestionE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorAuditLogsPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/FeedbackSubmitPage.java
  src/web/app/components/question-submission-form/question-submission-form-model.ts
  src/web/app/components/question-submission-form/question-submission-form.component.html
  src/web/app/components/question-submission-form/question-submission-form.component.spec.ts
  src/web/app/components/question-submission-form/question-submission-form.component.ts
  src/web/app/components/question-submission-form/question-submission-form.module.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-data.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.html
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
  src/web/app/pages-session/session-submission-page/saving-complete-modal/saving-complete-modal.component.html
  src/web/app/pages-session/session-submission-page/session-submission-page.component.html
  src/web/app/pages-session/session-submission-page/session-submission-page.component.spec.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.module.ts
Labels: s.ToMerge, c.Task

#11577 [#11570] Move all external service classes to new package
  docs/design.md
  docs/diagrams/LogicComponent.puml
  docs/diagrams/packageDiagram.puml
  docs/images/LogicComponent.png
  docs/images/packageDiagram.png
  src/main/java/teammates/logic/api/EmailSender.java
  src/main/java/teammates/logic/api/FileStorage.java
  src/main/java/teammates/logic/api/LogsProcessor.java
  src/main/java/teammates/logic/api/RecaptchaVerifier.java
  src/main/java/teammates/logic/api/TaskQueuer.java
  src/main/java/teammates/logic/external/EmailSenderService.java
  src/main/java/teammates/logic/external/EmptyEmailService.java
  src/main/java/teammates/logic/external/EmptyRecaptchaService.java
  src/main/java/teammates/logic/external/FileStorageService.java
  src/main/java/teammates/logic/external/GoogleCloudLoggingService.java
  src/main/java/teammates/logic/external/GoogleCloudStorageService.java
  src/main/java/teammates/logic/external/GoogleCloudTasksService.java
  src/main/java/teammates/logic/external/GoogleRecaptchaService.java
  src/main/java/teammates/logic/external/LocalFileStorageService.java
  src/main/java/teammates/logic/external/LocalLoggingService.java
  src/main/java/teammates/logic/external/LocalTaskQueueService.java
  src/main/java/teammates/logic/external/LogService.java
  src/main/java/teammates/logic/external/MailgunService.java
  src/main/java/teammates/logic/external/MailjetService.java
  src/main/java/teammates/logic/external/RecaptchaService.java
  src/main/java/teammates/logic/external/SendgridService.java
  src/main/java/teammates/logic/external/TaskQueueService.java
  src/main/java/teammates/logic/external/package-info.java
  src/test/java/teammates/architecture/ArchitectureTest.java
  src/test/java/teammates/logic/api/EmailSenderTest.java
  src/test/java/teammates/logic/external/GoogleRecaptchaServiceTest.java
  src/test/java/teammates/logic/external/package-info.java
  src/test/resources/testng-component.xml
Labels: s.ToMerge, c.Task

#11650 [#11572] Add delete notification route
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/DeleteNotificationAction.java
  src/test/java/teammates/ui/webapi/GetActionClassesActionTest.java
Labels: s.FinalReview

#11574 [#8011] Improve scalability of student cascade delete
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/StudentsLogic.java
  src/main/java/teammates/storage/api/StudentsDb.java
  src/main/java/teammates/ui/webapi/DeleteStudentsAction.java
  src/test/java/teammates/logic/core/StudentsLogicTest.java
  src/test/java/teammates/ui/webapi/DeleteStudentsActionTest.java
  src/web/app/components/simple-modal/simple-modal.module.ts
  src/web/app/pages-instructor/instructor-course-details-page/__snapshots__/instructor-course-details-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.html
  src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.spec.ts
  src/web/app/pages-instructor/instructor-course-details-page/instructor-course-details-page.component.ts
  src/web/services/student.service.spec.ts
  src/web/services/student.service.ts
Labels: s.ToMerge, c.Feature

#11652 [#11572] Notification feature - admin page delete notification function
  src/web/app/pages-admin/admin-notifications-page/admin-notifications-page.component.html
  src/web/app/pages-admin/admin-notifications-page/admin-notifications-page.component.ts
  src/web/app/pages-admin/admin-notifications-page/notifications-table/notifications-table-model.ts
  src/web/app/pages-admin/admin-notifications-page/notifications-table/notifications-table.component.html
  src/web/app/pages-admin/admin-notifications-page/notifications-table/notifications-table.component.ts
  src/web/services/notification.service.ts
Labels: s.FinalReview

#11648 [#11572] Notification: GET API test and access control
  src/main/java/teammates/common/datatransfer/DataBundle.java
  src/main/java/teammates/common/datatransfer/attributes/NotificationAttributes.java
  src/main/java/teammates/logic/core/DataBundleLogic.java
  src/main/java/teammates/ui/webapi/GetNotificationAction.java
  src/test/java/teammates/common/datatransfer/attributes/NotificationAttributesTest.java
  src/test/java/teammates/common/util/FieldValidatorTest.java
  src/test/java/teammates/ui/webapi/GetNotificationActionTest.java
  src/test/resources/data/typicalDataBundle.json
Labels: s.ToReview

#11651 [#11572] Notification feature - Database Test
  src/main/java/teammates/storage/api/NotificationsDb.java
  src/test/java/teammates/storage/api/NotificationsDbTest.java
  src/test/java/teammates/ui/webapi/GetNotificationActionTest.java
  src/test/resources/data/typicalDataBundle.json
Labels: s.ToMerge

#11649 [#11571] Selective Deadline Extensions - C_UD selective deadlines
  src/main/appengine/index.yaml
  src/main/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributes.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/common/util/FieldValidator.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/InstructorsLogic.java
  src/main/java/teammates/logic/core/StudentsLogic.java
  src/main/java/teammates/storage/api/InstructorsDb.java
  src/main/java/teammates/storage/api/StudentsDb.java
  src/main/java/teammates/ui/request/FeedbackSessionUpdateRequest.java
  src/main/java/teammates/ui/webapi/UpdateFeedbackSessionAction.java
  src/test/java/teammates/common/util/FieldValidatorTest.java
  src/test/java/teammates/logic/core/InstructorsLogicTest.java
  src/test/java/teammates/logic/core/StudentsLogicTest.java
  src/test/java/teammates/storage/api/FeedbackSessionsDbTest.java
  src/test/java/teammates/storage/api/InstructorsDbTest.java
  src/test/java/teammates/storage/api/StudentsDbTest.java
  src/test/java/teammates/ui/webapi/UpdateFeedbackSessionActionTest.java
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
  src/web/services/feedback-sessions.service.ts
Labels: s.ToReview

#11667 [#11572] Add get notification route and helper functions for testing
  src/e2e/java/teammates/e2e/cases/BaseE2ETestCase.java
  src/main/java/teammates/common/datatransfer/attributes/NotificationAttributes.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/ui/constants/ResourceEndpoints.java
  src/main/java/teammates/ui/output/NotificationData.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/GetNotificationAction.java
  src/main/java/teammates/ui/webapi/GetNotificationsAction.java
  src/test/java/teammates/test/AbstractBackDoor.java
  src/test/java/teammates/test/BaseTestCaseWithDatabaseAccess.java
  src/test/java/teammates/test/BaseTestCaseWithLocalDatabaseAccess.java
  src/test/java/teammates/ui/webapi/GetActionClassesActionTest.java
  src/test/java/teammates/ui/webapi/GetNotificationsActionTest.java
  src/web/services/notification.service.ts
Labels: s.ToMerge

#11602 [#11571] Selective Deadline Extensions - DeadlineExtension entity and sending of emails
  src/e2e/java/teammates/e2e/cases/BaseE2ETestCase.java
  src/e2e/java/teammates/e2e/util/TestDataValidityTest.java
  src/main/appengine/index.yaml
  src/main/java/teammates/common/datatransfer/AttributesDeletionQuery.java
  src/main/java/teammates/common/datatransfer/DataBundle.java
  src/main/java/teammates/common/datatransfer/attributes/DeadlineExtensionAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/EntityAttributes.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/common/util/EmailType.java
  src/main/java/teammates/common/util/Templates.java
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/CoursesLogic.java
  src/main/java/teammates/logic/core/DataBundleLogic.java
  src/main/java/teammates/logic/core/DeadlineExtensionsLogic.java
  src/main/java/teammates/logic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/logic/core/InstructorsLogic.java
  src/main/java/teammates/logic/core/StudentsLogic.java
  src/main/java/teammates/storage/api/DeadlineExtensionsDb.java
  src/main/java/teammates/storage/api/OfyHelper.java
  src/main/java/teammates/storage/entity/DeadlineExtension.java
  src/main/java/teammates/ui/output/DeadlineExtensionData.java
  src/main/java/teammates/ui/request/DeadlineExtensionsRequest.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/DeadlineExtensionsWorkerAction.java
  src/main/java/teammates/ui/webapi/FeedbackSessionClosingRemindersAction.java
  src/main/resources/userEmailTemplate-deadlineExtension.html
  src/test/java/teammates/common/datatransfer/attributes/DeadlineExtensionAttributesTest.java
  src/test/java/teammates/logic/api/EmailGeneratorTest.java
  src/test/java/teammates/logic/core/DeadlineExtensionsLogicTest.java
  src/test/java/teammates/storage/api/DeadlineExtensionsDbTest.java
  src/test/java/teammates/test/BaseTestCaseWithDatabaseAccess.java
  src/test/java/teammates/test/BaseTestCaseWithLocalDatabaseAccess.java
  src/test/java/teammates/ui/request/DeadlineExtensionsRequestTest.java
  src/test/java/teammates/ui/webapi/DeadlineExtensionsWorkerActionTest.java
  src/test/java/teammates/ui/webapi/FeedbackSessionClosingRemindersActionTest.java
  src/test/java/teammates/ui/webapi/GetActionClassesActionTest.java
  src/test/resources/data/EmailGeneratorTest.json
  src/test/resources/data/typicalDataBundle.json
  src/test/resources/emails/deadlineExtensionGivenInstructor.html
  src/test/resources/emails/deadlineExtensionGivenStudent.html
  src/test/resources/emails/deadlineExtensionRevokedInstructor.html
  src/test/resources/emails/deadlineExtensionRevokedStudent.html
  src/test/resources/emails/deadlineExtensionUpdatedInstructor.html
  src/test/resources/emails/deadlineExtensionUpdatedStudent.html
  src/test/resources/emails/sessionClosingEmailForInstructorWithExtension.html
  src/test/resources/emails/sessionClosingEmailForStudentWithExtension.html
Labels: s.FinalReview

#11660 [#11572] Notification Feature - Add tests for notification POST route
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/ui/output/NotificationData.java
  src/main/java/teammates/ui/request/CreateNotificationRequest.java
  src/test/java/teammates/logic/core/NotificationsLogicTest.java
  src/test/java/teammates/ui/webapi/CreateNotificationActionTest.java
Labels: s.Ongoing

#11665 [#11572] Notification Feature - PUT notification route
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/ui/request/NotificationBasicRequest.java
  src/main/java/teammates/ui/request/NotificationCreateRequest.java
  src/main/java/teammates/ui/request/NotificationUpdateRequest.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/CreateNotificationAction.java
  src/main/java/teammates/ui/webapi/UpdateNotificationAction.java
  src/test/java/teammates/ui/webapi/CreateNotificationActionTest.java
  src/test/java/teammates/ui/webapi/GetActionClassesActionTest.java
  src/web/services/notification.service.ts
Labels: s.ToMerge

#11600 [#11086] Enrolling students: show a progress indicator when enrolling a large class
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.html
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.scss
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.spec.ts
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.module.ts
Labels: s.FinalReview

#11657 [#11655] Devise a better way to handle duplicate account requests
  src/e2e/java/teammates/e2e/cases/AdminHomePageE2ETest.java
  src/e2e/java/teammates/e2e/cases/AdminSearchPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/AdminHomePage.java
  src/e2e/java/teammates/e2e/pageobjects/AdminSearchPage.java
  src/e2e/resources/data/AdminHomePageE2ETest.json
  src/main/java/teammates/common/datatransfer/attributes/AccountRequestAttributes.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/AccountsLogic.java
  src/main/java/teammates/storage/api/AccountsDb.java
  src/main/java/teammates/ui/constants/ResourceEndpoints.java
  src/main/java/teammates/ui/output/AccountsData.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/CreateAccountRequestAction.java
  src/main/java/teammates/ui/webapi/GetAccountsAction.java
  src/main/java/teammates/ui/webapi/ResetAccountRequestAction.java
  src/test/java/teammates/common/datatransfer/attributes/AccountRequestAttributesTest.java
  src/test/java/teammates/logic/core/AccountsLogicTest.java
  src/test/java/teammates/storage/api/AccountsDbTest.java
  src/test/java/teammates/ui/webapi/CreateAccountRequestActionTest.java
  src/test/java/teammates/ui/webapi/GetAccountsActionTest.java
  src/test/java/teammates/ui/webapi/GetActionClassesActionTest.java
  src/test/java/teammates/ui/webapi/ResetAccountRequestActionTest.java
  src/web/app/pages-admin/admin-home-page/__snapshots__/admin-home-page.component.spec.ts.snap
  src/web/app/pages-admin/admin-home-page/admin-home-page.component.html
  src/web/app/pages-admin/admin-home-page/admin-home-page.component.spec.ts
  src/web/app/pages-admin/admin-home-page/admin-home-page.component.ts
  src/web/app/pages-admin/admin-home-page/admin-home-page.module.ts
  src/web/app/pages-admin/admin-home-page/instructor-data.ts
  src/web/app/pages-admin/admin-home-page/new-instructor-data-row/__snapshots__/new-instructor-data-row.component.spec.ts.snap
  src/web/app/pages-admin/admin-home-page/new-instructor-data-row/new-instructor-data-row.component.html
  src/web/app/pages-admin/admin-home-page/new-instructor-data-row/new-instructor-data-row.component.spec.ts
  src/web/app/pages-admin/admin-home-page/new-instructor-data-row/new-instructor-data-row.component.ts
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.html
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.spec.ts
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.ts
  src/web/services/account.service.spec.ts
  src/web/services/account.service.ts
  src/web/services/simple-modal.service.ts
Labels: s.ToMerge, c.Feature

#11666 [#11618] Backend for usage statistics collection
  src/main/appengine/cron.yaml
  src/main/java/teammates/common/datatransfer/attributes/UsageStatisticsAttributes.java
  src/main/java/teammates/common/datatransfer/logs/QueryLogsParams.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/common/util/TimeHelper.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/api/LogsProcessor.java
  src/main/java/teammates/logic/core/AccountRequestsLogic.java
  src/main/java/teammates/logic/core/CoursesLogic.java
  src/main/java/teammates/logic/core/FeedbackResponsesLogic.java
  src/main/java/teammates/logic/core/InstructorsLogic.java
  src/main/java/teammates/logic/core/LogicStarter.java
  src/main/java/teammates/logic/core/StudentsLogic.java
  src/main/java/teammates/logic/core/UsageStatisticsLogic.java
  src/main/java/teammates/storage/api/AccountRequestsDb.java
  src/main/java/teammates/storage/api/CoursesDb.java
  src/main/java/teammates/storage/api/FeedbackResponsesDb.java
  src/main/java/teammates/storage/api/InstructorsDb.java
  src/main/java/teammates/storage/api/OfyHelper.java
  src/main/java/teammates/storage/api/StudentsDb.java
  src/main/java/teammates/storage/api/UsageStatisticsDb.java
  src/main/java/teammates/storage/entity/UsageStatistics.java
  src/main/java/teammates/ui/constants/ResourceEndpoints.java
  src/main/java/teammates/ui/output/UsageStatisticsData.java
  src/main/java/teammates/ui/output/UsageStatisticsRangeData.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/CalculateUsageStatisticsAction.java
  src/main/java/teammates/ui/webapi/GetUsageStatisticsAction.java
  src/test/java/teammates/common/util/TimeHelperTest.java
  src/test/java/teammates/logic/core/UsageStatisticsLogicTest.java
  src/test/java/teammates/ui/webapi/CalculateUsageStatisticsActionTest.java
  src/test/java/teammates/ui/webapi/GetActionClassesActionTest.java
  src/test/java/teammates/ui/webapi/GetUsageStatisticsActionTest.java
Labels: s.ToMerge, c.Task

#11677 [#11674] Time picker displaying duplicate options
  src/web/app/components/timepicker/timepicker.component.ts
Labels: c.Bug, s.ToMerge

#11672 [#11621][#11622] Minor fixes for angular.json and typos
  angular.json
  src/main/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributes.java
  src/main/java/teammates/common/datatransfer/attributes/StudentProfileAttributes.java
Labels: s.ToMerge, c.Task

#11613 [#8184] Instructor create session: default questions: replace 'contribution question'
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackSessionsPage.java
  src/main/resources/InstructorSampleData.json
  src/web/app/components/session-edit-form/session-edit-form.component.html
  src/web/data/template-sessions.json
Labels: s.ToMerge, c.Feature

#11675 [#11673] Add ESLint rule for member delimiter style
  src/web/app/components/sortable-table/sortable-table.component.ts
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
  src/web/services/feedback-sessions.service.ts
  src/web/services/log.service.ts
  src/web/services/search.service.ts
  static-analysis/teammates-eslint.yml
Labels: s.ToMerge, c.Task

#11671 [#11571] Selective Deadline Extensions - Integrate the backend
  src/main/appengine/queue.yaml
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/logic/api/TaskQueuer.java
  src/main/java/teammates/ui/webapi/UpdateFeedbackSessionAction.java
  src/test/java/teammates/ui/webapi/UpdateFeedbackSessionActionTest.java
Labels: s.ToMerge

#11685 [#11684] Fix minor typos
  docs/CONTRIBUTING.md
  docs/e2e-testing.md
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/AccountRequestsLogic.java
  src/main/java/teammates/logic/core/AccountsLogic.java
  src/main/java/teammates/logic/core/DataBundleLogic.java
  src/main/java/teammates/ui/webapi/BinFeedbackSessionAction.java
  src/test/java/teammates/common/util/StringHelperTest.java
  src/web/app/components/question-edit-form/question-edit-form.component.ts
  src/web/app/components/teammates-common/enum-to-array.pipe.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-courses-section/courses-section-questions.ts
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.ts
  src/web/types/sort-properties.ts
Labels: s.ToMerge
