Repository TEAMMATES/teammates, pull requests merged in 2022-06, with the labels that each got.

#11828 [#8933] Instructor: Edit rubric question: adding reorder options using up and down arrows for rows
  src/web/app/components/question-types/question-edit-details-form/rubric-question-edit-details-form.component.html
  src/web/app/components/question-types/question-edit-details-form/rubric-question-edit-details-form.component.ts
Labels: s.ToMerge, c.Feature

#11838 [#2488] Instructor: edit questions: give more recipient type options
  src/e2e/java/teammates/e2e/pageobjects/AppPage.java
  src/e2e/java/teammates/e2e/pageobjects/FeedbackSubmitPage.java
  src/e2e/resources/data/FeedbackSubmitPageE2ETest.json
  src/main/java/teammates/common/datatransfer/questions/FeedbackQuestionDetails.java
  src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
  src/main/java/teammates/logic/core/FeedbackResponsesLogic.java
  src/test/resources/data/GetFeedbackQuestionRecipientsActionTest.json
  src/test/resources/data/typicalDataBundle.json
  src/web/app/components/question-submission-form/question-submission-form.component.html
  src/web/app/components/question-submission-form/recipient-type-name.pipe.ts
  src/web/app/components/visibility-messages/visibility-entity-name.pipe.ts
  src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
  src/web/services/feedback-questions.service.ts
Labels: s.ToMerge, c.Feature

#11814 [#11767] Prevent users from joining binned courses
  src/main/java/teammates/logic/core/AccountsLogic.java
  src/test/java/teammates/logic/core/AccountsLogicTest.java
  src/web/app/__snapshots__/user-join-page.component.spec.ts.snap
  src/web/app/user-join-page.component.spec.ts
  src/web/app/user-join-page.component.ts
Labels: s.ToMerge, c.Feature

#11829 [#11794] Update help pages
  src/web/app/pages-help/instructor-help-page/instructor-help-courses-section/instructor-help-courses-section.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-getting-started/instructor-help-getting-started.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.html
  src/web/app/pages-help/student-help-page/student-help-page.component.html
  src/web/app/pages-help/student-help-page/student-help-page.module.ts
  src/web/app/pages-static/features-page/features-page.component.html
  src/web/app/pages-static/static-page.component.ts
Labels: s.ToMerge, c.Feature

#11842 [#11837] Add support for multiples of 5 for team contribution question
  src/main/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetails.java
  src/test/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetailsTest.java
  src/web/app/components/question-types/question-edit-answer-form/contribution-question-edit-answer-form.component.ts
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
Labels: s.ToMerge, c.Feature

#11824 [#8769] Extract question brief and description component
  src/web/app/components/question-edit-brief-description-form/question-edit-brief-description-form.component.html
  src/web/app/components/question-edit-brief-description-form/question-edit-brief-description-form.component.scss
  src/web/app/components/question-edit-brief-description-form/question-edit-brief-description-form.component.ts
  src/web/app/components/question-edit-brief-description-form/question-edit-brief-description-form.module.ts
  src/web/app/components/question-edit-brief-description-form/question-edit-brief-description-form.spec.ts
  src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap
  src/web/app/components/question-edit-form/question-edit-form.component.html
  src/web/app/components/question-edit-form/question-edit-form.component.scss
  src/web/app/components/question-edit-form/question-edit-form.component.spec.ts
  src/web/app/components/question-edit-form/question-edit-form.module.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-page.module.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.spec.ts
  src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
Labels: s.ToMerge, c.Feature

#11850 [#11846] Instructor help page: provide a way to direct a user to a specific question
  src/web/app/pages-admin/admin-home-page/admin-home-page.component.spec.ts
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.spec.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-courses-section/instructor-help-courses-section.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-courses-section/instructor-help-courses-section.component.scss
  src/web/app/pages-help/instructor-help-page/instructor-help-courses-section/instructor-help-courses-section.component.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-general-section/instructor-help-general-section.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-general-section/instructor-help-general-section.component.scss
  src/web/app/pages-help/instructor-help-page/instructor-help-general-section/instructor-help-general-section.component.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-panel/instructor-help-panel.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-panel/instructor-help-panel.component.scss
  src/web/app/pages-help/instructor-help-page/instructor-help-panel/instructor-help-panel.component.spec.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-panel/instructor-help-panel.component.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.scss
  src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-section.component.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-section.component.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.scss
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.scss
  src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.ts
  src/web/services/link.service.spec.ts
  src/web/services/navigation.service.spec.ts
  src/web/services/navigation.service.ts
  src/web/services/search.service.spec.ts
Labels: s.FinalReview

#11864 [#11858] Instructor viewing results: 'Other teams in the same section' path is causing timeout
  src/main/java/teammates/logic/core/FeedbackQuestionsLogic.java
Labels: s.ToMerge, c.Task

#11856 [#11753] Differentiate button/dialog for individual/all-question submissions
  src/web/app/components/question-submission-form/question-submission-form.component.html
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
  src/web/app/pages-session/session-submission-page/saving-complete-modal/saving-complete-modal.component.html
Labels: s.ToMerge

#11855 [#11854] Refactor NavigationService to use Angular's dependency injection for services
  src/web/app/__snapshots__/user-join-page.component.spec.ts.snap
  src/web/app/pages-admin/admin-accounts-page/admin-accounts-page.component.ts
  src/web/app/pages-admin/admin-page.component.ts
  src/web/app/pages-instructor/instructor-course-edit-page/__snapshots__/instructor-course-edit-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.ts
  src/web/app/pages-instructor/instructor-course-student-edit-page/__snapshots__/instructor-course-student-edit-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.ts
  src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.ts
  src/web/app/pages-instructor/instructor-session-base-page.component.ts
  src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.spec.ts
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
  src/web/app/pages-instructor/instructor-session-modal-page.component.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.ts
  src/web/app/pages-session/session-result-page/__snapshots__/session-result-page.component.spec.ts.snap
  src/web/app/pages-session/session-result-page/session-result-page.component.spec.ts
  src/web/app/pages-session/session-result-page/session-result-page.component.ts
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
  src/web/app/pages-session/session-submission-page/session-submission-page.component.spec.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
  src/web/app/user-join-page.component.spec.ts
  src/web/app/user-join-page.component.ts
  src/web/services/navigation.service.ts
Labels: s.ToMerge, c.Task

#11863 [#11862] Instructor viewing results: make critical error message persist
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-gqr-view.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-gqr-view.component.spec.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-grq-view.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-grq-view.component.spec.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-question-view.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-question-view.component.spec.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rgq-view.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rgq-view.component.spec.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rqg-view.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-rqg-view.component.spec.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-view.module.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-view.ts
Labels: s.ToMerge, c.Feature

#11871 [#10819] Instructor edit session page: Add scroll to top button
  src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.html
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
Labels: s.ToMerge, c.Feature

#11870 [#11865] Add to instructor help: 'Can I use a different team structure for different sessions?'
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-section.component.scss
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/sessions-section-questions.ts
Labels: s.ToMerge, c.Feature

#11872 [#11861] Instructor enrolling students: Fix scroll down link for instructor enroll student page
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.html
Labels: c.Bug, s.ToMerge
