Repository TEAMMATES/teammates, pull requests merged in 2023-06, with the labels that each got.

#12440 [#10920] Add testing for sortCoursesBy method in instructor home page.
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.spec.ts
Labels: s.FinalReview

#12456 [#12442] Massive string is not correctly treated
  src/web/app/pages-admin/admin-search-page/__snapshots__/admin-search-page.component.spec.ts.snap
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.html
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.ts
  src/web/app/pages-instructor/instructor-search-page/__snapshots__/instructor-search-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-search-page/instructor-search-bar/instructor-search-bar.component.html
  src/web/app/pages-instructor/instructor-search-page/instructor-search-bar/instructor-search-bar.component.ts
Labels: s.FinalReview

#12439 [#12099] Add 'course -> copy' option to the instructor home page
  src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.ts
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.module.ts
Labels: s.ToMerge

#12462 [#10920] Added test for Instructor Course Edit Page
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.spec.ts
Labels: s.ToReview

#12465 [#12464] Add verification step for Docker instance of Datastore in docs
  docs/development.md
Labels: s.FinalReview

#12479 [#1501] Create Unit Tests for Feedback*QuestionDetails classes
  src/test/java/teammates/common/datatransfer/questions/FeedbackMsqQuestionDetailsTest.java
  src/test/java/teammates/common/datatransfer/questions/FeedbackNumericalScaleQuestionDetailsTest.java
Labels: s.ToMerge

#12482 [#12481] Fix running of component tests using Windows Powershell
  build.gradle
Labels: s.FinalReview

#12475 [#1501] Add tests cases to FeedbackRankOptionsQuestionDetails
  src/test/java/teammates/common/datatransfer/questions/FeedbackRankOptionsQuestionDetailsTest.java
Labels: s.ToMerge

#12496 [#12268] Make instructor getting started page more prominent
  src/web/app/pages-instructor/instructor-page.component.ts
Labels: s.FinalReview

#12495 [#12400] Instructor editing questions: warning about visibility is removed if the edit is cancelled.
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
Labels: s.ToMerge
