Repository TEAMMATES/teammates, pull requests merged in 2023-04, with the labels that each got.

#12325 [#12081] User-friendliness: Fix all remaining sortable table headers
  src/web/app/components/extension-confirm-modal/__snapshots__/extension-confirm-modal.component.spec.ts.snap
  src/web/app/components/extension-confirm-modal/extension-confirm-modal.component.html
  src/web/app/components/extension-confirm-modal/extension-confirm-modal.component.scss
  src/web/app/components/extension-confirm-modal/extension-confirm-modal.component.ts
  src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.html
  src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.scss
  src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.ts
  src/web/app/components/sessions-recycle-bin-table/sessions-recycle-bin-table.component.html
  src/web/app/components/sessions-recycle-bin-table/sessions-recycle-bin-table.component.scss
  src/web/app/components/sessions-recycle-bin-table/sessions-recycle-bin-table.component.ts
  src/web/app/components/sessions-table/__snapshots__/sessions-table.component.spec.ts.snap
  src/web/app/components/sessions-table/sessions-table.component.html
  src/web/app/components/sessions-table/sessions-table.component.scss
  src/web/app/components/sessions-table/sessions-table.component.ts
  src/web/app/components/student-list/__snapshots__/student-list.component.spec.ts.snap
  src/web/app/components/student-list/student-list.component.html
  src/web/app/components/student-list/student-list.component.scss
  src/web/app/components/student-list/student-list.component.ts
  src/web/app/pages-admin/admin-notifications-page/notifications-table/__snapshots__/notifications-table.component.spec.ts.snap
  src/web/app/pages-admin/admin-notifications-page/notifications-table/notifications-table.component.html
  src/web/app/pages-admin/admin-notifications-page/notifications-table/notifications-table.component.scss
  src/web/app/pages-admin/admin-notifications-page/notifications-table/notifications-table.component.ts
  src/web/app/pages-instructor/instructor-course-details-page/__snapshots__/instructor-course-details-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-course-edit-page/copy-instructors-from-other-courses-modal/__snapshots__/copy-instructors-from-other-courses-modal.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-course-edit-page/copy-instructors-from-other-courses-modal/copy-instructors-from-other-courses-modal.component.html
  src/web/app/pages-instructor/instructor-course-edit-page/copy-instructors-from-other-courses-modal/copy-instructors-from-other-courses-modal.component.scss
  src/web/app/pages-instructor/instructor-course-edit-page/copy-instructors-from-other-courses-modal/copy-instructors-from-other-courses-modal.component.ts
  src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.html
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.scss
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts
  src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-search-page/__snapshots__/instructor-search-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-edit-page/copy-questions-from-other-sessions-modal/__snapshots__/copy-questions-from-other-sessions-modal.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-edit-page/copy-questions-from-other-sessions-modal/copy-questions-from-other-sessions-modal.component.html
  src/web/app/pages-instructor/instructor-session-edit-page/copy-questions-from-other-sessions-modal/copy-questions-from-other-sessions-modal.component.scss
  src/web/app/pages-instructor/instructor-session-edit-page/copy-questions-from-other-sessions-modal/copy-questions-from-other-sessions-modal.component.ts
  src/web/app/pages-instructor/instructor-session-individual-extension-page/__snapshots__/instructor-session-individual-extension-page.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-individual-extension-page/instructor-session-individual-extension-page.component.html
  src/web/app/pages-instructor/instructor-session-individual-extension-page/instructor-session-individual-extension-page.component.scss
  src/web/app/pages-instructor/instructor-session-individual-extension-page/instructor-session-individual-extension-page.component.ts
Labels: s.ToMerge

#11891 [#11890] Add Firebase Authentication
  .gitignore
  build.gradle
  package-lock.json
  package.json
  src/main/java/teammates/common/exception/AuthException.java
  src/main/java/teammates/common/util/Config.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/common/util/EmailType.java
  src/main/java/teammates/common/util/Templates.java
  src/main/java/teammates/logic/api/AuthProxy.java
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/main/java/teammates/logic/external/AuthService.java
  src/main/java/teammates/logic/external/EmptyAuthService.java
  src/main/java/teammates/logic/external/FirebaseAuthService.java
  src/main/java/teammates/ui/constants/ResourceEndpoints.java
  src/main/java/teammates/ui/output/SendLoginEmailResponseData.java
  src/main/java/teammates/ui/servlets/LoginServlet.java
  src/main/java/teammates/ui/servlets/OAuth2CallbackServlet.java
  src/main/java/teammates/ui/servlets/WebSecurityHeaderFilter.java
  src/main/java/teammates/ui/webapi/Action.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/SendLoginEmailAction.java
  src/main/resources/build.template.properties
  src/main/resources/loginEmail.html
  src/test/java/teammates/logic/api/MockAuthProxy.java
  src/test/java/teammates/ui/webapi/BaseActionTest.java
  src/test/java/teammates/ui/webapi/GetActionClassesActionTest.java
  src/test/java/teammates/ui/webapi/SendLoginEmailActionTest.java
  src/web/app/app.module.ts
  src/web/app/login-page.component.html
  src/web/app/login-page.component.scss
  src/web/app/login-page.component.spec.ts
  src/web/app/login-page.component.ts
  src/web/app/login-page.module.ts
  src/web/app/page.component.html
  src/web/app/page.component.spec.ts
  src/web/app/page.component.ts
  src/web/environments/config.template.ts
  src/web/index.html
  src/web/services/auth.service.spec.ts
  src/web/services/auth.service.ts
Labels: s.ToMerge, c.Feature

#12316 [#12117] Students viewing submission form: Some answered essay questions are not shown in green
  src/web/app/components/question-submission-form/question-submission-form.component.ts
Labels: c.Bug, s.ToMerge

#12310 [#12307] Modified session timing modal does not use updated session name
  src/web/app/pages-instructor/instructor-session-base-page.component.ts
Labels: c.Bug, s.ToMerge

#12330 [#12317] Release V8.26.0
  src/web/data/developers.json
Labels: s.ToMerge, c.Release

#12294 [#12048] Migrate get has responses action
  src/it/java/teammates/it/sqllogic/core/FeedbackQuestionsLogicIT.java
  src/it/java/teammates/it/storage/sqlapi/FeedbackQuestionsDbIT.java
  src/it/java/teammates/it/storage/sqlapi/FeedbackResponsesDbIT.java
  src/it/java/teammates/it/ui/webapi/GetHasResponsesActionIT.java
  src/it/resources/data/typicalDataBundle.json
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/FeedbackQuestionsLogic.java
  src/main/java/teammates/sqllogic/core/FeedbackResponsesLogic.java
  src/main/java/teammates/storage/sqlapi/FeedbackQuestionsDb.java
  src/main/java/teammates/storage/sqlapi/FeedbackResponsesDb.java
  src/main/java/teammates/ui/webapi/GetFeedbackResponsesAction.java
  src/main/java/teammates/ui/webapi/GetHasResponsesAction.java
Labels: s.ToReview

#12324 [#12282] Instructor sessions page: Fix create feedback session card header
  src/web/app/components/session-edit-form/session-edit-form.component.html
  src/web/app/components/session-edit-form/session-edit-form.component.scss
  src/web/app/pages-instructor/instructor-sessions-page/__snapshots__/instructor-sessions-page.component.spec.ts.snap
Labels: s.ToMerge

#12244 [#12048] Migrate Feedback Session publish-related email worker actions.
  src/main/java/teammates/ui/webapi/FeedbackSessionPublishedEmailWorkerAction.java
  src/main/java/teammates/ui/webapi/FeedbackSessionResendPublishedEmailWorkerAction.java
  src/main/java/teammates/ui/webapi/FeedbackSessionUnpublishedEmailWorkerAction.java
  src/test/java/teammates/sqlui/webapi/FeedbackSessionPublishedEmailWorkerActionTest.java
  src/test/java/teammates/sqlui/webapi/FeedbackSessionResendPublishedEmailWorkerActionTest.java
  src/test/java/teammates/sqlui/webapi/FeedbackSessionUnpublishedEmailWorkerActionTest.java
Labels: s.ToMerge

#12337 [#12048] Migrate DeleteFeedbackQuestionAction
  src/it/java/teammates/it/storage/sqlapi/FeedbackResponsesDbIT.java
  src/it/java/teammates/it/ui/webapi/DeleteFeedbackQuestionActionIT.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/FeedbackQuestionsLogic.java
  src/main/java/teammates/ui/webapi/DeleteFeedbackQuestionAction.java
  src/test/java/teammates/ui/webapi/DeleteFeedbackQuestionActionTest.java
Labels: s.ToReview

#12304 [#12048] Migrate RemindFeedbackSessionSubmissionAction
  src/main/java/teammates/ui/webapi/RemindFeedbackSessionSubmissionAction.java
  src/test/java/teammates/sqlui/webapi/RemindFeedbackSessionSubmissionActionTest.java
Labels: s.ToMerge

#12326 [#12048] Migrate GetDeadlineExtensionAction
  src/it/java/teammates/it/sqllogic/core/DeadlineExtensionsLogicIT.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/DeadlineExtensionsLogic.java
  src/main/java/teammates/storage/sqlapi/DeadlineExtensionsDb.java
  src/main/java/teammates/ui/output/DeadlineExtensionData.java
  src/main/java/teammates/ui/webapi/GetDeadlineExtensionAction.java
  src/test/java/teammates/ui/webapi/GetDeadlineExtensionActionTest.java
Labels: s.ToReview

#12343 [#12048] Migrate UpdateInstructorPrivilegeAction
  src/it/java/teammates/it/sqllogic/core/UsersLogicIT.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/UsersLogic.java
  src/main/java/teammates/ui/webapi/UpdateInstructorPrivilegeAction.java
  src/test/java/teammates/sqllogic/core/UsersLogicTest.java
  src/test/java/teammates/sqlui/webapi/UpdateInstructorPrivilegeActionTest.java
  src/test/java/teammates/ui/webapi/UpdateInstructorPrivilegeActionTest.java
Labels: s.ToMerge

#12341 [#12048] Migrate RegenerateInstructorKeyAction
  src/it/java/teammates/it/ui/webapi/RegenerateInstructorKeyActionIT.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/UsersLogic.java
  src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java
  src/main/java/teammates/ui/webapi/RegenerateInstructorKeyAction.java
Labels: s.ToMerge

#12348 [#12335] fix copy questions modal checkbox
  src/web/app/pages-instructor/instructor-session-edit-page/copy-questions-from-other-sessions-modal/__snapshots__/copy-questions-from-other-sessions-modal.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-edit-page/copy-questions-from-other-sessions-modal/copy-questions-from-other-sessions-modal.component.html
  src/web/app/pages-instructor/instructor-session-edit-page/copy-questions-from-other-sessions-modal/copy-questions-from-other-sessions-modal.component.scss
Labels: s.ToMerge

#12249 [#12125] Instructor results page stats tables: differentiate students with same team and name
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackResultsPage.java
  src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.html
  src/web/app/components/question-types/question-statistics/constsum-recipients-question-statistics.component.ts
  src/web/app/components/question-types/question-statistics/contribution-question-statistics/contribution-question-statistics.component.ts
  src/web/app/components/question-types/question-statistics/mcq-question-statistics.component.ts
  src/web/app/components/question-types/question-statistics/msq-question-statistics.component.ts
  src/web/app/components/question-types/question-statistics/num-scale-question-statistics.component.ts
  src/web/app/components/question-types/question-statistics/question-statistics-calculation/mcq-question-statistics-calculation.ts
  src/web/app/components/question-types/question-statistics/question-statistics-calculation/msq-question-statistics-calculation.ts
  src/web/app/components/question-types/question-statistics/question-statistics-calculation/num-scale-question-statistics-calculation.ts
  src/web/app/components/question-types/question-statistics/rank-recipients-question-statistics.component.ts
  src/web/app/components/question-types/question-statistics/rubric-question-statistics.component.ts
  src/web/app/components/question-types/question-statistics/test-data/mcqQuestionResponses.json
  src/web/app/components/question-types/question-statistics/test-data/msqQuestionResponses.json
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.html
Labels: s.ToMerge

#12351 [#4570] Instructor: support previewing results as a student
  src/e2e/java/teammates/e2e/cases/FeedbackResultsPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/FeedbackResultsPage.java
  src/e2e/resources/data/FeedbackResultsPageE2ETest.json
  src/main/java/teammates/common/datatransfer/SessionResultsBundle.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/FeedbackResponsesLogic.java
  src/main/java/teammates/ui/output/SessionResultsData.java
  src/main/java/teammates/ui/webapi/BasicFeedbackSubmissionAction.java
  src/main/java/teammates/ui/webapi/GetFeedbackQuestionsAction.java
  src/main/java/teammates/ui/webapi/GetFeedbackSessionAction.java
  src/main/java/teammates/ui/webapi/GetSessionResultsAction.java
  src/test/java/teammates/common/datatransfer/SessionResultsBundleTest.java
  src/test/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetailsTest.java
  src/test/java/teammates/logic/core/FeedbackResponsesLogicTest.java
  src/test/java/teammates/ui/webapi/GetFeedbackSessionActionTest.java
  src/test/java/teammates/ui/webapi/GetSessionResultsActionTest.java
  src/web/app/components/preview-session-result-panel/preview-session-result-panel.component.html
  src/web/app/components/preview-session-result-panel/preview-session-result-panel.component.scss
  src/web/app/components/preview-session-result-panel/preview-session-result-panel.component.spec.ts
  src/web/app/components/preview-session-result-panel/preview-session-result-panel.component.ts
  src/web/app/components/preview-session-result-panel/preview-session-result-panel.module.ts
  src/web/app/components/question-response-panel/__snapshots__/question-response-panel.component.spec.ts.snap
  src/web/app/components/question-response-panel/question-response-panel.component.html
  src/web/app/components/question-response-panel/question-response-panel.component.spec.ts
  src/web/app/components/question-response-panel/question-response-panel.component.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-sessions-section/instructor-help-sessions-data.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.spec.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.module.ts
  src/web/app/pages-session/session-result-page/__snapshots__/session-result-page.component.spec.ts.snap
  src/web/app/pages-session/session-result-page/session-result-page.component.html
  src/web/app/pages-session/session-result-page/session-result-page.component.scss
  src/web/app/pages-session/session-result-page/session-result-page.component.spec.ts
  src/web/app/pages-session/session-result-page/session-result-page.component.ts
  src/web/services/feedback-sessions.service.ts
Labels: s.ToMerge, c.Feature

#12358 [#12022] [#10623] Update development, troubleshooting, and process documentation
  .github/CODE_OF_CONDUCT.md
  .github/DISCUSSION_TEMPLATE/help-requests.yml
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/help-request.md
  .github/SECURITY.md
  .github/workflows/jdk17.yml
  docs/CONTRIBUTING.md
  docs/SUPPORT.md
  docs/best-practices/testing.md
  docs/design.md
  docs/development.md
  docs/diagrams/Actors.puml
  docs/diagrams/ClientComponent.puml
  docs/diagrams/E2EComponent.puml
  docs/diagrams/TestDriverComponent.puml
  docs/diagrams/highlevelArchitecture.puml
  docs/diagrams/packageDiagram.puml
  docs/diagrams/workflow.puml
  docs/images/Actors.png
  docs/images/IssueLifecycle.png
  docs/images/RolesAndTechnologies.png
  docs/images/RolesAndTechnologies.pptx
  docs/images/UI testing guidelines.pptx
  docs/images/highlevelArchitecture.png
  docs/images/workflow.png
  docs/images/workflow.pptx
  docs/issues.md
  docs/process.md
  docs/setting-up.md
  docs/troubleshooting-guide.md
  src/main/webapp/index.html
Labels: s.ToReview, c.DevOps

#12352 [#12308] Add session: time picker constraint not applied correctly
  src/web/app/components/session-edit-form/session-edit-form.component.ts
Labels: c.Bug, s.ToMerge

#12321 [#10986] Show loading message below response loading spinner
  src/web/app/components/loading-spinner/loading-spinner.component.html
  src/web/app/components/loading-spinner/loading-spinner.component.ts
Labels: s.ToMerge, c.Feature

#12357 [#12048] Migrate GetRegkeyValidityAction
  src/it/java/teammates/it/ui/webapi/GetRegKeyValidityActionIT.java
  src/main/java/teammates/ui/webapi/GetRegkeyValidityAction.java
Labels: s.ToReview

#12342 [#12293] Admin logs page: Extension of query start/end time is not reflected in search range
  src/web/app/pages-monitoring/logs-page/logs-page.component.ts
  src/web/services/datetime.service.ts
Labels: c.Bug, s.ToMerge

#12369 [#12334] Instructor courses page: fix copy instructors from other courses modal checkbox
  src/web/app/pages-instructor/instructor-course-edit-page/copy-instructors-from-other-courses-modal/__snapshots__/copy-instructors-from-other-courses-modal.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-course-edit-page/copy-instructors-from-other-courses-modal/copy-instructors-from-other-courses-modal.component.html
Labels: s.ToMerge

#12331 [#12048] Get Courses Action
  src/it/java/teammates/it/ui/webapi/GetCoursesActionIT.java
  src/it/resources/data/GetCoursesActionIT.json
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/CoursesLogic.java
  src/main/java/teammates/sqllogic/core/LogicStarter.java
  src/main/java/teammates/sqllogic/core/UsersLogic.java
  src/main/java/teammates/storage/sqlapi/UsersDb.java
  src/main/java/teammates/storage/sqlentity/Course.java
  src/main/java/teammates/ui/output/CoursesData.java
  src/main/java/teammates/ui/webapi/GetCoursesAction.java
  src/test/java/teammates/sqllogic/core/CoursesLogicTest.java
Labels: s.ToMerge

#12370 [#12361] Enhance Pull Request Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: s.ToMerge

#12298 [#12291] Admin logs page: Fix overflow of "Clear all" button
  src/web/app/pages-monitoring/logs-page/__snapshots__/logs-page.component.spec.ts.snap
  src/web/app/pages-monitoring/logs-page/logs-page.component.html
  src/web/app/pages-monitoring/logs-page/logs-page.component.scss
Labels: s.ToMerge

#12381 [#12380] PR template causing PR checker to automatically pass
  .github/PULL_REQUEST_TEMPLATE.md
Labels: s.ToMerge

#12382 [#12376] Release V8.27.0
  src/web/data/developers.json
Labels: s.ToMerge, c.Release

#12378 [#12277] Instructor home page: Remove links to video tour
  src/web/app/pages-help/instructor-help-page/instructor-help-getting-started/instructor-help-getting-started.component.html
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
Labels: s.ToMerge

#12386 [#12288] Admin notifications page: Fix notifications table overflow
  src/web/app/pages-admin/admin-notifications-page/notifications-table/__snapshots__/notifications-table.component.spec.ts.snap
  src/web/app/pages-admin/admin-notifications-page/notifications-table/notifications-table.component.html
  src/web/app/pages-admin/admin-notifications-page/notifications-table/notifications-table.component.scss
Labels: s.ToMerge

#12401 [#12230] Extension Confirm Modal: Misplaced submit buttons on mobile
  src/web/app/components/extension-confirm-modal/__snapshots__/extension-confirm-modal.component.spec.ts.snap
  src/web/app/components/extension-confirm-modal/extension-confirm-modal.component.html
Labels: s.ToMerge

#12389 [#12344] Instructor courses page: fix margin of copy instructors from other courses modal on mobile
  src/web/app/pages-instructor/instructor-course-edit-page/copy-instructors-from-other-courses-modal/copy-instructors-from-other-courses-modal.component.scss
Labels: s.ToMerge

#12394 [#12289] Usage statistics and logs page: Improve date/time input on mobile
  src/web/app/pages-monitoring/logs-page/__snapshots__/logs-page.component.spec.ts.snap
  src/web/app/pages-monitoring/logs-page/logs-page.component.html
  src/web/app/pages-monitoring/usage-stats-page/__snapshots__/usage-statistics-page.component.spec.ts.snap
  src/web/app/pages-monitoring/usage-stats-page/usage-statistics-page.component.html
Labels: s.ToMerge

#12396 [#12290] Instructor view session results (course-wide): Improve display of no-response card header
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackResultsPage.java
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-no-response-panel.component.scss
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.html
Labels: s.ToMerge

#12402 [#1501] Create Unit Tests for FeedbackConstantSumQuestionDetails class
  src/test/java/teammates/common/datatransfer/questions/FeedbackConstantSumQuestionDetailsTest.java
Labels: s.ToMerge

#12405 [#12333] Instructor students page: accessibility issue for course summary headers
  src/web/app/pages-instructor/instructor-student-list-page/instructor-student-list-page.component.html
Labels: s.ToMerge

#12241 [#12048] Migrate Delete Student/Students Action
  src/it/java/teammates/it/ui/webapi/DeleteStudentActionIT.java
  src/it/java/teammates/it/ui/webapi/DeleteStudentsActionIT.java
  src/it/resources/data/DataBundleLogicIT.json
  src/it/resources/data/typicalDataBundle.json
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/DeadlineExtensionsLogic.java
  src/main/java/teammates/sqllogic/core/FeedbackQuestionsLogic.java
  src/main/java/teammates/sqllogic/core/FeedbackResponsesLogic.java
  src/main/java/teammates/sqllogic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/sqllogic/core/LogicStarter.java
  src/main/java/teammates/sqllogic/core/UsersLogic.java
  src/main/java/teammates/storage/sqlapi/FeedbackResponsesDb.java
  src/main/java/teammates/storage/sqlapi/UsersDb.java
  src/main/java/teammates/storage/sqlentity/DeadlineExtension.java
  src/main/java/teammates/storage/sqlentity/FeedbackResponseComment.java
  src/main/java/teammates/storage/sqlentity/FeedbackSession.java
  src/main/java/teammates/ui/webapi/DeleteStudentAction.java
  src/main/java/teammates/ui/webapi/DeleteStudentsAction.java
  src/main/java/teammates/ui/webapi/FeedbackSessionRemindEmailWorkerAction.java
  src/test/java/teammates/sqllogic/core/FeedbackQuestionsLogicTest.java
  src/test/java/teammates/sqllogic/core/UsersLogicTest.java
  src/test/java/teammates/sqlui/webapi/FeedbackSessionRemindEmailWorkerActionTest.java
Labels: s.ToReview

#12273 [#12048] Migrate GetFeedbackSessionsAction
  src/it/java/teammates/it/sqllogic/core/FeedbackSessionsLogicIT.java
  src/it/java/teammates/it/storage/sqlapi/UsersDbIT.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/sqllogic/core/UsersLogic.java
  src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java
  src/main/java/teammates/storage/sqlapi/UsersDb.java
  src/main/java/teammates/ui/output/FeedbackSessionsData.java
  src/main/java/teammates/ui/webapi/GetFeedbackSessionsAction.java
  src/test/java/teammates/sqlui/webapi/GetFeedbackSessionsActionTest.java
Labels: s.ToReview

#12409 [#12399] Instructor editing feedback path of a question: unnecessary scrollbars
  src/web/app/components/feedback-path-panel/feedback-path-panel.component.html
  src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
Labels: s.ToMerge
