Repository TEAMMATES/teammates, pull requests merged in 2023-02, with the labels that each got.

#12044 [#12042] Style page navigation menu items as links
  src/web/app/pages-help/instructor-help-page/instructor-help-page.component.html
Labels: c.Bug, s.ToMerge

#11949 [#8431] InstructorFeedbackEditPage: include question type help in lightbox
  src/web/app/components/adding-question-panel/adding-question-panel.component.html
  src/web/app/components/adding-question-panel/adding-question-panel.component.spec.ts
  src/web/app/components/teammates-common/question-type-help-path.pipe.spec.ts
  src/web/app/components/teammates-common/question-type-help-path.pipe.ts
  src/web/app/components/teammates-common/teammates-common.module.ts
  src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
Labels: s.ToMerge, c.Feature

#12040 [#1501] Create Unit tests for FeedbackRubricQuestionDetails Class
  src/test/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetailsTest.java
Labels: s.ToMerge, c.Task

#12057 [#12043] Navigation menu got collapsed
  src/web/app/page.component.html
Labels: c.Bug, s.ToMerge

#12054 [#12020] Set generated app.admins field in build.properties to app_admin@gmail.com instead of app_admin
  src/e2e/resources/test.ci-chrome.properties
  src/e2e/resources/test.ci-edge.properties
  src/e2e/resources/test.ci-firefox.properties
  src/e2e/resources/test.template.properties
  src/main/resources/build.template.properties
  src/main/resources/devServerLoginPage.html
Labels: s.ToMerge, c.Task

#12030 [#11853] Add stricter checks for potentially destructive question edits
  src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap
  src/web/app/components/question-edit-form/question-edit-form.component.ts
  src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.html
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
Labels: s.ToMerge, c.Task

#12060 [#12058] Release V8.22.0
  src/web/data/developers.json
Labels: s.ToMerge, c.Release

#12063 [#12048] Add isMigrated flag to course
  src/main/java/teammates/common/datatransfer/attributes/CourseAttributes.java
  src/main/java/teammates/storage/entity/Course.java
  src/test/java/teammates/common/datatransfer/attributes/CourseAttributesTest.java
Labels: s.ToMerge, c.Task

#12066 [#12065] Student viewing rubric results: average doesn't match
  src/web/app/components/question-types/question-statistics/question-statistics-calculation/rubric-question-statistics-calculation.ts
  src/web/app/components/question-types/question-statistics/test-data/rubricQuestionResponses.json
  src/web/services/__snapshots__/session-result-csv.service.spec.ts.snap
Labels: c.Bug, s.ToMerge

#12061 Create Notification Entity for PostgreSQL migration
  src/main/java/teammates/storage/sqlentity/Notification.java
Labels: s.ToReview

#12075 Create notification DB layer for v9 migration
  src/main/java/teammates/storage/sqlapi/NotificationsDb.java
  src/main/java/teammates/storage/sqlentity/Notification.java
Labels: s.ToReview

#12076 Add UsageStatistics entity and db
  src/main/java/teammates/storage/sqlapi/UsageStatisticsDb.java
  src/main/java/teammates/storage/sqlentity/UsageStatistics.java
Labels: s.ToMerge, c.Task

#12077 Create SQL logic for CreateNotificationAction and add relevant tests for v9 migration
  src/it/java/teammates/it/storage/sqlapi/NotificationDbIT.java
  src/it/java/teammates/it/test/BaseTestCaseWithSqlDatabaseAccess.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/LogicStarter.java
  src/main/java/teammates/sqllogic/core/NotificationsLogic.java
  src/main/java/teammates/storage/sqlapi/NotificationsDb.java
  src/main/java/teammates/storage/sqlentity/Notification.java
  src/main/java/teammates/ui/output/NotificationData.java
  src/main/java/teammates/ui/webapi/CreateNotificationAction.java
  src/test/java/teammates/storage/sqlapi/NotificationsDbTest.java
Labels: s.ToMerge

#12095 [#12021] Update Jetty library to 10 or 11
  build.gradle
  src/main/java/teammates/main/Application.java
Labels: s.ToMerge, c.Task

#12102 [#12097] Release V8.23.0
  src/web/data/developers.json
Labels: s.ToMerge, c.Release

#12105 [#12081] User-friendliness: Make header dropdowns focusable
  src/web/app/page.component.html
  src/web/app/page.component.scss
Labels: s.ToMerge

#12108 [#12081] Tag all TEAMMATES pages with <main>
  .github/workflows/axe.yml
  .github/workflows/e2e.yml
  src/web/app/page.component.html
  src/web/app/page.component.scss
  src/web/app/pages-help/instructor-help-page/instructor-help-students-section/instructor-help-students-section.component.html
  src/web/app/pages-help/session-links-recovery/session-links-recovery-page.component.html
  src/web/app/pages-help/student-help-page/student-help-page.component.html
  src/web/app/pages-session/session-result-page/__snapshots__/session-result-page.component.spec.ts.snap
  src/web/app/pages-session/session-result-page/session-result-page.component.html
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
  src/web/app/pages-session/session-submission-page/session-submission-page.component.html
  src/web/app/pages-static/contact-page/contact-page.component.html
  src/web/app/pages-static/features-page/features-page.component.html
  src/web/app/pages-static/index-page/index-page.component.html
  src/web/app/pages-static/request-page/request-page.component.html
  src/web/app/pages-static/terms-page/terms-page.component.html
Labels: s.ToMerge

#12080 Create SQL logic for GetNotificationAction and add relevant tests for v9 migration
  src/it/java/teammates/it/storage/sqlapi/NotificationDbIT.java
  src/it/java/teammates/it/test/BaseTestCaseWithSqlDatabaseAccess.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/NotificationsLogic.java
  src/main/java/teammates/ui/webapi/Action.java
  src/main/java/teammates/ui/webapi/GetNotificationAction.java
  src/test/java/teammates/storage/sqlapi/NotificationsDbTest.java
  src/test/java/teammates/ui/webapi/GetNotificationActionTest.java
Labels: s.ToReview

#12123 [#12115] Instructor viewing results of rubric questions: some students not shown in the stats table
  src/web/app/components/question-types/question-statistics/question-statistics-calculation/rubric-question-statistics-calculation.ts
  src/web/app/components/question-types/question-statistics/test-data/rubricQuestionResponses.json
Labels: s.ToMerge

#12114 [#12048] Migrate accounts Db
  src/it/java/teammates/it/storage/sqlapi/AccountRequestDbIT.java
  src/it/java/teammates/it/storage/sqlapi/AccountsDbIT.java
  src/it/java/teammates/it/test/BaseTestCaseWithSqlDatabaseAccess.java
  src/main/java/teammates/common/util/HibernateUtil.java
  src/main/java/teammates/storage/sqlapi/AccountsDb.java
  src/main/java/teammates/storage/sqlapi/EntitiesDb.java
  src/main/java/teammates/storage/sqlentity/Account.java
  src/test/java/teammates/storage/sqlapi/AccountsDbTest.java
  src/test/java/teammates/storage/sqlapi/CoursesDbTest.java
Labels: s.ToMerge

#12093 Create FeedbackQuestion Entity for PostgreSQL Migration
  src/main/java/teammates/common/util/HibernateUtil.java
  src/main/java/teammates/storage/sqlentity/BaseEntity.java
  src/main/java/teammates/storage/sqlentity/FeedbackQuestion.java
  src/main/java/teammates/storage/sqlentity/questions/FeedbackNumericalScaleQuestion.java
  src/main/java/teammates/storage/sqlentity/questions/FeedbackTextQuestion.java
  src/main/java/teammates/storage/sqlentity/questions/package-info.java
Labels: s.ToReview

#12133 [#12131] Instructor edit session times: timing restrictions are not as expected
  src/web/app/components/timepicker/timepicker.component.ts
  src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-sessions-page/__snapshots__/instructor-sessions-page.component.spec.ts.snap
Labels: s.ToMerge

#12129 [#12081] User-friendliness: Landmark questions in feedback sessions results page
  src/e2e/java/teammates/e2e/pageobjects/FeedbackResultsPage.java
  src/web/app/components/question-response-panel/__snapshots__/question-response-panel.component.spec.ts.snap
  src/web/app/components/question-text-with-info/__snapshots__/question-text-with-info.component.spec.ts.snap
  src/web/app/components/question-text-with-info/question-text-with-info.component.html
  src/web/app/components/question-text-with-info/question-text-with-info.component.scss
  src/web/app/components/question-text-with-info/question-text-with-info.component.spec.ts
Labels: s.ToReview

#12139 [#12081] User-friendliness: Fix evaluee/recipient mobile text wrap
  src/web/app/components/question-submission-form/question-submission-form.component.html
  src/web/app/components/question-submission-form/question-submission-form.component.scss
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
Labels: s.ToMerge

#12146 Resolve width issue for num scale question
  src/web/app/components/question-types/question-edit-answer-form/num-scale-question-edit-answer-form.component.html
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
Labels: c.Bug

#12144 [#12081] User-friendliness: Add labels for MSQ checkboxes
  src/web/app/components/question-submission-form/question-submission-form.component.html
  src/web/app/components/question-types/question-edit-answer-form/__snapshots__/mcq-question-edit-answer-form.component.spec.ts.snap
  src/web/app/components/question-types/question-edit-answer-form/msq-question-edit-answer-form.component.html
  src/web/app/components/question-types/question-edit-answer-form/question-edit-answer-form.ts
  src/web/app/components/question-types/question-edit-answer-form/text-question-edit-answer-form.component.ts
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
Labels: s.ToMerge

#12147 [#12081] User-friendliness: Add labels for MCQ question
  src/web/app/components/question-submission-form/question-submission-form.component.html
  src/web/app/components/question-types/question-edit-answer-form/__snapshots__/mcq-question-edit-answer-form.component.spec.ts.snap
  src/web/app/components/question-types/question-edit-answer-form/mcq-question-edit-answer-form.component.html
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
Labels: s.ToMerge

#12148 [#12081] User-friendliness: Add labels for numerical scale questions
  src/web/app/components/question-submission-form/question-submission-form.component.html
  src/web/app/components/question-types/question-edit-answer-form/num-scale-question-edit-answer-form.component.html
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
Labels: s.ToMerge
