Repository TEAMMATES/teammates, pull requests merged in 2023-05, with the labels that each got.

#12408 [#12281] Fix deleted feedback sessions table overflow
  src/web/app/components/sessions-recycle-bin-table/sessions-recycle-bin-table.component.html
  src/web/app/components/sessions-recycle-bin-table/sessions-recycle-bin-table.component.scss
Labels: s.ToMerge

#12403 [#12327] Consolidate duplicate modified timestamp modals
  src/web/app/components/modified-timestamps-modal/__snapshots__/modified-timestamps-modal.component.spec.ts.snap
  src/web/app/components/modified-timestamps-modal/modified-timestamps-modal.component.html
  src/web/app/components/modified-timestamps-modal/modified-timestamps-modal.component.scss
  src/web/app/components/modified-timestamps-modal/modified-timestamps-modal.component.spec.ts
  src/web/app/components/modified-timestamps-modal/modified-timestamps-modal.component.ts
  src/web/app/components/modified-timestamps-modal/modified-timestamps-module.module.ts
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.html
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.module.ts
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.module.ts
  src/web/app/pages-instructor/instructor-session-base-page.component.ts
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.html
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.module.ts
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.html
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.module.ts
Labels: s.Ongoing

#12411 [#12292] Admin logs page: Fix display of logs table on mobile
  src/web/app/components/logs-table/logs-table.component.html
  src/web/app/components/logs-table/logs-table.component.scss
  src/web/app/pages-monitoring/logs-page/__snapshots__/logs-page.component.spec.ts.snap
  src/web/app/pages-monitoring/logs-page/logs-page.component.html
  src/web/app/pages-monitoring/logs-page/logs-page.component.scss
Labels: s.FinalReview

#12429 [#12407] Sort icons in info table headings are hard to see
  src/web/app/components/student-list/student-list.component.scss
Labels: s.ToMerge

#12436 [#10976] Document frontend standardizations
  docs/best-practices/ui-design.md
Labels: s.ToReview

#12365 [#12048] Restore sent*email fields
  src/it/java/teammates/it/sqllogic/core/DataBundleLogicIT.java
  src/it/resources/data/DataBundleLogicIT.json
  src/it/resources/data/typicalDataBundle.json
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/api/SqlEmailGenerator.java
  src/main/java/teammates/sqllogic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/storage/sqlentity/DeadlineExtension.java
  src/main/java/teammates/storage/sqlentity/FeedbackSession.java
  src/main/java/teammates/ui/output/DeadlineExtensionData.java
  src/main/java/teammates/ui/webapi/FeedbackSessionPublishedEmailWorkerAction.java
  src/main/java/teammates/ui/webapi/FeedbackSessionUnpublishedEmailWorkerAction.java
Labels: s.Ongoing

#12420 [#12312] Instructor giving individual deadline extensions: give an easy way to select all those who have not submitted yet
  src/web/app/pages-instructor/instructor-session-individual-extension-page/__snapshots__/instructor-session-individual-extension-page.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-individual-extension-page/extension-table-column-model.ts
  src/web/app/pages-instructor/instructor-session-individual-extension-page/instructor-session-individual-extension-page.component.html
  src/web/app/pages-instructor/instructor-session-individual-extension-page/instructor-session-individual-extension-page.component.ts
  src/web/app/pages-instructor/instructor-session-individual-extension-page/instructor-session-individual-extension-page.spec.ts
Labels: s.FinalReview

#12412 [#12048] Migrate DeleteInstructorAction
  src/it/java/teammates/it/ui/webapi/DeleteInstructorActionIT.java
  src/it/resources/data/typicalDataBundle.json
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/UsersLogic.java
  src/main/java/teammates/ui/webapi/DeleteInstructorAction.java
Labels: s.ToReview

#12435 [#12430] Include student email in 'distribute points' type question summary table CSV
  src/web/services/__snapshots__/session-result-csv.service.spec.ts.snap
  src/web/types/question-details-impl/feedback-constsum-recipient-question-details.impl.ts
  src/web/types/question-details-impl/feedback-num-scale-question-details.impl.ts
  src/web/types/question-details-impl/feedback-rank-recipients-question-details.impl.ts
Labels: s.FinalReview

#12428 [#12010] Notifications box overlaps with the page menu in the instructor help page
  src/web/app/pages-help/instructor-help-page/instructor-help-page.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-page.component.scss
Labels: s.FinalReview

#12443 [#10920] Add test for restoreCourse in Instructor Courses Page
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.spec.ts
Labels: s.ToMerge
