Repository TEAMMATES/teammates, pull requests merged in 2023-07, with the labels that each got.

#12477 [#12269] Instructor edit sessions page: Fix add question button overflow.
  src/web/app/components/adding-question-panel/adding-question-panel.component.html
  src/web/app/components/adding-question-panel/adding-question-panel.component.scss
  src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
Labels: s.ToReview

#12492 [#12275] Instructor edit sessions page: Fix preview sessions button overflow
  src/web/app/components/preview-session-panel/preview-session-panel.component.html
  src/web/app/components/preview-session-panel/preview-session-panel.component.scss
  src/web/app/components/preview-session-result-panel/preview-session-result-panel.component.html
  src/web/app/components/preview-session-result-panel/preview-session-result-panel.component.scss
  src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
Labels: s.FinalReview

#12500 [#12280] Improve display for create course card header
  src/web/app/components/course-edit-form/__snapshots__/course-edit-form.component.spec.ts.snap
  src/web/app/components/course-edit-form/course-edit-form.component.html
  src/web/app/components/course-edit-form/course-edit-form.component.scss
  src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap
Labels: s.FinalReview

#12463 [#12457] Make the table buttons easier to use on mobile devices
  src/web/app/components/student-list/__snapshots__/student-list.component.spec.ts.snap
  src/web/app/components/student-list/student-list.component.html
  src/web/app/components/student-list/student-list.component.scss
  src/web/app/pages-instructor/instructor-course-details-page/__snapshots__/instructor-course-details-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.html
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.scss
  src/web/app/pages-instructor/instructor-search-page/__snapshots__/instructor-search-page.component.spec.ts.snap
  src/web/app/pages-student/student-home-page/__snapshots__/student-home-page.component.spec.ts.snap
  src/web/app/pages-student/student-home-page/student-home-page.component.html
  src/web/app/pages-student/student-home-page/student-home-page.component.scss
Labels: s.FinalReview

#12498 [#12494] Allow instructors to use start/end dates up to 12 months in future
  src/main/java/teammates/common/util/FieldValidator.java
  src/main/java/teammates/common/util/TimeHelper.java
  src/test/java/teammates/common/util/FieldValidatorTest.java
  src/test/java/teammates/common/util/TimeHelperExtension.java
  src/test/java/teammates/common/util/TimeHelperTest.java
  src/web/app/components/session-edit-form/session-edit-form.component.ts
  src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-base-page.component.ts
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.html
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.html
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.ts
Labels: s.ToReview

#12509 [#11947] Format error toasts
  src/e2e/java/teammates/e2e/cases/BaseE2ETestCase.java
  src/e2e/java/teammates/e2e/cases/InstructorCourseEditPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorHomePageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/AppPage.java
  src/main/java/teammates/ui/webapi/CreateFeedbackQuestionAction.java
  src/main/java/teammates/ui/webapi/SubmitFeedbackResponsesAction.java
  src/main/java/teammates/ui/webapi/UpdateFeedbackQuestionAction.java
  src/web/app/components/toast/toast.component.scss
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.ts
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.ts
Labels: s.ToMerge

#12516 [#12514] Release V8.28.0
  src/web/data/developers.json
Labels: s.ToMerge, c.Release

#12493 [#12287] Student home page: Make it easier to navigate courses
  src/main/java/teammates/ui/output/CourseData.java
  src/test/java/teammates/ui/webapi/GetCoursesActionTest.java
  src/web/app/pages-student/student-home-page/__snapshots__/student-home-page.component.spec.ts.snap
  src/web/app/pages-student/student-home-page/student-home-page.component.html
  src/web/app/pages-student/student-home-page/student-home-page.component.spec.ts
  src/web/app/pages-student/student-home-page/student-home-page.component.ts
  src/web/app/pages-student/student-home-page/student-home-page.module.ts
Labels: s.FinalReview

#12506 [#12473] Add steps on how to use the masquerade mode in developer guide
  docs/development.md
Labels: s.FinalReview

#12426 [#12421] Comments for Responses for Essay Question
  src/main/java/teammates/common/datatransfer/questions/FeedbackConstantSumQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackMcqQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackMsqQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackNumericalScaleQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRankOptionsQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRankRecipientsQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackTextQuestionDetails.java
  src/main/java/teammates/ui/webapi/BasicCommentSubmissionAction.java
  src/main/java/teammates/ui/webapi/CreateFeedbackResponseCommentAction.java
  src/main/java/teammates/ui/webapi/GetFeedbackResponsesAction.java
  src/test/java/teammates/common/datatransfer/questions/FeedbackConstantSumQuestionDetailsTest.java
  src/test/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetailsTest.java
  src/test/java/teammates/common/datatransfer/questions/FeedbackMcqQuestionDetailsTest.java
  src/test/java/teammates/common/datatransfer/questions/FeedbackMsqQuestionDetailsTest.java
  src/test/java/teammates/common/datatransfer/questions/FeedbackNumericalScaleQuestionDetailsTest.java
  src/test/java/teammates/common/datatransfer/questions/FeedbackRankOptionsQuestionDetailsTest.java
  src/test/java/teammates/common/datatransfer/questions/FeedbackRankRecipientsQuestionDetailsTest.java
  src/test/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetailsTest.java
  src/test/java/teammates/common/datatransfer/questions/FeedbackTextQuestionDetailsTest.java
  src/test/java/teammates/ui/webapi/CreateFeedbackResponseCommentActionTest.java
  src/test/java/teammates/ui/webapi/GetFeedbackResponsesActionTest.java
  src/test/resources/data/FeedbackResponseCommentCRUDTest.json
  src/web/app/components/question-responses/per-question-view-responses/__snapshots__/per-question-view-responses.component.spec.ts.snap
  src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.html
  src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.spec.ts
  src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.ts
  src/web/app/components/question-submission-form/question-submission-form.component.html
  src/web/app/components/question-submission-form/question-submission-form.component.ts
  src/web/app/components/question-types/question-constraint/contribution-question-constraint.component.ts
  src/web/app/components/question-types/question-constraint/question-constraint.component.ts
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
  src/web/services/__snapshots__/session-result-csv.service.spec.ts.snap
  src/web/services/feedback-questions.service.ts
  src/web/services/feedback-response-comment.service.spec.ts
  src/web/services/session-result-csv.service.ts
  src/web/services/test-data/feedbackSessionResultsConstsumResults.json
  src/web/services/test-data/feedbackSessionResultsContribResults.json
  src/web/services/test-data/feedbackSessionResultsMcqResults.json
  src/web/services/test-data/feedbackSessionResultsNumscaleResults.json
  src/web/services/test-data/feedbackSessionResultsRankResults.json
  src/web/services/test-data/feedbackSessionResultsRubricResults.json
Labels: s.ToMerge

#12525 [#12444] Updated development.md
  docs/development.md
  docs/search.md
Labels: s.ToMerge

#12528 [#12259] Update tzdb version to 2023c
  src/main/resources/tzdb.dat
  src/web/data/timezone.json
Labels: s.ToMerge, c.Task

#12515 [#12059] Separate stable and unstable E2E tests
  .github/workflows/e2e.yml
  build.gradle
  src/e2e/resources/testng-e2e.xml
  src/e2e/resources/testng-unstable-e2e.xml
Labels: s.ToMerge, c.DevOps

#12521 [#10508] Instructor courses page: some items don't show spinners
  src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.html
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.spec.ts
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts
Labels: s.ToMerge
