Repository TEAMMATES/teammates, pull requests merged in 2023-03, with the labels that each got.

#12149 [#12081] User-friendliness: Add labels and groups to distribute points (options) question
  src/web/app/components/question-submission-form/question-submission-form.component.html
  src/web/app/components/question-types/question-edit-answer-form/constsum-options-question-edit-answer-form.component.html
  src/web/app/components/question-types/question-edit-answer-form/constsum-options-question-edit-answer-form.component.ts
Labels: s.ToMerge

#12051 [#12045] Instructor copying sessions: preserve time when auto-changing dates
  src/e2e/java/teammates/e2e/cases/InstructorFeedbackSessionsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorHomePageE2ETest.java
  src/web/app/pages-instructor/instructor-session-base-page.component.ts
Labels: s.ToMerge

#12150 [#12081] User-friendliness: Add labels for distribute points by recipient questions
  src/web/app/components/question-submission-form/question-submission-form.component.html
  src/web/app/components/question-submission-form/question-submission-form.component.ts
  src/web/app/components/question-types/question-edit-answer-form/constsum-recipients-question-edit-answer-form.component.html
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
Labels: s.ToMerge

#12153 User-friendliness: Add labels and change "more info" button for team contribution questions
  src/web/app/components/question-submission-form/question-submission-form.component.html
  src/web/app/components/question-types/question-edit-answer-form/contribution-question-edit-answer-form.component.html
  src/web/app/components/question-types/question-edit-answer-form/contribution-question-edit-answer-form.component.ts
  src/web/app/components/question-types/question-instruction/contribution-question-instruction.component.html
  src/web/app/components/question-types/question-instruction/contribution-question-instruction.component.ts
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
Labels: s.ToMerge

#12156 [#12048] Update GetReadNotificationsAction and MarkNotificationAsReadAction for v9 migration
  src/it/java/teammates/it/sqllogic/core/AccountsLogicIT.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/AccountsLogic.java
  src/main/java/teammates/sqllogic/core/LogicStarter.java
  src/main/java/teammates/storage/sqlentity/Account.java
  src/main/java/teammates/storage/sqlentity/Notification.java
  src/main/java/teammates/ui/webapi/GetReadNotificationsAction.java
  src/main/java/teammates/ui/webapi/MarkNotificationAsReadAction.java
  src/test/java/teammates/sqllogic/core/AccountsLogicTest.java
  src/test/java/teammates/test/BaseTestCase.java
  src/test/java/teammates/ui/webapi/GetReadNotificationsActionTest.java
  src/test/java/teammates/ui/webapi/MarkNotificationAsReadActionTest.java
Labels: s.ToReview

#12151 [#12116] Instructor viewing results of rubric questions: missing space after checkbox
  src/web/app/components/question-types/question-statistics/rubric-question-statistics.component.html
Labels: s.ToMerge

#12162 [#12081] Refactor accessibility rule disabling logic
  src/e2e/java/teammates/e2e/util/AxeUtil.java
Labels: s.ToMerge

#12167 [#12081] User-friendliness: Add label to rank recipients question
  src/web/app/components/question-submission-form/question-submission-form.component.html
  src/web/app/components/question-types/question-edit-answer-form/rank-recipients-question-edit-answer-form.component.html
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
Labels: s.ToMerge

#12164 [#12081] Modify header and footer colours
  src/web/app/page.component.html
  src/web/app/page.component.scss
  src/web/styles.scss
Labels: s.ToMerge

#12172 [#12081] User-friendliness: Add labels to rank options questions
  src/web/app/components/question-submission-form/question-submission-form.component.html
  src/web/app/components/question-types/question-edit-answer-form/rank-options-question-edit-answer-form.component.html
  src/web/app/components/question-types/question-edit-answer-form/rank-options-question-edit-answer-form.component.ts
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
Labels: s.ToMerge

#12152 [#12064] Add back per criterion averages to the stat table
  angular.json
  src/web/app/components/question-types/question-statistics/rubric-question-statistics.component.ts
  src/web/services/__snapshots__/session-result-csv.service.spec.ts.snap
  src/web/types/question-details-impl/feedback-rubric-question-details.impl.ts
Labels: s.ToMerge

#12178 [#12048] Migrate GetNotificationsAction
  src/it/java/teammates/it/storage/sqlapi/NotificationDbIT.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/NotificationsLogic.java
  src/main/java/teammates/storage/sqlapi/NotificationsDb.java
  src/main/java/teammates/ui/output/NotificationsData.java
  src/main/java/teammates/ui/webapi/GetNotificationsAction.java
  src/test/java/teammates/ui/webapi/GetNotificationsActionTest.java
Labels: s.ToReview

#12174 [#12081] User-friendliness: Fix numerical scale question table in view responses page
  src/web/app/components/question-types/question-statistics/num-scale-question-statistics.component.html
  src/web/app/components/sortable-table/sortable-table.component.html
  src/web/app/components/sortable-table/sortable-table.component.scss
  src/web/app/components/sortable-table/sortable-table.component.ts
  src/web/app/pages-instructor/instructor-student-activity-logs/__snapshots__/instructor-student-activity-logs.component.spec.ts.snap
Labels: s.ToMerge

#12179 [#12081] User-friendliness: Fix dropdown caret overlap
  src/web/app/components/question-submission-form/question-submission-form.component.html
  src/web/app/components/question-submission-form/question-submission-form.component.scss
Labels: s.ToMerge

#12183 [#12182][#12068] student viewing results: the spinner keeps going until the user clicks on the page
  src/e2e/java/teammates/e2e/cases/FeedbackResultsPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/FeedbackResultsPage.java
  src/main/java/teammates/ui/output/SessionResultsData.java
  src/web/app/components/question-types/question-statistics/question-statistics-calculation/rubric-question-statistics-calculation.ts
  src/web/app/components/question-types/question-statistics/rubric-question-statistics.component.html
  src/web/app/components/question-types/question-statistics/rubric-question-statistics.component.ts
Labels: c.Bug, s.ToReview

#12190 [#12048] Update MarkNotificationAsReadAction logic for unmigrated accounts
  src/main/java/teammates/ui/webapi/Action.java
  src/main/java/teammates/ui/webapi/MarkNotificationAsReadAction.java
Labels: s.ToReview

#12180 [#12081] Remove Bootstrap column style override
  src/web/app/components/course-edit-form/__snapshots__/course-edit-form.component.spec.ts.snap
  src/web/app/components/course-edit-form/course-edit-form.component.html
  src/web/app/components/course-edit-form/course-edit-form.component.scss
  src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.html
  src/web/app/components/question-submission-form/question-submission-form.component.html
  src/web/app/components/question-submission-form/question-submission-form.component.scss
  src/web/app/components/question-types/question-edit-answer-form/num-scale-question-edit-answer-form.component.html
  src/web/app/components/question-types/question-edit-answer-form/num-scale-question-edit-answer-form.component.scss
  src/web/app/components/question-types/question-edit-details-form/constsum-recipients-question-edit-details-form.component.html
  src/web/app/components/question-types/question-edit-details-form/constsum-recipients-question-edit-details-form.component.scss
  src/web/app/pages-help/session-links-recovery/session-links-recovery-page.component.html
  src/web/app/pages-help/session-links-recovery/session-links-recovery-page.component.scss
  src/web/app/pages-instructor/instructor-course-edit-page/__snapshots__/instructor-course-edit-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-edit-panel/instructor-edit-panel.component.html
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-edit-panel/instructor-edit-panel.component.scss
  src/web/app/pages-instructor/instructor-course-student-edit-page/__snapshots__/instructor-course-student-edit-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.html
  src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.scss
  src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
  src/web/styles.scss
Labels: s.ToMerge

#12187 [#12067] Inconsistent spacing in headings of rubric question statistics
  src/web/app/components/question-types/question-statistics/rubric-question-statistics.component.html
Labels: s.ToMerge

#12155 [#12081] User-friendliness: Add labels to rubric questions
  src/e2e/java/teammates/e2e/pageobjects/AppPage.java
  src/e2e/java/teammates/e2e/pageobjects/FeedbackSubmitPage.java
  src/web/app/components/question-submission-form/question-submission-form.component.html
  src/web/app/components/question-types/question-edit-answer-form/rubric-question-edit-answer-form.component.html
  src/web/app/components/question-types/question-edit-answer-form/rubric-question-edit-answer-form.component.ts
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
Labels: s.ToMerge

#12191 [#12161] Instructor adding a new session: stray X in the form UI
  src/web/app/components/session-edit-form/session-edit-form.component.scss
Labels: s.ToMerge

#12197 [#12081] User-friendliness: Display card header content in column format for mobile
  src/web/app/components/question-response-panel/__snapshots__/question-response-panel.component.spec.ts.snap
  src/web/app/components/question-text-with-info/__snapshots__/question-text-with-info.component.spec.ts.snap
  src/web/app/components/question-text-with-info/question-text-with-info.component.html
  src/web/app/components/question-text-with-info/question-text-with-info.component.scss
Labels: s.ToMerge

#12200 [#12081] User-friendliness: Change white text on info background
  src/web/app/components/question-response-panel/__snapshots__/question-response-panel.component.spec.ts.snap
  src/web/app/components/question-responses/student-view-responses/student-view-responses.component.html
Labels: s.ToMerge

#12202 [#12048] Update FeedbackSession entity and add methods for FeedbackQuestion use
  src/it/java/teammates/it/storage/sqlapi/FeedbackSessionsDbIT.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java
  src/main/java/teammates/storage/sqlentity/FeedbackSession.java
  src/main/java/teammates/ui/webapi/Action.java
Labels: s.ToReview

#12201 [#12081] User-friendliness: Make rubric question response table mobile responsive
  src/web/app/components/question-response-panel/__snapshots__/question-response-panel.component.spec.ts.snap
  src/web/app/components/question-responses/student-view-responses/student-view-responses.component.html
  src/web/app/components/question-types/question-response/rubric-question-response.component.html
Labels: s.ToMerge

#12205 [#12081] User-friendliness: Make submit feedback rubric table cell clickable
  src/web/app/components/question-types/question-edit-answer-form/rubric-question-edit-answer-form.component.html
  src/web/app/components/question-types/question-edit-answer-form/rubric-question-edit-answer-form.component.ts
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
Labels: s.ToMerge

#12196 [#12194] Add simple workflow to vet pull requests
  .github/workflows/pr.yml
Labels: s.ToMerge

#12193 [#12186] Remove raised-edge from home and features page
  src/web/app/pages-static/features-page/features-page.component.html
  src/web/app/pages-static/index-page/index-page.component.html
  src/web/assets/images/raised-edge.png
Labels: s.ToMerge

#12207 [#12081] User-friendliness: Fix feedback path dropdown
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java
  src/web/app/components/feedback-path-panel/feedback-path-panel.component.html
  src/web/app/components/feedback-path-panel/feedback-path-panel.component.scss
  src/web/app/components/feedback-path-panel/feedback-path-panel.component.ts
  src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
Labels: s.ToMerge

#12206 [#12081] Fix duplicate IDs in codebase
  src/e2e/java/teammates/e2e/pageobjects/FeedbackResultsPage.java
  src/e2e/java/teammates/e2e/pageobjects/FeedbackSubmitPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorCourseDetailsPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackResultsPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackSessionsPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorHomePage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorSearchPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorStudentListPage.java
  src/e2e/java/teammates/e2e/pageobjects/UserNotificationsPage.java
  src/web/app/components/comment-box/comment-row/comment-row.component.html
  src/web/app/components/question-response-panel/__snapshots__/question-response-panel.component.spec.ts.snap
  src/web/app/components/question-response-panel/question-response-panel.component.html
  src/web/app/components/question-response-panel/question-response-panel.component.scss
  src/web/app/components/question-responses/gqr-rqg-view-responses/gqr-rqg-view-responses.component.html
  src/web/app/components/question-responses/grouped-responses/grouped-responses.component.html
  src/web/app/components/question-submission-form/question-submission-form.component.html
  src/web/app/components/question-submission-form/question-submission-form.component.scss
  src/web/app/components/question-text-with-info/__snapshots__/question-text-with-info.component.spec.ts.snap
  src/web/app/components/question-text-with-info/question-text-with-info.component.html
  src/web/app/components/session-edit-form/session-edit-form.component.html
  src/web/app/components/sessions-table/__snapshots__/sessions-table.component.spec.ts.snap
  src/web/app/components/sessions-table/sessions-table.component.html
  src/web/app/components/student-list/__snapshots__/student-list.component.spec.ts.snap
  src/web/app/components/student-list/student-list.component.html
  src/web/app/components/user-notifications-list/__snapshots__/user-notifications-list.component.spec.ts.snap
  src/web/app/components/user-notifications-list/user-notifications-list.component.html
  src/web/app/components/user-notifications-list/user-notifications-list.component.spec.ts
  src/web/app/pages-instructor/instructor-course-details-page/__snapshots__/instructor-course-details-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.spec.ts
  src/web/app/pages-instructor/instructor-search-page/__snapshots__/instructor-search-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-individual-extension-page/__snapshots__/instructor-session-individual-extension-page.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-individual-extension-page/instructor-session-individual-extension-page.component.html
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-question-view.component.html
  src/web/app/pages-instructor/instructor-sessions-page/__snapshots__/instructor-sessions-page.component.spec.ts.snap
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
Labels: s.ToMerge

#12215 [#11383] Fix PR checking workflow permissions
  .github/workflows/pr.yml
Labels: s.ToMerge

#12209 [#12081] User-friendliness: Fix custom visibility options
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java
  src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap
  src/web/app/components/visibility-panel/visibility-panel.component.html
  src/web/app/components/visibility-panel/visibility-panel.component.scss
  src/web/app/components/visibility-panel/visibility-panel.component.ts
  src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
Labels: s.ToMerge

#12217 [#12048] Migrate CreateFeedbackQuestionAction
  src/it/java/teammates/it/sqllogic/core/DataBundleLogicIT.java
  src/it/java/teammates/it/sqllogic/core/FeedbackQuestionsLogicIT.java
  src/it/java/teammates/it/storage/sqlapi/FeedbackQuestionsDbIT.java
  src/it/java/teammates/it/test/BaseTestCaseWithSqlDatabaseAccess.java
  src/it/resources/data/DataBundleLogicIT.json
  src/it/resources/data/typicalDataBundle.json
  src/main/java/teammates/common/datatransfer/questions/FeedbackConstantSumQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackContributionQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackMcqQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackMsqQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackNumericalScaleQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRankOptionsQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRankRecipientsQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetails.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackTextQuestionDetails.java
  src/main/java/teammates/common/util/JsonUtils.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/DataBundleLogic.java
  src/main/java/teammates/sqllogic/core/FeedbackQuestionsLogic.java
  src/main/java/teammates/sqllogic/core/LogicStarter.java
  src/main/java/teammates/storage/sqlapi/FeedbackQuestionsDb.java
  src/main/java/teammates/storage/sqlentity/BaseEntity.java
  src/main/java/teammates/storage/sqlentity/FeedbackQuestion.java
  src/main/java/teammates/storage/sqlentity/FeedbackResponse.java
  src/main/java/teammates/storage/sqlentity/questions/FeedbackConstantSumQuestion.java
  src/main/java/teammates/storage/sqlentity/questions/FeedbackContributionQuestion.java
  src/main/java/teammates/storage/sqlentity/questions/FeedbackMcqQuestion.java
  src/main/java/teammates/storage/sqlentity/questions/FeedbackMsqQuestion.java
  src/main/java/teammates/storage/sqlentity/questions/FeedbackNumericalScaleQuestion.java
  src/main/java/teammates/storage/sqlentity/questions/FeedbackRankOptionsQuestion.java
  src/main/java/teammates/storage/sqlentity/questions/FeedbackRankRecipientsQuestion.java
  src/main/java/teammates/storage/sqlentity/questions/FeedbackRubricQuestion.java
  src/main/java/teammates/storage/sqlentity/questions/FeedbackTextQuestion.java
  src/main/java/teammates/storage/sqlentity/responses/FeedbackConstantSumResponse.java
  src/main/java/teammates/storage/sqlentity/responses/FeedbackContributionResponse.java
  src/main/java/teammates/storage/sqlentity/responses/FeedbackMcqResponse.java
  src/main/java/teammates/storage/sqlentity/responses/FeedbackMsqResponse.java
  src/main/java/teammates/storage/sqlentity/responses/FeedbackNumericalScaleResponse.java
  src/main/java/teammates/storage/sqlentity/responses/FeedbackRankOptionsResponse.java
  src/main/java/teammates/storage/sqlentity/responses/FeedbackRankRecipientsResponse.java
  src/main/java/teammates/storage/sqlentity/responses/FeedbackRubricResponse.java
  src/main/java/teammates/ui/output/FeedbackQuestionData.java
  src/main/java/teammates/ui/webapi/CreateFeedbackQuestionAction.java
  src/test/java/teammates/architecture/ArchitectureTest.java
  src/test/java/teammates/sqllogic/core/FeedbackQuestionsLogicTest.java
  src/test/java/teammates/ui/webapi/CreateFeedbackQuestionActionTest.java
Labels: s.ToReview

#12219 [#12081] User-friendliness: Fix screen reader issue for question description
  src/web/app/components/question-edit-brief-description-form/question-edit-brief-description-form.component.html
  src/web/app/components/question-edit-brief-description-form/question-edit-brief-description-form.component.scss
  src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
Labels: s.ToMerge

#12220 [#12081] User-friendliness: Add labels to input for essay question (instructor edit sessions page)
  src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap
  src/web/app/components/question-types/question-edit-details-form/text-question-edit-details-form.component.html
  src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
Labels: s.ToMerge

#12216 [#12035] Fix ChromeDriver setup for E2E tests
  src/e2e/java/teammates/e2e/pageobjects/Browser.java
Labels: s.ToMerge

#12225 [#12081] Minimise modal margin for mobile
  src/web/app/pages-instructor/instructor-session-edit-page/copy-questions-from-other-sessions-modal/copy-questions-from-other-sessions-modal.component.scss
  src/web/styles.scss
Labels: s.ToMerge

#12092 [#12048] Migrate Course Action classes
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/CoursesLogic.java
  src/main/java/teammates/sqllogic/core/UsersLogic.java
  src/main/java/teammates/storage/sqlapi/UsersDb.java
  src/main/java/teammates/storage/sqlentity/Course.java
  src/main/java/teammates/ui/webapi/BinCourseAction.java
  src/main/java/teammates/ui/webapi/CreateCourseAction.java
  src/main/java/teammates/ui/webapi/DeleteCourseAction.java
  src/main/java/teammates/ui/webapi/GetCourseAction.java
  src/main/java/teammates/ui/webapi/GetCourseSectionNamesAction.java
  src/main/java/teammates/ui/webapi/RestoreCourseAction.java
  src/main/java/teammates/ui/webapi/UpdateCourseAction.java
  src/test/java/teammates/architecture/ArchitectureTest.java
  src/test/java/teammates/sqllogic/core/CoursesLogicTest.java
  src/test/java/teammates/sqlui/webapi/BinCourseActionTest.java
  src/test/java/teammates/sqlui/webapi/CreateCourseActionTest.java
  src/test/java/teammates/sqlui/webapi/DeleteCourseActionTest.java
  src/test/java/teammates/sqlui/webapi/GetCourseActionTest.java
  src/test/java/teammates/sqlui/webapi/GetCourseSectionNamesActionTest.java
  src/test/java/teammates/sqlui/webapi/RestoreCourseActionTest.java
  src/test/java/teammates/sqlui/webapi/UpdateCourseActionTest.java
  src/test/java/teammates/storage/sqlapi/CoursesDbTest.java
  src/test/java/teammates/ui/webapi/BinCourseActionTest.java
  src/test/java/teammates/ui/webapi/CreateCourseActionTest.java
  src/test/java/teammates/ui/webapi/DeleteCourseActionTest.java
  src/test/java/teammates/ui/webapi/GetCourseActionTest.java
  src/test/java/teammates/ui/webapi/GetCourseSectionNamesActionTest.java
  src/test/java/teammates/ui/webapi/RestoreCourseActionTest.java
  src/test/java/teammates/ui/webapi/UpdateCourseActionTest.java
Labels: s.Ongoing

#12232 [#12048] Fix Typo in Naming of DB Tables
  src/main/java/teammates/storage/sqlentity/FeedbackResponse.java
  src/main/java/teammates/storage/sqlentity/FeedbackResponseComment.java
Labels: s.ToReview

#12235 [#12227] Release V8.25.0
  src/web/data/developers.json
Labels: s.ToMerge, c.Release

#12223 [#12081] Fix remaining accessibility tests
  src/e2e/java/teammates/e2e/pageobjects/InstructorCourseStudentDetailsEditPage.java
  src/e2e/java/teammates/e2e/util/AxeUtil.java
  src/web/app/__snapshots__/user-join-page.component.spec.ts.snap
  src/web/app/components/adding-question-panel/adding-question-panel.component.html
  src/web/app/components/course-edit-form/__snapshots__/course-edit-form.component.spec.ts.snap
  src/web/app/components/course-edit-form/course-edit-form.component.html
  src/web/app/components/course-related-info/course-related-info.component.html
  src/web/app/components/datepicker/datepicker.component.html
  src/web/app/components/preview-session-panel/preview-session-panel.component.html
  src/web/app/components/session-edit-form/session-edit-form.component.html
  src/web/app/components/timepicker/timepicker.component.html
  src/web/app/components/view-results-panel/view-results-panel.component.html
  src/web/app/pages-admin/admin-accounts-page/admin-accounts-page.component.html
  src/web/app/pages-admin/admin-home-page/__snapshots__/admin-home-page.component.spec.ts.snap
  src/web/app/pages-admin/admin-home-page/admin-home-page.component.html
  src/web/app/pages-admin/admin-notifications-page/__snapshots__/admin-notifications-page.component.spec.ts.snap
  src/web/app/pages-admin/admin-notifications-page/notification-edit-form/__snapshots__/notification-edit-form.component.spec.ts.snap
  src/web/app/pages-admin/admin-search-page/__snapshots__/admin-search-page.component.spec.ts.snap
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.html
  src/web/app/pages-admin/admin-sessions-page/admin-sessions-page.component.html
  src/web/app/pages-instructor/instructor-course-edit-page/__snapshots__/instructor-course-edit-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.html
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-edit-panel/instructor-edit-panel.component.html
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.html
  src/web/app/pages-instructor/instructor-course-student-edit-page/__snapshots__/instructor-course-student-edit-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.html
  src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.spec.ts
  src/web/app/pages-instructor/instructor-course-student-edit-page/instructor-course-student-edit-page.component.ts
  src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.html
  src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-individual-extension-page/__snapshots__/instructor-session-individual-extension-page.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-individual-extension-page/individual-extension-date-modal/__snapshots__/individual-extension-date-modal.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-individual-extension-page/instructor-session-individual-extension-page.component.html
  src/web/app/pages-instructor/instructor-session-individual-extension-page/instructor-session-individual-extension-page.component.ts
  src/web/app/pages-instructor/instructor-session-result-page/instructor-session-result-page.component.html
  src/web/app/pages-instructor/instructor-sessions-page/__snapshots__/instructor-sessions-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-student-activity-logs/__snapshots__/instructor-student-activity-logs.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-student-activity-logs/instructor-student-activity-logs.component.html
  src/web/app/pages-student/student-course-details-page/__snapshots__/student-course-details-page.component.spec.ts.snap
  src/web/app/pages-student/student-course-details-page/student-course-details-page.component.html
  src/web/app/user-join-page.component.html
Labels: s.ToMerge

#12224 [#12222] Instructor help page: Page not scrolling to the right section
  src/web/app/pages-help/instructor-help-page/instructor-help-page.component.html
  src/web/app/pages-help/instructor-help-page/instructor-help-page.component.ts
  src/web/styles.scss
Labels: s.ToMerge

#12243 [#12130] Fix scrolling mechanism when user click on scroll down button.
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.html
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.spec.ts
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts
Labels: s.ToMerge

#12239 [#12120] Instructor help page: page not scrolling to content when anchor links used
  src/web/app/pages-help/instructor-help-page/instructor-help-page.component.ts
Labels: s.ToMerge

#12250 [#12081] User-friendliness: Change feedback path dropdowns to column format on mobile
  src/web/app/components/feedback-path-panel/feedback-path-panel.component.html
  src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
Labels: s.ToMerge

#12254 [#12081] User-friendliness: Add labels to instructor edit sessions page questions
  src/web/app/components/question-types/question-edit-details-form/constsum-recipients-question-edit-details-form.component.html
  src/web/app/components/question-types/question-edit-details-form/contribution-question-edit-details-form.component.html
  src/web/app/components/question-types/question-edit-details-form/num-scale-question-edit-details-form.component.html
Labels: s.ToMerge

#12251 [#12081] User-friendliness: Fix visibility dropdown overflow
  src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap
  src/web/app/components/visibility-panel/visibility-panel.component.html
  src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
Labels: s.ToMerge

#12253 [#12238] Instructors editing session dates: disable calendar popup if the form is not in edit mode
  src/web/app/components/datepicker/datepicker.component.html
  src/web/app/components/datepicker/datepicker.component.ts
  src/web/app/components/session-edit-form/session-edit-form.component.html
  src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
Labels: c.Bug, s.ToMerge

#12260 [#12081] Wrap buttons vertically in mobile for instructor edit sessions page
  src/web/app/components/question-edit-form/__snapshots__/question-edit-form.component.spec.ts.snap
  src/web/app/components/question-edit-form/question-edit-form.component.html
  src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
Labels: s.ToMerge

#12266 [#12081] User-friendliness: Fix distribute points options question
  src/web/app/components/question-types/question-edit-details-form/constsum-options-field/constsum-options-field.component.html
  src/web/app/components/question-types/question-edit-details-form/constsum-options-question-edit-details-form.component.html
  src/web/app/components/question-types/question-edit-details-form/constsum-recipients-question-edit-details-form.component.html
Labels: s.ToMerge

#12270 [#12264] fix/removed extra space form links
  src/web/app/pages-static/about-page/about-page.component.html
Labels: s.ToMerge

#12263 [#12081] Fix rubric question overflow for instructors edit session page
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java
  src/web/app/components/question-types/question-edit-details-form/rubric-question-edit-details-form.component.html
  src/web/app/components/question-types/question-edit-details-form/rubric-question-edit-details-form.component.scss
Labels: s.ToMerge

#12272 [#12081] Modify accessibility tests workflow to rerun failed tests once
  build.gradle
Labels: s.ToMerge

#12295 [#12278] Instructor home page: Fix alignment of "Add New Course" button
  src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
Labels: s.ToMerge

#12303 [#12048] Migrate RemindFeedbackSessionResultAction
  src/main/java/teammates/ui/webapi/RemindFeedbackSessionResultAction.java
  src/test/java/teammates/sqlui/webapi/RemindFeedbackSessionResultActionTest.java
Labels: s.ToMerge

#12258 [#12048] Migrate GetFeedbackSessionSubmittedGiverSetAction
  src/it/java/teammates/it/sqllogic/core/FeedbackSessionsLogicIT.java
  src/it/java/teammates/it/ui/webapi/GetStudentsActionIT.java
  src/it/resources/data/typicalDataBundle.json
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/ui/webapi/GetFeedbackSessionSubmittedGiverSetAction.java
Labels: s.ToMerge
