Repository TEAMMATES/teammates, pull requests merged in 2023-01, with the labels that each got.

#12019 [#1501] Create Unit Tests for FeedbackConstantSumQuestionDetails class
  src/test/java/teammates/common/datatransfer/questions/FeedbackConstantSumQuestionDetailsTest.java
Labels: s.ToMerge, c.Task

#12025 [#1501] Create Unit Tests for FeedbackRubricQuestionDetails class
  src/test/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetailsTest.java
Labels: s.ToMerge, c.Task

#12032 [#12029] Fix team members cannot see responses received by team issue and add relevant tests
  src/main/java/teammates/logic/core/FeedbackResponsesLogic.java
  src/test/java/teammates/logic/core/FeedbackResponsesLogicTest.java
  src/test/resources/data/FeedbackResponseVisibilityTest.json
Labels: c.Bug, s.ToMerge

#11844 [#11728] Apply stricter checks for session timestamps
  src/e2e/java/teammates/e2e/cases/InstructorCoursesPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorFeedbackEditPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorFeedbackSessionsPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/InstructorHomePageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/AppPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackSessionsPage.java
  src/e2e/resources/data/InstructorCoursesPageE2ETest.json
  src/e2e/resources/data/InstructorHomePageE2ETest.json
  src/main/java/teammates/common/util/FieldValidator.java
  src/main/java/teammates/common/util/TimeHelper.java
  src/main/java/teammates/ui/webapi/CreateFeedbackSessionAction.java
  src/main/java/teammates/ui/webapi/UpdateFeedbackSessionAction.java
  src/test/java/teammates/common/util/FieldValidatorTest.java
  src/test/java/teammates/common/util/TimeHelperExtension.java
  src/test/java/teammates/common/util/TimeHelperTest.java
  src/test/java/teammates/logic/core/FeedbackSessionsLogicTest.java
  src/test/java/teammates/storage/api/FeedbackSessionsDbTest.java
  src/test/java/teammates/ui/webapi/CreateFeedbackSessionActionTest.java
  src/test/java/teammates/ui/webapi/UpdateFeedbackSessionActionTest.java
  src/web/app/components/session-edit-form/session-edit-form.component.html
  src/web/app/components/session-edit-form/session-edit-form.component.ts
  src/web/app/components/timepicker/timepicker.component.html
  src/web/app/components/timepicker/timepicker.component.ts
  src/web/app/pages-instructor/instructor-courses-page/__snapshots__/instructor-courses-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.html
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.scss
  src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts
  src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.scss
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.ts
  src/web/app/pages-instructor/instructor-session-base-page.component.ts
  src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.html
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.scss
  src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.ts
  src/web/app/pages-instructor/instructor-session-modal-page.component.ts
  src/web/app/pages-instructor/instructor-sessions-page/__snapshots__/instructor-sessions-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.html
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.scss
  src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.ts
  src/web/services/datetime.service.ts
Labels: s.ToMerge, c.Feature

#12026 [#11632] Update frontend libraries to fix CVE warnings
  jest.config.js
  package-lock.json
  package.json
  src/web/app/components/logs-histogram/logs-histogram.component.ts
  src/web/app/components/rich-text-editor/rich-text-editor.component.ts
  src/web/app/components/rich-text-editor/tinymce.ts
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.html
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.spec.ts
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts
  src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.module.ts
  src/web/app/pages-monitoring/usage-stats-page/stats-line-chart/stats-line-chart.component.ts
  src/web/index.html
  src/web/index.prod.html
  src/web/typings.d.ts
Labels: s.ToMerge, c.Task
