Repository TEAMMATES/teammates, pull requests merged in 2024-03, with the labels that each got.

#12854 [#12588] Add tests for student list component
  src/web/app/components/student-list/student-list.component.spec.ts
  src/web/app/components/student-list/student-list.component.ts
  src/web/test-helpers/generic-builder.ts
Labels: s.FinalReview

#12851 [#12048] SQL injection test for UsersDbIT
  src/it/java/teammates/it/storage/sqlapi/UsersDbIT.java
Labels: s.FinalReview, c.Task

#12858 [#12048] Add SQL injection tests in NotificationDbIT
  src/it/java/teammates/it/storage/sqlapi/NotificationDbIT.java
Labels: s.FinalReview, c.Task

#12786 [#12048] Add tests for CourseDbIT
  src/it/java/teammates/it/storage/sqlapi/CoursesDbIT.java
Labels: s.ToMerge

#12788 [#12048] SQL injection test for AccountRequestsDbIT
  src/it/java/teammates/it/storage/sqlapi/AccountRequestsDbIT.java
Labels: s.ToMerge, c.Task

#12800 [#12048] SQL injection test for AccountsDbIT
  src/it/java/teammates/it/storage/sqlapi/AccountsDbIT.java
Labels: s.FinalReview, c.Task

#12863 [#12588] Add unit tests for sessions table
  src/web/app/components/sessions-table/resend-results-link-to-respondent-modal/resend-results-link-to-respondent-modal.component.spec.ts
  src/web/app/components/sessions-table/respondent-list-info-table/respondent-list-info-table.component.spec.ts
  src/web/app/components/sessions-table/send-reminders-to-respondents-modal/send-reminders-to-respondents-modal.component.spec.ts
Labels: s.ToMerge

#12862 [#12048] Migrate GetFeedbackSessionLogsAction
  src/it/java/teammates/it/ui/webapi/GetFeedbackSessionLogsActionIT.java
  src/main/java/teammates/ui/output/FeedbackSessionLogData.java
  src/main/java/teammates/ui/output/FeedbackSessionLogEntryData.java
  src/main/java/teammates/ui/output/FeedbackSessionLogsData.java
  src/main/java/teammates/ui/webapi/GetFeedbackSessionLogsAction.java
Labels: s.ToMerge

#12801 [#12048] SQL injection test for CoursesDbIT
  src/it/java/teammates/it/storage/sqlapi/CoursesDbIT.java
Labels: s.FinalReview, c.Task

#12848 [#12048] SQL Injection Test for FeedbackResponsesDb
  src/it/java/teammates/it/storage/sqlapi/FeedbackResponsesDbIT.java
Labels: s.FinalReview, c.Task

#12853 [#12048] SQL Injection tests for FeedbackResponseCommentsDbIT
  src/it/java/teammates/it/storage/sqlapi/FeedbackResponseCommentsDbIT.java
Labels: s.ToReview

#12815 [#12048] Migrate StudentCourseJoinConfirmationPageE2ETest
  src/e2e/java/teammates/e2e/cases/StudentCourseJoinConfirmationPageE2ETest.java
  src/e2e/resources/data/StudentCourseJoinConfirmationPageE2ETest.json
  src/e2e/resources/data/StudentCourseJoinConfirmationPageE2ETest_SqlEntities.json
Labels: s.ToReview

#12870 [#12048] add check for sql tests in TestNgXml
  src/e2e/java/teammates/e2e/util/TestNgXmlTest.java
  src/e2e/resources/testng-e2e-sql.xml
Labels: s.ToMerge

#12769 Add testcases for FeedbackResponseCommentsLogicTest
  src/test/java/teammates/sqllogic/core/FeedbackResponseCommentsLogicTest.java
Labels: s.FinalReview, c.Task

#12871 [#12048] Fix account creation
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/main/java/teammates/logic/core/AccountsLogic.java
  src/main/java/teammates/logic/core/CoursesLogic.java
  src/main/java/teammates/storage/sqlentity/Account.java
  src/main/java/teammates/storage/sqlentity/Notification.java
  src/main/java/teammates/ui/webapi/GetFeedbackResponsesAction.java
  src/main/java/teammates/ui/webapi/GetFeedbackSessionsAction.java
  src/main/java/teammates/ui/webapi/InstructorCourseJoinEmailWorkerAction.java
  src/test/java/teammates/logic/api/EmailGeneratorTest.java
  src/test/java/teammates/logic/core/AccountsLogicTest.java
  src/test/java/teammates/logic/core/CoursesLogicTest.java
  src/test/java/teammates/sqlui/webapi/GetFeedbackSessionsActionTest.java
  src/test/java/teammates/test/BaseTestCaseWithLocalDatabaseAccess.java
  src/test/java/teammates/ui/webapi/InstructorCourseJoinEmailWorkerActionTest.java
Labels: s.ToMerge

#12759 [#12048] Add tests for FeedbackQuestionsDb
  src/it/java/teammates/it/sqllogic/core/FeedbackQuestionsLogicIT.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/FeedbackQuestionsLogic.java
  src/main/java/teammates/storage/sqlapi/FeedbackQuestionsDb.java
  src/main/java/teammates/ui/webapi/CreateFeedbackQuestionAction.java
  src/main/java/teammates/ui/webapi/CreateFeedbackSessionAction.java
  src/test/java/teammates/sqllogic/core/FeedbackQuestionsLogicTest.java
  src/test/java/teammates/storage/sqlapi/FeedbackQuestionsDbTest.java
Labels: s.ToMerge, c.Task

#12785 [#12048] Create Non Course Data Migration Script
  src/client/java/teammates/client/scripts/sql/DataMigrationEntitiesBaseScriptSql.java
  src/client/java/teammates/client/scripts/sql/DataMigrationForAccountAndReadNotificationSql.java
  src/client/java/teammates/client/scripts/sql/DataMigrationForAccountRequestSql.java
  src/client/java/teammates/client/scripts/sql/DataMigrationForNotificationSql.java
  src/client/java/teammates/client/scripts/sql/DataMigrationForUsageStatisticsSql.java
  src/client/java/teammates/client/scripts/sql/MigrateAndVerifyNonCourseEntities.java
  src/client/java/teammates/client/scripts/sql/SeedDb.java
  src/client/java/teammates/client/scripts/sql/SeedUsageStatistics.java
  src/client/java/teammates/client/scripts/sql/VerifyAccountAttributes.java
  src/client/java/teammates/client/scripts/sql/VerifyAccountRequestAttributes.java
  src/client/java/teammates/client/scripts/sql/VerifyDataMigrationConnection.java
  src/client/java/teammates/client/scripts/sql/VerifyNonCourseEntityAttributesBaseScript.java
  src/client/java/teammates/client/scripts/sql/VerifyNonCourseEntityCounts.java
  src/client/java/teammates/client/scripts/sql/VerifyNotificationAttributes.java
  src/client/java/teammates/client/scripts/sql/VerifyUsageStatisticsAttributes.java
  src/client/java/teammates/client/scripts/sql/package-info.java
  src/client/java/teammates/client/scripts/sql/typicalDataBundle.json
  src/client/java/teammates/client/util/ClientProperties.java
  src/client/resources/client.template.properties
Labels: s.ToReview

#12879 [#12876] Release V9.0.0-beta.0
  src/web/data/developers.json
Labels: s.ToMerge, c.Release

#12881 [#12048] Revert column type for notification title
  src/main/java/teammates/storage/sqlentity/Notification.java
Labels: c.Task

#12868 [#12588] Add unit tests for visibility panel
  src/web/app/components/visibility-panel/visibility-panel.component.spec.ts
Labels: s.ToMerge

#12781 [#12048] Add tests for FeedbackQuestionsDbIT
  src/it/java/teammates/it/storage/sqlapi/FeedbackQuestionsDbIT.java
  src/it/java/teammates/it/test/BaseTestCaseWithSqlDatabaseAccess.java
Labels: s.ToMerge

#12849 [#12048] Add integration tests for FeedbackResponseCommentsDb
  src/it/java/teammates/it/storage/sqlapi/FeedbackResponseCommentsDbIT.java
  src/it/resources/data/FeedbackResponsesITBundle.json
Labels: s.ToMerge

#12867 [#12588] Improve test code coverage of QuestionResponsePanelComponent
  src/web/app/components/question-response-panel/question-response-panel.component.spec.ts
Labels: s.ToMerge

#12856 [#12048] Add integration tests for FeedbackResponsesDb
  src/it/java/teammates/it/storage/sqlapi/FeedbackResponsesDbIT.java
Labels: s.FinalReview

#12893 [#12271] Docs: Upgrade to latest MarkBind version
  docs/_markbind/layouts/default.md
  docs/_markbind/layouts/footer.md
  docs/_markbind/layouts/header.md
  docs/_markbind/variables.md
  docs/design.md
  docs/diagrams/ClientComponent.puml
  docs/diagrams/CommonComponent.puml
  docs/diagrams/DataTransferClasses.puml
  docs/diagrams/E2EComponent.puml
  docs/diagrams/IssueLifecycle.puml
  docs/diagrams/LogicComponent.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/StorageComponent.puml
  docs/diagrams/TestDriverComponent.puml
  docs/diagrams/UiComponent.puml
  docs/diagrams/UiWorkflow.puml
  docs/diagrams/highlevelArchitecture.puml
  docs/diagrams/packageDiagram.puml
  docs/diagrams/workflow.puml
  docs/package-lock.json
  docs/package.json
Labels: s.ToMerge

#12895 [#11843] Create FeedbackSessionLog entity and cron job action
  src/main/java/teammates/common/datatransfer/FeedbackSessionLogEntry.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/logic/api/LogsProcessor.java
  src/main/java/teammates/logic/external/GoogleCloudLoggingService.java
  src/main/java/teammates/logic/external/LocalLoggingService.java
  src/main/java/teammates/logic/external/LogService.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/storage/sqlentity/FeedbackSessionLog.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/GetFeedbackSessionLogsAction.java
  src/main/java/teammates/ui/webapi/UpdateFeedbackSessionLogsAction.java
  src/test/java/teammates/logic/api/MockLogsProcessor.java
  src/test/java/teammates/sqlui/webapi/UpdateFeedbackSessionLogsActionTest.java
  src/test/java/teammates/ui/webapi/GetActionClassesActionTest.java
Labels: s.ToReview

#12907 [#12588] Add unit test to rubric-question-edit-details-form
  src/web/app/components/question-types/question-edit-details-form/rubric-question-edit-details-form.component.spec.ts
Labels: s.ToReview

#12857 [#12048] Add SQL injection tests in FeedbackSessionsDbIT
  src/it/java/teammates/it/storage/sqlapi/FeedbackSessionsDbIT.java
  src/main/java/teammates/storage/sqlentity/FeedbackSession.java
Labels: s.ToMerge, c.Task

#12892 [#12048] Add deep comparison for entities in `verifyEquals` for E2E
  src/test/java/teammates/test/BaseTestCaseWithSqlDatabaseAccess.java
Labels: s.ToReview

#12906 [#12048] Migrate InstructorNotificationsPageE2E
  src/e2e/java/teammates/e2e/cases/sql/InstructorNotificationsPageE2ETest.java
  src/e2e/resources/data/InstructorNotificationsPageE2ESqlTest.json
  src/e2e/resources/testng-e2e-sql.xml
  src/main/java/teammates/sqllogic/core/DataBundleLogic.java
Labels: s.ToMerge

#12898 [#11878] Add status and comments to AccountRequest
  src/client/java/teammates/client/scripts/sql/DataMigrationForAccountRequestSql.java
  src/client/java/teammates/client/scripts/sql/VerifyDataMigrationConnection.java
  src/it/java/teammates/it/sqllogic/core/AccountRequestsLogicIT.java
  src/it/java/teammates/it/sqllogic/core/DataBundleLogicIT.java
  src/it/java/teammates/it/storage/sqlapi/AccountRequestsDbIT.java
  src/it/resources/data/DataBundleLogicIT.json
  src/main/java/teammates/common/datatransfer/AccountRequestStatus.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/AccountRequestsLogic.java
  src/main/java/teammates/storage/sqlentity/AccountRequest.java
  src/main/java/teammates/ui/webapi/CreateAccountRequestAction.java
  src/test/java/teammates/storage/sqlapi/AccountRequestsDbTest.java
Labels: s.ToMerge, c.Task

#12904 [#12048] Migrate FeedbackMsqQuestionE2ETest
  src/e2e/java/teammates/e2e/cases/sql/FeedbackMsqQuestionE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/FeedbackSubmitPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java
  src/e2e/resources/data/FeedbackMsqQuestionE2ESqlTest.json
  src/e2e/resources/testng-e2e-sql.xml
  src/main/java/teammates/sqllogic/core/FeedbackQuestionsLogic.java
  src/main/java/teammates/storage/sqlentity/questions/FeedbackMsqQuestion.java
  src/test/java/teammates/test/BaseTestCaseWithSqlDatabaseAccess.java
Labels: s.FinalReview

#12923 [#12921] Reintroduce AccountRequest search indexing
  src/it/java/teammates/it/ui/webapi/CreateAccountRequestActionIT.java
  src/main/java/teammates/ui/webapi/CreateAccountRequestAction.java
Labels: s.FinalReview, s.ToMerge, c.Feature

#12924 [#12909] :Dev docs (E2E testing): update Chromedriver link
  docs/e2e-testing.md
Labels: c.Bug, s.FinalReview

#12917 [#12048] Add SQL configuration into build.properties and build-dev.properties
  src/main/java/teammates/common/util/Config.java
  src/main/java/teammates/ui/servlets/HibernateContextListener.java
  src/main/resources/build-dev.template.properties
  src/main/resources/build.template.properties
Labels: s.ToMerge, c.Task

#12931 [#12048] Add SQL description for postgres config
  src/main/resources/build-dev.template.properties
  src/main/resources/build.template.properties
Labels: s.ToMerge, c.Task

#12926 [#11878] Add new account request alert email for admins
  src/it/java/teammates/it/ui/webapi/CreateAccountRequestActionIT.java
  src/main/java/teammates/common/util/EmailType.java
  src/main/java/teammates/common/util/Templates.java
  src/main/java/teammates/sqllogic/api/SqlEmailGenerator.java
  src/main/java/teammates/ui/webapi/CreateAccountRequestAction.java
  src/main/resources/adminEmailTemplate-newAccountRequestAlert.html
  src/test/java/teammates/sqllogic/api/SqlEmailGeneratorTest.java
  src/test/resources/emails/adminNewAccountRequestAlertEmailWithComments.html
  src/test/resources/emails/adminNewAccountRequestAlertEmailWithNoComments.html
Labels: s.ToMerge, c.Feature

#12916 [#12588] Improve test code coverage of core components - ToastComponent
  src/web/app/components/toast/toast.component.spec.ts
Labels: s.FinalReview

#12935 [#12588] Add unit tests to question edit answer form
  src/web/app/components/question-types/question-edit-answer-form/constsum-options-question-edit-answer-form.component.spec.ts
Labels: s.ToMerge, c.Task

#12927 [#11878] Add GetAllPendingAccountRequests API
  src/it/java/teammates/it/ui/webapi/GetAccountRequestsActionIT.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/AccountRequestsLogic.java
  src/main/java/teammates/storage/sqlapi/AccountRequestsDb.java
  src/main/java/teammates/ui/constants/ResourceEndpoints.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/GetAccountRequestsAction.java
  src/test/java/teammates/ui/webapi/GetActionClassesActionTest.java
Labels: s.ToMerge, c.Feature

#12913 [#11878] Modify CreateAccountRequestAction
  src/it/java/teammates/it/ui/webapi/CreateAccountRequestActionIT.java
  src/main/java/teammates/common/datatransfer/attributes/AccountRequestAttributes.java
  src/main/java/teammates/ui/output/AccountRequestData.java
  src/main/java/teammates/ui/request/AccountCreateRequest.java
  src/main/java/teammates/ui/webapi/CreateAccountRequestAction.java
  src/test/java/teammates/logic/core/AccountRequestsLogicTest.java
  src/test/java/teammates/ui/webapi/CreateAccountRequestActionTest.java
  src/web/app/pages-admin/admin-home-page/admin-home-page.component.spec.ts
  src/web/app/pages-admin/admin-home-page/admin-home-page.component.ts
  src/web/services/account.service.ts
  src/web/services/search.service.spec.ts
Labels: s.ToMerge, c.Feature

#12932 [#12048] Rerunnable Account Request Migration Script
  src/client/java/teammates/client/scripts/sql/DataMigrationForAccountRequestSql.java
Labels: s.ToMerge, c.Task

#12937 [#12048] Relax read notif verification for migration verification script
  src/client/java/teammates/client/scripts/sql/SeedDb.java
  src/client/java/teammates/client/scripts/sql/VerifyAccountAttributes.java
Labels: s.ToMerge, c.Task

#12922 [#12920] Create script to migrate noSQL test data to SQL schema format
  src/client/java/teammates/client/scripts/testdataconversion/ConvertDatastoreJsonToSqlJson.java
  src/client/java/teammates/client/scripts/testdataconversion/DataStoreToSqlConverter.java
  src/client/java/teammates/client/scripts/testdataconversion/UuidGenerator.java
  src/client/java/teammates/client/scripts/testdataconversion/package-info.java
  src/main/java/teammates/common/util/JsonUtils.java
Labels: a-Testing, s.ToMerge

#12918 [#12588] Improve test code coverage of core components - ViewResultsPanelComponent
  src/web/app/components/view-results-panel/view-results-panel.component.spec.ts
Labels: s.ToMerge, c.Task

#12902 [#12048] Migrate Feedback Rank Option E2E test
  src/e2e/java/teammates/e2e/cases/sql/FeedbackRankOptionQuestionE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/FeedbackSubmitPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java
  src/e2e/resources/data/FeedbackRankOptionQuestionE2ESqlTest.json
  src/e2e/resources/testng-e2e-sql.xml
  src/main/java/teammates/storage/sqlentity/questions/FeedbackRankOptionsQuestion.java
Labels: s.ToMerge

#12820 [#12048] Migrate FeedbackMcqQuestionE2ETest
  src/e2e/java/teammates/e2e/cases/sql/FeedbackMcqQuestionE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/FeedbackSubmitPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java
  src/e2e/resources/data/FeedbackMcqQuestionE2ESqlTest.json
  src/e2e/resources/testng-e2e-sql.xml
  src/main/java/teammates/sqllogic/core/FeedbackQuestionsLogic.java
Labels: s.ToMerge

#12929 [#11878] Upgrade instructor request form UI
  src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form-model.ts
  src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.html
  src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.scss
  src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.spec.ts
  src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.ts
  src/web/app/pages-static/request-page/request-page.component.html
  src/web/app/pages-static/request-page/request-page.component.scss
  src/web/app/pages-static/request-page/request-page.component.ts
  src/web/app/pages-static/request-page/request-page.module.ts
Labels: s.ToMerge, c.Feature

#12911 [#12048] Remove unnecessary loading of datastore entities in InstructorNotificationsPageE2ETest
  src/e2e/resources/data/InstructorNotificationsPageE2ETest.json
Labels: s.ToMerge

#12933 [#11878] Update Admin Home Page UI for ARF
  src/web/app/components/account-requests-table/account-request-table-model.ts
  src/web/app/components/account-requests-table/account-request-table.component.html
  src/web/app/components/account-requests-table/account-request-table.component.scss
  src/web/app/components/account-requests-table/account-request-table.component.ts
  src/web/app/components/account-requests-table/account-request-table.module.ts
  src/web/app/pages-admin/admin-home-page/__snapshots__/admin-home-page.component.spec.ts.snap
  src/web/app/pages-admin/admin-home-page/admin-home-page.component.html
  src/web/app/pages-admin/admin-home-page/admin-home-page.component.spec.ts
  src/web/app/pages-admin/admin-home-page/admin-home-page.component.ts
  src/web/app/pages-admin/admin-home-page/admin-home-page.module.ts
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.spec.ts
  src/web/services/account.service.ts
  src/web/services/search.service.spec.ts
  src/web/services/search.service.ts
Labels: s.ToMerge, c.Feature

#12953 [#11878] Add methods to get an account request by ID
  src/it/java/teammates/it/sqllogic/core/AccountRequestsLogicIT.java
  src/it/java/teammates/it/storage/sqlapi/AccountRequestsDbIT.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/AccountRequestsLogic.java
  src/main/java/teammates/storage/sqlapi/AccountRequestsDb.java
  src/test/java/teammates/sqllogic/core/AccountRequestsLogicTest.java
  src/test/java/teammates/storage/sqlapi/AccountRequestsDbTest.java
Labels: s.ToReview, c.Task

#12897 [#12588] add unit tests for question submission form
  src/web/app/components/question-submission-form/question-submission-form.component.spec.ts
Labels: s.ToMerge, c.Task

#12958 [#12939] Release V9.0.0-beta.1
  src/web/data/developers.json
Labels: s.ToMerge, c.Release

#12914 [#11843] Create Logic and Db layer for FeedbackSessionLogs
  src/it/java/teammates/it/storage/sqlapi/FeedbackSessionLogsDbIT.java
  src/it/java/teammates/it/ui/webapi/GetFeedbackSessionLogsActionIT.java
  src/it/java/teammates/it/ui/webapi/UpdateFeedbackSessionLogsActionIT.java
  src/main/java/teammates/common/datatransfer/FeedbackSessionLogEntry.java
  src/main/java/teammates/common/datatransfer/logs/FeedbackSessionAuditLogDetails.java
  src/main/java/teammates/common/util/HibernateUtil.java
  src/main/java/teammates/logic/api/LogsProcessor.java
  src/main/java/teammates/logic/external/GoogleCloudLoggingService.java
  src/main/java/teammates/logic/external/LocalLoggingService.java
  src/main/java/teammates/logic/external/LogService.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/FeedbackSessionLogsLogic.java
  src/main/java/teammates/sqllogic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/sqllogic/core/LogicStarter.java
  src/main/java/teammates/sqllogic/core/UsersLogic.java
  src/main/java/teammates/storage/sqlapi/FeedbackSessionLogsDb.java
  src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java
  src/main/java/teammates/storage/sqlapi/UsersDb.java
  src/main/java/teammates/storage/sqlentity/FeedbackSessionLog.java
  src/main/java/teammates/ui/output/FeedbackSessionData.java
  src/main/java/teammates/ui/output/StudentData.java
  src/main/java/teammates/ui/webapi/CreateFeedbackSessionLogAction.java
  src/main/java/teammates/ui/webapi/UpdateFeedbackSessionLogsAction.java
  src/test/java/teammates/logic/api/MockLogsProcessor.java
  src/test/java/teammates/sqlui/webapi/UpdateFeedbackSessionLogsActionTest.java
  src/test/java/teammates/storage/sqlapi/FeedbackSessionLogsDbTest.java
  src/test/java/teammates/ui/webapi/GetFeedbackSessionLogsActionTest.java
Labels: s.ToReview

#12942 [#11878] Add snapshot tests for instructor request form UI
  src/web/app/pages-static/request-page/__snapshots__/request-page.component.spec.ts.snap
  src/web/app/pages-static/request-page/instructor-request-form/__snapshots__/instructor-request-form.component.spec.ts.snap
  src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.spec.ts
  src/web/app/pages-static/request-page/request-page.component.spec.ts
Labels: s.ToMerge, c.Task

#12957 [#11878] Foundation for getting by ID in account request endpoints
  src/main/java/teammates/common/util/Const.java
  src/web/app/components/account-requests-table/account-request-table-model.ts
  src/web/app/pages-admin/admin-home-page/admin-home-page.component.ts
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.spec.ts
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.ts
  src/web/services/search.service.spec.ts
  src/web/services/search.service.ts
Labels: s.FinalReview, c.Task

#12955 [#11878] Get account requests by ID in storage update method
  src/it/java/teammates/it/storage/sqlapi/AccountRequestsDbIT.java
  src/main/java/teammates/storage/sqlapi/AccountRequestsDb.java
  src/test/java/teammates/storage/sqlapi/AccountRequestsDbTest.java
Labels: s.FinalReview, c.Task

#12956 [#11878] Get by account request ID in SQL injection tests
  src/it/java/teammates/it/storage/sqlapi/AccountRequestsDbIT.java
Labels: s.FinalReview, c.Task

#12967 [#12048] Fix account request indexing
  src/it/java/teammates/it/ui/webapi/CreateAccountRequestActionIT.java
  src/main/java/teammates/logic/api/TaskQueuer.java
  src/main/java/teammates/logic/api/UserProvision.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/AccountRequestsLogic.java
  src/main/java/teammates/ui/servlets/WebApiServlet.java
  src/main/java/teammates/ui/webapi/Action.java
  src/main/java/teammates/ui/webapi/CreateAccountRequestAction.java
Labels: c.Bug

#12944 [#11878] Create instructor request acknowledgement email
  src/it/java/teammates/it/ui/webapi/CreateAccountRequestActionIT.java
  src/main/java/teammates/common/util/EmailType.java
  src/main/java/teammates/common/util/Templates.java
  src/main/java/teammates/sqllogic/api/SqlEmailGenerator.java
  src/main/java/teammates/ui/webapi/CreateAccountRequestAction.java
  src/main/resources/instructorEmailTemplate-newAccountRequestAcknowledgement.html
  src/test/java/teammates/sqllogic/api/SqlEmailGeneratorTest.java
  src/test/resources/emails/instructorNewAccountRequestAcknowledgementEmailWithComments.html
  src/test/resources/emails/instructorNewAccountRequestAcknowledgementEmailWithNoComments.html
Labels: s.ToMerge, c.Feature
