Repository TEAMMATES/teammates, pull requests merged in 2024-04, with the labels that each got.

#12974 [#11878] Change institute length limit
  src/main/java/teammates/common/util/FieldValidator.java
  src/test/java/teammates/common/util/FieldValidatorTest.java
Labels: s.ToMerge, c.Task

#12950 [#11878] Update SearchAccountRequests endpoint
  solr/solr.sh
  src/it/java/teammates/it/storage/sqlsearch/AccountRequestSearchIT.java
  src/it/resources/data/typicalDataBundle.json
  src/main/java/teammates/storage/sqlapi/AccountRequestsDb.java
  src/main/java/teammates/storage/sqlsearch/AccountRequestSearchDocument.java
  src/main/java/teammates/storage/sqlsearch/AccountRequestSearchManager.java
Labels: s.ToMerge, c.Feature

#12948 [#12946] Initialise Entities for Course Structure
  src/main/java/teammates/storage/sqlentity/Course.java
  src/main/java/teammates/storage/sqlentity/CourseStructure.java
  src/main/java/teammates/storage/sqlentity/FeedbackSession.java
  src/main/java/teammates/storage/sqlentity/Section.java
  src/main/java/teammates/storage/sqlentity/Student.java
  src/main/java/teammates/storage/sqlentity/Team.java
  src/main/java/teammates/storage/sqlentity/TeamToStudentMap.java
  src/main/java/teammates/storage/sqlentity/User.java
Labels: s.FinalReview

#12943 [#11878] Integrate instructor request form with API
  src/main/java/teammates/ui/constants/ApiStringConst.java
  src/web/app/pages-static/request-page/__snapshots__/request-page.component.spec.ts.snap
  src/web/app/pages-static/request-page/instructor-request-form/__snapshots__/instructor-request-form.component.spec.ts.snap
  src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form-model.ts
  src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.html
  src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.scss
  src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.spec.ts
  src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.ts
  src/web/app/pages-static/request-page/request-page.component.html
  src/web/app/pages-static/request-page/request-page.component.spec.ts
  src/web/app/pages-static/request-page/request-page.module.ts
  src/web/types/const.spec.ts
  src/web/types/form-validator.ts
Labels: s.ToMerge, c.Feature

#12982 [#11878] Create Update Account Request Action
  src/it/java/teammates/it/ui/webapi/CreateAccountRequestActionIT.java
  src/it/java/teammates/it/ui/webapi/UpdateAccountRequestActionIT.java
  src/main/java/teammates/ui/request/AccountRequestUpdateRequest.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/UpdateAccountRequestAction.java
  src/test/java/teammates/ui/webapi/GetActionClassesActionTest.java
Labels: s.ToMerge, c.Feature

#12930 [#12048] Update liquibase configuration
  build.gradle
  docs/schema-migration.md
  src/main/java/teammates/common/util/HibernateUtil.java
  src/main/resources/db/changelog/db.changelog-root.xml
  src/main/resources/db/changelog/db.changelog-v9.0.0.xml
  src/main/resources/db/changelog/db.changelog-v9.xml
Labels: s.ToMerge, c.Task

#12984 [#11878] Fix Account Request Update Search Indexing
  src/it/java/teammates/it/ui/webapi/AccountRequestSearchIndexingWorkerActionIT.java
  src/it/java/teammates/it/ui/webapi/BaseActionIT.java
  src/it/java/teammates/it/ui/webapi/UpdateAccountRequestActionIT.java
  src/main/java/teammates/logic/api/TaskQueuer.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/AccountRequestsLogic.java
  src/main/java/teammates/storage/sqlapi/AccountRequestsDb.java
  src/main/java/teammates/ui/webapi/AccountRequestSearchIndexingWorkerAction.java
  src/main/java/teammates/ui/webapi/CreateAccountRequestAction.java
  src/main/java/teammates/ui/webapi/UpdateAccountRequestAction.java
  src/test/java/teammates/logic/api/MockUserProvision.java
Labels: c.Bug, s.ToMerge

#12975 [#11878] Add Edit and Approve Account Requests functionality
  src/web/app/components/account-requests-table/account-request-table-model.ts
  src/web/app/components/account-requests-table/account-request-table.component.html
  src/web/app/components/account-requests-table/account-request-table.component.ts
  src/web/app/components/account-requests-table/account-request-table.module.ts
  src/web/app/components/account-requests-table/admin-edit-request-modal/admin-edit-request-modal-model.ts
  src/web/app/components/account-requests-table/admin-edit-request-modal/admin-edit-request-modal.component.html
  src/web/app/components/account-requests-table/admin-edit-request-modal/admin-edit-request-modal.component.scss
  src/web/app/components/account-requests-table/admin-edit-request-modal/admin-edit-request-modal.component.ts
  src/web/app/pages-admin/admin-search-page/__snapshots__/admin-search-page.component.spec.ts.snap
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.html
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.spec.ts
  src/web/services/account.service.ts
  src/web/services/search.service.ts
Labels: s.ToMerge, c.Feature

#12986 [#12048] Data migration for feedback session entities
  src/client/java/teammates/client/scripts/sql/DataMigrationForFeedbackSessionSql.java
  src/client/java/teammates/client/scripts/sql/SeedDb.java
  src/client/java/teammates/client/scripts/sql/VerifyCourseEntityCounts.java
  src/client/java/teammates/client/scripts/sql/VerifyFeedbackSessionAttributes.java
  src/main/java/teammates/common/util/HibernateUtil.java
Labels: s.FinalReview, c.Task

#12987 [#11878] Add AccountRequest Rejection email generator.
  src/main/java/teammates/common/util/EmailType.java
  src/main/java/teammates/sqllogic/api/SqlEmailGenerator.java
  src/test/java/teammates/sqllogic/api/SqlEmailGeneratorTest.java
  src/test/resources/emails/instructorAccountRequestRejectionEmail.html
Labels: s.ToMerge, c.Feature

#12991 [#12048] Data migration for section entities
  src/client/java/teammates/client/scripts/sql/DataMigrationForSectionSql.java
  src/client/java/teammates/client/scripts/sql/SeedDb.java
  src/client/java/teammates/client/scripts/sql/VerifyCourseEntityCounts.java
  src/client/java/teammates/client/scripts/sql/VerifySectionAttributes.java
Labels: s.Ongoing, c.Task

#12780 [#12048] Migrate AccountRequestsLogicTest
  src/test/java/teammates/sqllogic/core/AccountRequestsLogicTest.java
  src/test/java/teammates/test/BaseTestCase.java
Labels: s.ToReview, c.Task

#12985 [#11878] Create reject account request endpoint
  src/it/java/teammates/it/ui/webapi/RejectAccountRequestActionIT.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/constants/ResourceEndpoints.java
  src/main/java/teammates/ui/request/AccountRequestRejectionRequest.java
  src/main/java/teammates/ui/webapi/ActionFactory.java
  src/main/java/teammates/ui/webapi/RejectAccountRequestAction.java
  src/main/java/teammates/ui/webapi/UpdateAccountRequestAction.java
  src/test/java/teammates/ui/request/AccountRequestRejectionRequestTest.java
  src/test/java/teammates/ui/webapi/GetActionClassesActionTest.java
Labels: s.ToMerge, c.Task

#12992 [#12048] Remove feedbackSession attributes @fetch annotation
  src/main/java/teammates/storage/sqlentity/FeedbackSession.java
Labels: s.ToReview, c.Task

#12998 [#11878] Remove unused modal in AdminHomePage
  src/web/app/pages-admin/admin-home-page/__snapshots__/admin-home-page.component.spec.ts.snap
  src/web/app/pages-admin/admin-home-page/admin-home-page.component.html
  src/web/app/pages-admin/admin-home-page/admin-home-page.component.spec.ts
  src/web/app/pages-admin/admin-home-page/admin-home-page.component.ts
  src/web/app/pages-admin/admin-home-page/instructor-data.ts
  src/web/app/pages-admin/admin-home-page/new-instructor-data-row/__snapshots__/new-instructor-data-row.component.spec.ts.snap
  src/web/app/pages-admin/admin-home-page/new-instructor-data-row/new-instructor-data-row.component.html
  src/web/app/pages-admin/admin-home-page/new-instructor-data-row/new-instructor-data-row.component.spec.ts
  src/web/app/pages-admin/admin-home-page/new-instructor-data-row/new-instructor-data-row.component.ts
Labels: s.ToReview, c.Task

#13001 [#11878] Convert RejectAccountRequestAction to use transactions
  src/it/java/teammates/it/ui/webapi/RejectAccountRequestActionIT.java
  src/it/java/teammates/it/ui/webapi/UpdateAccountRequestActionIT.java
  src/main/java/teammates/ui/webapi/RejectAccountRequestAction.java
  src/main/java/teammates/ui/webapi/UpdateAccountRequestAction.java
Labels: c.Bug, s.FinalReview

#12994 [#12048] create skeleton for sql LNP tests
  src/lnp/java/teammates/lnp/sql/BaseLNPTestCase.java
  src/lnp/java/teammates/lnp/sql/InstructorCourseUpdateLNPTest.java
  src/lnp/java/teammates/lnp/sql/package-info.java
  src/lnp/java/teammates/lnp/util/LNPSqlTestData.java
  src/test/java/teammates/architecture/ArchitectureTest.java
Labels: a-Testing

#12989 [#11878] Create Rejection Modal for Account Requests
  src/web/app/components/account-requests-table/account-request-table.component.html
  src/web/app/components/account-requests-table/account-request-table.component.ts
  src/web/app/components/account-requests-table/account-request-table.module.ts
  src/web/app/components/account-requests-table/admin-reject-with-reason-modal/admin-reject-with-reason-modal-model.ts
  src/web/app/components/account-requests-table/admin-reject-with-reason-modal/admin-reject-with-reason-modal.component.html
  src/web/app/components/account-requests-table/admin-reject-with-reason-modal/admin-reject-with-reason-modal.component.scss
  src/web/app/components/account-requests-table/admin-reject-with-reason-modal/admin-reject-with-reason-modal.component.ts
  src/web/app/pages-admin/admin-home-page/admin-home-page.component.html
  src/web/app/pages-admin/admin-search-page/__snapshots__/admin-search-page.component.spec.ts.snap
  src/web/services/account.service.ts
Labels: s.ToMerge, c.Feature

#13005 [#12048] Add v9.0.0 tag to liquibase changelog
  src/main/resources/db/changelog/db.changelog-v9.0.0.xml
Labels: s.ToReview, c.Task

#12997 [#11878] Update DeleteAccountRequest to reference by ID
  src/e2e/java/teammates/e2e/cases/AdminHomePageE2ETest.java
  src/e2e/java/teammates/e2e/cases/AdminSearchPageE2ETest.java
  src/it/java/teammates/it/sqllogic/core/AccountRequestsLogicIT.java
  src/it/java/teammates/it/ui/webapi/CreateAccountRequestActionIT.java
  src/it/java/teammates/it/ui/webapi/UpdateAccountRequestActionIT.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/AccountRequestsLogic.java
  src/main/java/teammates/sqllogic/core/DataBundleLogic.java
  src/main/java/teammates/ui/webapi/DeleteAccountRequestAction.java
  src/test/java/teammates/test/AbstractBackDoor.java
  src/web/app/components/account-requests-table/account-request-table.component.ts
  src/web/services/account.service.spec.ts
  src/web/services/account.service.ts
Labels: s.ToMerge, c.Task

#13002 [#11878] Update ResetAccountRequest to reference by ID
  src/it/java/teammates/it/sqllogic/core/AccountRequestsLogicIT.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/AccountRequestsLogic.java
  src/main/java/teammates/ui/webapi/ResetAccountRequestAction.java
  src/web/app/components/account-requests-table/account-request-table.component.ts
  src/web/services/account.service.spec.ts
  src/web/services/account.service.ts
Labels: s.ToMerge, c.Task

#13004 [#11878] Add Error Message for Approving Existing Account
  src/it/java/teammates/it/ui/webapi/UpdateAccountRequestActionIT.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/AccountsLogic.java
  src/main/java/teammates/ui/webapi/CreateAccountAction.java
  src/main/java/teammates/ui/webapi/UpdateAccountRequestAction.java
Labels: s.ToMerge, c.Task

#13003 [#12048] Fix flaky component test
  src/it/java/teammates/it/ui/webapi/GetCoursesActionIT.java
Labels: s.ToReview

#13007 [#11878] Get account request by uuid
  src/e2e/java/teammates/e2e/cases/AdminHomePageE2ETest.java
  src/e2e/java/teammates/e2e/cases/AdminSearchPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/BaseE2ETestCase.java
  src/e2e/java/teammates/e2e/cases/InstructorCourseJoinConfirmationPageE2ETest.java
  src/it/java/teammates/it/ui/webapi/RejectAccountRequestActionIT.java
  src/main/java/teammates/ui/webapi/GetAccountRequestAction.java
  src/test/java/teammates/test/AbstractBackDoor.java
Labels: s.ToMerge, c.Task

#12977 [#11878] Add tests for Account Request Table
  src/web/app/components/account-requests-table/__snapshots__/account-request-table.component.spec.ts.snap
  src/web/app/components/account-requests-table/account-request-table.component.html
  src/web/app/components/account-requests-table/account-request-table.component.spec.ts
  src/web/app/components/account-requests-table/account-request-table.component.ts
  src/web/app/components/account-requests-table/admin-edit-request-modal/__snapshots__/admin-edit-request-modal.component.spec.ts.snap
  src/web/app/components/account-requests-table/admin-edit-request-modal/admin-edit-request-modal.component.html
  src/web/app/components/account-requests-table/admin-edit-request-modal/admin-edit-request-modal.component.spec.ts
  src/web/app/components/account-requests-table/admin-reject-with-reason-modal/__snapshots__/admin-reject-with-reason-modal.component.spec.ts.snap
  src/web/app/components/account-requests-table/admin-reject-with-reason-modal/admin-reject-with-reason-modal.component.spec.ts
  src/web/app/pages-admin/admin-search-page/__snapshots__/admin-search-page.component.spec.ts.snap
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.spec.ts
  src/web/services/account.service.ts
Labels: s.FinalReview, c.Task

#13017 [#11878] Reference account requests by ID in tests
  src/it/java/teammates/it/sqllogic/core/AccountRequestsLogicIT.java
  src/it/java/teammates/it/storage/sqlapi/AccountRequestsDbIT.java
  src/it/java/teammates/it/test/BaseTestCaseWithSqlDatabaseAccess.java
  src/it/java/teammates/it/ui/webapi/CreateAccountActionIT.java
  src/it/java/teammates/it/ui/webapi/GetCourseJoinStatusActionIT.java
  src/test/java/teammates/storage/sqlapi/AccountRequestsDbTest.java
Labels: s.FinalReview, c.Task

#13027 [#11878] Fix Approval Email Bug
  src/main/java/teammates/ui/webapi/UpdateAccountRequestAction.java
Labels: c.Bug, s.ToMerge

#13028 [#11878] Add Toasts
  src/web/app/components/account-requests-table/account-request-table.component.ts
Labels: s.ToMerge, c.Task

#13030 [#11878] Remove mention of home page URL in email
  src/main/resources/instructorEmailTemplate-newAccountRequestAcknowledgement.html
  src/test/resources/emails/instructorNewAccountRequestAcknowledgementEmailWithComments.html
  src/test/resources/emails/instructorNewAccountRequestAcknowledgementEmailWithNoComments.html
Labels: s.ToMerge, c.Task

#13024 [#12048] Fix FeedBackResponsesLogic bug
  src/main/java/teammates/sqllogic/core/FeedbackResponsesLogic.java
Labels: s.FinalReview

#13031 [#11878] Fix Highlighting and Null Statuses
  src/web/app/components/account-requests-table/__snapshots__/account-request-table.component.spec.ts.snap
  src/web/app/components/account-requests-table/account-request-table.component.html
  src/web/app/components/account-requests-table/admin-reject-with-reason-modal/admin-reject-with-reason-modal.component.ts
Labels: c.Bug, s.ToMerge

#12983 [#12946] Revert attributes removed in initialisation of MCS entities
  src/main/java/teammates/storage/sqlentity/Course.java
  src/main/java/teammates/storage/sqlentity/CourseStructure.java
  src/main/java/teammates/storage/sqlentity/FeedbackSession.java
  src/main/java/teammates/storage/sqlentity/Section.java
  src/main/java/teammates/storage/sqlentity/Student.java
  src/main/java/teammates/storage/sqlentity/Team.java
  src/main/java/teammates/storage/sqlentity/TeamToStudentMap.java
Labels: s.ToReview

#13032 [#11878] Check if account request is not created by admin before sending email
  src/it/java/teammates/it/ui/webapi/CreateAccountRequestActionIT.java
  src/main/java/teammates/ui/webapi/CreateAccountRequestAction.java
Labels: c.Bug, s.ToReview

#13038 [#11878] Add sort by created_at for getAllPendingRequests
  src/it/java/teammates/it/ui/webapi/GetAccountRequestsActionIT.java
  src/it/resources/data/typicalDataBundle.json
  src/main/java/teammates/storage/sqlapi/AccountRequestsDb.java
Labels: s.ToMerge, c.Task

#13015 [#11878] Request Page E2E
  src/e2e/java/teammates/e2e/cases/sql/RequestPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/RequestPage.java
  src/e2e/resources/testng-e2e-sql.xml
  src/main/java/teammates/common/util/Const.java
  src/web/app/pages-static/request-page/__snapshots__/request-page.component.spec.ts.snap
  src/web/app/pages-static/request-page/instructor-request-form/__snapshots__/instructor-request-form.component.spec.ts.snap
  src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.html
  src/web/app/pages-static/request-page/request-page.component.html
Labels: s.ToMerge, c.Task

#13039 [#12954] CreateAccountAction seems to have redundant code
  src/main/java/teammates/ui/webapi/CreateAccountAction.java
Labels: s.FinalReview, c.Task

#13010 [#12048] Data migration for team entities
  src/client/java/teammates/client/scripts/sql/DataMigrationForTeamSql.java
  src/client/java/teammates/client/scripts/sql/SeedDb.java
  src/client/java/teammates/client/scripts/sql/VerifyCourseEntityCounts.java
  src/client/java/teammates/client/scripts/sql/VerifyTeamAttributes.java
Labels: s.ToReview, c.Task

#13023 [#12048] Fix getSessionResultAction bugs
  src/it/java/teammates/it/ui/webapi/GetSessionResultsActionIT.java
  src/main/java/teammates/ui/webapi/GetSessionResultsAction.java
Labels: s.FinalReview

#13044 [#11878] Remove ref by email and institute
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/AccountRequestsLogic.java
  src/main/java/teammates/storage/sqlapi/AccountRequestsDb.java
Labels: s.FinalReview, c.Task

#13043 [#11878] Migrate AccountRequestsLogic unit tests
  src/test/java/teammates/sqllogic/core/AccountRequestsLogicTest.java
  src/test/java/teammates/test/BaseTestCase.java
Labels: s.ToMerge, c.Task

#13020 [#11878] Add Admin E2E Tests
  src/e2e/java/teammates/e2e/cases/sql/AdminHomePageE2ETest.java
  src/e2e/java/teammates/e2e/cases/sql/AdminSearchPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/AdminHomePage.java
  src/e2e/java/teammates/e2e/pageobjects/AdminSearchPage.java
  src/e2e/java/teammates/e2e/pageobjects/AppPage.java
  src/e2e/resources/data/AdminSearchPageE2ESqlTest.json
  src/e2e/resources/testng-e2e-sql.xml
  src/web/app/components/account-requests-table/admin-reject-with-reason-modal/__snapshots__/admin-reject-with-reason-modal.component.spec.ts.snap
  src/web/app/components/account-requests-table/admin-reject-with-reason-modal/admin-reject-with-reason-modal.component.html
  src/web/app/components/account-requests-table/admin-reject-with-reason-modal/admin-reject-with-reason-modal.component.ts
Labels: s.ToMerge, c.Task

#13047 [#11878] Add SQL injection tests for AccountRequestsDb
  src/it/java/teammates/it/storage/sqlapi/AccountRequestsDbIT.java
Labels: s.ToMerge, c.Task

#13037 [#11843] Fix front end bugs
  src/web/app/pages-instructor/instructor-student-activity-logs/__snapshots__/instructor-student-activity-logs.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-student-activity-logs/instructor-student-activity-logs.component.html
  src/web/app/pages-instructor/instructor-student-activity-logs/instructor-student-activity-logs.component.ts
Labels: s.FinalReview

#12964 [#12666] Instructor's Student Records Page: Moderate response button (on panel)
  src/web/app/components/question-responses/grq-rgq-view-responses/grq-rgq-view-responses.component.html
Labels: s.ToMerge

#13013 [#12048] Migrate InstructorStudentRecordsPageE2ETest
  src/e2e/java/teammates/e2e/cases/sql/InstructorStudentRecordsPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorStudentRecordsPage.java
  src/e2e/resources/data/InstructorStudentRecordsPageE2ETestSql.json
  src/e2e/resources/testng-e2e-sql.xml
Labels: s.ToReview

#13042 [#12048] Data migration section chain fixs
  src/client/java/teammates/client/scripts/sql/DataMigrationForCourseEntitySql.java
  src/client/java/teammates/client/scripts/sql/VerifyCourseEntityAttributes.java
Labels: s.ToReview

#13056 [#11878] Fix Edit
  src/web/app/components/account-requests-table/account-request-table.component.spec.ts
  src/web/app/components/account-requests-table/account-request-table.component.ts
Labels: c.Bug, s.FinalReview

#13014 [#12048] Migrate InstructorStudentListPageE2ETest
  src/e2e/java/teammates/e2e/cases/sql/InstructorStudentListPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorStudentListPageSql.java
  src/e2e/resources/data/InstructorStudentListPageE2ETestSql.json
  src/e2e/resources/testng-e2e-sql.xml
Labels: s.ToMerge

#13016 [#12048] Migrate instructor home page e2e test
  src/e2e/java/teammates/e2e/cases/sql/BaseE2ETestCase.java
  src/e2e/java/teammates/e2e/cases/sql/InstructorHomePageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorHomePage.java
  src/e2e/resources/data/InstructorHomePageE2ETestSql.json
  src/e2e/resources/testng-e2e-sql.xml
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java
  src/main/java/teammates/storage/sqlentity/FeedbackSession.java
  src/main/java/teammates/ui/webapi/BinFeedbackSessionAction.java
  src/main/java/teammates/ui/webapi/RestoreFeedbackSessionAction.java
  src/test/java/teammates/test/AbstractBackDoor.java
  src/test/java/teammates/test/BaseTestCaseWithSqlDatabaseAccess.java
Labels: s.ToReview

#13045 [#12048] Data migration for feedback entities chain
  src/client/java/teammates/client/scripts/sql/DataMigrationForCourseEntitySql.java
  src/main/java/teammates/storage/sqlentity/FeedbackQuestion.java
  src/main/java/teammates/storage/sqlentity/FeedbackResponse.java
  src/main/java/teammates/storage/sqlentity/FeedbackResponseComment.java
  src/main/java/teammates/storage/sqlentity/FeedbackSession.java
Labels: s.ToReview

#13008 [#12048] Migrate StudentCourseJoinConfirmationPageE2ETest
  src/e2e/java/teammates/e2e/cases/sql/StudentCourseJoinConfirmationPageE2ETest.java
  src/e2e/resources/data/StudentCourseJoinConfirmationPageE2ETestSql.json
  src/e2e/resources/testng-e2e-sql.xml
Labels: s.ToReview

#13058 [#11878] Fix console errors
  src/web/app/components/account-requests-table/__snapshots__/account-request-table.component.spec.ts.snap
  src/web/app/components/account-requests-table/account-request-table.component.html
  src/web/app/components/account-requests-table/account-request-table.component.ts
Labels: p.Urgent, c.Bug, s.ToMerge

#13059 [#11878] Fix Rejection Modal
  src/web/app/components/account-requests-table/account-request-table.component.spec.ts
  src/web/app/components/account-requests-table/account-request-table.component.ts
Labels: p.Urgent, c.Bug, s.ToMerge

#13057 [#12048] Add composite index for data migration
  src/client/java/teammates/client/scripts/sql/IndexCourseFields.java
  src/main/appengine/index.yaml
Labels: s.ToReview

#13062 [#12048] Update changelog docs and changelog name
  docs/schema-migration.md
  src/main/resources/db/changelog/db.changelog-root.xml
  src/main/resources/db/changelog/db.changelog-v9.0.0-beta.5.xml
Labels: s.ToReview, c.Task

#13012 [#12048] Migrate StudentCourseDetailsPageE2ETest
  src/e2e/java/teammates/e2e/cases/sql/StudentCourseDetailsPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/StudentCourseDetailsPage.java
  src/e2e/resources/data/StudentCourseDetailsPageE2ETestSql.json
  src/e2e/resources/testng-e2e-sql.xml
Labels: s.ToReview

#13046 [#12048] Data migration: ensure consistency when script is stopped and resumed
  src/client/java/teammates/client/scripts/sql/DataMigrationForCourseEntitySql.java
  src/main/java/teammates/storage/sqlentity/Course.java
Labels: s.ToReview

#13071 [#12048] Add migration script for instructors and Deadline Extensions
  src/client/java/teammates/client/scripts/sql/DataMigrationForCourseEntitySql.java
  src/client/java/teammates/client/scripts/sql/DataMigrationForTeamSql.java
  src/client/java/teammates/client/scripts/sql/VerifyCourseEntityAttributes.java
  src/client/java/teammates/client/scripts/sql/VerifyTeamAttributes.java
  src/main/java/teammates/storage/sqlentity/DeadlineExtension.java
  src/main/java/teammates/storage/sqlentity/FeedbackQuestion.java
  src/main/java/teammates/storage/sqlentity/FeedbackResponse.java
  src/main/java/teammates/storage/sqlentity/FeedbackResponseComment.java
  src/main/java/teammates/storage/sqlentity/FeedbackSession.java
Labels: s.Ongoing

#13076 [#11878] Account Request Indexing Script
  src/client/java/teammates/client/scripts/UpdateAccountRequestIndexing.java
Labels: c.Bug, s.ToMerge

#13074 [#12048] Add seed and verification scripts for feedback chain
  src/client/java/teammates/client/scripts/sql/DataMigrationForCourseEntitySql.java
  src/client/java/teammates/client/scripts/sql/SeedDb.java
  src/client/java/teammates/client/scripts/sql/VerifyCourseEntityAttributes.java
Labels: s.ToReview

#13081 [#11878] Add CAPTCHA to ARF
  src/main/java/teammates/ui/request/AccountCreateRequest.java
  src/main/java/teammates/ui/webapi/CreateAccountRequestAction.java
  src/web/app/pages-static/request-page/instructor-request-form/__snapshots__/instructor-request-form.component.spec.ts.snap
  src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.html
  src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.spec.ts
  src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.ts
  src/web/app/pages-static/request-page/request-page.module.ts
Labels: p.Urgent, s.ToMerge, c.Feature

#13068 [#13064] Use AccountRequestUpdateRequest as parameter
  src/web/app/components/account-requests-table/account-request-table.component.ts
  src/web/services/account.service.ts
Labels: s.ToMerge, c.Task

#13077 [#12048] Add patch script for account request and notifications to amend createdAt field
  src/client/java/teammates/client/scripts/sql/PatchCreatedAtAccountRequest.java
  src/client/java/teammates/client/scripts/sql/PatchCreatedAtTimeNotification.java
  src/client/java/teammates/client/scripts/sql/VerifyAccountRequestAttributes.java
  src/client/java/teammates/client/scripts/sql/VerifyNotificationAttributes.java
Labels: s.FinalReview, c.Task

#13090 [#12048] Add dangling course delete script
  src/client/java/teammates/client/scripts/sql/DeleteDanglingCourseScript.java
  src/client/java/teammates/client/scripts/sql/SeedDb.java
Labels: s.ToReview, c.Task

#13078 [#12048] Migrate FeedbackRubricQuestionsE2E
  src/e2e/java/teammates/e2e/cases/sql/FeedbackRubricQuestionE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/FeedbackSubmitPage.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorFeedbackEditPage.java
  src/e2e/resources/data/FeedbackRubricQuestionE2ESqlTest.json
  src/e2e/resources/testng-e2e-sql.xml
Labels: s.FinalReview
