Repository TEAMMATES/teammates, pull requests merged in 2024-07, with the labels that each got.

#13135 [#13105] Admin managing account requests: use spinners to indicate actions in progress
  src/web/app/components/account-requests-table/__snapshots__/account-request-table.component.spec.ts.snap
  src/web/app/components/account-requests-table/account-request-table.component.html
  src/web/app/components/account-requests-table/account-request-table.component.spec.ts
  src/web/app/components/account-requests-table/account-request-table.component.ts
  src/web/app/components/account-requests-table/account-request-table.module.ts
  src/web/app/pages-admin/admin-search-page/__snapshots__/admin-search-page.component.spec.ts.snap
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.html
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.spec.ts
  src/web/app/pages-admin/admin-search-page/admin-search-page.component.ts
  src/web/app/pages-admin/admin-search-page/admin-search-page.module.ts
Labels: s.ToMerge

#13083 [#12779] Fix notifications update logic
  src/it/java/teammates/it/sqllogic/core/NotificationsLogicIT.java
  src/main/java/teammates/common/util/HibernateUtil.java
  src/main/java/teammates/sqllogic/core/NotificationsLogic.java
  src/main/java/teammates/storage/sqlapi/EntitiesDb.java
  src/main/java/teammates/storage/sqlapi/NotificationsDb.java
  src/test/java/teammates/sqllogic/core/NotificationsLogicTest.java
  src/test/java/teammates/storage/sqlapi/AccountRequestsDbTest.java
  src/test/java/teammates/storage/sqlapi/AccountsDbTest.java
  src/test/java/teammates/storage/sqlapi/CoursesDbTest.java
  src/test/java/teammates/storage/sqlapi/FeedbackResponseCommentsDbTest.java
  src/test/java/teammates/storage/sqlapi/FeedbackSessionsDbTest.java
  src/test/java/teammates/storage/sqlapi/NotificationsDbTest.java
  src/test/java/teammates/storage/sqlapi/UsersDbTest.java
Labels: s.FinalReview

#13141 [#12894] Calculate msq totals by student email instead of name
  src/web/app/components/question-types/question-statistics/msq-question-statistics.component.ts
  src/web/app/components/question-types/question-statistics/question-statistics-calculation/msq-question-statistics-calculation.ts
  src/web/app/components/question-types/question-statistics/test-data/msqQuestionResponses.json
Labels: s.FinalReview

#13069 [#12048] Migrate InstructorCourseStudentDetailsEditPageE2ETest
  src/e2e/java/teammates/e2e/cases/sql/InstructorCourseStudentDetailsEditPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/InstructorCourseStudentDetailsEditPageSql.java
  src/e2e/resources/data/InstructorCourseStudentDetailsEditPageE2ETestSql.json
  src/e2e/resources/testng-e2e-sql.xml
Labels: s.FinalReview

#13117 [#13104] Accounts request form: auto-unify country names
  src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.spec.ts
  src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.ts
Labels: s.FinalReview, c.Feature

#13143 [#12655] Instructor Edit Session Page: If make session visible is later than submission opening time, automatically default to opening time
  src/web/app/components/session-edit-form/session-edit-form.component.html
  src/web/app/components/session-edit-form/session-edit-form.component.spec.ts
  src/web/app/components/session-edit-form/session-edit-form.component.ts
Labels: s.FinalReview

#13087 [#12588] Test coverage improvements for InstructorResponsesViewBase
  src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.spec.ts
Labels: s.FinalReview

#13154 [#11383] Add detection of PRs linking to closed issues
  .github/workflows/pr.yml
Labels: s.FinalReview

#13152 [#12169] Update `teammates-eslint.yml` to mark trailing whitespaces as errors on Ubuntu
  static-analysis/teammates-eslint.yml
Labels: s.FinalReview
