Repository TEAMMATES/teammates, pull requests merged in 2024-01, with the labels that each got.

#12691 [#12657] Instructor Home Page: Students dropdown buttons of the wrong colour .
  src/web/app/pages-instructor/instructor-home-page/__snapshots__/instructor-home-page.component.spec.ts.snap
  src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
Labels: s.FinalReview

#12053 [#12052] Per Receiver Submission
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/ui/webapi/SubmitFeedbackResponsesAction.java
  src/web/app/components/question-submission-form/question-submission-form-model.ts
  src/web/app/components/question-submission-form/question-submission-form.component.html
  src/web/app/components/question-submission-form/question-submission-form.component.spec.ts
  src/web/app/components/question-submission-form/question-submission-form.component.ts
  src/web/app/pages-help/instructor-help-page/instructor-help-questions-section/instructor-help-questions-data.ts
  src/web/app/pages-session/session-submission-page/__snapshots__/session-submission-page.component.spec.ts.snap
  src/web/app/pages-session/session-submission-page/session-submission-page.component.html
  src/web/app/pages-session/session-submission-page/session-submission-page.component.spec.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
  src/web/app/pages-session/session-submission-page/session-submission-page.module.ts
  src/web/test-helpers/json-helpers.ts
Labels: s.ToMerge, c.Feature

#12434 [#12048] Migrate UpdateInstructorAction
  src/it/java/teammates/it/ui/webapi/UpdateInstructorActionIT.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/FeedbackResponseCommentsLogic.java
  src/main/java/teammates/sqllogic/core/LogicStarter.java
  src/main/java/teammates/sqllogic/core/UsersLogic.java
  src/main/java/teammates/storage/sqlapi/FeedbackResponseCommentsDb.java
  src/main/java/teammates/storage/sqlapi/UsersDb.java
  src/main/java/teammates/ui/webapi/UpdateInstructorAction.java
  src/test/java/teammates/sqllogic/core/UsersLogicTest.java
Labels: s.OnHold

#12701 [#12699] Replace ng command in setting-up.md
  docs/setting-up.md
Labels: c.Bug, a-Docs

#12705 [#12704] Release V8.30.0
  docs/static-analysis.md
  docs/troubleshooting-guide.md
  src/web/data/developers.json
Labels: s.ToMerge, c.Release
