Repository TEAMMATES/teammates, pull requests merged in 2024-06, with the labels that each got.

#13127 [#13126] Fix failing component test cases
  src/it/java/teammates/it/ui/webapi/UpdateAccountRequestActionIT.java
  src/it/java/teammates/it/ui/webapi/UpdateFeedbackSessionLogsActionIT.java
Labels: s.ToMerge

#13128 [#13126] Update timezone db
  package-lock.json
  package.json
  src/main/resources/tzdb.dat
  src/web/data/timezone.json
Labels: s.ToMerge, c.Task

#13120 [#13109]-IndexOutOfBoundsException encountered by LogsProcessor
  src/main/java/teammates/logic/api/LogsProcessor.java
Labels: c.Bug, s.ToMerge

#13116 [#13103]Account request form: No need to CC the email 'Acknowledgement of Instructor Account Request'
  src/main/java/teammates/sqllogic/api/SqlEmailGenerator.java
  src/test/java/teammates/sqllogic/api/SqlEmailGeneratorTest.java
Labels: s.ToMerge, c.Feature

#13111 [#12048] Fix course migration script
  src/client/java/teammates/client/scripts/sql/DataMigrationForAccountAndReadNotificationSql.java
  src/client/java/teammates/client/scripts/sql/DataMigrationForCourseEntitySql.java
  src/client/java/teammates/client/scripts/sql/DataMigrationForCourseSql.java
  src/client/java/teammates/client/scripts/sql/Logger.java
  src/client/java/teammates/client/scripts/sql/SeedDb.java
  src/client/java/teammates/client/scripts/sql/VerifyCourseEntityAttributes.java
  src/client/java/teammates/client/scripts/sql/VerifyNonCourseEntityAttributesBaseScript.java
  src/main/java/teammates/storage/sqlentity/DeadlineExtension.java
  src/main/java/teammates/storage/sqlentity/FeedbackQuestion.java
  src/main/java/teammates/storage/sqlentity/FeedbackResponse.java
  src/main/java/teammates/storage/sqlentity/FeedbackResponseComment.java
  src/main/java/teammates/storage/sqlentity/FeedbackSession.java
  src/main/java/teammates/storage/sqlentity/Section.java
  src/main/java/teammates/storage/sqlentity/User.java
Labels: s.ToReview, c.Task

#13130 [#12875] Some feedback sessions duplicated in student home page
  src/web/app/pages-student/student-home-page/student-home-page.component.ts
Labels: c.Bug, s.FinalReview

#13118 [#13102] Admin rejecting account request: give actual account in the email template
  src/web/app/components/account-requests-table/admin-reject-with-reason-modal/__snapshots__/admin-reject-with-reason-modal.component.spec.ts.snap
  src/web/app/components/account-requests-table/admin-reject-with-reason-modal/admin-reject-with-reason-modal.component.spec.ts
  src/web/app/components/account-requests-table/admin-reject-with-reason-modal/admin-reject-with-reason-modal.component.ts
Labels: s.ToReview

#13101 [#12901] Check if the search service is active in account request search test
  src/it/java/teammates/it/storage/sqlapi/AccountRequestsDbIT.java
  src/it/java/teammates/it/storage/sqlsearch/AccountRequestSearchIT.java
Labels: s.OnHold, c.Task
