Repository TEAMMATES/teammates, pull requests merged in 2024-02, with the labels that each got.

#12710 [#12048] Migrate GetOngoingSessionsAction for V9
  src/it/java/teammates/it/sqllogic/core/FeedbackSessionsLogicIT.java
  src/it/java/teammates/it/storage/sqlapi/FeedbackSessionsDbIT.java
  src/it/resources/data/typicalDataBundle.json
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java
  src/main/java/teammates/storage/sqlentity/FeedbackSession.java
  src/main/java/teammates/ui/output/OngoingSession.java
  src/main/java/teammates/ui/webapi/Action.java
  src/main/java/teammates/ui/webapi/GetOngoingSessionsAction.java
  src/test/java/teammates/sqlui/webapi/BaseActionTest.java
  src/test/java/teammates/sqlui/webapi/GetOngoingSessionsActionTest.java
Labels: s.ToReview, c.Task

#12713 [#12048] Migrate GetCourseJoinStatusAction
  src/it/java/teammates/it/storage/sqlapi/AccountRequestsDbIT.java
  src/it/java/teammates/it/storage/sqlsearch/InstructorSearchIT.java
  src/it/java/teammates/it/ui/webapi/DeleteStudentsActionIT.java
  src/it/java/teammates/it/ui/webapi/GetCourseJoinStatusActionIT.java
  src/it/java/teammates/it/ui/webapi/GetInstructorsActionIT.java
  src/it/java/teammates/it/ui/webapi/GetStudentsActionIT.java
  src/it/resources/data/typicalDataBundle.json
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/AccountRequestsLogic.java
  src/main/java/teammates/storage/sqlapi/AccountRequestsDb.java
  src/main/java/teammates/ui/webapi/GetCourseJoinStatusAction.java
Labels: s.ToMerge, c.Task

#12715 [#12048] Migrate enroll students action
  src/it/java/teammates/it/ui/webapi/EnrollStudentsActionIT.java
  src/it/resources/data/typicalDataBundle.json
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/DeadlineExtensionsLogic.java
  src/main/java/teammates/sqllogic/core/FeedbackResponseCommentsLogic.java
  src/main/java/teammates/sqllogic/core/FeedbackResponsesLogic.java
  src/main/java/teammates/sqllogic/core/LogicStarter.java
  src/main/java/teammates/sqllogic/core/UsersLogic.java
  src/main/java/teammates/storage/sqlapi/FeedbackResponseCommentsDb.java
  src/main/java/teammates/storage/sqlapi/FeedbackResponsesDb.java
  src/main/java/teammates/storage/sqlapi/UsersDb.java
  src/main/java/teammates/storage/sqlentity/Student.java
  src/main/java/teammates/ui/webapi/EnrollStudentsAction.java
Labels: s.ToMerge

#12723 [#12048] Refactor email generator
  src/main/java/teammates/logic/api/EmailGenerator.java
Labels: s.ToReview, c.Task

#12722 [#12048] Migrate join course action
  src/it/java/teammates/it/sqllogic/core/AccountsLogicIT.java
  src/it/java/teammates/it/storage/sqlsearch/InstructorSearchIT.java
  src/it/java/teammates/it/test/BaseTestCaseWithSqlDatabaseAccess.java
  src/it/java/teammates/it/ui/webapi/JoinCourseActionIT.java
  src/it/resources/data/typicalDataBundle.json
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/AccountsLogic.java
  src/main/java/teammates/sqllogic/core/LogicStarter.java
  src/main/java/teammates/ui/webapi/JoinCourseAction.java
  src/test/java/teammates/sqllogic/core/AccountsLogicTest.java
Labels: s.FinalReview

#12721 [#12048] Add SQL email generator unit test
  src/it/java/teammates/it/sqllogic/api/EmailGeneratorTestIT.java
  src/it/java/teammates/it/sqllogic/api/package-info.java
  src/it/resources/data/SqlEmailGeneratorTest.json
  src/it/resources/testng-it.xml
  src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java
  src/test/resources/data/EmailGeneratorTest.json
Labels: s.ToReview, c.Task

#12706 [#12048] Migrate CreateInstructorAction
  src/it/java/teammates/it/ui/webapi/CreateInstructorActionIT.java
  src/main/java/teammates/common/datatransfer/InstructorPrivileges.java
  src/main/java/teammates/sqllogic/core/UsersLogic.java
  src/main/java/teammates/storage/sqlapi/UsersDb.java
  src/main/java/teammates/ui/webapi/CreateInstructorAction.java
Labels: s.Ongoing

#12728 [#12048] Support for twin db for search + replace datastore test
  src/main/java/teammates/ui/webapi/SearchInstructorsAction.java
  src/test/java/teammates/ui/webapi/SearchInstructorsActionTest.java
Labels: s.FinalReview

#12726 [#12048] Migrate search account requests action
  src/it/java/teammates/it/storage/sqlsearch/AccountRequestSearchIT.java
  src/it/java/teammates/it/ui/webapi/GetCourseJoinStatusActionIT.java
  src/it/java/teammates/it/ui/webapi/SearchAccountRequestsActionIT.java
  src/it/resources/data/typicalDataBundle.json
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/AccountRequestsLogic.java
  src/main/java/teammates/storage/sqlapi/AccountRequestsDb.java
  src/main/java/teammates/ui/webapi/SearchAccountRequestsAction.java
Labels: s.ToReview

#12737 [#12693] Excess padding on edit course details component
  src/web/app/pages-instructor/instructor-course-edit-page/instructor-course-edit-page.component.html
Labels: s.FinalReview

#12734 [#12048] Migrate PutDataBundleDocumentsAction
  src/main/java/teammates/ui/webapi/PutDataBundleDocumentsAction.java
  src/test/java/teammates/test/AbstractBackDoor.java
Labels: s.FinalReview

#12742 [#12048] Finish partial testcases
  src/test/java/teammates/storage/sqlapi/AccountRequestsDbTest.java
  src/test/java/teammates/storage/sqlapi/CoursesDbTest.java
  src/test/java/teammates/storage/sqlapi/UsersDbTest.java
Labels: s.FinalReview

#12744 [#12048] Move getTypicalEntity functions to BaseTestCase
  src/it/java/teammates/it/sqllogic/core/UsersLogicIT.java
  src/it/java/teammates/it/storage/sqlapi/AccountsDbIT.java
  src/it/java/teammates/it/storage/sqlapi/CoursesDbIT.java
  src/it/java/teammates/it/storage/sqlapi/UsersDbIT.java
  src/test/java/teammates/sqllogic/core/AccountsLogicTest.java
  src/test/java/teammates/sqllogic/core/CoursesLogicTest.java
  src/test/java/teammates/sqllogic/core/NotificationsLogicTest.java
  src/test/java/teammates/sqllogic/core/UsersLogicTest.java
  src/test/java/teammates/storage/sqlapi/AccountsDbTest.java
  src/test/java/teammates/storage/sqlapi/NotificationsDbTest.java
  src/test/java/teammates/storage/sqlapi/UsersDbTest.java
  src/test/java/teammates/test/BaseTestCase.java
Labels: s.ToMerge

#12735 [#12048] Migrate search students action
  src/it/java/teammates/it/storage/sqlsearch/StudentSearchIT.java
  src/it/java/teammates/it/ui/webapi/SearchStudentsActionIT.java
  src/it/resources/data/typicalDataBundle.json
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/CoursesLogic.java
  src/main/java/teammates/sqllogic/core/UsersLogic.java
  src/main/java/teammates/storage/sqlapi/UsersDb.java
  src/main/java/teammates/ui/webapi/SearchStudentsAction.java
Labels: s.ToMerge

#12733 [#12048] Migrate StudentSearchIndexingWorkerAction
  src/it/java/teammates/it/ui/webapi/StudentSearchIndexingWorkerActionIT.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/ui/webapi/StudentSearchIndexingWorkerAction.java
Labels: s.FinalReview

#12712 [#12048] Migrate Session Links Recovery Action
  src/it/java/teammates/it/sqllogic/api/EmailGeneratorTestIT.java
  src/it/java/teammates/it/storage/sqlsearch/StudentSearchIT.java
  src/it/java/teammates/it/ui/webapi/SearchStudentsActionIT.java
  src/it/java/teammates/it/ui/webapi/SessionLinksRecoveryActionTestIT.java
  src/it/resources/data/typicalDataBundle.json
  src/main/java/teammates/logic/api/EmailGenerator.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/sqllogic/api/SqlEmailGenerator.java
  src/main/java/teammates/ui/webapi/SessionLinksRecoveryAction.java
Labels: s.ToMerge, c.Task

#12751 [#12048] Update restoreDeletedFeedbackSession to save updated entity to db
  src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java
Labels: s.FinalReview

#12750 [#12048] Remove typical data bundle from feedbackquestionlogic test
  src/test/java/teammates/sqllogic/core/FeedbackQuestionsLogicTest.java
  src/test/java/teammates/test/BaseTestCase.java
Labels: s.FinalReview

#12731 [#12048] Migrate instructor search indexing worker action
  src/it/java/teammates/it/ui/webapi/InstructorSearchIndexingWorkerActionIT.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/ui/webapi/InstructorSearchIndexingWorkerAction.java
Labels: s.ToMerge, c.Task

#12746 [#12048] Add tests for CoursesLogic
  src/test/java/teammates/sqllogic/core/CoursesLogicTest.java
Labels: s.FinalReview

#12748 [#12048] Add test for getUsageStatisticsForTimeRange
  src/it/java/teammates/it/storage/sqlapi/UsageStatisticsDbIT.java
Labels: s.ToMerge

#12732 [#12048] Migrate SubmitFeedbackResponseAction's Logic and Db methods
  src/it/java/teammates/it/sqllogic/core/FeedbackResponsesLogicIT.java
  src/it/java/teammates/it/storage/sqlapi/FeedbackResponsesDbIT.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/FeedbackResponseCommentsLogic.java
  src/main/java/teammates/sqllogic/core/FeedbackResponsesLogic.java
  src/main/java/teammates/storage/sqlapi/FeedbackResponseCommentsDb.java
  src/main/java/teammates/storage/sqlentity/FeedbackResponseComment.java
Labels: s.ToReview

#12755 Add testcases for FeedbackResponseCommentsDbTest
  src/main/java/teammates/storage/sqlapi/FeedbackResponseCommentsDb.java
  src/test/java/teammates/storage/sqlapi/FeedbackResponseCommentsDbTest.java
  src/test/java/teammates/test/BaseTestCase.java
Labels: s.ToReview, c.Task

#12740 [#12048] Migrate FeedbackSessionOpeningSoonRemindersAction
  src/it/java/teammates/it/ui/webapi/FeedbackSessionOpeningSoonRemindersActionIT.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java
  src/main/java/teammates/storage/sqlentity/FeedbackSession.java
  src/main/java/teammates/ui/webapi/FeedbackSessionOpeningSoonRemindersAction.java
Labels: s.FinalReview

#12720 [#12048] Migrate SubmitFeedbackResponseAction
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/logic/api/Logic.java
  src/main/java/teammates/logic/core/FeedbackResponsesLogic.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/storage/sqlentity/FeedbackResponse.java
  src/main/java/teammates/ui/output/FeedbackResponsesData.java
  src/main/java/teammates/ui/webapi/BasicFeedbackSubmissionAction.java
  src/main/java/teammates/ui/webapi/SubmitFeedbackResponsesAction.java
Labels: s.ToMerge

#12757 [#12048] Migrate AccountRequestSearchIndexingWorkerAction
  src/it/java/teammates/it/ui/webapi/AccountRequestSearchIndexingWorkerActionIT.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/ui/webapi/AccountRequestSearchIndexingWorkerAction.java
Labels: s.FinalReview

#12743 [#12048] Migrate FeedbackSessionClosingRemindersAction
  src/it/java/teammates/it/ui/webapi/FeedbackSessionClosingRemindersActionIT.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/api/SqlEmailGenerator.java
  src/main/java/teammates/sqllogic/core/DeadlineExtensionsLogic.java
  src/main/java/teammates/sqllogic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/storage/sqlapi/DeadlineExtensionsDb.java
  src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java
  src/main/java/teammates/storage/sqlentity/FeedbackSession.java
  src/main/java/teammates/ui/webapi/FeedbackSessionClosingRemindersAction.java
Labels: s.ToMerge

#12738 [#12048] Migrate FeedbackSessionClosedRemindersAction
  src/it/java/teammates/it/ui/webapi/FeedbackSessionClosedRemindersActionIT.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java
  src/main/java/teammates/storage/sqlentity/FeedbackSession.java
  src/main/java/teammates/ui/webapi/FeedbackSessionClosedRemindersAction.java
Labels: s.ToReview

#12741 [#12048] Migrate feedbackSessionPublishedRemindersAction
  src/it/java/teammates/it/ui/webapi/FeedbackSessionPublishedRemindersActionIT.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java
  src/main/java/teammates/ui/webapi/FeedbackSessionPublishedRemindersAction.java
Labels: s.ToMerge

#12752 [#12048] Add test cases for FeedbackSessionsDb
  src/test/java/teammates/storage/sqlapi/FeedbackSessionsDbTest.java
  src/test/java/teammates/test/BaseTestCase.java
Labels: s.ToMerge

#12739 [#12048] Migrate FeedbackSessionOpeningRemindersAction
  src/it/java/teammates/it/ui/webapi/FeedbackSessionOpeningRemindersActionIT.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/storage/sqlapi/FeedbackSessionsDb.java
  src/main/java/teammates/ui/webapi/FeedbackSessionOpeningRemindersAction.java
Labels: s.FinalReview, c.Task

#12790 [#12048] migrate InstructorCourseJoinConfirmationPageE2ETest
  src/e2e/java/teammates/e2e/cases/InstructorCourseJoinConfirmationPageE2ETest.java
  src/e2e/resources/data/InstructorCourseJoinConfirmationPageE2ETest.json
  src/e2e/resources/data/InstructorCourseJoinConfirmationPageE2ETest_SqlEntities.json
Labels: s.ToMerge

#12789 [#12048] Migrate instructor courses page e2e test
  src/e2e/java/teammates/e2e/cases/InstructorCoursesPageE2ETest.java
  src/e2e/resources/data/InstructorCoursesPageE2ETest.json
  src/e2e/resources/data/InstructorCoursesPageE2ETest_SqlEntities.json
  src/main/java/teammates/ui/webapi/CreateCourseAction.java
  src/test/java/teammates/sqlui/webapi/CreateCourseActionTest.java
  src/test/java/teammates/ui/webapi/CreateCourseActionTest.java
Labels: s.ToMerge

#12792 [#12048] Migrate instructor notification page e2e test
  src/e2e/java/teammates/e2e/cases/InstructorNotificationsPageE2ETest.java
  src/e2e/resources/data/InstructorNotificationsPageE2ETest_SqlEntities.json
Labels: s.ToMerge

#12778 [#12048] Create IT for GetFeedbackSessionSubmittedGiverSetAction
  src/it/java/teammates/it/ui/webapi/GetFeedbackSessionSubmittedGiverSetActionIT.java
  src/main/java/teammates/sqllogic/core/FeedbackSessionsLogic.java
  src/main/java/teammates/storage/sqlapi/FeedbackResponsesDb.java
Labels: s.ToMerge

#12798 [#12048] Add migration script for Usage Statistics
  src/client/java/teammates/client/scripts/sql/DataMigrationForUsageStatisticsSql.java
  src/client/java/teammates/client/scripts/sql/SeedUsageStatistics.java
Labels: s.ToReview

#12799 [#12048] Add migration script for Account Request
  src/client/java/teammates/client/scripts/sql/DataMigrationForAccountRequestSql.java
Labels: s.ToReview

#12802 [#12048] Move accounts JSON for AdminSessionsPageE2ETest
  src/e2e/java/teammates/e2e/cases/AdminSessionsPageE2ETest.java
  src/e2e/resources/data/AdminSessionsPageE2ETest.json
  src/e2e/resources/data/AdminSessionsPageE2ETest_SqlEntities.json
Labels: s.ToMerge

#12727 [#12048] Migrate UpdateStudentAction
  src/it/java/teammates/it/storage/sqlsearch/StudentSearchIT.java
  src/it/java/teammates/it/ui/webapi/DeleteStudentsActionIT.java
  src/it/java/teammates/it/ui/webapi/EnrollStudentsActionIT.java
  src/it/java/teammates/it/ui/webapi/FeedbackSessionClosingRemindersActionIT.java
  src/it/java/teammates/it/ui/webapi/GetStudentsActionIT.java
  src/it/java/teammates/it/ui/webapi/SearchStudentsActionIT.java
  src/it/java/teammates/it/ui/webapi/UpdateStudentActionIT.java
  src/it/resources/data/typicalDataBundle.json
  src/main/java/teammates/common/datatransfer/attributes/StudentAttributes.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/FeedbackResponsesLogic.java
  src/main/java/teammates/sqllogic/core/UsersLogic.java
  src/main/java/teammates/storage/sqlapi/UsersDb.java
  src/main/java/teammates/ui/webapi/EnrollStudentsAction.java
  src/main/java/teammates/ui/webapi/UpdateStudentAction.java
Labels: s.ToMerge, c.Task

#12804 [#12048] Move accounts JSON for FeedbackConstSumOptionQuestionE2ETest
  src/e2e/java/teammates/e2e/cases/FeedbackConstSumOptionQuestionE2ETest.java
  src/e2e/resources/data/FeedbackConstSumOptionQuestionE2ETest.json
  src/e2e/resources/data/FeedbackConstSumOptionQuestionE2ETest_SqlEntities.json
Labels: s.FinalReview

#12805 [#12048] Move accounts JSON for FeedbackConstSumRecipientQuestionE2ETest
  src/e2e/java/teammates/e2e/cases/FeedbackConstSumRecipientQuestionE2ETest.java
  src/e2e/resources/data/FeedbackConstSumRecipientQuestionE2ETest.json
  src/e2e/resources/data/FeedbackConstSumRecipientQuestionE2ETest_SqlEntities.json
Labels: s.ToMerge

#12808 [#12048] Move accounts JSON for FeedbackContributionQuestionE2ETest
  src/e2e/java/teammates/e2e/cases/FeedbackContributionQuestionE2ETest.java
  src/e2e/resources/data/FeedbackContributionQuestionE2ETest.json
  src/e2e/resources/data/FeedbackContributionQuestionE2ETest_SqlEntities.json
Labels: s.ToMerge

#12809 [#12048] Move accounts JSON for FeedbackMcqQuestionE2ETest
  src/e2e/java/teammates/e2e/cases/FeedbackMcqQuestionE2ETest.java
  src/e2e/resources/data/FeedbackMcqQuestionE2ETest.json
  src/e2e/resources/data/FeedbackMcqQuestionE2ETest_SqlEntities.json
Labels: s.ToMerge

#12810 [#12048] Move accounts JSON for FeedbackMsqQuestionE2ETest
  src/e2e/java/teammates/e2e/cases/FeedbackMsqQuestionE2ETest.java
  src/e2e/resources/data/FeedbackMsqQuestionE2ETest.json
  src/e2e/resources/data/FeedbackMsqQuestionE2ETest_SqlEntities.json
Labels: s.ToMerge

#12812 [#12048] Move accounts JSON for FeedbackNumScaleQuestionE2ETest
  src/e2e/java/teammates/e2e/cases/FeedbackNumScaleQuestionE2ETest.java
  src/e2e/resources/data/FeedbackNumScaleQuestionE2ETest.json
  src/e2e/resources/data/FeedbackNumScaleQuestionE2ETest_SqlEntities.json
Labels: s.ToMerge

#12816 [#12048] Move accounts JSON for FeedbackResultsPageE2ETest
  src/e2e/java/teammates/e2e/cases/FeedbackResultsPageE2ETest.java
  src/e2e/resources/data/FeedbackResultsPageE2ETest.json
  src/e2e/resources/data/FeedbackResultsPageE2ETest_SqlEntities.json
Labels: s.ToMerge

#12817 [#12048] Move accounts JSON for FeedbackRubricQuestionE2ETest
  src/e2e/java/teammates/e2e/cases/FeedbackRubricQuestionE2ETest.java
  src/e2e/resources/data/FeedbackRubricQuestionE2ETest.json
  src/e2e/resources/data/FeedbackRubricQuestionE2ETest_SqlEntities.json
Labels: s.ToMerge

#12818 [#12048] Migrate account for StudentCourseDetailsPageE2ETest
  src/e2e/java/teammates/e2e/cases/StudentCourseDetailsPageE2ETest.java
  src/e2e/resources/data/StudentCourseDetailsPageE2ETest.json
  src/e2e/resources/data/StudentCourseDetailsPageE2ETest_SqlEntities.json
Labels: s.ToMerge

#12819 [#12048] Move accounts JSON for FeedbackSubmitPageE2ETest
  src/e2e/java/teammates/e2e/cases/FeedbackSubmitPageE2ETest.java
  src/e2e/resources/data/FeedbackSubmitPageE2ETest.json
  src/e2e/resources/data/FeedbackSubmitPageE2ETest_SqlEntities.json
Labels: s.ToMerge

#12821 [#12048] Move accounts JSON for FeedbackTextQuestionE2ETest
  src/e2e/java/teammates/e2e/cases/FeedbackTextQuestionE2ETest.java
  src/e2e/resources/data/FeedbackTextQuestionE2ETest.json
  src/e2e/resources/data/FeedbackTextQuestionE2ETest_SqlEntities.json
Labels: s.ToMerge

#12825 [#12048] Move accounts JSON for InstructorCourseEditPageE2ETest
  src/e2e/java/teammates/e2e/cases/InstructorCourseEditPageE2ETest.java
  src/e2e/resources/data/InstructorCourseEditPageE2ETest.json
  src/e2e/resources/data/InstructorCourseEditPageE2ETest_SqlEntities.json
Labels: s.ToMerge

#12814 [#12048] Move accounts JSON for FeedbackRankRecipientQuestionE2ETest
  src/e2e/java/teammates/e2e/cases/FeedbackRankRecipientQuestionE2ETest.java
  src/e2e/resources/data/FeedbackRankRecipientQuestionE2ETest.json
  src/e2e/resources/data/FeedbackRankRecipientQuestionE2ETest_SqlEntities.json
Labels: s.ToMerge

#12822 [#12048] Move accounts JSON for InstructorStudentRecordsPageE2ETest
  src/e2e/java/teammates/e2e/cases/InstructorStudentRecordsPageE2ETest.java
  src/e2e/resources/data/InstructorStudentRecordsPageE2ETest.json
  src/e2e/resources/data/InstructorStudentRecordsPageE2ETest_SqlEntities.json
Labels: s.ToMerge

#12824 Create script to verify row count for non-course entities
  src/client/java/teammates/client/scripts/sql/VerifyNonCourseEntityCounts.java
Labels: a-Testing, c.Task

#12793 [#12048] Migrate Admin Notifications E2E Test
  src/e2e/java/teammates/e2e/cases/AdminNotificationsPageE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/AdminNotificationsPage.java
  src/e2e/resources/data/AdminNotificationsPageE2ETest_SqlEntities.json
  src/main/java/teammates/ui/output/NotificationData.java
Labels: s.ToMerge

#12803 [#12048] Move accounts JSON for AutomatedSessionRemindersE2ETest
  src/e2e/java/teammates/e2e/cases/AutomatedSessionRemindersE2ETest.java
  src/e2e/resources/data/AutomatedSessionRemindersE2ETest.json
  src/e2e/resources/data/AutomatedSessionRemindersE2ETest_SqlEntities.json
Labels: s.ToMerge

#12823 [#12048] Move accounts JSON for InstructorCourseDetailsPageE2ETest
  src/e2e/java/teammates/e2e/cases/InstructorCourseDetailsPageE2ETest.java
  src/e2e/resources/data/InstructorCourseDetailsPageE2ETest.json
  src/e2e/resources/data/InstructorCourseDetailsPageE2ETest_SqlEntities.json
Labels: s.ToMerge

#12827 [#12048] Move accounts JSON for InstructorCourseEnrollPageE2ETest
  src/e2e/java/teammates/e2e/cases/InstructorCourseEnrollPageE2ETest.java
  src/e2e/resources/data/InstructorCourseEnrollPageE2ETest.json
  src/e2e/resources/data/InstructorCourseEnrollPageE2ETest_SqlEntities.json
Labels: s.ToMerge

#12829 [#12048] Move accounts JSON for InstructorCourseStudentDetailsEditPageE2ETest
  src/e2e/java/teammates/e2e/cases/InstructorCourseStudentDetailsEditPageE2ETest.java
  src/e2e/resources/data/InstructorCourseStudentDetailsEditPageE2ETest.json
  src/e2e/resources/data/InstructorCourseStudentDetailsEditPageE2ETest_SqlEntities.json
Labels: s.ToMerge

#12831 [#12048] Move accounts JSON for InstructorCourseStudentDetailsPageE2ETest
  src/e2e/java/teammates/e2e/cases/InstructorCourseStudentDetailsPageE2ETest.java
  src/e2e/resources/data/InstructorCourseStudentDetailsPageE2ETest.json
  src/e2e/resources/data/InstructorCourseStudentDetailsPageE2ETest_SqlEntities.json
Labels: s.ToMerge

#12833 [#12048] Move accounts JSON for InstructorFeedbackReportPageE2ETest
  src/e2e/java/teammates/e2e/cases/InstructorFeedbackReportPageE2ETest.java
  src/e2e/resources/data/InstructorFeedbackReportPageE2ETest.json
  src/e2e/resources/data/InstructorFeedbackReportPageE2ETest_SqlEntities.json
Labels: s.ToMerge

#12832 [#12048] Move accounts JSON for InstructorSessionIndividualExtensionPageE2ETest
  src/e2e/java/teammates/e2e/cases/InstructorSessionIndividualExtensionPageE2ETest.java
  src/e2e/resources/data/InstructorSessionIndividualExtensionPageE2ETest.json
  src/e2e/resources/data/InstructorSessionIndividualExtensionPageE2ETest_SqlEntities.json
Labels: s.ToMerge

#12834 [#12048] Move accounts JSON for InstructorFeedbackSessionsPageE2ETest
  src/e2e/java/teammates/e2e/cases/InstructorFeedbackSessionsPageE2ETest.java
  src/e2e/resources/data/InstructorFeedbackSessionsPageE2ETest.json
  src/e2e/resources/data/InstructorFeedbackSessionsPageE2ETest_SqlEntities.json
Labels: s.ToMerge

#12830 [#12048] Move accounts JSON for InstructorStudentListPageE2ETest
  src/e2e/java/teammates/e2e/cases/InstructorStudentListPageE2ETest.java
  src/e2e/resources/data/InstructorStudentListPageE2ETest.json
  src/e2e/resources/data/InstructorStudentListPageE2ETest_SqlEntities.json
Labels: s.ToMerge

#12841 Add base script for verifying migrated attributes
  src/client/java/teammates/client/scripts/sql/VerifyNonCourseEntityAttributesBaseScript.java
  src/client/java/teammates/client/scripts/sql/VerifyNotificationAttributes.java
  src/main/java/teammates/storage/sqlentity/Account.java
  src/main/java/teammates/storage/sqlentity/AccountRequest.java
  src/main/java/teammates/storage/sqlentity/Notification.java
  src/main/java/teammates/storage/sqlentity/UsageStatistics.java
Labels: a-Testing, c.Task

#12838 [#12048] Migrate AdminSearchPageE2ETest
  src/e2e/java/teammates/e2e/cases/AdminSearchPageE2ETest.java
  src/e2e/java/teammates/e2e/cases/BaseE2ETestCase.java
  src/e2e/java/teammates/e2e/pageobjects/AdminSearchPage.java
  src/e2e/resources/data/AdminSearchPageE2ETest.json
  src/e2e/resources/data/AdminSearchPageE2ETest_SqlEntities.json
  src/it/java/teammates/it/storage/sqlsearch/InstructorSearchIT.java
  src/it/java/teammates/it/test/BaseTestCaseWithSqlDatabaseAccess.java
  src/main/java/teammates/storage/search/SearchManager.java
  src/main/java/teammates/storage/sqlapi/AccountRequestsDb.java
  src/main/java/teammates/storage/sqlsearch/SearchManager.java
  src/main/java/teammates/ui/webapi/SearchAccountRequestsAction.java
  src/main/java/teammates/ui/webapi/SearchInstructorsAction.java
  src/main/java/teammates/ui/webapi/SearchStudentsAction.java
  src/test/java/teammates/test/BaseTestCaseWithDatabaseAccess.java
  src/test/java/teammates/test/BaseTestCaseWithLocalDatabaseAccess.java
Labels: s.FinalReview

#12839 [#12048] fix InstructorHomePageE2ETest
  src/e2e/java/teammates/e2e/cases/InstructorHomePageE2ETest.java
  src/e2e/resources/data/AutomatedSessionRemindersE2ETest_SqlEntities.json
  src/e2e/resources/data/InstructorHomePageE2ETest.json
  src/e2e/resources/data/InstructorHomePageE2ETest_SqlEntities.json
Labels: s.ToReview

#12840 [#12048] Migrate Notification Banner E2E
  src/e2e/java/teammates/e2e/cases/NotificationBannerE2ETest.java
  src/e2e/java/teammates/e2e/pageobjects/StudentHomePage.java
  src/e2e/resources/data/NotificationBannerE2ETest.json
  src/e2e/resources/data/NotificationBannerE2ETest_SqlEntities.json
  src/web/app/components/notification-banner/__snapshots__/notification-banner.component.spec.ts.snap
  src/web/app/components/notification-banner/notification-banner.component.html
Labels: s.ToMerge

#12719 [#12048] Migrate GetSessionResultsAction
  src/it/java/teammates/it/ui/webapi/GetSessionResultsActionIT.java
  src/main/java/teammates/common/datatransfer/SqlSessionResultsBundle.java
  src/main/java/teammates/common/datatransfer/questions/FeedbackQuestionDetails.java
  src/main/java/teammates/common/util/Const.java
  src/main/java/teammates/sqllogic/api/Logic.java
  src/main/java/teammates/sqllogic/core/FeedbackQuestionsLogic.java
  src/main/java/teammates/sqllogic/core/FeedbackResponseCommentsLogic.java
  src/main/java/teammates/sqllogic/core/FeedbackResponsesLogic.java
  src/main/java/teammates/storage/sqlapi/FeedbackResponseCommentsDb.java
  src/main/java/teammates/storage/sqlapi/FeedbackResponsesDb.java
  src/main/java/teammates/storage/sqlentity/FeedbackQuestion.java
  src/main/java/teammates/storage/sqlentity/FeedbackResponse.java
  src/main/java/teammates/storage/sqlentity/FeedbackResponseComment.java
  src/main/java/teammates/storage/sqlentity/responses/FeedbackMissingResponse.java
  src/main/java/teammates/ui/output/SessionResultsData.java
  src/main/java/teammates/ui/webapi/BasicFeedbackSubmissionAction.java
  src/main/java/teammates/ui/webapi/GetSessionResultsAction.java
  src/test/java/teammates/common/datatransfer/SqlSessionResultsBundleTest.java
  src/test/java/teammates/test/BaseTestCase.java
  src/test/resources/data/SqlFeedbackSessionResultsBundleTest.json
Labels: s.FinalReview
